### ISSUE TITLE
"Whole Collection" in sidebar

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1005]
Following on from https://github.com/ankitects/anki/commit/b8d67cdad54b933aafb310759f840cf82204e5f2#commitcomment-46786195

I wasn't sure about this one - it doesn't really fit in the "Recent" category, and felt a bit alone sitting at the top level by itself. Perhaps we could add it to the default saved searches for new users? Mind elaborating on how you use it in your workflow?
<img width="283" alt="Screen Shot 2021-02-05 at 10 27 46 pm" src="https://user-images.githubusercontent.com/180542/107033764-7c9f4200-6801-11eb-9bde-f41d9d722839.png">

**Comment by dae** [comment]
@abdnh replied here

**Comment by abdnh** [comment]
Adding it as a saved search sounds like a good idea.
I don't actually use it that much, except to get a general view of my collection and the card count. Of course, an empty search string will result in the same thing and may be convenient enough, though a bit less discoverable.

**Comment by dae** [comment]
Created a forum thread about this: https://forums.ankiweb.net/t/poll-where-should-whole-collection-and-or-current-deck-go/7326

**Comment by dae** [comment]
As discussed on the forum, resolved by making 'Decks' clickable.
