### ISSUE TITLE
Create an ARCHITECTURE.md for new contributors

### ISSUE THREAD

**Issue by alt-romes** [ankitects/anki#1010]
Hello!

I'm a user of Anki and I would like to help contributing - however, as a newcomer, it's quite complicated to understand where I should start.

Today I came across this [small post](https://matklad.github.io//2021/02/06/ARCHITECTURE.md.html) about `ARCHITECTURE.md` and thought that it would be super neat if the Anki repository had one of these.

I'm sure there's a lot going on and it's time consuming to write documentation, but if someone could get around to it someday, even if it was a simple pointer as to where to start reading code, it would be helpful for new want-to-be-contributors like me.

Thank you,
~romes

**Comment by zzzbra** [comment]
I was just thinking this yesterday.

**Comment by RumovZ** [comment]
Writing and maintaining such a file would be probably be quite time-consuming, only Damien himself could do it and he has probably more pressing things to see to most of the time. However, as someone who has worked through a couple of modules and crates the hard way by now, I couldn't agree more that development documention is desparately needed.
I wouldn't mind writing docstrings for the modules I learned to work with but it always felt out of place as the codebase has hardly any of those currently. So maybe a more pragmatic approach would be to encourage and set standards for creating class and module level documentation?

**Comment by zzzbra** [comment]
I think this might paint a little more color on what @alt-romes and I are suggesting: https://matklad.github.io//2021/02/06/ARCHITECTURE.md.html 

Based on what’s argued there, I’m not sure it would be so time consuming past the first completed draft—it’s a high level description of what the main projects are, and the purpose of their immediate sub-directories (and maybe a few of _their_ sub-directories, when their purpose is particularly salient to the high level functioning of Anki). My guess is this structure is relatively fixed (of course having a document like what we’re proposing here would immediately help to verify that) and so it’s not a huge maintenance cost unless some sort of architectural overhaul has happened—and updating ARCHITECTURE.md would be a fairly minor part of such a change.

**Comment by RumovZ** [comment]
I hear you and I would love it. However, there is currently a lot of refactoring going on (see [contributing.md](https://github.com/ankitects/anki/blob/main/docs/contributing.md)), so I just don't see this work at the moment.
Better internal documentation may not be a substitute but it seems more realistic to me as it can be done concurrently with the refactoring and would definitely be an improvement.

**Comment by alt-romes** [comment]
I don't see why it should be one or the other.
I am trying to read the code and maybe get the ball rolling but it's so complicated for me.

If anyone else reading this has any kind of knowledge just to get a small file going, then maybe it could be built piece by piece...

**Comment by dae** [comment]
There is a very brief mention of the submodules in development.md, and there are some .md files scattered around the tree describing the purpose of that subfolder. The code is still a bit in flux, but once the remaining parts of the pylib refactoring are further along, an overview file sounds like a good idea.

Re the docstring tangent, I have tried to use more verbose method names and variables in recent code, as they both help to explain the purpose of the function, and can't accidentally fall out of line with the behaviour of the routine like docstrings can. Will happily accept PRs that add useful docstrings, but not entirely sure about setting a lint or convention that they must exist - I fear that can sometimes lead to useless comments that do nothing except restate the call signature. I am conscious though that sometimes what I think should be obvious from the call signature [may not always be](https://en.wikipedia.org/wiki/Curse_of_knowledge).

**Comment by hgiesel** [comment]
The Ankidroid docs have a [good introduction into the database structure](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure). It might be worth taking a look there.

**Comment by alt-romes** [comment]
I've just now seen the start of [`architecture.md`](https://github.com/ankitects/anki/blob/main/docs/architecture.md)! (and coincidentally I have some free time the next weeks)
I'm quite excited by this and will soon start looking into the libraries described.

Thank you kindly @dae,
~romes

**Comment by aracelix** [comment]
Does anyone find dependency graphs useful as a form of documentation? Messing around with [pydeps](https://github.com/thebjorn/pydeps), I was able to get a visual of dependencies under pylib/anki:

Command: `pydeps anki --max-bacon=4 --cluster --max-cluster-size=10 --show-cycles --keep-target-cluster --rankdir TB`
![anki](https://user-images.githubusercontent.com/5705238/152913645-a3f49ecb-31fc-47b6-ba47-b1756d869004.svg)

Command: `pydeps anki --max-bacon=4 --cluster --max-cluster-size=1000 --rankdir TB`
![anki](https://user-images.githubusercontent.com/5705238/152914001-9da27846-7034-470c-8067-f32c45da193e.svg)

I'm not familiar with this codebase, so I'm unable to verify if these graphs reflect the Python architecture well. This could probably be automated and referenced in the `architecture.md` file.

**Comment by dae** [comment]
The latter graph seems like an accurate representation of how each file references others, but is that helpful in understanding the codebase? The key takeaway I think is that the collection object is the central object from which everything flows.

**Comment by aracelix** [comment]
The problem I'm trying to solve is how to get a bird's eye view of the architecture, which I think is very helpful in those beginning stages when you're trying to orient yourself in the code base. However, they are rarely good and need to be coupled with some written documentation if the names of classes/files are not meaningful, like the above. So my example is probably not that helpful, looking at it. 😢

Visual suggestion #2: I just stumbled across [this visualization tool from GitHub](https://octo-repo-visualization.vercel.app/?repo=ankitects%2Fanki), and it's pretty amazing. You can interact with it, hover, click, and search for specific files to see where they live. Screenshot:

<img width="829" alt="Screen Shot 2022-02-07 at 9 55 06 PM" src="https://user-images.githubusercontent.com/5705238/152927458-66c89782-1bc2-4375-9f13-add0129cf8de.png">

I'm still a newbie in this code base, but I can already infer from the above "oh, I now understand that there's these four main chunks: rslib, pylib, ts, and qt", "oh, if I'm going to be working in rslib, I should probably know what the scheduler, backend, and storage are for", "what's that unnamed blob in aqt", etc.

**Comment by dae** [comment]
That is quite neat, and adding a link to it in ARCHITECTURE.md might be helpful for others too.

**Comment by dae** [comment]
While architecture.md is fairly minimal, I think the original request has been satisfied. If there are particular points that you feel must be covered there, please create a new issue.
