### ISSUE TITLE
Multiple selection in the browser sidebar

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1011]
Multiple selection is currently disabled.

https://github.com/ankitects/anki/commit/126b64211566b473d1c2d25fbef9f79ddd062f1d

There are two things we'll need to fix before we can turn it on:

- [ ] shift+clicking to OR items leads to unwanted selections. Maybe we need to way to toggle multiple selection on and off? Other ideas on how this could be solved welcome.
- [ ] most of the right click context menu actions in the sidebar assume they should operate only on the right-clicked item. In some cases that's the only thing that makes sense (eg rename), but other actions like "delete deck" would ideally function on the whole selection. 
  - [ ] This will require updating the Rust end to support a list of IDs instead of a single ID, eg remove_deck_and_child_decks() will need to change. While calling it in a loop from the Python end would work for now, that will make life harder when we move undoing to the backend in the future.
  - [ ] Will need to handle cases where the user has selected a range of different kinds of items, and ignore ones not appropriate for the action

**Comment by dae** [comment]
I think the first one needs solving before we can enable this; the second one could potentially be done later.

**Comment by dae** [comment]
Sorry, fat fingers. :-)

**Comment by kleinerpirat** [comment]
Toggling multiple selection on and off seems cumbersome.
Maybe I'm missing something, but

- Ctrl+click for AND
- Ctrl+Shift+click for OR

seems like the simpler option? One would have to prevent multiple selection when Ctrl+Shift are pressed simultaneously. If more than one node is selected, they should be chained with OR in search to match the visual clue of the highlight.

People who would use logical operators in search are probably power users, so I reckon they are already used to more complex keyboard commands.

**Comment by RumovZ** [comment]
I would prefer not breaking the current filter clicking because it's an established and arguably more useful feature.
Multiselection in the sidebar could be implemented for Ctrl+*Right*click. We would even have Shift+Rightclick available for the probably less useful but expected range selection. The context menu would only show for Rightclick without modifiers then.

**Comment by dae** [comment]
Feedback on the current approach (or better ideas) welcome :-)

**Comment by kleinerpirat** [comment]
Using right click for AND/OR/NOT is a neat way of preventing the conflict. I like the simplicity of this!

I'm not going to be a frequent user of the logical operators, but I imagine that some color coding for the node background (like green for AND, blue or yellow for OR and red for NOT) would be helpful for long queries where the search bar is filled up.

**Comment by dae** [comment]
It's not ideal, as right clicks can be harder to trigger (especially on Macs), but I couldn't think of a better solution

We've gotten by without indicators when building search queries so far, so I would probably defer on that for now :-)

**Comment by dae** [comment]
For the record, the right click experiment was rolled back in https://github.com/ankitects/anki/commit/67d612926c6bfde0440251f92eb8654d86dc78cb

The issue with the wrong element being selected is likely resolved by https://github.com/ankitects/anki/pull/1035, but separate select/search modes as mentioned on the forum may be the best way forward.
