### ISSUE TITLE
build for 2.1.40 fails

### ISSUE THREAD

**Issue by OSS542** [ankitects/anki#1021]
2021/02/14 17:18:28 Downloading https://releases.bazel.build/3.7.0/release/bazel-3.7.0-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Repository npm instantiated at:
  /home/jhart/temp4/anki-2.1.40/WORKSPACE:14:11: in <toplevel>
  /home/jhart/temp4/anki-2.1.40/defs.bzl:46:17: in setup_deps
  /home/jhart/.cache/bazel/_bazel_jhart/fb395a9cac4c0def01657d368845d2db/external/build_bazel_rules_nodejs/index.bzl:74:18: in yarn_install
Repository rule yarn_install defined at:
  /home/jhart/.cache/bazel/_bazel_jhart/fb395a9cac4c0def01657d368845d2db/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:463:31: in <toplevel>
Loading: 0 packages loaded
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
	File "/home/jhart/.cache/bazel/_bazel_jhart/fb395a9cac4c0def01657d368845d2db/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 456, column 13, in _yarn_install_impl
		fail("yarn_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn_install failed: yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (warning " > protobufjs-cli-taylorm@7.0.4" has incorrect peer dependency "protobufjs@~6.7.0".
warning " > svelte2tsx@0.1.156" has incorrect peer dependency "typescript@^4.1.2".
error /home/jhart/temp4/anki-2.1.40/ts/node_modules/protobufjs: Command failed.
Exit code: 126
Command: node scripts/postinstall
Arguments: 
Directory: /home/jhart/temp4/anki-2.1.40/ts/node_modules/protobufjs
Output:
/bin/sh: /tmp/yarn--1613290775086-0.6220927402102825/node: /bin/sh: bad interpreter: Permission denied
)
Loading: 0 packages loaded
ERROR: no such package '@npm//@bazel/labs': yarn_install failed: yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (warning " > protobufjs-cli-taylorm@7.0.4" has incorrect peer dependency "protobufjs@~6.7.0".
warning " > svelte2tsx@0.1.156" has incorrect peer dependency "typescript@^4.1.2".
error /home/jhart/temp4/anki-2.1.40/ts/node_modules/protobufjs: Command failed.
Exit code: 126
Command: node scripts/postinstall
Arguments: 
Directory: /home/jhart/temp4/anki-2.1.40/ts/node_modules/protobufjs
Output:
/bin/sh: /tmp/yarn--1613290775086-0.6220927402102825/node: /bin/sh: bad interpreter: Permission denied
)
INFO: Elapsed time: 91.247s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by dae** [comment]
Judging by your other issue, this is likely something specific to your distro, which you have neglected to mention. If you are not able to figure it out, you could try asking over on the forums.
