### ISSUE TITLE
anki 2.1.14 fails

### ISSUE THREAD

**Issue by OSS542** [ankitects/anki#1023]
bash-3.2$ /opt/anki/runanki 
Traceback (most recent call last):
  File "/opt/anki/runanki", line 3, in <module>
    import aqt
  File "/opt/anki-2.1.14/aqt/__init__.py", line 14, in <module>
    from aqt.qt import *
  File "/opt/anki-2.1.14/aqt/qt.py", line 17, in <module>
    from PyQt5.QtWebEngineWidgets import *
ImportError: dlopen: cannot load any more object with static TLS

**Comment by OSS542** [comment]
It looks like this might be due to a need to upgrade to glibc-2.22 or later.  This appears to be due to a check against the value of DTV_SURPLUS, which is set to 14 in sysdeps/generic/ldsodefs.h.  Supposedly this check was removed from glibc-2.22.   I have not yet confirmed this.

**Comment by dae** [comment]
This appears to be an issue with PyQt and/or your distro, not Anki.
