### ISSUE TITLE
White line across the top of the screen on macOS

### ISSUE THREAD

**Issue by chrisnerio** [ankitects/anki#1041]
A white line appears at the top of the screen when in full screen and on dark mode. Unfortunately when I try to screenshot my screen the white line disappears in the screenshot.

This problem as far as I know started when macOS big sur update was released. There are other users with this same problem. Below is a link from reddit about this issue.

https://www.reddit.com/r/Anki/comments/l7gsco/thin_white_line_in_night_mode/

**Comment by chrisnerio** [comment]
I was able to take a picture of it with my phone. When I use a monitor the line is not as pronounced, however, with a normal computer, the line is more noticeable.

![IMG_1295](https://user-images.githubusercontent.com/63787525/109049920-6ec13c00-769e-11eb-94ed-73544e7cf3dd.jpeg)
![IMG_1296](https://user-images.githubusercontent.com/63787525/109049921-71239600-769e-11eb-977d-0cc92bcce692.jpeg)

**Comment by dae** [comment]
Can you reproduce the problem using the latest beta version published on the forums?

**Comment by chrisnerio** [comment]
I just downloaded it. I will let you know.

**Comment by chrisnerio** [comment]
I have been using it repeatedly and have quit Anki and booted it again and have not been able to reproduce the problem.
