### ISSUE TITLE
Cursor position is lost and set at the end of line after text input field loses focus in editor and browser

### ISSUE THREAD

**Issue by sandersantema** [ankitects/anki#1054]
This bug occurs using the latest `main` branch commit `3ba08d1189999c38f983288e980f39494c1c0057` and the latest beta version.

Cursor position before losing focus, underlined in red for clarity:
![image](https://user-images.githubusercontent.com/21057514/110206870-9b383d80-7e80-11eb-9d17-ca930ab067dc.png)

Cursor position after add window has lost focus (same bug occurs in browser editor too) i.e. after switching to another window:
![image](https://user-images.githubusercontent.com/21057514/110206902-c6bb2800-7e80-11eb-892e-dd8f11d71e56.png)

Some more information on my system given that the WM and QT version might be of importance here:
KDE Plasma Version: 5.21.1
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Graphics Platform: X11

**Comment by dae** [comment]
@sandersantema thanks for the report

@hgiesel is this an easy fix? We've run into the same issue in the past: 844778636c913c9a53ff002ce2cb577d67e97248
