### ISSUE TITLE
Undoing notetype edits leads to outdated model cache

### ISSUE THREAD

**Issue by RumovZ** [ankitects/anki#1056]
Modifying a model and then undoing the action leads to inconsistencies, presumably because the model cache isn't cleared correctly.

Example:
Change the name X of a (used) notetype to Y, then undo the action. The notetype will still be listed as Y in the browser sidebar and table, but `note:Y` will find no cards whereas `note:X` does, showing that the renaming was indeed undone on the backend.

**Comment by dae** [comment]
Thanks, will fix

**Comment by dae** [comment]
Please let me know if that didn't address it
