### ISSUE TITLE
"You have a lot of decks." alert link doesn't exist anymore.

### ISSUE THREAD

**Issue by ElnuDev** [ankitects/anki#1058]
I just got the following alert:

![image](https://user-images.githubusercontent.com/9874955/110261374-da3fbf00-7f64-11eb-9fe2-0611287ae6fb.png)

When I clicked on "this page," it said that the page was moved before redirecting to homepage of the Anki manual. In other words, the link is useless since the page it's linking to no longer exists.

I meant to open an issue on [ankitects/anki-manual](https://github.com/ankitects/anki-manual), but it seems like it is not possible to open issues there.

**Comment by dae** [comment]
That message doesn't exist in recent Anki versions.

**Comment by ElnuDev** [comment]
Oh wow, my Anki version is a lot older than I thought. I'm running 2.1.15 (442df9d6), which is what is on the Ubuntu repositories. Seems like I'll have to start using the release from GitHub.
