### ISSUE TITLE
[Anki 2.1.42, macOS] Cmd + Enter cannot submit new note

### ISSUE THREAD

**Issue by zhongdongy** [ankitects/anki#1089]
### Description
In previous versions on macOS, I can use the keyboard combination `⌘`+`Enter` to submit new note directly from any field once I finished editing. This is equivalent to clicking the "Add" button on the bottom left.

But when I upgraded to Anki 2.1.42 a few days ago, the shortcut stopped working. And it produced a line break in the current editing field instead. This behavior is exactly the same as pressing `Enter` directly. But when hovering mouse over the "Add" button, it says the shortcut is still `⌘`+`Enter`.

I suspected there might be another program or my add-ons causing issue (inspired by [this page](https://faqs.ankiweb.net/shortcut-not-working.html)). But when I disable add-ons, quit all other programs and even rebooted the Mac, the issue still exists.

### Ways to reproduce
1. Open Anki (2.1.42) on macOS. (With or without add-ons)
2. Select any deck.
3. Click "Add" on the first row below window title.
4. Do some editing (fill in the blanks)
5. Use keyboard combination `⌘`+`Enter` to try submitting.

### Additional information
- Mac model: MacBook Pro (16-inch, 2019), 16 GB memory
- OS: macOS Big Sur 11.2.3 (20D91)
- Last normal status: March 22 (might be Anki 2.1.35, not 100% sure)

**Comment by dae** [comment]
cmd+enter is working for me on 2.1.42 - did you remember to restart Anki after disabling add-ons?

**Comment by zhongdongy** [comment]
> cmd+enter is working for me on 2.1.42 - did you remember to restart Anki after disabling add-ons?

Yes I did. I think there might be something wrong with my installation. Please let me try to uninstall Anki and install back again. Will check after I done today's study on Anki. Thanks!

**Comment by zhongdongy** [comment]
> cmd+enter is working for me on 2.1.42 - did you remember to restart Anki after disabling add-ons?

Hi @dae , just now I uninstalled Anki and deleted `~/Library/Application Support/Anki*` directories. Then I downloaded Anki 2.1.42 from [Anki website](https://apps.ankiweb.net) and synced my collection. When I attempted to add one note, it still failed to respond my Cmd+Enter keyboard shortcut.

Here is a GIF demonstrating the issue I encountered:
![Cmd+Enter not working](https://obs-qn.dongs.xyz/targeted/cmd_enter_anki.gif)

And another screenshot of my Add-ons:
![Anki Add-ons](https://obs-qn.dongs.xyz/targeted/anki-addons.png)

**Comment by dae** [comment]
Hmm, strange. I presume you're hitting the normal enter key and not one on a numeric pad? What language is your keyboard set to? If it's not English, does switching to English make a difference? Do you use external programs that modify the keyboard handling, such as macro programs?

**Comment by zhongdongy** [comment]
> Hmm, strange. I presume you're hitting the normal enter key and not one on a numeric pad? What language is your keyboard set to? If it's not English, does switching to English make a difference? Do you use external programs that modify the keyboard handling, such as macro programs?

Hi @dae . Thanks for your information. I've found the cause: it is a Chinese input method called [loginputmac2](https://im.logcg.com/en/loginputmac2). Once I disable it, all back to normal. I think if future users of Anki have the same issue like me can refer to this thread. 

Sorry to disturb you. Thank you very much! 🌹 👍 🙇
