### ISSUE TITLE
Anki hangs on switching language with hot keys for input languages on Windows 10

### ISSUE THREAD

**Issue by ghost** [ankitects/anki#1105]
### Steps to reproduce

1. Open Settings app (`Win + I`)
2. Search for *Advanced keyboard settings*
3. Open *Input language hot keys*
4. Set some key sequence for the language
5. Open Anki
6. Try to change language via hot key

**Comment by ponlawat-w** [comment]
I also faced the same problem but got solved by changing video driver in Preferences to ANGLE. The previous one was OpenGL.

I don't know what is the relationship between language hotkey and video driver to cause the problem.

**Comment by RKBK** [comment]
This sounds related https://discussion.evernote.com/forums/topic/88139-client-freezes-when-swithing-a-language-via-keyboard/?do=findComment&comment=413388

**Comment by dae** [comment]
I originally reported this to Qt in Feb 2019:

https://bugreports.qt.io/browse/QTBUG-73994

**Comment by dae** [comment]
Still a problem with Qt 6.3.

**Comment by ponlawat-w** [comment]
It seems that Anki 2.1.54 Qt6 does not allow me to configure video driver in preference, so it will always freeze when switching language. I have to switch to Anki 2.1.54 Qt5 which allows such option in preference.

**Comment by dae** [comment]
https://docs.ankiweb.net/platform/windows/display-issues.html#qt6

**Comment by AommyPatty** [comment]
> https://docs.ankiweb.net/platform/windows/display-issues.html#qt6

change it to software doesn't help anything.

**Comment by YakovL** [comment]
@ponlawat-w could you clarify where to find that setting? I've checked those opened by ctrl+p but don't see anything in any tab there

**Comment by ponlawat-w** [comment]
@YakovL Here is my current settings, it's the third option. (Anki version 2.1.56)
![image](https://user-images.githubusercontent.com/15243484/235306139-07644b0e-f818-4c09-bb20-56de86de375e.png)

**Comment by YakovL** [comment]
@ponlawat-w hmm, here's mine (2.1.61 Qt6):

![image](https://user-images.githubusercontent.com/1131924/235309188-510ab0f0-8c2d-4b36-ade9-6902aae7740f.png)

Any idea if it is still available somewhere?

**Comment by dae** [comment]
The ANGLE option is only available with qt5.

**Comment by YakovL** [comment]
Might be worth noting on the download page (Win): if you use the Qt6 version, the app will hand each time you try to switch keyboard layout (obviously Anki is frequently used for learning vocabular, so this is an important issue, to say the least).

**Comment by dae** [comment]
I've updated the qt5/qt6 docs to mention this.

**Comment by StanislavKoncebovski** [comment]
I reported the issue  under https://forums.ankiweb.net/c/anki-desktop/9 without knowing of this GitHub discussion. 
If I am switching between EN and HE,  then Anki hangs on, with the only possibility to stop it is to kill the process. However, Anki operates quite normally if I switch between the English keyboard and the Ukrainian one. Is this an RTL/LTR problem? 
Anki Version ⁨2.1.62 (77dd1dc1)⁩; Python 3.9.15 Qt 6.4.3 PyQt 6.4.0.
PS: I do not think Python can be involved, but just in case: my Python installed globally is 3.11 (64 bit).

**Comment by YakovL** [comment]
@StanislavKoncebovski no, it's definitely not an (only) RTL/LTR problem: switching between en/ge/ru also causes the issue (although I haven't tested all the 6 combinations: en → ge, ge → en, en → ru, ...)

**Comment by dae** [comment]
Could someone please try 2.1.62beta1 on https://apps.ankiweb.net/downloads/beta/ and confirm the issue still exists? The stable 2.1.62 had to revert to Qt 6.4 as some users found 6.5 slower, but beta 1 was built with the latest 6.5. It would be useful to know 6.5 is still crashing so the Qt bug report can be updated.

**Comment by StanislavKoncebovski** [comment]
I have tested it. The beta version with qt5 functions fine, that with qt6 makes the same problem. Hope, it jelps.

**Comment by dae** [comment]
Thanks, I've updated the bug report.

**Comment by pedro-walter** [comment]
> https://docs.ankiweb.net/platform/windows/display-issues.html#qt6

I`m using Anki version 2.1.61 with qt6 and changing it to software solved my problem. I was switching from ja to pt-br and it crashed every time.

**Comment by YakovL** [comment]
@pedro-walter could you clarify, what do you mean by

> changing it to software

? Did you switch to qt5 or something else?

**Comment by dae** [comment]
@pedro-walter previous users have said that only angle helped for them, but perhaps (recent?) qt6 versions are different

@YakovL https://docs.ankiweb.net/platform/windows/display-issues.html#qt6

**Comment by omdenis** [comment]
Setting:
1) Version ⁨2.1.65 (aa9a734f)⁩, Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
2) Disable: Tools > Preferences > Reduce motion
3) Video driver: ANGEL

![image](https://github.com/ankitects/anki/assets/52582898/d4044c33-a2e0-4ccc-8fb8-cf05f52c3a8e)

languages: english <> danish <> russian

The problem was gone. Works fine at least today :-)

**Comment by YakovL** [comment]
> @pedro-walter previous users have said that only angle helped for them, but perhaps (recent?) qt6 versions are different
> 
> @YakovL https://docs.ankiweb.net/platform/windows/display-issues.html#qt6

it suggests to

> echo software > %APPDATA%\Anki2\gldriver6

to switch the ~mode, but running this (in PowerShell) results in

> Out-File: Could not find a part of the path 'C:\Users\YL\%APPDATA%\Anki2\gldriver6'.

for me

**Comment by hikaru-y** [comment]
@YakovL Use `cmd.exe`, or if you prefer to use PowerShell, try the following:
`echo software > $env:APPDATA\Anki2\gldriver6`

**Comment by ZYinMD** [comment]
Since @dae has reported the issue to Qt, I want to add a little info that might help Qt diagnose the issue - I found it's not the hotkey that triggers the bug, it's the windows api call that switches the input method. I found this when I tried to use AutoHotkey to replace the native hotkey:
```autohotkey
en := DllCall("LoadKeyboardLayout", "Str", "00000409", "Int", 1)
PostMessage 0x50, 0, %en%,, A
```
This code switches the input method, and it triggers the bug too.
You don't need to understand the syntax, but you can see it uses [DllCall](https://www.autohotkey.com/docs/v1/lib/DllCall.htm) to call a windows API.

**Comment by dae** [comment]
Thank you, I've mentioned that on the Qt report.

**Comment by YakovL** [comment]
@hikaru-y thanks, that worked! If anyone cares about the docs clarity, I suggest to mention cmd in the linked paragraph as well (and may be the pwsh solution, I've used that one). Like change

> If you run into display issues, you can try switching to software mode:

to

> If you run into display issues, you can try switching to software mode via cmd:

Adding pwsh may be done like this:

> If you run into display issues, you can try switching to software mode via cmd:
>
>     echo software > %APPDATA%\Anki2\gldriver6
>
> Or you can do it via PowerShell:
>
>     echo software > $env:APPDATA\Anki2\gldriver6

(may be I'll create a PR for https://github.com/ankitects/anki-manual/, if I have some time)

**Comment by ecsalamanc** [comment]
Hello, I'm having this same problem on Mac M.1, Ventura 13.1; Anki:
Version ⁨2.1.65 (aa9a734f)⁩
Python 3.9.15 Qt 6.5.0 PyQt 6.5.0.

Any help? It crashes every time I use the Korean/English input key.

**Comment by Packsolite** [comment]
IMO it's rediculus qt didn't address this issue after 4 years. I am used to using the hotkey and end up freezing/crashing anki multiple times a day.

**Comment by ZYinMD** [comment]
I can confirm that setting [this](https://docs.ankiweb.net/platform/windows/display-issues.html#qt6) to `software` fixes the problem on qt6.

So here's my summary, correct me if I'm wrong:

|                          | Qt5                           | Qt6              |
| ------------------------ | ----------------------------- | ---------------- |
| Cause of issue | Graphics Acceleration Setting | Same             |
| Possible value           | software<br>auto<br>angle | auto<br>software |
| Default value            | software| auto             |
| Fix                      | set to angle                  | set to software  |
| How to change | Anki UI | [manually](https://docs.ankiweb.net/platform/windows/display-issues.html#qt6)|

**Comment by e-git-hub** [comment]
Hello, I'm a new user of Anki, and I encountered this problem when I tried to add new cards. After navigating through this and other threads, I tried the proposed solutions reached here, but ran into to 2 problems:

1. With the Qt6 version installed on my PC, when entering the suggested prompt "echo software > %APPDATA%\Anki2\gldriver6", as Administrator, my computer says it cannot find the specified path. Also, when I looked for the file in Appdata, I couldn't find a file named gldriver6, which might be the problem. 
Another thing to note is that I am trying this on a non-administrator profile in Windows (although I have the password to access Admin mode), which might be interfereing with the commands, seeing as when I try to type the prompt in cmd.exe not as Administrator, it provides the following entry : Access Denied.

2. After uninstalling the Qt6 version of Anki and installing the Qt5 version, I tried to open the program and it would not boot, as Administrator or not.

I appreciate any tips you can provide, thanks!

OS: Windows 10. Anki Version ⁨2.1.65 (aa9a734f)⁩ Python 3.9.15 Qt 6.4.3 PyQt 6.4.0

**Comment by ZYinMD** [comment]
@e-git-hub what that command does is simply creating a file with `software` being the content. You can also create it yourself with notepad.

For details, ask ChatGPT `explain what this means: "echo software > %APPDATA%\Anki2\gldriver6"`

**Comment by e-git-hub** [comment]
@ZYinMD well, if I understood correctly, creating a text file named "gldriver6" with the text "software" written inside, within the directory C:\Users\Username\AppData\Roaming\Anki2 ought to have solved the problem. But I must have gotten something wrong because I did just that and it still crashes Anki when I try to change the keyboard using custom windows shortcuts. 

Does it need a special extension maybe? I wouldn't want to make things complicated, seeing as it's probably just a local issue...

**Comment by ZYinMD** [comment]
@e-git-hub what you said sounds all correct, at least that's what worked for me with qt6. The file needs no extension. If it didn't work for you, maybe it doesn't solve the issue on all PCs thus not a real solution...

**Comment by e-git-hub** [comment]
After tinkering around with it a while longer I figured it out. 

In summary, if for some reason, you can't create the file using the suggested prompt (either because you're on a non-Admin profile of Windows or for any other reason), just do the following:

1. Navigate to C:\Users\Username\AppData\Roaming\Anki2

2. Create a text file named "gldriver6" in that directory

3. Type "software" in the text file by opening it with notepad

4. Save and close the file, then rename the file to remove the ".txt" extension.

This is what worked for me.

@ZYinMD Thanks again for all your help!

**Comment by dae** [comment]
The Qt ticket has been updated and mentions that this should no longer be an issue with the default video driver in Qt 6.5.1+. Can people affected by this please try the Qt6 beta on https://apps.ankiweb.net/downloads/beta/?C=N&O=D and confirm if the problem is gone for them or not?

**Comment by e-git-hub** [comment]
@dae I can confirm that with a fresh installation of Anki with the Qt6 beta downloaded from the link you provided that this problem no longer occurs for me. Thanks for the follow-up!

**Comment by dae** [comment]
Thanks for letting me know, and sorry about the delayed reply.
