### ISSUE TITLE
Stats displays not properly rounded cards/minute in german

### ISSUE THREAD

**Issue by lukaspanni** [ankitects/anki#1111]
When setting the language to english cards/minute is rounded properly:
![grafik](https://user-images.githubusercontent.com/16417093/113473161-24cf3100-9468-11eb-9444-5365b75b4db2.png)

But when I set the language to german Anki displays it like this:
![grafik](https://user-images.githubusercontent.com/16417093/113473177-39abc480-9468-11eb-8e49-64cbfab95ea5.png)

Other Stats seem not to be affected.

I could not find the exact problem in the code yet, because I'm not really familiar with the code base.
I will add a comment to this issue if I can figure it out.

**Comment by dae** [comment]
I can't seem to reproduce this. Are you testing with the code in master and without add-ons? If so, could you share your deck or a subsection that reproduces it with me on help.tenderapp.com, or your AnkiWeb ID, so that I can try to dig into it further?

**Comment by dae** [comment]
Nevermind, found a repro in the old stats screen

**Comment by dae** [comment]
Was a mistake by the translator, thanks for the report.
