### ISSUE TITLE
⁨error sending request for url (): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known⁩

### ISSUE THREAD

**Issue by cluttered-patience** [ankitects/anki#1112]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/81524596/113694077-e0f75880-9701-11eb-96b7-ef1e82641a86.png">

**Comment by aimegumi** [comment]
![image](https://user-images.githubusercontent.com/81137552/114157119-e2b95a00-9955-11eb-9d48-9b0b204b341f.png)
当我使用网络代理时，就会出现这种情况。

**Comment by dae** [comment]
https://faqs.ankiweb.net/error-establishing-a-secure-connection-when-syncing.html

It may be your local internet; you may have more luck using a VPN.

**Comment by flespark** [comment]
I tried 2.1.44  and 2.1.20 version windows app have same failure at login, but 2.1.15 worked well
