### ISSUE TITLE
incorrect parsing of tags in flds in sqlite3 notes' table

### ISSUE THREAD

**Issue by felipejinli** [ankitects/anki#1143]
**My version** Version ⁨2.1.36 (c505894b)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

**Problem** I am creating/updating notes by populating the notes table of the Anki sqlite database. I realised that for some notes which have the characters `<` `/>`  in them they are partially parsed. E.g. for the flds value
```
2-Programming-Techniq...0code out the simplest c++ template for CP?#include <bits/stdc++.h>

using namsepace std;

int main() {
}
```
where each field is correctly separated by the 0x1f character, I incorrectly get the output shown on the image. **The field is correctly set for other string values, so I was wondering if this is a bug relating to how it escapes `<` and `>` character? @dae **

I've disabled all add-ons to make sure it wasn't an add-on that incorrectly modified the card.

<img width="457" alt="Screenshot 2021-04-21 at 19 05 48" src="https://user-images.githubusercontent.com/42386776/115600413-99152b80-a2d4-11eb-9aa4-700fefbd0716.png">

[note model] based on                  `fields=[
                     {"name": "CategoryTag"},
                     {"name": "OrderNumber"},
                     {"name": "Front"},
                     {"name": "Back"},
                     {"name": "Answer"},
                     {"name": "MyMedia"},
                 ],`

**Comment by dae** [comment]
I can't offer any support for modifying the database directly. If you can reproduce the problem when adding content inside Anki or with the import feature, please post on the forums.
