### ISSUE TITLE
Directory "mpv" in current directory prevents Anki from starting

### ISSUE THREAD

**Issue by xstnztk** [ankitects/anki#1158]
When starting Anki from the command line on Linux, I stumbled over a minor problem: if there is a directory called "mpv" in the current working directory, Anki fails to start:

```
Error during startup: ⁨Traceback (most recent call last):
  File "aqt/main.py", line 122, in __init__
  File "aqt/main.py", line 155, in setupUI
  File "aqt/main.py", line 465, in setupSound
  File "aqt/sound.py", line 871, in setup_audio
  File "aqt/sound.py", line 381, in __init__
  File "aqt/mpv.py", line 442, in __init__
  File "aqt/mpv.py", line 102, in __init__
  File "aqt/mpv.py", line 128, in _start_process
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1702, in _execute_child
PermissionError: [Errno 13] Permission denied: '/home/user/scratch/mpv'
```

The problem is actually in distutil's `find_executable`: contrary to the documentation I could find, it also looks in the current directory for the executable, not only in PATH. It also does not seem to check if the directory entry it found is actually an executable file; it just returns the first one with a matching name.

AFAICT using `find_executable` is not really necessary because `Popen` will look for the executable in PATH anyway. On Windows it uses CreateProcess() which automatically appends ".exe" if no path and no extension is used, so simply using "mpv" as the name of the executable as it is done now should work there, too.

OTOH `find_executable` is present since the first version of mpv.py, so maybe there is indeed a reason to use it.

**Comment by dae** [comment]
mpv.py is mostly third-party code, so I'm not sure why they used find_executable. Given that nobody seems to have hit this before, I'm afraid it's probably not worth trying to fix at the moment.

**Comment by xstnztk** [comment]
I fully understand that you are reluctant to change this because it may have effects that someone on some platform depends on. It is probably just something to be aware of if you get reports that Anki fails to start.

Again thanks for Anki! I am using it literally seven days a week.

**Comment by dae** [comment]
Appreciate your understanding, and delighted to hear you're finding Anki useful :-)
