### ISSUE TITLE
Shift+Tab initially jumps to incorrect button

### ISSUE THREAD

**Issue by e-e** [ankitects/anki#1161]
I just upgraded to the latest desktop version and noticed the following:
 
Immediately after revealing the answer, the "Good" button has focus
<img width="700" alt="Screen Shot 2021-05-07 at 7 49 05 AM" src="https://user-images.githubusercontent.com/5191838/117467701-c5ea5500-af08-11eb-91f4-a04784071571.png">

Pressing `shift+tab` once to shift focus to the previous ("Hard") button instead jumps focus to the "More" button. 
<img width="703" alt="Screen Shot 2021-05-07 at 7 49 11 AM" src="https://user-images.githubusercontent.com/5191838/117467633-b79c3900-af08-11eb-8ce1-026f24848ccd.png">

Subsequent `shift+tab`s work as expected, moving focus to the previous button.

**Comment by e-e** [comment]
I think that what is happening is that even though the button appears to have the focus, the first focusable item in the Back card content is what actually has focus. Pressing `shift+tab` moves from the beginning of the card content to the last item, which is the "More" button. Pressing `tab` first starts cycling through the focusable items in the card, and doesn't move the focus from the answer difficulty buttons. I hope this isn't intended behavior, because being able to use tab to select the card difficulty makes reviews much faster.

**Comment by dae** [comment]
The behaviour is a big surprising here because of the way the UI is comprised of multiple webviews. Instead of using tab, I'd recommend you use the 1-4 keys, which will trigger a button in a single keystroke.
