### ISSUE TITLE
Shortcuts based on raw keycodes need a rethink

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1162]
@hgiesel Unfortunately I'm not sure the current approach with raw keys is going to work. Consider a user who uses a Dvorak keyboard layout for example, where most physical keys represent a different letter. When the user sees a shortcut like 'cmd+shift+c', they expect to press the key that presents a c in Dvorak, and not the physical c key. I would have caught this myself (I'm a Dvorak user), but my main machine uses a hardware Dvorak keyboard that remaps the physical keycodes.

I suspect it will adversely affect users with some language keymaps as well.

Original report from @nwwt:
https://forums.ankiweb.net/t/card-browser-hotkeys-semi-broken/9815/3

**Comment by hgiesel** [comment]
Yes, you're right. We should use `event.key` for these cases. I wonder if we can use `event.code` for some cases though, e.g.  "Control+Shift+2". We could only check for "Control+@", which in turn could be in inconvenient positions

**Comment by hgiesel** [comment]
1. What I meant was that displaying: "@", we could display "Shift+2", and activate it on clicking `Shift+Digit2` based on `event.code`. The digits are more consistent on keyboards, and if they not on they keyboard top row, they are usually completely missing from that locale (e.g. Thai or Vietnamese keyboard layouts). This is not that relevant yet, but could be interesting once we move the reviewer shortcuts to JS.

2. There is one possible complication I noticed. We do have some which involve the Alt modfier, like the cloze shortcuts. On Macs, the Alt modifier may also change the output of `event.code`. [For example](https://keycode.info/) `Ctrl+Alt+Shift+C` will give me `¸`. Weirdly enough, that does not happen on Chromium inside Anki, but it does happen in any up-to-date browser on my machine.

**Comment by dae** [comment]
@hgiesel is this safe to close now, or are there still issues remaining?

**Comment by hgiesel** [comment]
I think this is solved.
