### ISSUE TITLE
Update Banner Incorrectly Showing

### ISSUE THREAD

**Issue by adamhl8** [ankitects/anki#1163]
On both my Linux (Mint 20.1) machine and secondary Windows machine, every time I start Anki I get a banner message telling me to update to Anki 2.1:
"Anki 2.1 comes with a new scheduler, which fixes a number of issues that previously Anki versions had. Updating to it is recommended."

I'm on Anki version 2.1.43. This happens with a fresh install of Anki. Selecting Update does not clear the message. Strangely, this doesn't happen on my main Windows machine, so I'm not sure what's causing the issue.

**Comment by RumovZ** [comment]
See here, e.g.: https://forums.ankiweb.net/t/upgrade-to-2-1-message-after-upgrade-wont-go-away/9828

**Comment by adamhl8** [comment]
Thank you. I guess I didn't google hard enough.
