### ISSUE TITLE
Audio is paused unusual

### ISSUE THREAD

**Issue by HarryRen** [ankitects/anki#1164]
When I am playing a audio file with anki-2.1.37 (windows), I press pause key almost at the end of the file, then it is paused.
But it can't be replayed when I press the replay key, then I have to press the pause key next and it starts to replay, It 's really weird！

I downgrade to version 2.0.52, using a Adjust_Audio_Speed plugin, it works well.  The code of new anki version which control the Mpv Player must have some bugs. Is anybody can fix that in a new version?

**Comment by vorspohl** [comment]
I use Anki für Windows 2.1.44.
When I open a desk and start to play there is a delay of around 15 seconds for me with the first card.
After continue no delay but when I try to play the sound again, same delay.
Looks like a bug in the sound system.

**Comment by kelciour** [comment]
@vorspohl maybe use the following code in the [Debug Console](https://docs.ankiweb.net/misc.html?#debug-console) to temporarily enable mpv logging, maybe it'll contain some useful information.

```python
import os
from aqt.sound import mpvManager

logfile = os.path.join(r'%USERPROFILE%\Desktop', 'anki.mpv.log.txt')
logfile = os.path.expandvars(logfile)

mpvManager.set_property("log-file", logfile)
print('log-file:', mpvManager.get_property('log-file'))
```
