### ISSUE TITLE
[Bug] When I changed the "next day start at", the past statistical data got out of order. 

### ISSUE THREAD

**Issue by mikunimaru** [ankitects/anki#1179]
###### Reproduction Steps

1. View Statistics "Review Cownt" "Review Time"
2. Chante "next day start at"
3. Restart the app.
4. Check the "Review Cownt" "Review Time" on the statistics screen again.

###### Expected Result

Displaying consistent statistical data.

###### Actual Result

Since the date change time goes back to the past, the past data will be distorted.
(Two days' worth of statistical data is displayed on some days, half a day's worth of statistical data is displayed on another day, and so on.)

**Comment by dae** [comment]
Anki does not record the cutoff point you're using when reviews are made, so when you adjust the starting time of a day, that affects the cutoff of previous reviews too. I do not see any practical way to handle this differently in a backwards-compatible way.

**Comment by mikunimaru** [comment]
How about saving only the change history of "next day start at" in the app?

If the change history of "next day start at" can be taken into consideration when calculating statistics, I feel that statistical inconsistencies can be suppressed with minimal impact.
It's more realistic than a major change that records the cutoff points for all reviews.

**Comment by dae** [comment]
That fails the "practical" part - having to consider different cutoff points as we go through the history would make the code a fair bit more complicated. I'm afraid I don't think it's worth it at this point.
