### ISSUE TITLE
undo handling for browser headers

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1184]
Re: https://github.com/ankitects/anki/commit/3d4cf26758a242d8b2444a0e70f33b3425b59f8b

We'll need to figure out how to handle changes to the browser headers, such as reordering them, or changing the sort order. If we want to make them undoable, we'd need to:

- Use CollectionOp() when calling set_config_bool() or set_config(), so that it triggers the undo menu item to update. Passing initiator=self will allow us to avoid doing extra work in the case we're already explicitly refreshing. A brief example is in the sidebar in the above commit.
- op_executed() in table.py will need to check if handler is self, and if not, check to see if the columns and reverse setting have changed. If the sort order has changed, we'd presumably want to repeat the search.

The alternatives are to:

- revert to the old behaviour (clearing the undo queue - not great)
- add an option to make config changes that get ignored by the undo code - that's probably the cleanest/easiest solution here, though I'm a bit worried it may lead to bugs in the future if we allow config changes to bypass undo

The current behaviour of "any config change forces a redraw" is not optimal; this could be improved in the future by creating a separate backend op that adjusts the settings, and it can then be special-cased when determining what has changed.

@RumovZ thoughts? Would you like to work on this?

**Comment by RumovZ** [comment]
I haven't looked into the undo code, so I can't contribute to the discussion, yet. But I will catch up on that.
From a user perspective I, too, think that primarily optical changes like toggling columns shouldn't be added to the undo queue. As for reordering, I believe that this is handled by Qt, so we can't undo that anyway, can we? If I'm not mistaken here, this would be another reason for similar ops not to be undoable, either.
But again, I'm ignorant regarding the potential issues you mention.

**Comment by dae** [comment]
Good point about reordering. From a user perspective I suspect it doesn't make a big difference whether we make these operations undoable or not, but it will complicate the code if we do - maybe skipping the undo queue is the best option. Will look into adding a routine to do that over the next few days.

**Comment by dae** [comment]
Closed by https://github.com/ankitects/anki/commit/adcdb422c54c7e38c15dc6a79a0781278740fe87
