### ISSUE TITLE
[bug] Interval setting in seconds is not reflected

### ISSUE THREAD

**Issue by mikunimaru** [ankitects/anki#1203]
In previous versions of anki, I used to set the Interval in seconds like this.

![Screenshot at 2021-05-27 23-41-31](https://user-images.githubusercontent.com/43168745/119850290-5fc18280-bf48-11eb-8f20-c16d650e687f.png)

This setting works satisfactorily, including synchronization.

In this version, it is possible to set in seconds, which is convenient at first glance, but if you set a value such as 10s, the deck option will be broken.

Set to 10 seconds
![Screenshot at 2021-05-28 00-16-31](https://user-images.githubusercontent.com/43168745/119853096-d6f81600-bf4a-11eb-861f-2b5e6288d2e7.png)

Reopen the deck options
![Screenshot at 2021-05-28 00-21-54](https://user-images.githubusercontent.com/43168745/119853237-fb53f280-bf4a-11eb-9228-cd9478e6d200.png)

When I tap the Learning steps once and then tap another item, the display is displayed in 10 minutes instead of 10 seconds.
![Screenshot at 2021-05-28 00-22-08](https://user-images.githubusercontent.com/43168745/119853524-3d7d3400-bf4b-11eb-82dc-b357111b50e6.png)

After synchronizing and checking the numerical value on a conventional terminal
Since it was displayed correctly as 0.166666 ... (About 10 seconds), it may be a bug only for display.

**Comment by dae** [comment]
Your font is looking pretty bad there. What does the following the debug console say?

```
pp(aqt.mw.font().family())
```

**Comment by mikunimaru** [comment]
@dae 
![Screenshot at 2021-05-28 19-05-28](https://user-images.githubusercontent.com/43168745/119968129-0f016680-bfe8-11eb-9c04-63a40ce74c08.png)

Nothing is displayed.
The OS uses Debian 10 on Linux.

**Comment by mikunimaru** [comment]
@dae 
Thank you, it was displayed.

>>> pp(aqt.mw.font().family())
'Cantarell'

**Comment by dae** [comment]
I'm not good with fonts, but it seems like the font being used there is not Cantarell - not sure why that would be.

**Comment by mikunimaru** [comment]
The font itself seems to be installed.

```bash
fc-list | grep "Cantarell"
/usr/share/fonts/opentype/cantarell/Cantarell-Bold.otf: Cantarell:style=Bold
/usr/share/fonts/opentype/cantarell/Cantarell-Regular.otf: Cantarell:style=Regular
/usr/share/fonts/opentype/cantarell/Cantarell-Light.otf: Cantarell,Cantarell Light:style=Light,Regular
/usr/share/fonts/opentype/cantarell/Cantarell-ExtraBold.otf: Cantarell,Cantarell Extra Bold:style=Extra Bold,Regular
/usr/share/fonts/opentype/cantarell/Cantarell-Thin.otf: Cantarell,Cantarell Thin:style=Thin,Regular
```

It seems that font-related problems occur on some Linux.
https://www.reddit.com/r/Anki/comments/i2rn1e/anki_not_using_the_default_gtk_themefonts_on/
https://www.reddit.com/r/Anki/comments/7r82hj/some_fonts_look_weird_in_anki_2046_why_and_how_to/
