### ISSUE TITLE
Tag march works bad

### ISSUE THREAD

**Issue by Leethring** [ankitects/anki#1204]
After updating 2.1.44. My tag march goes wrong. 

![H_M{_I634BDW`WFXW27_ ID](https://user-images.githubusercontent.com/47080668/119927316-cfb52480-bfab-11eb-8d43-0e24bbcdc144.png)

The 'English' should be the first option in the past, but it march backforward. How can I fix it?

**Comment by dae** [comment]
Searching now matches anywhere in the text. Anki could be smarter about which matches it shows first, but that's a feature request, not a bug per-se.
