### ISSUE TITLE
shared deck page link no longer valid

### ISSUE THREAD

**Issue by liamvdv** [ankitects/anki#1214]
Hey Anki-Devs!
First of all, I would like to thank you for the great product you're building. Keep up the good work. In my case, your work helped me succeed in my school exams. Be proud of the impact your making! Because your time is spare, I will get right to it:

The desktop Anki client for Windows shows a 
"Please see the [shared deck page](https://ankiweb.net/shared/info/) for more info."
message for decks containing cards imported from a downloaded .apkg file. **The link is not valid.**

Steps to replicate:
a) Just press on the link in the above message. 
Or
b)
1. Download any Shared Anki decks. To get to the right page, press "Get Shared" (Deck). 
2. Import the downloaded .apkg file.
3. Click on the imported deck, now the message should appear. Click on the blue underlined link.

Windows Anki Client:
Version ⁨2.1.44 (b2b3275f)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
(latest, message also appears with prior versions)

**Comment by dae** [comment]
I just downloaded https://ankiweb.net/shared/info/2109889812, and the link worked for me. Those links are inserted when the deck is originally shared, so maybe the ones you downloaded were created in the past when this was not working correctly?

**Comment by liamvdv** [comment]
I've done a test, downloading and importing a deck that was last updated in a given year.
Last Updated in 2012: Works!
Tried with [this](https://ankiweb.net/shared/info/840017292) deck.

Last Updated in 2013: **Fail**:
Tried with [this](https://ankiweb.net/shared/info/3341204081) deck.

Last Updated in 2014: **Fail**
When I download and import [this](https://ankiweb.net/shared/info/51975584) or [this](https://ankiweb.net/shared/info/1021974894) deck however, it doesn't work.  These first one was last updated on 2014-04-02, the second one on 2014-06-16. (It was presumably not an issue that applied to that specific deck.)

Last Updated in 2015: **Fail**
Tried with [this](https://ankiweb.net/shared/info/129986190) deck.

Last Updated in 2016: Works!
Tried with [this](https://ankiweb.net/shared/info/203373679) deck.

Last Updated in 2017: Works!
Tried with [this](https://ankiweb.net/shared/info/1409968244) deck.

Last Updated in 2018: Works!
Tried with [this](https://ankiweb.net/shared/info/1409968244) deck.

Last Updated in 2019: Works!
Tried with [this](https://ankiweb.net/shared/info/2086567642) deck.

Last Updated in 2020: Works!
Tried with [this](https://ankiweb.net/shared/info/186859955) deck.

So it seems to be fixed for newer decks. For the time period between 2013 and 2015, the link doesn't work. 
I think there are three paths going forward:
1. Ignore the faulty behaviour.
   + only affects old decks and people tend to use newer ones
   + even if they choose an old deck, it is not a problem that breaks the experience
   + doesn't require any additional work; focus on new features / fixing mor important issues
   - leds to confusion
   - there are good decks from 2014 and it should be handeled properly anyway.
  
2. Change Backend:
   host/shared/info/:id is the path, i. e. https://ankiweb.net/shared/info/:id.
   Problem with: host/shared/info/
   1) Handle the upper path by checking if an id was provided and if not, returning a simple html page that explains the issue (f. e. "this is known, .... for shared decks last updated between 2013 and 2015." or redirecting to host/shared/decks/ as a fallback. This should be straight forward, but doesn't solve the root issue.
   2) Write a patch script that goes through the shared decks in that time period and pulls out the id and the according .apkg file, and modifies the value. This may be time and computationally expensive and does not solve the problem for prior users who downloaded the deck before this patch. 
Because 2) doesn't fix this problem for decks imported before the patch and could be quite a burdon on the servers, I would favor 1).
3. Change Client:
   Changing the client is generally not a good idea, because changes must be done to all platforms. Moreover, it does not fix the problem for previous clients nor does it fix the root issue.
   Anyway, a possible solution would be to check if the last part of the URL is a number and if not, replacing it with the host/shared/decks/ URL.

**Comment by dae** [comment]
Yep, there was a period when this was broken. I'm afraid due to the fact that this was fixed years ago and is not a particularly serious issue, I can't see it bubbling up to the top of the priority list any time soon.

**Comment by liamvdv** [comment]
For sure! There are definitively more important features (like a consistent api for add-ons so that they're not broken every release)! Should I then close the issue or are you going to?

**Comment by dae** [comment]
Thank you for the feedback in any case!
