### ISSUE TITLE
The HTML parser doesn't correctly escape HTML entities in attributes

### ISSUE THREAD

**Issue by gregorias** [ankitects/anki#1219]
I've reproduced this on Anki 2.1.44

## Steps to reproduce

1. Create an image with an ampersand in its name, e.g., `a&b.png`.
2. Start creating a card and insert the image.
3. Open the HTML editor (Ctrl+Shift+x), and edit the HTML to have `<img src="a&b.png"><img src="a&amp;b.png">`.
4. Close the editor.

### Expected Behavior

The card previewer should display two images side-by-side:

![Screenshot from 2021-06-05 11-38-54](https://user-images.githubusercontent.com/722385/120887369-ad965480-c5f2-11eb-99d4-39fb21b325b2.png)

According to https://stackoverflow.com/questions/12444605/is-it-okay-to-use-html-entities-in-attributes, it's valid HTML to have HTML entities inside attributes and they should be decoded.

### Actual Behavior

![Screenshot from 2021-06-05 11-38-37](https://user-images.githubusercontent.com/722385/120887396-da4a6c00-c5f2-11eb-8bc9-2485271575cb.png)

The card previewer doesn't display the second image. and outputs `Not found: 'a&amp;b.png'` on the command line.

**Comment by dae** [comment]
Please let me know if it's still a problem in the next beta or stable release.

**Comment by gregorias** [comment]
Thank you.
