### ISSUE TITLE
Glitch when inserting image in half-screen mode

### ISSUE THREAD

**Issue by terrenay** [ankitects/anki#1223]
(Windows 10, Anki 2.1.44)

Steps to reproduce:

1) Open the "add card" window in half screen mode (by dragging it to the side of the screen).
2) Insert an image
3) Press enter
4) Keep a key pressed to fill several lines with text. 
On the fifth line (for me), the screen starts changing size with each key stroke.

https://user-images.githubusercontent.com/62691118/121436871-9e602f80-c981-11eb-9b90-e3a4502c9ec9.mp4

**Comment by dae** [comment]
Does the issue still exist in the the qt6 Anki beta? https://betas.ankiweb.net/

**Comment by dae** [comment]
Closing for now; please post back when you've had a chance to test the 2.1.50 release.
