### ISSUE TITLE
Sorting by "Overdue Interval" in the browser throws an error

### ISSUE THREAD

**Issue by brainexcerpts** [ankitects/anki#1226]
Anki Desktop 2.1.44 
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
UI language set to Japanese 

In the browser clicking on the "Overdue Interval" tab will trigger the following pop up error and make the cards disappear.

`DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"near \\\"select\\\": syntax error\"))", kind: Other }`

Other subsequent browsing related action will then keep trigger the error and cards won't show up.
However as soon as you click on another sorting option the cards appear again and the error stops popping up.

**Comment by dae** [comment]
Sounds like something added by an add-on.

**Comment by brainexcerpts** [comment]
Oh indeed, I totally forgot I had advanced-browser installed.
Removing the addon removes the "overdue interval" tab but now I'm left with empty tabs named "Add-on"
![image](https://user-images.githubusercontent.com/8319592/121704256-8a960400-cb0e-11eb-815e-069578f9b5a1.png)

I guess I should issue this to their git.
Sorry for the noise.

**Comment by brainexcerpts** [comment]
It was already issued...

https://github.com/hssm/advanced-browser/issues/112
https://github.com/hssm/advanced-browser/issues/98
