### ISSUE TITLE
Exception, probably related to #1219

### ISSUE THREAD

**Issue by mowgli** [ankitects/anki#1227]
On gentoo, I get the following stack trace when entering an answer. (I did with 10x10 Multiplication, but I had it in all stacks.)
```
Fehler 
Ein Fehler ist aufgetreten. Bitte benutzen Sie Extras > Datenbank überprüfen, um das Problem evtl. zu lösen. 
Sollte das Problem fortbestehen, wenden Sie sich bitte mit Ihrem Problem an unsere Support-Seite. Bitte fügen Sie in diesem Fall die folgenden Informationen in den Problembericht ein.
Anki 2.1.15 (442df9d6) Python 3.9.4 Qt 5.15.2 PyQt 5.15.2
Platform: Linux
Flags: frz=False ao=False sv=1

Caught exception:
  File "/usr/lib/python3.9/site-packages/aqt/webview.py", line 322, in handler
    cb(val)
  File "/usr/lib/python3.9/site-packages/aqt/reviewer.py", line 461, in _onTypedAnswer
    self._showAnswer()
  File "/usr/lib/python3.9/site-packages/aqt/reviewer.py", line 217, in _showAnswer
    a = self._mungeQA(a)
  File "/usr/lib/python3.9/site-packages/aqt/reviewer.py", line 156, in _mungeQA
    return self.typeAnsFilter(mungeQA(self.mw.col, buf))
  File "/usr/lib/python3.9/site-packages/aqt/reviewer.py", line 306, in typeAnsFilter
    return self.typeAnsAnswerFilter(buf)
  File "/usr/lib/python3.9/site-packages/aqt/reviewer.py", line 362, in typeAnsAnswerFilter
    cor = parser.unescape(cor)
<class 'AttributeError'>: 'HTMLParser' object has no attribute 'unescape'
```

I do not know python so I cannot tell what how to read that stack trace and from which end.

Further info:
* This is on Gentoo linux
* A week before it was working fine
* In between, the transition from Python 3.8 to Python 3.9 took place
* On Devuan linux, all work fine

From this I think there is an incompatibility to Python 3.9.

**Comment by mowgli** [comment]
By the way, I first tried to look at the forum but I seems to be incompatible with forums. I do not have a account and did not found out how to post without.

**Comment by dae** [comment]
https://faqs.ankiweb.net/when-problems-occur.html

**Comment by mowgli** [comment]
All already done. Except the "Change the video driver" as there is only one, X11, on the system. The system related does also not have any hardware acceleration.

The stack trace with blocking the further funktionality of anki still remains.

**Comment by mowgli** [comment]
Ah yes, as it is gentoo, the anki IS from https://apps.ankiweb.net/downloads/archive/${P}-source.tgz. However, let me tell, that I find no download link on your website. There is nothing undr "Download Anki".

**Comment by Austin-Ray** [comment]
Related Gentoo bug: https://bugs.gentoo.org/795309

**Comment by mowgli** [comment]
Thanks. I missed that bug report. The patch over there fixes the issue.
