### ISSUE TITLE
Quick find and replace, only can find a part ,some is missed

### ISSUE THREAD

**Issue by HillCat** [ankitects/anki#1229]
![image](https://user-images.githubusercontent.com/41800196/121743333-c8f1ea00-cb33-11eb-9cf2-6f222d2b8117.png)

![image](https://user-images.githubusercontent.com/41800196/121743410-e58e2200-cb33-11eb-95e7-a5fe3ce8db36.png)

find and replace, I need to find all the '\<br\>' in my 'stem' field and replace it to empty. but it only can find several one, not all. the others can not find. when I manually operated find and replace, It can find the '\<br\>'  symbol and replace it but need to use the mouse left click button click the field, after that find and replace can work right. I think there is some bug in there. cause me a puzzle.

**Comment by dae** [comment]
https://forums.ankiweb.net/t/html-editor-modifies-note-when-a-field-with-break-tags-is-opened/10772
