### ISSUE TITLE
Japanese hiragana input fails after first keypress in anki

### ISSUE THREAD

**Issue by fuzzyBSc** [ankitects/anki#1239]
Since I upgraded ubuntu to 21.04 I am seeing what appears to be a bad interaction between the Japanese input method and anki or QT, I'm not sure. Japanese hiragana input works by typing the roman characters that make up a word. After typing a few characters you'll get suggestions for the correct Japanese text.

For example, I type the characters for "aimasu", which will appear on screen as あいます, with the suggestion that I probably meant 会います which I can select from a drop-down.

Since upgrading when I type the first character into the anki "Add card" dialog I see the first hiragana あ appear correctly, the "i" character appears to be ignored and maybe is the place things fail, followed by the roman characters for "masu". In other words, aimasu appears on the screen as あmasu as opposed to the correct あいます. The drop-down I would normally expect to see appears only for the あ character and then gets stuck on the screen until I switch back to an English input method and back again to Japanese. I can't enter the full Japanese text, although my web browser and terminal window are able to accept Japanese text without any issues. I can also type normally into the search box within anki for browsing cards, so it seems to be something special about the add card dialog that is causing issues.

My input method shows in the UI as "Japanese (Mozc)" with input mode "hiragana".

c.f. https://bugs.launchpad.net/ubuntu/+source/anki/+bug/1931554

**Comment by dae** [comment]
Closing in favour of the launchpad ticket: https://faqs.ankiweb.net/third-party-linux-packages-and-source-builds-are-not-supported.html

**Comment by fuzzyBSc** [comment]
I have reproduced the same problem on the vanilla build 2.1.44. As with the Ubuntu version, hiragana entry works correctly in the Browse -> Search cards/notes field, and when entering text on an existing card in that browse view. The problem seems only to happen on the add card dialog for me.

**Comment by dae** [comment]
Strange that it works when editing an existing card. I presume you've ruled out add-ons?

**Comment by fuzzyBSc** [comment]
Yeah, I'm not sure exactly how to debug it... It seems like we're running mostly python but it's complied into a binary for deploy? I don't have any add ons unless they've been picked up somehow without my knowledge by adding decks. I usually work between AnkiDroid for actual practice and the Ubuntu deploy for adding new cards after a Japanese lesson. The fact that it works in other apps and works in the browse dialog makes me think it is something about how the add card dialog itself is constructed, but it also looks like a crash of the IME. I might have to do some more research into how to collect IME logs.

**Comment by dae** [comment]
It working in the search area would not surprise me, as often webviews behave differently to the other toolkit widgets, but it's odd that it works in the editing area which is also a webview. The add screen is not a standalone window IIRC, so you could try playing with the window flags to see if that makes any difference.

**Comment by fuzzyBSc** [comment]
I've done some work debugging on the mozc side and raised the problem there, which has now been fixed. Thanks for the help along the way: https://github.com/google/mozc/issues/510

**Comment by dae** [comment]
Thanks for chasing it up; glad to hear they were able to work around the issue.
