### ISSUE TITLE
pin fields forgotten after opening cards screen

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1246]
1. Have one or more fields pinned
2. Open Cards... and close it again (no need to save)
3. Add the card, and the pinned fields are not retained

@hgiesel mind looking into this when you have a chance?

While I have your attention, do you have any other changes in the pipeline that are important to get into 2.1.45? I'd like to start pushing larger changes back until a subsequent release soon, so we can get 2.1.45 out in the not too distant future.

**Comment by hgiesel** [comment]
I will have a look.

The only PR I'd really like to get into it is #1207. Not for any visual changes, but for the extensibility aspect (`<Item></Item>`). I'll try to sit down to it right after and get it into a mergeable state :)
