### ISSUE TITLE
PEP8 pylib

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1256]
0ddd31638815478c2abbb91c4a9ab0331e95545b introduced some helpers so we can get automatic conversion from camelCase methods to snake_case and mark methods as deprecated, and fee486aaa1a8fd4fc301bc6a68ebd7f7784a0b1c started migrating some files so that they pass pylint's invalid-name tests. While the mapping of camelCase to snake_case is automatic, it's still a semi-manual process, as some methods use different names, or take different arguments.

It would be nice to continue doing this with the rest of pylib's codebase, so we can move away from a mix of camelCase and snake_case methods, and so we can improve on the use of variable names like 'x'.

We'll probably want to avoid the following files, as they've been replaced with newer code, or will soon be:

- the importing/exporting code
- the v1 and v2 scheduler code
- the old stats code

The existing helper works with classes, so it doesn't help us in files like utils.py that contain a lot of free-standing
functions. We can use a module-level __getattr__ like at the bottom of decks.py, but we'll probably want to write a helper
to make things easier, and to give us automatic camelCase lookups.

Given that the goal is to get a stable release of 2.1.45 out soon, it probably wasn't the best timing to be starting on these changes 😓 . I'm going to stop here for now; hopefully they will not cause any problems in the next beta. It might be best to hold off on further work on this until 2.1.45 has had a chance to stabilize.

**Comment by dae** [comment]
Did #1451 make this closable?

**Comment by RumovZ** [comment]
> Did #1451 make this closable?

Was this directed at me? I just saw it by chance.

**Comment by dae** [comment]
@RumovZ sorry, I assumed you'd be notified like when you create a PR :-)

**Comment by RumovZ** [comment]
Ah, okay. 🙂 Then to answer the question, I think this was finalised with #1454, provided it was only about naming and no other PEP8 conventions.
