### ISSUE TITLE
Unable to delete addon (Invalid cross-device link)

### ISSUE THREAD

**Issue by digital-carver** [ankitects/anki#1258]
![Screenshot_20210628_005530](https://user-images.githubusercontent.com/28880/123557227-4302af80-d77f-11eb-8fe7-6ae8242a9b6d.png)

I believe the error is happening because my Trash folder is (a link to a folder) in another device. It seems like Anki is trying to create a hard link as part of the deletion process? Since hard links are not allowed across device boundaries, this fails and hence the deletion itself fails. This issue would then arise any time someone's trash folder is in a different device to where their addons folder is.

**Comment by dae** [comment]
The library Anki uses doesn't handle this case: https://github.com/arsenetar/send2trash/issues/26

**Comment by digital-carver** [comment]
Thanks, I'll keep an eye on that issue. For now, just manually deleting the addon folder seems to have worked.
