### ISSUE TITLE
Anki displaying unusual artifacts on Elementary OS with NVIDIA graphics after system suspension

### ISSUE THREAD

**Issue by bugginreporter** [ankitects/anki#1259]
## What Happened

When putting the system to sleep and starting back up, some applications, including Anki, are displaying unusual artifacts.
Sometimes, I need to restart the application, but I can usually just put my mouse over the "pixels" and Anki resumes to be usable again.

I believe this may be a similar issue:
https://askubuntu.com/questions/1273399/problems-with-chrome-browser-after-suspending-the-computer-on-ubuntu-20-04

## Expected Behavior
Anki should resume normally without any artifacts.

## Steps to Reproduce
1. Install Elementary OS on Nvidia GTX 1070TI
2. Install any NVIDIA Driver available from the App Center.
3. Try running Anki from the Flathub repository
4. Suspend the machine
5. Turn on the machine
6. See affected application
![anki_artifacts](https://user-images.githubusercontent.com/86578199/123564666-c5a06480-d7a9-11eb-928a-f89a3b9c11dd.png)

### Logs
I am not aware of any logs I should provide for this issue.

## Platform Information

- Elementary OS 5.1.7 Hera
- AMD Ryzen 7 2700x
- Nvidia GTX 1070 TI

**Comment by dae** [comment]
This is an issue with the toolkit Anki is built on, and thus out of our control I'm afraid.

**Comment by bugginreporter** [comment]
Hi @dae ,

Thanks for the clarification. Can you let me know of the toolkit name so I can open a respective issue there?

Thanks.

**Comment by dae** [comment]
I don't recommend it - you'll need to reproduce the issue outside of Anki, and then the issue will likely sit on their bug tracker for years anyway. They have changes to the GUI handling in the pipeline, so hopefully they will indirectly address the issue.
