### ISSUE TITLE
Dynamically adjust new cards / day

### ISSUE THREAD

**Issue by omgold** [ankitects/anki#1263]
What I want to ask about is the feature which the addon Cardistry provided. It tries to limit the number of learn and young cards in a deck, by not scheduling new cards, when this number is above a certain threshold.

Unfortunately the addon is broken for Anki>2.1.33. Fixing it seems not to be trivial due to major changes in the relevant addon API. Tried to do it myself, but some things important to the implementation are no longer exposed to Python. I assume the original author couldn't fix a fix either, thus there is no update.

Don't know how others feel about it, but to be it is such an important feature, that I didn't switch to a more recent version of Anki. Actually in my opinion it should be a builtin feature of Anki. Not sure what others are doing, whether they manually adjust 'New Cards / Day' all the time, or whether they are content with a fixed number of cards per day on the long term.

In any case, I would like to ask how you feel about adding the feature directly to Anki. The logic is rather trivial so the amount of work should be small compared to the gain in usability. I could help with it, if needed.

**Comment by dae** [comment]
This is supported in the v3 scheduler: https://faqs.ankiweb.net/the-2021-scheduler.html

If you'd like to discuss it further, please create a post over on the forums.

**Comment by omgold** [comment]
Hmm, I believe there might be misunderstanding. I checked the document about the new scheduler and I only found this:

> Another change is that the new count is now capped by the review count.

In the forum thread a opened, I also only got pointed to this.

Although controlling the number of new cards by the number of open reviews is somewhat similar to controlling the number of new cards by the number of young cards, the latter IMHO gives a much nicer behavior.

Thus I would kindly ask to reopen the ticket.

**Comment by dae** [comment]
The forum is the correct place for feature requests. I saw your request, and will keep an eye on demand.

**Comment by Kosezu** [comment]
I would like this feature as well, if it could be implemented. It lets you manually set the mature level of cards, scan ahead multiple days, cap the number of learning/young cards to whatever amount you would like, and lets you bury new cards that are related to current review/learning sibling cards until that sibling exceeds a certain interval in days.

The current V3 scheduler will show a sibling fairly soon, and I think this is the feature @omgold is looking for. We can manually set this to bury any new cards until their siblings have exceeded a certain number of days. 

The code is here: https://github.com/lovac42/Cardistry
