### ISSUE TITLE
[BUG] Cloze deletion incorrectly matching }} in nested mathjax expression

### ISSUE THREAD

**Issue by xaviershay** [ankitects/anki#1268]
Hello, hopefully this the correct place/form to report a bug. Thanks for all your hard work 🙏

## Repro

Create a new card, type "Cloze". Using the following text:

    \[{{c1:: {{x}} }}\]

This does not work as expected, instead causing error formatting and errant punctuation.

![Capture](https://user-images.githubusercontent.com/1714/124231867-318d1f00-db54-11eb-94b8-ac50fb525b9c.PNG)

Motivating real-world example:

    \[ {{c1::cos(x) }} = {{c2:: \sum_{k=0}^\infty (-1)^k \frac{x^{2k}}{2k!} }} \]

(note the `2k}}` causing problems)

## Workaround

I'm not an expert but I believe mathjax is relatively insensitive to whitespace, hence the following text works as expected::

    \[{{c1:: {{x} } }}\]

## Cause Speculation

Sorry I haven't looked at the code and am not even a very sophisticated Anki user, but my first guess would be naive string parsing that's unaware of mathjax syntax, so unable to match balanced `}}`s. That's possibly hard to fix, potentially allowing for an alternate escape/closing pattern would be viable?

## Version

Windows
Version ⁨2.1.44 (b2b3275f)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

**Comment by dae** [comment]
https://docs.ankiweb.net/math.html#cloze-conflicts

**Comment by xaviershay** [comment]
ah thanks, sorry I missed that.

**Comment by dae** [comment]
No prob!
