### ISSUE TITLE
Feature Request to Allow more than one "Add Notes" window on Desktop Anki

### ISSUE THREAD

**Issue by filucian** [ankitects/anki#1282]
_Every day, I create 50-60 cards on Anki. They usually relate to 2-3 different topics._ 

After noting down a complete topic in the Extra section of a Cloze card, I convert the notes into questions and answers. This results in multiple notes/cards for the topic.

Because there are more than 2 topics in progress at any given time, current restriction of ONLY ONE "New Note" Window is restrictive.
  - I have to keep one topic in the New Note window
  - The other topics have to be tracked in the Browser Window using tags.
I need to carefully ensure that the tags, deck names, three sections of Text, Extra and Tags are not mixed up with the other topics on hand.

**_This process would be simplified if I could have a separate "Add Notes" Window for each topic._** This will not need me to worry about things mentioned above.

Please consider this request if it can be a value addition to the other users and does not deviate considerably from your current roadmap.

Thanks.
Nilesh

**Comment by RumovZ** [comment]
There's an add-on for that: https://ankiweb.net/shared/info/354407385

If you still want to suggest this feature, you should do so on the forum as it says when opening an issue:
![grafik](https://user-images.githubusercontent.com/48286681/125104359-93fa9800-e0dd-11eb-8b09-cde1ee955087.png)
