### ISSUE TITLE
deleteDecks does not work on 2.1.44 due to changes to Anki's DeckManager rem function

### ISSUE THREAD

**Issue by baderj** [ankitects/anki#1289]
The latest release of Anki, 2.1.44, requires both ``cardsToo`` and ``childrenToo`` to be set to true when calling ``rem`` on a ``DeckManager``:

```
def rem(self, did: int, cardsToo: bool = True, childrenToo: bool = True) -> None:
        "Remove the deck. If cardsToo, delete any cards inside."
        if isinstance(did, str):
            did = int(did)  
        assert cardsToo and childrenToo
        self.col._backend.remove_deck(did)

```

AnkiConnect passes down ``cardsToo``, which will result in an ``AssertionError`` if ``cardsToo`` is set to  ``false`` (which is also the default).

As a result, not only is the deck not deleted, the way AnkiConnect parses the exception means that the return will have an empty string in the error field ``{"error": ""}``. This is different from the success case ``{"error": null}``, but still not ideal. If the string representation of an exception is empty, then AnkiConnect should return a fallback string.

To fix the issue, simply don't accept the ``cardsToo`` argument anymore. Note that ``rem`` will also be deprecated in the next releases for ``remove``, which no longer has any ``cardsToo`` parameter.

**Comment by dae** [comment]
Did you meant to report this to the AnkiConnect add-on instead of here?

**Comment by baderj** [comment]
Yes, I'm sorry. I opened an issue on the AnkiConnect repository.
