### ISSUE TITLE
 Starting Ease on Anki 2.1.45

### ISSUE THREAD

**Issue by Feripe-a** [ankitects/anki#1317]
I've been using the configuration for Starting Ease and Interval Modifier recommend in [this website](https://tatsumoto-ren.github.io/blog/setting-up-anki.html#options-groups) to prevent [Ease Hell](https://www.youtube.com/watch?v=roR8S9zjUh8). It works pretty well with Schedule V2 ([watch this video](https://streamable.com/lvw0gq)). Schedule V2 uses the Starting ease of 131. Schedule V3, however, does not use Starting ease of 131 ([watch this video](https://streamable.com/p2ef69)). Therefore, when I get one of those cards with 250 ease wrong, its ease will be lowered as it should do so.

**Comment by dae** [comment]
Thanks for the report, a fix will be in the next update.

**Comment by Feripe-a** [comment]
Thank you so much.
