### ISSUE TITLE
Endless "Processing..." on Anki 2.1.46

### ISSUE THREAD

**Issue by Feripe-a** [ankitects/anki#1322]
I've updated my Anki today to 2.1.46 and I've been facing the following issue while editing cards on browser:

https://user-images.githubusercontent.com/84395172/128232112-46d9e34b-798a-41a8-8754-b6cc38c6b1b9.mp4

I've closed Anki and continue to edit cards. The issue happened again while I was coping something to GoldenDict. So it tested it again:

https://user-images.githubusercontent.com/84395172/128232527-005e3710-5f68-46ff-be23-131997e37fc1.mp4

I kept editing cards without coping words to GoldenDict, the error didn't happen. So I thought it might have something to do with "coping and pasting". So I tested it:

https://user-images.githubusercontent.com/84395172/128232923-99c390c9-de24-40af-bb90-193f7d2e664d.mp4

I retasted it without using any addons and the error vanished:

https://user-images.githubusercontent.com/84395172/128233160-cc486aae-62e0-4aa7-9e15-c797add6aacc.mp4

Here's my Debug info:
    
    Anki 2.1.46 (94913ec2) Python 3.9.6 Qt 5.15.2 PyQt 5.15.4
    Platform: Linux
    Flags: frz=False ao=True sv=2
    Add-ons, last update check: 2021-08-03 21:22:40
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AJT Browser Play Button ['182970692', 2021-07-21T20:17, 'None', mod]
    AJT Flexible Grading ['1715096333', 2021-07-30T16:02, 'None', '']
    Advanced Browser ['874215009', 2021-07-22T18:14, 'None', '']
    Anki Zoom ['538879081', 2020-04-03T21:20, 'v1.1.3', '']
    AnkiConnect ['2055492159', 2021-07-13T21:59, 'None', mod]
    JaPitch ['1225470483', 2021-06-03T22:57, 'None', mod]
    Japanese Support ['3918629684', 2019-07-12T03:54, 'None', mod]
    Learn now Button ['1021636467', 2021-07-31T04:16, 'None', '']
    MergeNotes ['1425504015', 2021-03-01T16:02, 'None', mod]
    Mortician ['1255924302', 2021-08-01T04:35, 'None', mod]
    Paste Images As WebP ['1151815987', 2021-07-21T19:32, 'None', mod]
    Quick Colour Changing ['2491935955', 2017-08-28T09:48, 'None', mod]
    RefoldEase ['819023663', 2021-07-31T22:35, 'None', mod]
    Simple Free Forvo Audio Downloader ['560814150', 2021-02-18T18:58, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1021636467 1151815987 1225470483 1255924302 1425504015 1715096333 182970692 2055492159 2491935955 3918629684 538879081 560814150 819023663 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Kanji Grid ['909972618', 2019-01-09T20:40, 'None', '']
    More Overview Stats 21 ['738807903', 2021-07-30T16:13, 'None', '']
    Reset Card Scheduling ['300884351', 2018-09-18T13:17, 'None', '']
    True Retention by Card Maturity Simplified ['1779060522', 2020-06-28T10:45, 'None', '']
    Yomichan Forvo Server ['580654285', 2021-03-22T17:48, 'None', '']

I think that **AJT Browser Play Button ['182970692', 2021-07-21T20:17, 'None', mod]**    **Advanced Browser ['874215009', 2021-07-22T18:14, 'None', '']**    **Paste Images As WebP ['1151815987', 2021-07-21T19:32, 'None', mod]**    **Simple Free Forvo Audio Downloader ['560814150', 2021-02-18T18:58, 'None', mod]** might have something to do with the error. I'm not a programmer, so I cant test it myself.

**Comment by dae** [comment]
You can disable some add-ons and test until you figure out the cause. Once you find the culprit, you'll need to report the issue to the add-on author.

**Comment by Feripe-a** [comment]
👍

**Comment by Feripe-a** [comment]
|||update|||
I found the source of the error. It was JaPitch ['1225470483', 2021-06-03T22:57, 'None', mod]. I contacted the author. He had faced with the same issue, he didn't know how to fix it. It was related to "on_flush". JaPitch was based on an old add-on, the author rewrote the addon with newer Anki code. The error was fixed.
Sorry for reporting such issue. It won't happen again.

**Comment by dae** [comment]
No problem, glad you were able to get to resolve the issue.
