### ISSUE TITLE
Hook 'review_did_undo' not called on V3 scheduler

### ISSUE THREAD

**Issue by TheDabblingDuck** [ankitects/anki#1323]
Anki version: 2.4.6
Platform: Mac

Steps to reproduce:

1. Assign a function to the hook by running the following debug console:
```
def myundo(card_id):
    showInfo('review_did_undo hook called')
gui_hooks.review_did_undo.append(myundo)
```
2.  Dialog box will pop up when undoing a card using V2 scheduler, but will not show when 'V3 Scheduler' is checked in Anki settings.

**Comment by dae** [comment]
This was deliberate - the new undo code does not behave the same way, and existing callers may be performing operations that clear the undo queue, or make assumptions that don't apply to v3. What does your add-on use the hook for?

**Comment by TheDabblingDuck** [comment]
Ok, thanks for letting me know about that. My addon uses the hook to detect when a card review has an undo in order to show a feedback popup.

I guess the alternative now would be to catch the "state_did_undo" hook instead and then check to see if Anki is currently on the reviewer screen? Is there a way I can see which Anki versions and scheduler versions support the "state_did_undo" hook (and other hooks)?

**Comment by dae** [comment]
state_did_undo was introduced in 2.1.45. The operation name can be compared against, but it will change depending on the user's language. Anki already shows a popup when undoing - why do you need a custom one when the undone operation is a review?

**Comment by TheDabblingDuck** [comment]
My addon is a remote that shows feedback for again/hard/good/easy and I wanted to feedback in the same style for undo. I found another way of implementing it.

Thanks for the info about the hooks.
