### ISSUE TITLE
Using Svelte across compilation units

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1328]
Following on from https://github.com/hgiesel/anki_new_format_pack/issues/2 and https://github.com/sveltejs/svelte/issues/6530

Correct me if I'm wrong @hgiesel, but isn't this a fairly serious problem? The breakage happened in a minor Svelte release, not a major version bump. In the above case you were able to fix it by updating the Svelte version your add-on was using, but think about what will happen when Anki wants to update to a newer Svelte version - we run the risk of breaking any existing Svelte-based add-ons, and add-on authors may need to build again with a new Svelte version just to fix things.

I'd previously thought that perhaps we could work around it by providing the Svelte files so that users could include them in their add-on compilation process, but I presume that would not help in this case? If Svelte expects all files to be compiled with the same compiler in a single compile step, it seems like the approach we have is not going to be viable.

**Comment by dae** [comment]
Oh, I've just need you've posted #1327 while I was writing this :-) I've only given it a quick scan so far, but a quick question - does this solve the problem with differing compiler versions, or is it only targeted at resolving the binding issues mentioned in the svelte repo ticket?

**Comment by hgiesel** [comment]
The PR is adressing the binding issue, not the issue with differing compiler versions.

Looking at https://github.com/sveltejs/svelte/issues/6584, it seems to me that we're not the only ones affected and that this kind of breaking after a minor version is not common. In fact, the people in the issue seem to have the same use case as ours: combining different compilation units.

However it is worrying that after 13 days, no Svelte maintainer has answered to the proposed solution in this issue yet.

**Comment by hgiesel** [comment]
Also one thing to keep I noticed: The error caused in  hgiesel/anki_new_format_pack#2, was due to the add-on using a newer Svelte version, compared to Anki 2.1.46, not the other way around.
Quickly testing Anki with the newest Svelte version (from #1327) against the updated New Format Pack does not show the same issue.

**Comment by dae** [comment]
Thanks, that is a relief to hear
