### ISSUE TITLE
time_taken is not taking the answer time but the scoring time

### ISSUE THREAD

**Issue by awesome-rdash** [ankitects/anki#1334]
Hello,

The **time_taken** function that is used to calculate how much time it takes to anwser a question takes into account the moment I grade my anwser. Would it be not correct to measure the time it takes to reveal the anwser instead of grading?

I'm not good enough to write a code that would correct this behaviour but the process I would do is:

1. When pressing the reveal anwser button, calculate the time taken by using the same code and store it in a variable.
2. When pressing the grading button, use that variable to feed the output of time_taken...

https://github.com/ankitects/anki/blob/7ba35b7249e1ac829843f365105a13c6209d4f57/pylib/anki/cards.py#L188

Thanks for taking this into considaration,
Justin

**Comment by dae** [comment]
Anki changed from the behaviour you describe back in 2008. Given the relative lack of opposition since then, I'm afraid it's likely to stay as-is.
