### ISSUE TITLE
Links in cards with `target="_blank"` don't open when clicked

### ISSUE THREAD

**Issue by casey** [ankitects/anki#1339]
I use links with the target attribute set to `_blank` to open them in new tabs when clicked on AnkiWeb. It looks like such links don't work in Anki desktop, when I click them there, nothing happens.

An example of such a link is:

```html
<a href="https://ankiweb.net/" target="_blank">link</a>
```

**Comment by naomiceron** [comment]
Hello! I would like to give this issue a try, could you assign it to me? :)

**Comment by danishprakash** [comment]
@dae is this something a new contributor can pick up? I'd like to work on this, thanks!

**Comment by dae** [comment]
Sure, go for it. I'm guessing it's connected to the link/request handling in webview.py.
