### ISSUE TITLE
Avoid JS globals where possible?

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1341]
(for after the .47 release)

@hgiesel is it practical to move almost everything we export under an 'anki' namespace? eg components→anki.components, $editorToolbar→anki.editorToolbarPromise, etc?

- Do you agree it's a good idea?
- We'll of course need to leave around various globals that people are already relying on. Maybe with a deprecation message to direct people to the correct location?
- Maybe we could add a routine in ts/lib that adds an entry to the anki namespace, creating it if it doesn't already exist?
- Presumably in cases where we're using --global-name, we'll need to switch to an approach like editor/index_wrapper.ts (with it perhaps using the routine in the previous point)?

**Comment by hgiesel** [comment]
I agree it's a good idea.

After 12ea482c8768e7e6f33e4e531682968d6ef077b6, I thought it would also be nice to able to use the `import` syntax for ankis functionality.

For example

```typescript
const {
    IconButton,
    contextKeys,
} = anki.components;
// becomes
import { IconButton, contextKeys } from "anki/components";
// or without compiler
const { IconButton, contextKeys } = require("anki/components");
```

This might also prevent issues, where addon devs might be tempted to modify the `anki` global.

Another danger of just extending the `anki` object I see is with ease of understanding. I imagine the following situation: We expose some utility function `do_thing()` in the editor. An add-on dev now wants to write an add-on for the deck-options screen, and wants to use this `do_thing()` utility, so he goes:

```typescript
// my-deck-options-addon.js
const { do_thing } = anki;

do_thing();
```
And gets an error "do_thing is not a function". Even though in a different context (webview) this would work. However if we exported those libraries under different names, this would make it a bit clearer:

```typescript
// editor-addon.js
const { do_thing } = require("anki/editor");
/* works */

// deck-options-addon.js
const { do_thing } = require("anki/editor");
/* Error: Cannot require(anki/editor) at runtime. */
```

And once we start having bigger webviews doing more things (let's say the browser) we'll have multiple "packages" exposed in the same webview:
`require("anki/editor"); require("anki/browser"); require("anki/sidebar");`

Concerning the deprecation message, maybe we can use the [DOM Proxy API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) for this. Somewhere along the lines of [this](https://www.typescriptlang.org/play?#code/FAehAIBsEsCMDoBWBnYBjA9gO2QF3AIZYDW0AXOAEoCmmATgCYA8ed0WA5gDSFYCeAPnABecAG8AvgG5gwIqXgAzDBhHhFAVyxpc0bAAoAlOPCYcGSNXiQMHfQCJlqgO4FkpgpEsN7hqeGk5Emh4WAI6NU1tXQNjMVNsZAsrGzt7MIjXdzRPb19-QPRE-AZqAAc6WgJcagYKfVZ2DgAfZD4AW1gLQwBtAF01HuBwEfBHFXsuYD7ZMzxwCowADz41LGpncAAFOmW+fXloHjFh0Y5qXHrccPPcHjKeSrRqaAA3ajpjYSET0b-waCKcD6UoVKo1BjwdhoSAaUrIfRlQxxU7-f5zZLWWz6AAGhwoABIxABlXBsTiIwwSAHuUFPaq1eA4wyo-4SWRokaVXAaOhYcDXOi3Hqk8l2JF9GR-dkSPyyMCEBgMbBIVBzfDxJw8DIBNSLFYyYBOIwyDImoA).

**Comment by dae** [comment]
Closing this, as recent code is moving in this direction.
