### ISSUE TITLE
Ligature for Indian (Devanagari) characters not supported

### ISSUE THREAD

**Issue by damiansp** [ankitects/anki#1346]
For at least some Indian scripts (e.g., Devanagari for Hindi), cannot input ligature characters in Anki (2.1.46).
For example, the combination of प "p" + र "r" should be the ligature character प्र "pr". 

Using the QWERTY input method on Mac OSX (11.3/Big Sur), this is input by typing p-f-r (where f is the key used to indicate that the next character typed should be combined with the previous), but attempting to do this in Anki results in the incorrect input: प््र.  The only way around it is to type in another process and then paste into Anki.

This problem did not happen in earlier versions, though I am unsure where the break occurred, as I missed some updates (may also be that the breaking change happened in the OS...?)

**Comment by dae** [comment]
Can you reproduce this with the qt6 build?

https://forums.ankiweb.net/t/new-toolkit-and-packaging-test-round-2/14513

**Comment by damiansp** [comment]
Sorry for the slow reply... I was not intending to be a developer on this, just wanted to alert the team to the problem.  Thanks and best wishes.

**Comment by dae** [comment]
I presume it's the same issue as https://bugreports.qt.io/browse/QTBUG-71718, which is fixed in the Qt6 build.
