### ISSUE TITLE
Wait until mediasrv.py to completely start

### ISSUE THREAD

**Issue by evandrocoan** [ankitects/anki#1362]
Some rare times when I open anki, I see the top toolbar with unloaded/not found image (sync button maybe?). I think this is because we do not wait until the waitress/wsi server to completely start up as done in: https://github.com/Pylons/webtest/blob/4b8a3ebf984185ff4fefb31b4d0cf82682e1fcf7/webtest/http.py#L123-L132
```python
    def wait(self, retries=30):
        """Wait until the server is started"""
        running = check_server(self.adj.host, self.adj.port,
                               '/__application__', retries=retries)
        if running:
            return True
        try:
            self.shutdown()
        finally:
            return False

def check_server(host, port, path_info='/', timeout=3, retries=30):
    """Perform a request until the server reply"""
    if retries < 0:
        return 0
    time.sleep(.3)
    for i in range(retries):
        try:
            conn = http_client.HTTPConnection(host, int(port), timeout=timeout)
            conn.request('GET', path_info)
            res = conn.getresponse()
            return res.status
        except (socket.error, http_client.HTTPException):
            time.sleep(.3)
    return 0
```

May be related to https://github.com/ankitects/anki/issues/1137 - Investigate page-loading race conditions

**Comment by evandrocoan** [comment]
Here is a referene image:
![image](https://user-images.githubusercontent.com/5332158/132933019-eaafc6b0-505f-4cc9-b620-c284fa1c9ccc.png)

**Comment by dae** [comment]
Hmm, it's possible this would help, though the issue may actually lie in Chromium. I gather you're running a custom fork of Anki, so maybe it would be worth trying to add this and seeing if the display issue comes back within a month or so?

**Comment by evandrocoan** [comment]
If I recall correctly, I also had this issue when running Anki from this repository, when I did my first bazel setup. Today I run it from my fork, but it did not change much other than some shortcuts and some code from my pull requests. Here is a diff for it: https://github.com/ankitects/anki/pull/1367

I could add this code, but I am not sure where should I put it. Can you point the line I should add this so it blocks the qt webview start-up (until the mediasrv.py starts up)?

**Comment by dae** [comment]
Maybe in setupMediaServer()?
