### ISSUE TITLE
adding missing wayland plugins

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1368]
From #1061:

> Actually Qt and PyQt have native wayland support. The reason that the release package cannot run in wayland natively before is because some files of Qt5 on wayland support is missing from the package. I found that by including these files, the release Anki can run natively in wayland
> 
> anki/bin/PyQt5/Qt/plugins/wayland-shell-integration
> anki/bin/PyQt5/Qt/plugins/wayland-decoration-client
> anki/bin/PyQt5/Qt/plugins/wayland-graphics-integration-client
> 
> So please just add these files manually or change the packaging script to include them.

@goduck777 I'll let you know when there's a beta available with these changes

**Comment by dae** [comment]
Please give the rc a try: https://forums.ankiweb.net/t/2-1-48-release-candidate/13268

**Comment by goduck777** [comment]
The new rc version works well in KDE wayland.

Thank you.

**Comment by dae** [comment]
Due to some reported issues, this'll need to default to off in the stable release, but the plugins will remain included (thanks for the tip about them!). To enable it, you'll need to define ANKI_WAYLAND=1 before starting Anki.

**Comment by xrishox** [comment]
is this something that should make it by default in one of the upcoming releases or is this put back on to the backburner?

**Comment by dae** [comment]
It's in .48
