### ISSUE TITLE
fail to install in ubuntu

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [ankitects/anki#1373]
After runing `sudo ./install.sh` in ubuntu 21.04, I can't launch anki. I get errors below:
```bash
  File "runanki.py", line 4, in <module>
  File "aqt/__init__.py", line 437, in run
  File "aqt/__init__.py", line 492, in _run
  File "aqt/profiles.py", line 134, in setupMeta
  File "aqt/profiles.py", line 501, in _loadMeta
resetting corrupt _global
Qt info: Could not load the Qt platform plugin "xcb" in "" even though it was found. 
Qt fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
 
Aborted (core dumped)
```

**Comment by Xinyu-Wu-0000** [comment]
fixed by `sudo apt install qtwayland5`

**Comment by abdusamed91** [comment]
+ issue popped up again and that command fixed this issue.

**Comment by 12kittens** [comment]
I have the same error with Ubuntu 24 over X11, so `qtwayland5` didn't work.

**Comment by abdnh** [comment]
If installing the libraries listed in the [manual](https://docs.ankiweb.net/platform/linux/installing.html#requirements) doesn't help, you might have luck installing these: https://github.com/ankitects/anki/blob/81eefc5f7128988a54ff5bb58a6b08697d1214a8/.github/actions/setup-anki/action.yml#L11
