### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [ankitects/anki#1380]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by dae** [comment]
Thank you! If you could provide more info over on https://anki.tenderapp.com/discussion/new, that would be great. I'll get a SECURITY.md added in the next day or so.

**Comment by homocomputeris** [comment]
Despite the commit message, some addons still use some of the removed methods: https://github.com/Ajatt-Tools/mergenotes/issues/6

**Comment by tatsumoto-ren** [comment]
It would be nice to see `entsToTxt` back. If not, I'll do something to work around it by the time 2.1.50 comes out.

**Comment by homocomputeris** [comment]
Yup, MergeNotes provides the automatic cards merge function which is **very** useful while Anki itself can only tag duplicates
