### ISSUE TITLE
media deletion needs to be run in the background

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1389]
https://forums.ankiweb.net/t/enhance-delete-bulk-of-unused-media-files-seems-a-blocked-process/13588

**Comment by androidpcguy** [comment]
I'll take this issue

**Comment by dae** [comment]
Should be fairly simple, it basically just needs to use mw.taskman.with_progress()

**Comment by dae** [comment]
Actually QueryOp() might be a better choice

**Comment by dae** [comment]
Please let us know if you're still working on this, or whether it's free for someone else to take.

**Comment by dae** [comment]
I'd like to get this fixed soon - if you don't think you'll be able to finish it in the next 7 days, please let us know and someone else can take over.

**Comment by androidpcguy** [comment]
Won't be able to complete this by tomorrow.

**Comment by dae** [comment]
No problem, thanks for letting us know.
