### ISSUE TITLE
consider removing old Documents/Anki migration

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1390]
Anki used to store its files in ~/Anki or ~/Documents/Anki. It was changed ~ 4 years ago in 4c9a45bd0deb1fb7f5319788ed6ca400eadfc7a3, with the old folders being automatically moved to the new location. This occasionally [trips up people](https://forums.ankiweb.net/t/anki-moves-anki-folder-to-local-share-anki2-linux/13623) who manually create those folders, and it may be about time we stop doing this.

**Comment by blue-putty** [comment]
Hi Damien! Would you be interested in a pull request addressing this change?

**Comment by dae** [comment]
That would be great, thank you. We can probably just cut out the code - I considered printing a warning or something, but there are very few users who were not already on 2.0.52, so we probably don't need to preserve it.

**Comment by dae** [comment]
No need to work on this anymore - it turns out the migration code is a minor impediment to updating to a later Qt, so it's easier for me to strip it out now as part of that work.
