### ISSUE TITLE
4294967295 Reviews

### ISSUE THREAD

**Issue by Munzu** [ankitects/anki#1395]
![image](https://user-images.githubusercontent.com/31477160/135123829-780b8e7e-8f41-49c3-a8f6-29f5562ba0a7.png)

This just happened to me and another Reddit user 10 days ago 
https://www.reddit.com/r/Anki/comments/pqnnoo/i_swear_i_dont_have_4_billion_cards_due_today/

It stayed that way when I answered this card and the ones after it but it returned to normal when I synced.
I haven't been able to reproduce it yet.

**Comment by dae** [comment]
This is already fixed. For future problems, please follow https://faqs.ankiweb.net/when-problems-occur.html
