### ISSUE TITLE
Jarring fonts

### ISSUE THREAD

**Issue by Carrot-Circumflex** [ankitects/anki#1411]
The fonts in the browser don't display properly, specifically in the question and answer columns. The font renders smaller than it should:

![image](https://user-images.githubusercontent.com/51193876/136490223-6bbc5a42-4019-4904-b29c-fd0df008fcd4.png)

Version: 2.1.48 (Linux)

Prior to the last update, everything was fine

**Comment by dae** [comment]
Please use the forums for future reports.

If you click on Cards... and then the button in the top right, do you have a custom browser appearance defined?
