### ISSUE TITLE
Toggling showing cards/notes is broken

### ISSUE THREAD

**Issue by Carrot-Circumflex** [ankitects/anki#1412]
The new feature doesn't work:

![image](https://user-images.githubusercontent.com/51193876/136490694-bc1eb3cb-519a-4e93-b4ce-7fe752214f13.png)

Version: 2.1.48 (Linux)

**Comment by RumovZ** [comment]
What's not working there? At any rate, you should follow the steps in https://faqs.ankiweb.net/when-problems-occur.html and post over on https://forums.ankiweb.net/ if problems persist.
