### ISSUE TITLE
V2 Scheduler Fuzz not working for cards with short intervals (<= 4 days)?

### ISSUE THREAD

**Issue by kuroahna** [ankitects/anki#1416]
OS: Windows 10
Anki Version: 2.1.48 (fb07bad3)
Python: 3.8.6
Qt: 5.14.2
PyQt: 5.14.2

I'm using the [load-balanced-scheduler addon](https://github.com/xquercus/load-balanced-scheduler) which basically patches the `_fuzzedIvl` function in the v2 scheduler by instead of using a random interval from the fuzz range, we choose the interval from the fuzz range that has the least amount of cards.

However, we noticed there's an issue with the algorithm where the best interval chosen by the load balancer addon isn't being respected and seemed to be "off by 1" sometimes. I've done some analysis in the [issue thread](https://github.com/xquercus/load-balanced-scheduler/issues/11#issuecomment-937912581) but the issue seems to arise from the `_constrainedIvl` function:

```python
    def _constrainedIvl(
        self, ivl: float, conf: QueueConfig, prev: int, fuzz: bool
    ) -> int:
        ivl = int(ivl * conf.get("ivlFct", 1))
        if fuzz:
            ivl = self._fuzzedIvl(ivl)
        ivl = max(ivl, prev + 1, 1)
        ivl = min(ivl, conf["maxIvl"])
        return int(ivl)
```

Particularly, this line `ivl = max(ivl, prev + 1, 1)`

For my Anki settings, I have interval modifier set to 100%, hard interval set to 120%, easy bonus set to 130%, starting ease set to 250% and new interval set to 20%, so the calculations below will reflect accordingly.

Looking at the scheduler code in `2.1.48`: https://github.com/ankitects/anki/blob/2.1.48/pylib/anki/scheduler/v2.py

From what I understand (correct me if I'm wrong, as I don't fully understand anki's scheduler code as I've only tried reading and playing around with it for a few hours), but the Good button's interval is dependent on the Hard button's calculated interval. And likewise, the Easy button's interval is dependent on the Good button's calculated interval. This can be seen in the `_nextRevIvl` function:

```python
    def _nextRevIvl(self, card: Card, ease: int, fuzz: bool) -> int:
        "Next review interval for CARD, given EASE."
        delay = self._daysLate(card)
        conf = self._revConf(card)
        fct = card.factor / 1000
        hardFactor = conf.get("hardFactor", 1.2)
        if hardFactor > 1:
            hardMin = card.ivl
        else:
            hardMin = 0
        ivl2 = self._constrainedIvl(card.ivl * hardFactor, conf, hardMin, fuzz)
        if ease == BUTTON_TWO:
            return ivl2

        ivl3 = self._constrainedIvl((card.ivl + delay // 2) * fct, conf, ivl2, fuzz)
        if ease == BUTTON_THREE:
            return ivl3

        ivl4 = self._constrainedIvl(
            (card.ivl + delay) * fct * conf["ease4"], conf, ivl3, fuzz
        )
        return ivl4
```

Also, we have:
```python
    def _fuzzedIvl(self, ivl: int) -> int:
        min, max = self._fuzzIvlRange(ivl)
        return random.randint(min, max)

    def _fuzzIvlRange(self, ivl: int) -> Tuple[int, int]:
        if ivl < 2:
            return (1, 1)
        elif ivl == 2:
            return (2, 3)
        elif ivl < 7:
            fuzz = int(ivl * 0.25)
        elif ivl < 30:
            fuzz = max(2, int(ivl * 0.15))
        else:
            fuzz = max(4, int(ivl * 0.05))
        # fuzz at least a day
        fuzz = max(fuzz, 1)
        return (ivl - fuzz, ivl + fuzz)
```

**Hard Button Interval**
So if we have a card with `card.ivl = 1` and `hardFactor = 1.2` then `card.ivl * hardFactor = 1.2`. And since `hardFactor = 1.2 > 1`, then `hardMin = card.ivl`. And assuming `fuzz = true`, then we call `ivl2 = self._constrainedIvl(card.ivl * hardFactor, conf, hardMin, fuzz)` and hence, this is `ivl2 = self._constrainedIvl(1.2, conf, 1, true)`.

In `_constrainedIvl`, we first calculate `ivl = int(ivl * conf.get("ivlFct", 1)) = int(1.2 * 1) = int(1.2) = 1`. Then since `fuzz = true`, we call `ivl = self._fuzzedIvl(ivl) = self._fuzzedIvl(1) = 1`. This returns `1` because  the fuzz interval range for an interval of 1 will return `[1, 1]`, and randomizing between a range of `[1,1]` will return `1`.

Then we call `ivl = max(ivl, prev + 1, 1) = max(1, 1 + 1, 1) = max(1, 2, 1) = 2`

And `ivl = min(ivl, conf["maxIvl"]) = min(2, 36500) = 2`

Finally, `return int(ivl) = int(2) = 2`

So `ivl2 = self._constrainedIvl(card.ivl * hardFactor, conf, hardMin, fuzz) = self._constrainedIvl(1.2, conf, 1, true) = 2`

**Good Button Interval**
Now, assuming `delay = 0` (since we're reviewing on the day it's due) and `fct = card.factor / 1000 = 2500 / 1000 = 2.5`, we call `ivl3 = self._constrainedIvl((card.ivl + delay // 2) * fct, conf, ivl2, fuzz) = self._constrainedIvl((1 + 0 // 2) * 2.5, conf, 2, true) = self._constrainedIvl((1 + 0) * 2.5, conf, 2, true) = self._constrainedIvl(2.5, conf, 2, true)`. 

In `_constrainedIvl`, we first calculate `ivl = int(ivl * conf.get("ivlFct", 1)) = int(2.5 * 1) = int(2.5) = 2`. Then since `fuzz = true`, we call `ivl = self._fuzzedIvl(ivl) = self._fuzzedIvl(2) = 2 OR 3`. This returns `2` OR `3` because the fuzz interval range for an interval of 2 will return `[2, 3]`, and randomizing between a range of `[2, 3]` will return `2` or `3`

**Case 1:** `ivl = 2`
Then we call `ivl = max(ivl, prev + 1, 1) = max(2, 2 + 1, 1) = max(2, 3, 1) = 3`. Note, `prev = 2` because this was the interval we calculated for the Hard Button interval. **But hold on**, the fuzz interval we calculated should've set the card's interval to `2` days, not `3`.

And to finish it off, we call `ivl = min(ivl, conf["maxIvl"]) = min(3, 36500) = 3` and finally `return int(ivl) = int(3) = 3`.

So pressing the Good Button will give it an interval of `ivl3 = self._constrainedIvl(card.ivl * hardFactor, conf, hardMin, fuzz) = self._constrainedIvl(2.5, conf, 2, true) = 3` days, despite the fuzz interval being calculated should've set `ivl3 = 2`, not `ivl3 = 3`.

**Case 2:** `ivl = 3`
On the other hand, we call `ivl = max(ivl, prev + 1, 1) = max(3, 2 + 1, 1) = max(3, 3, 1) = 3`. Note, `prev = 2` because this was the interval we calculated for the Hard Button interval. 

And to finish it off, we call `ivl = min(ivl, conf["maxIvl"]) = min(3, 36500) = 3` and finally `return int(ivl) = int(3) = 3`.

So pressing the Good Button will give it an interval of `ivl3 = self._constrainedIvl(card.ivl * hardFactor, conf, hardMin, fuzz) = self._constrainedIvl(2.5, conf, 2, true) = 3` days, which is expected for this case.

**Summary:** So pressing the good button with a card interval of 1 day (and the above assumed settings) with fuzz enabled will **always** force the next Good interval to be 3 days despite it should being fuzzed between 2 or 3 days (assuming this is the expected behavior).

Note, I believe the fuzz logic doesn't work until the Good button's interval is >= 4 days. So once the card has a longer interval (ie good button interval says 7 days), fuzzing the card will work properly.

I'm also looking at the [v1 scheduler code from 2018](https://github.com/ankitects/anki/blob/b5785f7ec8b3f95f88ba63cc43f9ee7ce829241a/anki/sched.py#L882) 

And using the same values as above, 

```python
    def _nextRevIvl(self, card, ease):
        "Ideal next interval for CARD, given EASE."
        delay = self._daysLate(card)
        conf = self._revConf(card)
        fct = card.factor / 1000
        ivl2 = self._constrainedIvl((card.ivl + delay // 4) * 1.2, conf, card.ivl)
        ivl3 = self._constrainedIvl((card.ivl + delay // 2) * fct, conf, ivl2)
        ivl4 = self._constrainedIvl(
            (card.ivl + delay) * fct * conf['ease4'], conf, ivl3)
        if ease == 2:
            interval = ivl2
        elif ease == 3:
            interval = ivl3
        elif ease == 4:
            interval = ivl4
        # interval capped?
        return min(interval, conf['maxIvl'])
```

Here, we get `ivl2 = 2` and `ivl3 = 3` as well (note `_constrainedIvl` function is different in v1 scheduler 2018 compared to v2), but 

```python
    def _updateRevIvl(self, card, ease):
        idealIvl = self._nextRevIvl(card, ease)
        card.ivl = min(max(self._adjRevIvl(card, idealIvl), card.ivl+1),
                       self._revConf(card)['maxIvl'])
```

Here, since assuming we press the Good button (so `ease = 3`) and `ivl3 = 3`, then `idealIvl = self._nextRevIvl(card, ease) = 3`. And so, `card.ivl = min(max(self._adjRevIvl(card, idealIvl), card.ivl+1), self._revConf(card)['maxIvl']) = min(max(self._adjRevIvl(card, 3), 1+1), 36500) = min(max(self._adjRevIvl(card, 3), 2), 36500)`

Note:
```python
    def _adjRevIvl(self, card, idealIvl):
        if self._spreadRev:
            idealIvl = self._fuzzedIvl(idealIvl)
        return idealIvl
```

And `_fuzzedIvl(idealIvl) = _fuzzedIvl(3) = 2 OR 3 OR 4`. So there's even a **discrepancy here** with v1 and v2 scheduler (this one gives a fuzzed interval of 2, 3, or 4, compared to v2, which gives it 2 or 3).

**Case 1**: `_adjRevIvl` returns `2`
So `card.ivl = min(max(self._adjRevIvl(card, idealIvl), card.ivl+1), self._revConf(card)['maxIvl']) = min(max(self._adjRevIvl(card, 3), 2), 36500) = min(max(2, 2), 36500) = min(2, 36500) = 2`

**Case 2**: `_adjRevIvl` returns `3`
So `card.ivl = min(max(self._adjRevIvl(card, idealIvl), card.ivl+1), self._revConf(card)['maxIvl']) = min(max(self._adjRevIvl(card, 3), 2), 36500) = min(max(3, 2), 36500) = min(3, 36500) = 3`

**Case 3**: `_adjRevIvl` returns `4`
So `card.ivl = min(max(self._adjRevIvl(card, idealIvl), card.ivl+1), self._revConf(card)['maxIvl']) = min(max(self._adjRevIvl(card, 3), 2), 36500) = min(max(4, 2), 36500) = min(4, 36500) = 4`

In all 3 cases, the fuzz works fine with the v1 scheduler.

So I'm wondering, is this expected behavior in the v2 scheduler? Or is this actually a bug?

EDIT: Seems like the change to these functions happened in this commit: https://github.com/ankitects/anki/commit/575f61c384ea5906535d23e0df59d06ceee45a49

**Comment by dae** [comment]
I'm afraid I don't think it's the best way to handle it - it requires a reasonably expensive table scan for each card answer, and all that work goes to waste if you take a day off anyway. If you're studying consistently things should be fairly balanced already, and you can use 'set due date' to shuffle things around if you find a peak has developed.

**Comment by dae** [comment]
Thanks for giving it some thought. I consider the v2 scheduler to be in "maintenance mode" at this point - if there was a simple fix that had a low risk of regressions then it might make sense, but anything more elaborate is not really appropriate.

We could still potentially address this in v3 however. It won't help the add-on use case, but fuzz is useful even without add-ons. Would you be interested in doing some digging into states/review.rs and seeing how practical a change might be?

**Comment by RumovZ** [comment]
> Would you be interested in doing some digging into states/review.rs and seeing how practical a change might be?

Definitely. Here is what I have in mind in more detail:

1. Compute a generic fuzz factor, between 0 and 1, in advance. It should probably be a field of `StateContext`.
2. For every interval, compute the fuzz range as before, but then apply all effective constraints to the upper and lower limits.
3. Use the fuzz factor to select the final interval from the fuzz range.

I'm not overly familiar with the relevant code, so please let me know if you can already see any flaws with this approach.
These are the advantages I see:

- The three intervals get fuzzed by the same amount (proportionally), so the differences won't get diminished or inflated through fuzz.
- The final interval is sampled from a uniform distribution.
- Compared to the detective work that @kuroahna had to do to find this issue, it's easier to infer the actual intervals from the code or reverse-engineer from the shown intervals.
- It's easier to test as we only have one random variable, and that can be set manually and passed into the interval routines.

**Comment by dae** [comment]
> Compute a generic fuzz factor, between 0 and 1, in advance. It should probably be a field of StateContext

Presumably we'd only need to use it in passing_(non)early_review_intervals() and the subroutines it calls - might it be better to compute it there, instead of storing it in the longer-lived StateContext?

 Having a single fuzz ratio that is applied to each fuzz range sounds 
reasonable at first pass, but one possible complicating factor is that large fuzz ranges can have negative deltas, eg a 2 day interval will only be 2 or 3 days, but a 10 day interval will be something like 7.5~13.5, so a ratio of 0.0~1.0 might not work?

**Comment by RumovZ** [comment]
The formula would be `lower_bound + fuzz_factor * (upper_bound - lower_bound)`, so that 0 always results in the lower bound and 1 in the upper bound. In the case of 2 to 3 days: `2 + fuzz_factor`. In the case of 7.5 to 13.5 days: `7.5 + fuzz_factor * 6`.
To achieve a uniform distribution, we would have to round first, though, and then with rounded values and a fuzz factor from the half-open interval `[0, 1)`:
`(lower_bound + fuzz_factor * (1 + upper_bound - lower_bound)).floor()`

**Comment by dae** [comment]
Ah, now I get you. Sounds good!

**Comment by RumovZ** [comment]
> might it be better to compute it there, instead of storing it in the longer-lived StateContext?

`StateContext.fuzz_seed` is currently used to disable fuzzing in unit tests. I thought it would be easiest if the new `fuzz_factor` replaced this field and was used likewise.

**Comment by dae** [comment]
The seed is also used a) the graduating of learning cards (fuzzed_graduating_interval_good/easy()), and b) with_learning_fuzz(). If you're planning to use the fuzz factor for those as well, then replacing the existing fuzz_seed in the context sounds reasonable.

**Comment by dae** [comment]
(reproducible unit tests are also nice, but the main goal of the seed is to ensure cards are given the same fuzz if undone and reviewed again)
