### ISSUE TITLE
Margin-left editing option doesn't work

### ISSUE THREAD

**Issue by JESii** [ankitects/anki#1423]
- Have a question or feature suggestion?
- Problems building/running on your system?
- Not 100% sure you've found a bug?

If so, please post on https://forums.ankiweb.net/ instead. This issue tracker is
intended primarily to track development tasks, and it is easier to provide support
over on the forums. Please make sure you read the following pages before
you post there:

- https://faqs.ankiweb.net/when-problems-occur.html
- https://faqs.ankiweb.net/getting-help.html

I'm creating a programming deck and need to show formatted code. When creating notes, I've tried highlighting the code section, selecting the margin-left icon, and saving the note. This shows an example -- the margin-left icon is highlighted showing that this was already applied to the text.
![2021-10-12 at 3 12 AM](https://user-images.githubusercontent.com/486/136937209-e5e038b7-1f23-431e-a2cf-0b52da1b6a31.png)

However, the text is still centered.
![image](https://user-images.githubusercontent.com/486/136937377-6f6f04ea-82fe-4744-850f-b6a097a49588.png)

**Comment by dae** [comment]
If you need further assistance, please post on the forums.
