### ISSUE TITLE
Anki on Mac won't work offline

### ISSUE THREAD

**Issue by phuongnd08** [ankitects/anki#1428]
I  use Anki to take notes while reading ebook offline. But I can only add the question. Once the question is created, and I want to edit it, I get a broken screen. This happens recently so I guess this is a bug with the way anki local web server is configured.

![image](https://user-images.githubusercontent.com/184037/137575941-8ea66062-cd00-43e6-8b75-7629a4e5dbce.png)

**Comment by dae** [comment]
Tried again on an M1 machine, and it still worked for me. Perhaps this is due to some specific network configuration on your machine, or other software like a firewall or antivirus program running on it.
