### ISSUE TITLE
Images starting with a space not working

### ISSUE THREAD

**Issue by johnnoren** [ankitects/anki#1430]
When I upgraded Anki a lot of images stopped working both on macOS and iOS.

It turned out I had images starting with spaces. Not sure why but that is how it was.

The images showed as broken in Anki. When I removed the starting space from both the file name and the html the images worked again.

**Comment by dae** [comment]
Do you mean you had a ` foo.jpg` and `<img src=" foo.jpg">` in your fields? HTML ignores leading/trailing whitespace in img sources. Anki unfortunately stores filenames unencoded, so it can't distinguish between a file with a leading space, and cases where the user just added a space to the img tag but not the filename. Fixing this will break users who were doing the latter, but it's probably the less common case

@RumovZ this probably just requires removing the trim() in transform_html_paths()
