### ISSUE TITLE
The latest （2.1.48）version can't refresh item when I use ODH  to add a new card

### ISSUE THREAD

**Issue by Brainbg** [ankitects/anki#1439]
But 2.1.44 is normal，I hope this can be fixed

**Comment by dae** [comment]
This is by design - the browse screen will only update the search when you activate the search.

**Comment by Brainbg** [comment]
> 
> 
> This is by design - the browse screen will only update the search when you activate the search.

This design is ineffecient，Although it looks better than before. As a result,I have to go back and come in again when I use ODH to add a new card . To do this I still used the original version (2.1.44).So I'd like to see the auto-refresh feature come back.Thanks.
