### ISSUE TITLE
flickering when external css reference used

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1455]
https://forums.ankiweb.net/t/flickering-since-v2-1-45/14365/3

**Comment by RumovZ** [comment]
I've tracked this down to e8d1a035a265e2f657f92c158f3fad40a4e0ce46, not sure where to go from here.

**Comment by dae** [comment]
Interesting - thanks for digging into that! I'm guessing it's either flask or werkzeug? Using the web inspector's network tab may tell us more - maybe the wrong content type is being sent, or timing of the packet delivery will differ?

**Comment by RumovZ** [comment]
Thanks for the pointers. It seems to be a cache handling issue. On 2.1.44 (no flicker), there are no packages visible. On a newer version (flicker), they keep appearing with status "Not modified". However, if I disable caching, both versions show the same flicker. So I guess there was some underlying cache that got switched off with the upgrade?
Sorry, this is not my area expertise and I'm probably not very helpful if I have to contact you after each step.

**Comment by dae** [comment]
No problem, appreciate you narrowing it down - will dig into it further when I get a chance.

**Comment by dae** [comment]
You were 99% there :-)

**Comment by RumovZ** [comment]
Thanks for letting me know and great to see it solved. 🙂
