### ISSUE TITLE
Feature Request: option to push/pull instead of just sync

### ISSUE THREAD

**Issue by edridgedsouza** [ankitects/anki#1459]
I'll often have anki open on both my phone and laptop. Usually I'm careful not to do too many different things at once, but every so often I'll have a slip-up and the automatic sync on one device will erase progress on another. It would be convenient if, under the sync button, there was perhaps an option to say "push only" or "pull only" the way you can in git.

**Comment by dae** [comment]
Please note you should not be using it regularly, as a one-way sync consumes more server resources, and will be slower.
