### ISSUE TITLE
minor regressions in HTML layout

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1479]
Just a reminder about https://github.com/ankitects/anki/pull/1470#issuecomment-955608657 so we don't forget about it

**Comment by dae** [comment]
@hgiesel this appears to fix the remaining problem; feel free to adjust if you think it should be done differently

**Comment by dae** [comment]
Looks like the bottom left margin in split deck options view is still a problem. Card info screen is also lacking a top margin

**Comment by hgiesel** [comment]
I'm looking into a bit more complete solution for this.
