### ISSUE TITLE
Glitching out of answer screen showing a different question and answer

### ISSUE THREAD

**Issue by Hertzzog** [ankitects/anki#1487]
After updating to the latest Windows version, I have experienced a problem I have never seen before.  When doing a review; I of course see the question or front of the card.  However, about every 5 notes, when I push the button to show the answer; a completely different question and answer pops up.  I don't actually know what question is in view and if it is just showing me a different card or what.  So, no matter what I chose to do; it will accept the answer and then be ok for about 5 more cards and then repeat this.
I have tried to repair the database and other things; but, nothings seems to work.

**Comment by ionic-corinthian** [comment]
I also have the same issue.

Windows version:
Edition	Windows 10 Home
Version	20H2
Installed on	‎01/‎11/‎2021
OS build	19042.1348
Serial number	YZ170178
Experience	Windows Feature Experience Pack 120.2212.3920.0

Anki version: 
Version ⁨2.1.49 (dc80804a)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

**Comment by dae** [comment]
Changing your video driver may help: https://docs.ankiweb.net/platform/windows/display-issues.html
