### ISSUE TITLE
Decide on a syntax for tts outside of field references

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1507]
Comments/suggestions would be appreciated.

https://forums.ankiweb.net/t/tts-for-multiple-fields-together/15197/2

**Comment by lucwastiaux** [comment]
Some AwesomeTTS users would like to concatenate multiple fields together before generating on-the-fly audio. The following syntax seems to work well:
```[anki:tts][zh_HK]{{Chinese}} {{English}}[/anki:tts]```
One possible use case in German is if someone stored pronoun and noun separately, which makes perfect sense for example if you want different formatting. I'd like to have blessing to use that format in AwesomeTTS.

**Comment by dae** [comment]
One other thing that springs to mind: we may want to support other tags in the same format in the future(eg [anki:type]). The current design wouldn't be easy to capture generically with a regex that lacks support for backreferences (eg Rust) - we'd probably need an outer wrapping tag (ugly), to exclude the type in the closing tag (eg [anki:tts] ... [/anki] - more risk of conflicts), or to write our own parser using something like nom (more work, but may be the best option)

**Comment by RumovZ** [comment]
Here's your list from the forum for convenience:

> - currently the first argument (the language) is special-cased and has no associated key
> - options are embedded inside the tag; they might be better placed in the opening tag instead
> - spaces and square brackets can’t be included in the keys or values. This may be an acceptable limitation (and the TTS code automatically replaces spaces with underscores in voice names already), but could use a bit more thought.

I agree, better to eliminate the special case for voices and have options inside the opening tag. As for spaces and square brackets, I have no idea if those characters will be needed. We could use a similar escape syntax as in the search engine, though: `\"[]` must be escaped and expressions can be wrapped in `"` to allow for whitespace.
Alternatively, the mentioned characters could be prohibited, facilitating simlple parsing for now, but with an option to implement escaping in the future while preserving backwards compatibility.


<hr>

I have difficulties following the discussion, so please excuse the lengthy post.
As far as I understand, the workflow for TTS is as follows:

1. Backend replaces `{{tts args:field}}` with `[anki:tts args] field text [/anki:tts]`.
2. Frontend calls into backend to replace `[anki:tts args] field text [/anki:tts]` with `[anki:play:side:no]` and extract args.
3. Frontend replaces `[anki:play:side:no]` with play buttons.

So the interesting part is step 2.
I don't understand the necessity to have a parser, unless you are suggesting a completely generic syntax like `[anki:filter_A key1=val1 key2=val2] ... [/anki:filter_A]`. However, do the different filters, foremost TTS, not require special treatment anyway? In which case a regex matching "tts" explicitly would be fine.
Escaping special characters in options like described above would also require a parser, of course.

**Comment by dae** [comment]
Thanks for the input! Good point about being able to optionally support those characters in the future if we wish to (assuming we treat the escape character as off-limits as well for now).

My thinking was that if the parser basically returns a tag name, embedded content, and set of keys/values, we could use the same approach for other features too, eg [anki:type ignore-case=true]{{Field 1}}, {{Field 2}}[/anki:type]. Each tag we introduce would need its own business logic, but with a consistent format, a single regex/parser could be shared.

**Comment by RumovZ** [comment]
TTS tags are currently handled simultaneously with sound tags in `extract_av_tags()`, so maybe we can parse the template to a Vec of nodes, where a node would look something like this (in pseudo Rust):
```Rust
enum Node {
    Text(&str),
    Sound(&str),
    AnkiTag{
        tag: Tag,
        options: Vec<FilterOption>,
        content: &str,
    }
}
```

The Vec would be a field of a struct, which might even be a full-blown AST, should the need arise in the future. At the moment. I think we don't even need nested nodes. The struct would implement functions for walking and writing out the nodes, replacing the currently used `strip_av_tags()` and `extract_av_tags()`.
Maybe this AST could even be extended to handle other functions in `text.rs` like `html_to_text_line()` in the future. Just throwing it out there.

Something like this?

**Comment by dae** [comment]
Yep, that's the sort of thing I had in mind, though I saw options as being Vec<(String, String)>, or a HashMap, since different tags will have different keys/values, some of which are optional/may only be used by add-ons.

One other possible use case I'd been thinking of is something similar to field filters, but not limited to a single field, eg something like [anki:strip_html]{{Field1}} some other text etc[/anki:strip_html]. Such cases would be useful to nest. But while it might have been nice to implement this before field filters were initially implemented, the ship may have already sailed on this one, and trying to handle both cases at once is probably not worth it.

**Comment by RumovZ** [comment]
> Yep, that's the sort of thing I had in mind, though I saw options as being Vec<(String, String)>, or a HashMap, since different tags will have different keys/values, some of which are optional/may only be used by add-ons.

I think it would make sense to use enums, which allow arbitrary tags and options, but special case native ones.

```rs
enum TagOption {
    Voices(Vec<&str>),
    Speed(f32),
    ...
    Other {
        key: &str,
        val: &str,
    }
}
```

The main advantage would be that we can define all syntax rules in one `parser.rs`, like "voices are comma-separated", "default speed is 1", etc.. For unknown tags or tag-option combinations, we would just dump the options into `Other`. Then, if we detect an invalid option, e.g. `[anki:tts speed=a]`, we can immediately reject the tag, interpreting it as text, an unknown tag, or raising an error. (In this example, we'd probably fallback to the default value, but imagine there's a mandatory option without which the tag couldn't be parsed.)

Which brings me to the next point.  Should we implement error handling like for the search syntax? I'd normally say we can always add it later if necessary. However, without error messages, I wonder how we can reserve certain characters like `"`. If we just refuse to evaluate a tag containing such characters, the user might never figure out what the problem is.

It would also be great to have some catchy name for these environments, because a tag is already a concept both in Anki and nom. As for the parsed result, I'd suggest the name "CardSide".

**Comment by lucwastiaux** [comment]
I welcome this effort to make the TTS interface more sophisticated. I don't have much of an intuition around what it should look like, but as an addon developer, I would like to have access to the following information:
- The fully expanded text data within the TTS tag (html stripped, clozes processed)
- The raw data within the TTS tag (no html stripped, cloze fields unprocessed, and an indication as to which cloze word is chosen). This allows me to handle things like furigana fields with special markup. It would also allow me to make pronouncing "blank" or not an option within AwesomeTTS.
- The note (i may do some conditional processing based on fields in the note).
- The note type, and the deck (this is because users may want different voices based on the exact combination, for example if someone uses a single "Chinese" note type which is used for Mandarin and Cantonese).

**Comment by dae** [comment]
Point 2 is not really practical, as the field replacements have already happened at that point. I think we need to solve that a different way, eg by making the blank replacement [optional/customizable](https://github.com/ankitects/anki/issues/1537).

**Comment by RumovZ** [comment]
I think such an option would really benefit from accepting whitespace. In fact, I've recently commited a translation for "blank" that contains spaces.
I reevaluated the escape method I suggested above and I think there may be better options. What if we accept every char if the value is wrapped in double quotes, except double quotes themselves, which are always invalid. This should be easier to implement and doesn't require any allocations. And if we really need to support double quotes in the future, we could implement something like the raw strings in Rust, without breaking backwards compatibility.

```
key=" val "   // ✅ good
key=" v"l "   // ❌ bad
key=#" v"l "# // ✖️ bad for now
```

**Comment by RumovZ** [comment]
By the way, I understand if you have your hands full with 2.1.50 currently. I just write these posts as they spring to mind.

**Comment by dae** [comment]
Ok, so since we're currently relying on .split_ascii_whitespace() in tts_tag_from_string(), to allow any embedded spaces, we're going to have to move away from simple splitting to some sort of parsing. And if we're doing the parsing in the options area, we might as well do it for the whole tag, instead of capturing it with a regex and then parsing parts of it. With the "easily regexable/parsable" constraint removed, that opens up our options.

How about something like the following syntax?

```
[anki:tagname aaa=bbb ccc="ddd eee"     ff=5]...[/anki:tagname]
```

and in the no-options case (which could possibly be used as alternative to [sound:...] tags in the future:

```
[anki:tagname]...[/anki:tagname]
```

Presumably we'll want to keep the keys as simple ascii without spaces for now.

We could then have a nom parser that extracts a vec of struct { tag: String, properties: HashMap<String, String>, content: String }. 

Then tts_tag_from_string() could instead take instances of that struct where tag == "tts", and convert the properties and content into AvTag::TextToSpeech. It would no longer need to worry about splitting, and can just focus on type checking/injecting defaults. The current approach could work, or perhaps we could use serde to deserialize from the HashMap into our struct using something like https://github.com/serde-rs/serde/issues/1739#issuecomment-585442986

We'll need to change the tts filter to pass lang as a key/value, instead of a bare argument.

How does that sound?

**Comment by BrucePlumb** [comment]
Sorry, slightly different question but this seems like a good place to ask how to apply TTS to a text not from a field. (Different cards to have different set text spoken.) The Ankiweb TTS support page gives an example for TTS for older Anki versions which I tried to adapt with the following:
<script>
  var w = "testword"
  window.setTimeout("speak(w)", 500);

  function speak(word) {
    var speech = new SpeechSynthesisUtterance();
    speech.text = word;
    speech.volume = 1; // 0 to 1
    speech.rate = 0.8; // 0.1 to 9
    speech.pitch = 1; // 0 to 2, 1=normal
    speech.voice = window.speechSynthesis
    	.getVoices()
     	.filter((v) => v.lang == "it_IT")[0];
    speechSynthesis.cancel();
    speechSynthesis.speak(speech);
  }
</script>
But how do I get the script to run and say the testword?

**Comment by RumovZ** [comment]
Yes, pretty much what I had in mind. 🙂 Shall I start with the parser?

**Comment by RumovZ** [comment]
@BrucePlumb, this discussion is about a future syntax that will make what you'd like to do easy. Please ask on https://forums.ankiweb.net/ if you need help with the current Anki version.

**Comment by dae** [comment]
That’d be great, thanks

**Comment by luc-languagetools** [comment]
will iOS AnkiMobile support this new syntax as well ?

**Comment by dae** [comment]
Yes, probably in the next release.

**Comment by luc-languagetools** [comment]
OK and the Anki desktop change discussed above is going into 2.1.50 ?

**Comment by dae** [comment]
Most likely, yes.

**Comment by nacho00112** [comment]
it's asking me to set `lang=` can't I just make it ask for the language like it does with the general TTS option? this is important because I'm intending to share my note type and other people may want to change the TTS language.
