### ISSUE TITLE
copying cards/notes

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1512]
Re https://forums.ankiweb.net/t/include-copy-duplicate-note-in-anki-desktop-or-as-official-plugin/15287

My concerns about such a feature are its potential for abuse, as it's not too uncommon to see users asking for this because they want to add reverse cards or (which is better done with a template adjustment), or want to place the same cards in multiple decks (which will make the card scheduling less effective).

Maybe one way of avoiding the downsides would be to have it apply to the add screen, instead of cloning notes directly? We could have an action that takes the selected note, and opens the add screen with its content and note type pre-filled, and then the user could edit as desired before adding the new note.

Thoughts?

**Comment by omarkohl** [comment]
I will describe my use case. While researching a topic I keep adding cards, for which the pinned fields (including the tags) are perfect. For example I can add card after card about "Marie Curie", without having to add the source, import date and tags again and again.

![Marie Curie was the first woman to ...](https://user-images.githubusercontent.com/1420656/143882853-ecf0e408-0c7c-4caa-a3ff-ac4cfa930279.png)

What does not work so well is if I want to add cards from different sources alternating between them. Or if I want to resume yesterday's study session about Ms. Curie.

> have it apply to the add screen, instead of cloning notes directly

Perfect for my use case!

I do think however that making the feature a little more generic to cover other use cases would be good. There are plenty of ways to abuse Anki and I suspect (hope?) that new users will slowly gravitate to better patterns with time if they are encouraged and documented (e.g. include warning about the misuses of the "copy note" feature in the documentation).

> see users asking for this because they want to add reverse cards or (which is better done with a template adjustment)

The fact that the note type "Basic (and reversed card)" exists by default already encourages the correct behaviour and sooner or later someone who duplicates notes to reverse them might wonder if there isn't a better way than to fix the same typo in N different notes.

> place the same cards in multiple decks (which will make the card scheduling less effective)

I can think of a legitimate use case for that, namely a "teacher" that is preparing decks for different students, with different levels. Some of the notes they want to place in multiple decks, so they copy paste them. The scenario you describe is inefficient without a doubt, but I would also suspect that sooner or later people would realize that it's not doing anything for them except creating more work.

**Comment by RumovZ** [comment]
> I do think however that making the feature a little more generic to cover other use cases would be good. There are plenty of ways to abuse Anki and I suspect (hope?) that new users will slowly gravitate to better patterns with time if they are encouraged and documented (e.g. include warning about the misuses of the "duplicate note" feature in the documentation).

I fail to see how this is an argument to support copying. Even if users finally see their mistake at some point, it's too late then, because they will already have messed up their collection or wasted time. Adding a feature that relies on subsequent user actions lest it be harmful seems like a questionable design choice.

I think @dae's suggestion will be a great addition, even though a lot of users who want to copy cards won't be satisfied, because frankly, it's not copying. Maybe the action could be called "Create copy...".

**Comment by omarkohl** [comment]
> I fail to see how this is an argument to support copying.

It's an argument in favour of "you can only protect people up to a point from themselves and have let them learn through their mistakes" :wink: There are other features that can also be abused, but since they are valuable at the same time it's a tradeoff worth making. After all nobody starts out with a perfect collection and cleaning up your mistakes with time or at least no longer making the same mistakes is part of the learning process.

**Comment by omarkohl** [comment]
That being said, I would be more than happy with your suggestion:

> I think @dae's suggestion will be a great addition, even though a lot of users who want to copy cards won't be satisfied, because frankly, it's not copying. Maybe the action could be called "Create copy...".

**Comment by RumovZ** [comment]
We agree that it's a tradeoff. 🙂 My point is that the cost is high, but we gain very little. The example you came up with is reasonable, but rare. In these cases, expecting the user to use an add-on or the export/import workaround should be within reason.
