### ISSUE TITLE
Copy-pasting images includes inline styles

### ISSUE THREAD

**Issue by kleinerpirat** [ankitects/anki#1515]
### Reproduction steps
- Insert an image into the editor.
  - It will be styled with the new image handle, but the styles do not show in the HTML editor.
- Select the image in the `RichTextInput` and copy-paste it below.
  - The pasted `<img>` tag is now polluted with tons of inline styling.

### Sample
```html
<!-- Original image -->
<img src="image.jpg">
<!-- Pasted image -->
<img src="image.jpg" style="max-width: min(250px, 100%) !important; max-height: 125px !important; width: 195px !important; height: auto !important;">
```

This issue might not be isolated to images, but at the moment, it's all I could reproduce (which is great).

In the past, I've seen borders get converted into `<hr>` and other funky stuff that really surprised me, because one would not expect styles from external sources get included inline like that. Perhaps the new toolkit has ironed out most of these issues.

**Comment by hgiesel** [comment]
The contenteditable will inline styles which are applied from above. It must use something akin to `getComputedStyle`. The solution would be to add the properties:

```js
    "width",
    "height",
    "max-width",
    "max-height",
```

to stylingInternal in `html-filter/styling.ts`. I wonder if there are any legitimate uses for using those styling properties?

**Comment by dae** [comment]
I imagine there will be some users who have added such styling themselves and may want to preserve them, but unwanted styling is likely to affect more users, and if there's no other simple way to fix this issue, maybe stripping them is for the best? Presumably users could copy and paste the underlying HTML as a workaround in such cases.
