### ISSUE TITLE
we should ignore crazy values in learning steps

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1518]
https://forums.ankiweb.net/t/anki-desktop-bugs/15415

User had learning steps set to 2014404352m, which causes errors when using Again on a card. Perhaps we should do something like:

- change to_secs() to to_secs_capped() in steps.rs (for upgrades/external imports)
- also cap numbers when saving deck options in the deck options screen

**Comment by RumovZ** [comment]
What should they be capped at? I guess `2^31-1` secs, about 68 years, would be possible with every datatype currently used to represent learning steps. Can we be more conservative and use 1 year? I bet there are people who'd complain, though.

**Comment by dae** [comment]
Yep, I think they probably would. There's no technical reason for a lower limit, and 1 year would be fairly arbitrary, so let's just go for u32::MAX

**Comment by RumovZ** [comment]
Correction: The due date for learning cards is an i32 timestamp, which will overflow in 2038, if I'm not mistaken. Can we make that an i64 to buy us a few more trillion years?
So technically, there's no definite limit for the size of a learning step, just somewhere below 2^63. I'd go with `i32::MAX` to be on the safe side though.

**Comment by dae** [comment]
Most of our other timestamp use is i64, so switching to i64 is probably prudent. I think the learning steps unsigned - the u32s in steps.rs could probably remain?

**Comment by RumovZ** [comment]
You're right. I was thinking about unintentional uses of smaller data types. But JS and Python won't have problems there and in Rust, we are probably taking enough care not to cause issues.

**Comment by RumovZ** [comment]
Yet another correction: Steps are actually f32 minutes, and only converted to u32 seconds in the scheduler. I'll cap them at `u32::max / 60`, and add some comments, because units have been confused at least once in the codebase.
Can we switch to using seconds with the next schema update? I've already stashed some changes while looking through the code.

**Comment by dae** [comment]
Seconds would be less surprising, and it would be nice to fix at one point, though we do always run the risk of an accidental regression when making changes like these.
