### ISSUE TITLE
Add View menu to Qt toolbars

### ISSUE THREAD

**Issue by kleinerpirat** [ankitects/anki#1530]
It's a game of luck to find the fullscreen mode currently (as mentioned by [cqg on the forum](https://forums.ankiweb.net/t/anki-2-1-50-beta/15608/22)). A `View` toolbar menu would be the go-to place for that toggle. Some add-ons like [Browser: Table/Editor side-by-side](https://ankiweb.net/shared/info/831846358) already implement that.

For the browser, I can think of three items that would fit into this category:
- Toggle Full Screen
- Toggle Showing Cards/Notes
- _Toggle Layout_ (potential future Table/Editor side-by side view)

Depending on future changes to the main window, it might benefit from a separate `View` menu as well.

**Comment by dae** [comment]
@RumovZ commented on the forum:

> I like the idea, but only a few windows have a menubar. If we only added an entry to the main window, users might infer that other windows couldn’t be opened in fullscreen.

Adding View menus to every screen doesn't seem practical. If we have a bunch of items that would fit in a View menu in the Browse screen, maybe it would make sense? Users may assume it will only work in that screen, but then they're no worse off than they were with no menu entries at all.

But before we add a new menu, I think we'd probably need more than 2 menu items. What else might we want to put there that is useful?

**Comment by abdnh** [comment]
> But before we add a new menu, I think we'd probably need more than 2 menu items. What else might we want to put there that is useful?

Maybe it's worth reintroducing the toggle sidebar button (removed in https://github.com/ankitects/anki/commit/b8d67cdad54b933aafb310759f840cf82204e5f2)? I don't use it personally, and just remembered it after reading this thread.

**Comment by dae** [comment]
It's a possibility, though I'd like the motivation for doing that to be a reasonable demand for the feature rather than a desire to fill out the menu, as  users sometimes turned it off in the past and couldn't figure out how to turn it on again :-)

**Comment by cqg2** [comment]
After a week working with 2.1.50, I've just realized that now you can zoom in / out the cards by using CTRL + Mouse Wheel, which is, by the way, great. Adding Zoom In / Zoom Out to the view menu would be an idea. 

Also, IMHO, the "Open Backup" and "Downgrade & Quit" options should be directly in Under the "File" menu, not as suboptions from "Profiles" window, and maybe (?), the "Profiles" window  would make more sense under the "View" menu than under "File".

So, my suggestion would be:

View Menu
- Swicht Profile (?)
- Full Screen
- Zoom +
- Zoom - 

File Menu:
- Swicht Profile (?)
- Open Backup
- Import
- Export
- Downgrade & Quit
- Exit

**Comment by RumovZ** [comment]
> Adding Zoom In / Zoom Out to the view menu would be an idea.

Good idea. I happened to discover zooming, but I missed a feature to reset the value to 100%, and there's no indicator for the currently set zoom.

> Also, IMHO, the "Open Backup" and "Downgrade & Quit" options should be directly in Under the "File" menu (not as sub-options from "Profiles" window);

The profile window is like a login screen, and operations like downgrading are placed there, because they are accessed independently of an opened profile. But I guess you could add actions to the main window, which act like shortcuts for "Close profile and downgrade/load backup".

**Comment by kleinerpirat** [comment]
I think the zoom funcitonality for webviews is yet another (nice, but unintended) byproduct of the toolkit update.

This really helps legitimize the "View" menu for the main window, for one because zooming is actually useful there, but also because people might accidentally trigger the zoom during review and will search for such a menu to reset it (recommended action: "Reset Zoom").

For the editor, it's probably better to prevent the zoom, though.

**Comment by dae** [comment]
For background on zoom in/out: https://github.com/ankitects/anki/issues/985

Putting more entries in the File menu makes them a bit easier to access, but also means there are more options people need to read. A 'load backup' is worth considering to increase its discoverability, but I don't really think 'downgrade and quit' should be added there, as most users wouldn't use it, and it's too easy to confuse with the existing quit option.

**Comment by roxgib** [comment]
From a Mac user's perspective, adding items to the menubar allows us to assign or reassign shortcuts to them at the OS level. I'm not sure how many people use this but it's nice to have the flexibility.

**Comment by dae** [comment]
So to reiterate/summarise what is being proposed here:

A View menu in the Browse screen, with:

- Toggle Full Screen
- Toggle Showing Cards/Notes
- Zoom In
- Zoom Out
- Reset Zoom

And in the main window:
- Toggle Full Screen
- Zoom In
- Zoom Out
- Reset Zoom

Does that sound about right? Rumo has fixed the zooming issue mentioned above, so no objections from me to adding these to menus, though in the browser case "Zoom Editor In" or similar may be clearer/avoid bug reports.
