### ISSUE TITLE
Deleting certain elements in the editor leaves <div><br></div> behind

### ISSUE THREAD

**Issue by kleinerpirat** [ankitects/anki#1536]
Here are two actions on an empty field that have the same result visually, but not in HTML:
(I removed the `ul` margins for better alignment of the images :)
#### Toggle a list button on, then off
<img src="https://user-images.githubusercontent.com/62722460/144900207-1634fdf4-161c-4e48-b3f9-dd98c000be95.png" width="48%"> <img src="https://user-images.githubusercontent.com/62722460/144903315-0be5626d-61ab-4b51-9cb4-6b44df189f6d.png" width="48%">

#### Insert a list, hit <kbd>Backspace</kbd>
<img src="https://user-images.githubusercontent.com/62722460/144900207-1634fdf4-161c-4e48-b3f9-dd98c000be95.png" width="48%"> <img src="https://user-images.githubusercontent.com/62722460/144903203-bb2c8bfd-b579-44e2-9581-a5d456c9d04c.png" width="48%">

This `<div>` can be removed by pressing <kbd>Backspace</kbd> a second time. But who would do that?
There is no visual indication that there's still a `<div>` inside the field, because it doesn't have any margins (see caret position).

### Why is this problematic?
Repeating the second action multiple times results in nested `<div>`s:

![image](https://user-images.githubusercontent.com/62722460/144905393-9fcb4617-d2cb-4f64-892a-cf3e67e98b70.png)

It's probably not uncommon to rethink the choice to use a list, or for a list to be deleted after it was preserved in a sticky field. Users will mark the list (some will hit <kbd>Ctrl</kbd>+<kbd>A</kbd>) and hit <kbd>Backspace</kbd> until the field is empty and the caret is at the starting position. Most people won't notice that there's still HTML inside the field and continue their work. Decks will (continue to) be cluttered with preventable nested `div` structures (https://forums.ankiweb.net/t/automatic-removal-of-div-div/9071).

---
A margin for `<div>` inside fields would help, but the much better fix would be to prevent `<div><br></div>` from happening in the first place. I don't know the editor code well enough to fix this myself, sadly.

**Comment by kleinerpirat** [comment]
[This forum post](https://forums.ankiweb.net/t/anki-2-1-50-beta/15608/82?u=kleinerpirat) by @nwwt describes a similar issue and makes a good point:
Invisible, left-behind HTML can trigger unwanted conditional card creation.

**Comment by dae** [comment]
Yep, it's not great. We're relying on standard contenteditable behaviour here AFAIK - not sure how complicated it would be to work around.

**Comment by dae** [comment]
@kleinerpirat assuming #1565 means this can be closed; happy to re-open if that's not the case
