### ISSUE TITLE
highlight color of buttons is orange on qt6

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1567]
Would be nice to return to the blue of before.

https://forums.ankiweb.net/t/anki-2-1-50-beta/15608/96

**Comment by RumovZ** [comment]
Is this a Mac thing? It's blue on Windows, but there is another small issue: The outline is square, but the border is rounded.
![grafik](https://user-images.githubusercontent.com/48286681/149745483-e84145bf-c03e-48e2-b491-de20b9f1f764.png) ![grafik](https://user-images.githubusercontent.com/48286681/149746073-88b6ab89-be71-417c-a2fa-6c1320001da1.png)

As for the colour, maybe the Mac code just needs something like this too:

https://github.com/ankitects/anki/blob/0e06a1c6797d8ac99a7b1b0c2041d9265d03ce35/qt/aqt/webview.py#L408

**Comment by dae** [comment]
Unfortunately that doesn't seem to help. An orange outline is also visible if you tab in the deck list to move the highlight to each deck in turn. It's starting to feel like Qt have (perhaps accidentally?) change the hard-coded color in Qt 6.2.

**Comment by roxgib** [comment]
mw.palette().highlight().color().getRgb() returns 119, 204, 255, which is blue, but if you flip the order of the RGB elements to 255, 204, 119, you get orange. A hack to fix this might involve manually reversing them back to the correct order, but it'd require checking exactly which platforms are affected.

**Comment by dae** [comment]
More discussion on #1627

**Comment by dae** [comment]
Appears to be resolved.
