### ISSUE TITLE
Unbloat Anki

### ISSUE THREAD

**Issue by Bracket-H** [ankitects/anki#1568]
Wtf is all this rust bazel and other shit?

Anki is spaced repetition flashcards. You can do this without all this horseshit.

**Comment by Bracket-H** [comment]
the cache directory for bazel in my home is almost four gigabytes?!?!?! 
Bro am I dealing with Flashcards here or the goddamn encyclopedia britannica or something?
Can I delete this?

**Comment by agentjudy** [comment]
> Wtf is all this rust bazel

Rust - https://www.rust-lang.org
Bazel - https://bazel.build

But it's better explained in [this YouTube video](https://youtu.be/dQw4w9WgXcQ).

**Comment by Bracket-H** [comment]
I watched that video several times now and it's not explained there at all. In fact it assumed that I already know all the rules and everything.

No wonder this project is going in the toilet, perhaps it would be prudent to not use rust or bazel if this results in such bs.

**Comment by Bracket-H** [comment]
I see this issue is closed, but the bloat remains. Highly incompetent staff.
