### ISSUE TITLE
“Hourly contribution” stats are adjusted by time zone.

### ISSUE THREAD

**Issue by whnr** [ankitects/anki#1570]
Hi.
The “hourly breakdown” statistics are adjusted for time zones. E.g. when traveling 6 hours east it looks like I studied six hours later before. Old study time 22:00 will now be 04:00.

Since human perform follows the sun, I would expect Anki to honor local time rather than adjusting for time zones. When cards Hebe been studied at 22:00 local time they should always be down at that time.

Can I set this somewhere?

**Comment by dae** [comment]
Anki reviews don't contain info about the timezone that was active at the time, so I'm afraid it's not possible to show the local time they were done in if the timezone has subsequently changed.

**Comment by whnr** [comment]
Ok. So The time stamp is just UTC? Or is it actually device time? As far as I joke there are devices that have their hardware clock set to either local or UTC.

**Comment by dae** [comment]
Yes, it's UTC.
