### ISSUE TITLE
screen flickering when reviewing.

### ISSUE THREAD

**Issue by huandney** [ankitects/anki#1591]
I noticed that in the cloze cards where I have Quotes HTML there is a flicker when showing the word, as shown below:

![Animação2](https://user-images.githubusercontent.com/19948348/149544499-5e67a8f7-189c-4a78-b58d-f710b712a299.gif)

~~when there are no HTML Quotes, it works perfectly.~~

Edit: even not using HTML Quotes the problem appears, although much less often, I think it is related to something like the style, when I remove @import url("_editor_button_styles.css"); the problem disappears.

OBS: I used version 2.1.40 and didn't have this bug. I didn't test the other versions because I upgraded straight to 2.1.49.

**Comment by dae** [comment]
I suspect this is already fixed. If you can reproduce it after 2.1.50beta3 comes out, please let us know.
