### ISSUE TITLE
Anki icon

### ISSUE THREAD

**Issue by xmha97** [ankitects/anki#1596]
Hi, I use Anki on Windows Server 2022.
After installation, icon is not displayed.
![image](https://user-images.githubusercontent.com/23485114/149640419-0325f955-991a-4ad7-a535-0b348579827b.png)

I have to set it manually:
![image](https://user-images.githubusercontent.com/23485114/149640463-e0240b3e-1e1d-48c5-af81-ee8849a4b09e.png)
![image](https://user-images.githubusercontent.com/23485114/149640561-8bcaccfd-1157-42f9-bc6f-b261153efb4d.png)

**Comment by dae** [comment]
Can you reproduce the issue with the latest beta?

https://betas.ankiweb.net/

**Comment by xmha97** [comment]
Thanks, this issue has been fixed in the beta version.
