### ISSUE TITLE
"Argument list too long" when attempting to run TS format check

### ISSUE THREAD

**Issue by glutanimate** [ankitects/anki#1612]
Heya, been running into a bit of fun issue while trying to run the checks:

Executing

```sh
bazel run //ts:format_check
```

currently fails on my system with the following error:

```sh
FATAL: execv of '/bin/bash' failed: (error: 7): Argument list too long
```

This seems originate in the bazel rule for prettier, which builds a long command line for all files to check: https://github.com/ankitects/anki/blob/main/ts/prettier.bzl#L21

First time running into this, so I suspect it's down to more modules being included. Still, I do wonder if something system-specific is at play as well, given that I haven't been able to find any reports about this, yet.

@dae any pointers / is this something you've seen before?

I did try increasing `ARG_MAX`:

```
$getconf ARG_MAX
2097152
ulimit -s 65535
$getconf ARG_MAX
16776960
```

but to no avail.

**Comment by RumovZ** [comment]
From which folder are you running this? According to development.md, it has to be a subfolder of ts, but I just realised that it also works from the root. However, since that also formats the build folders, it's probably not a good idea.

**Comment by glutanimate** [comment]
Ah, good point. It was being run from root as part of a git hook I had set up a while ago (to slim down the longer test battery that `bazel test //...` would run).

Unfortunately running the rule from a subfolder yields the same results, e.g.:

```
$bazel run //ts:format_check
...
FATAL: execv of '/bin/bash' failed: (error: 7): Argument list too long
```

Which is unsurprising now that I take another look at the rule as by default the glob doesn't exclude `node_modules` when run manually.

But that seems to be the main issue, I think. `ts:format_check` is probably not meant to be run manually – as opposed to `ts:format` which is documented in the dev docs. So likely not a bug, but just a use of this rule on my part which it wasn't intended for.

So yeah, I think the issue is resolved as far as I'm concerned. Will just switch the rule back to using `bazel test //...` which can be slow when checking the repo out for the first time in a while, but avoids issues like this.

**Comment by RumovZ** [comment]
Oh, sorry. I didn't realise you were talking about `ts:format_check`. But glad you could resolve it.

**Comment by dae** [comment]
node_modules moved from ts/ to / at one point - is it possible you had an old copying lying around in ts?

**Comment by glutanimate** [comment]
@dae yep, actually did! Removed it, thanks!
