### ISSUE TITLE
card counts and percentages are not easily distinguishable

### ISSUE THREAD

**Issue by mikey00001** [ankitects/anki#1621]
in the _card counts section_ (of the stats window), it is hard to see where the number of cards ends, and the percentage number begins. the reason is that there is _no space_ or other _visual cue_ between those two numbers. in the screenshot, one would read the number of young cards as "7644.7%" at first glance. that is a usability and/or accessibility issue in my opinion.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/91184743/150637808-2b0c8317-40f7-4a59-9c7e-a756550080a0.png">

_suggestion_: insert more space between numbers and percentages and put the percentage number in brackets.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/91184743/150638296-ca841f9f-e43d-4c70-a06e-dafde9266639.png">

**Comment by mikey00001** [comment]
Anki for Mac
Version ⁨2.1.49 (dc80804a)⁩

**Comment by dae** [comment]
I believe this is already fixed in the development code. If you run into any further issues, please let us know over on the user forums: https://forums.ankiweb.net/
