### ISSUE TITLE
paperclip should insert media at previous cursor position

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1624]
https://forums.ankiweb.net/t/images-are-included-in-the-start-of-the-field/16967

**Comment by hgiesel** [comment]
This works for me on current main.

**Comment by hgiesel** [comment]
I have to correct myself:it works on macOS, but it does not work on Windows.

**Comment by dae** [comment]
Perhaps focus/blur events are firing at different times on the two different platforms?

**Comment by hgiesel** [comment]
> Perhaps focus/blur events are firing at different times on the two different platforms?

Yep, it seems like this is the reason. It also affects setting the text color with the pick buttons, as it's a similar scenario: Picking the color will open a new window, and afterwards we want to act on the current selection, which on Windows will not be selected yet.
