### ISSUE TITLE
Decks configured to 'Bury review siblings until next day' show buried cards in deck card count

### ISSUE THREAD

**Issue by jiqz** [ankitects/anki#1633]
A deck which has a pair of sibling cards shows both cards in the deck list:
![image](https://user-images.githubusercontent.com/87089854/151719195-ef66d16e-0ece-4852-8196-9d829e611dcc.png)
Even when it has its options set to not show both of them (if they are new or reviewing):
![image](https://user-images.githubusercontent.com/87089854/151719201-193e6b3d-9f6c-4929-8f6e-0b0a9ce61b64.png)
Though they will not show when opening the deck or going through the cards:
![image](https://user-images.githubusercontent.com/87089854/151719292-efe6d2fb-3cfd-4bf0-ae8f-2c7db0ce077d.png)

I have testing and this bug happens on both Anki for Desktop version 2.1.49 and Anki for iOS 2.0.83. I have not tested any other platforms or versions. This bug happens with both 'Bury new siblings until the next day' and 'Bury review siblings until the next day' (when the cards satifsy one of the triggers).

If the deck card overview screen (figure 1) used the same buried sibling management code as the opened deck card overview screen (figure 2), then the bug would not occur.

I would also like to ask whether cards in the 'learning' phase follow the Bury new siblings until the next day' or 'Bury review siblings until the next day' option, or whether a 'Bury learning siblings until the next day' option is needed, though a new issue may be better suited for this despite the fact that it will affect the solution of this bug.

**Comment by dae** [comment]
This behaviour is documented:

https://faqs.ankiweb.net/the-2021-scheduler.html#burying

It wouldn't make sense to bury cards before the user clicks on a deck, since which cards are buried will depend on the order decks are studied in.

**Comment by jiqz** [comment]
> Previously if you had 10 forward and 10 reverse cards, the counts would start at 20 and jump down as you review, but now they'll start directly at 10.

Doesn't this mean the count is supposed to show the amount of cards that are available to do?
Between clicking on the deck and seeing the correct card count no steps are taken, but cards are still shown when on the deck viewer which can not be done that day.

I believe that it would make more sense if the card counts in figure 3 were consistant with figure 1, though I have not checked burying behaviour in depth.

**Comment by jiqz** [comment]
I see what you mean in the docs now. Surely it's still somewhat misleading, as a user may click on a deck thinking they have more cards to do, but then are shown that there aren't any cards left to do?

**Comment by RumovZ** [comment]
> Surely it's still somewhat misleading, as a user may click on a deck thinking they have more cards to do, but then are shown that there aren't any cards left to do?

As explained above, the difference arises from burying caused by studying cards. It follows that if the count on the deck tree screen shows due cards, there should be at least one actual card to do.

Apart from that, I agree with you that the behaviour could be confusing (as could be the one of the old scheduler). Maybe future Anki versions could include a discreet hint telling the user "x more cards will be buried", or simply "(+x)" after the count.

**Comment by dae** [comment]
I don't think that would be possible to know with the current way the deck list code works. Consider the case of siblings in deck A and A::B, one with burying enabling and one without. The order cards are introduced will dictate the counts, and ordering is only applied after a particular deck is selected.

**Comment by RumovZ** [comment]
I was talking about the deck overview screen. E.g. deck A shows 10 due cards in the deck list screen, and in its deck overview screen it says 7 due cards. Then there could be a hint "3 cards will be buried if you study this deck", or simply "7 (+3)".
Of course, limits also play a role, so reviewable cards + buried cards will not always match the count in the deck list, but it may help to explain any differences.

**Comment by dae** [comment]
Ah, that makes sense
