### ISSUE TITLE
Learning column missing from the Deck Viewer

### ISSUE THREAD

**Issue by jiqz** [ankitects/anki#1634]
There is no 'Learning' column in the deck viewer:
![image](https://user-images.githubusercontent.com/87089854/151719902-705fa759-687d-4964-aadf-e8f7d7ba5d86.png)

This is most likely an artefact from the old scheduler as there was no 'Learning' card count there.

This bug was found on Anki for Desktop version 2.1.49.

Anki for iOS version 2.0.83 also has no number to repesent the 'Learning' card count, and instead puts the count in the 'Review' tab, though this is understandable as there is a lack of space, though the New cards could be given their seperate space to the right of the other two numbers, and centred veritcally on its row.

**Comment by dae** [comment]
The heading is omitted for space reasons - with it present, a lot of space is taken up by the three number columns, and it eats into the amount of space available for the deck names. If we can solve the space issue, including the label would be preferable. One option would be to have the labels shown at a 45 degree angle to make the fit.

This screen will likely be refactored later this year, so I am tempted to postpone any work on this issue until then.

**Comment by dae** [comment]
It wasn't as bad as I remembered it being:
![2022-02-16T10:23:35,467951579+10:00](https://user-images.githubusercontent.com/180542/154172676-98f2365a-b18b-4c5f-be09-56ae08e785da.png)

**Comment by jiqz** [comment]
Awesome! Would you consider it beneficial to rename _Due_ to _Review_ (considering the other two column names now better represent the current status of the cards indicated in the count beneath them)?

**Comment by dae** [comment]
It would make more sense, but it ends up being too cramped:

![2022-02-16T11:56:14,819984146+10:00](https://user-images.githubusercontent.com/180542/154181576-a4ed3748-256b-4281-b9c4-6ea8f39e427f.png)
