### ISSUE TITLE
typescript should upgrade, how to do this?

### ISSUE THREAD

**Issue by qxo** [ankitects/anki#1635]
https://github.com/qxo/anki/runs/4997479166?check_suite_focus=true#step:9:238
```
C:\users\runneradmin\_bazel_runneradmin\lxuyldak\execroot\ankidesktop\node_modules\typescript\lib\tsc.js:1695
        return str.lastIndexOf(prefix, 0) === 0;
                   ^
```

ref:  https://github.com/microsoft/TypeScript/issues/47398

-   Have a question or feature suggestion?
-   Problems building/running on your system?
-   Not 100% sure you've found a bug?

If so, please post on https://forums.ankiweb.net/ instead. This issue tracker is
intended primarily to track development tasks, and it is easier to provide support
over on the forums. Please make sure you read the following pages before
you post there:

-   https://faqs.ankiweb.net/when-problems-occur.html
-   https://faqs.ankiweb.net/getting-help.html

If you post questions, suggestions, or vague bug reports here, please do not be
offended if we close your ticket without replying. If in doubt, please post on
https://forums.ankiweb.net/ instead.

**Comment by dae** [comment]
The problems you are facing may be a product of the GitHub runner environment. Do you get the same error message when building on a local Windows machine?

TypeScript can't be upgraded until it is confirmed to work with our Svelte code, and changes may be required.
