### ISSUE TITLE
leading html comments in fields are being swallowed

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1644]
https://forums.ankiweb.net/t/bug-the-html-source-view-introduced-in-anki-2-1-45-removes-html-comments-from-beginning-of-fields/17336

**Comment by hgiesel** [comment]
It seems like `parser.parseFromString("<!--before-->test<!--after-->", "text/html")` actually returns this parse result:

```html
<!--before--><html><head></head><body>test<!--after--></body></html>
```

And then we extract the HTML from the body. Which explains why it seemingly vanishes. The solutions I see is: we treat this case specially, or we disallow HTML comments, and strip from the output, in the same way we do with with inline scripts.

**Comment by dae** [comment]
Thanks for the quick fix!
