### ISSUE TITLE
Browser should not use 'Alt+T' as a shortcut to toggle card/note view

### ISSUE THREAD

**Issue by mark-stone** [ankitects/anki#1652]
The browser uses the shortcut 'Alt+T' to toggle between the card and note views. On a Mac, the issue is that this is the key combination 'Option+T', which is a character. As such, this character cannot be typed in the search bar nor in the editor as it triggers the toggle action.

Admittedly, on a standard English qwerty layout, this might not be a commonly used character. However, this can be an issue with different keyboard layouts.

A suggested solution would be to change the keyboard shortcut to 'Ctrl+Alt+T' in the browser form. When I search the source code, this shortcut does not appear to be in use elsewhere.

**Comment by dae** [comment]
That shortcut was picked because the previous one was conflicting with a macOS shortcut as well. :sweat_smile:  Thanks for the report and the suggestion; it does seem to be free, so let's give it a go.
