### ISSUE TITLE
control+shift+t shortcut not working?

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1670]
https://forums.ankiweb.net/t/anki-2-1-50-beta-3/17501/8

clicking on the add tag button in the bottom left doesn't do anything either

**Comment by hgiesel** [comment]
I was looking whether I could defer this bug fix until after #1695, and then make a general overhaul of tag editor, using Floating UI for the Autocomplete. If the 2.1.50 release is imminent, I could also start working on it immediately.

**Comment by dae** [comment]
It would be nice not to delay a release too much longer - 2.1.49 is showing a blank screen on recent Linux distros due to libc changes, and some Windows users have been having troubles with it as well. Add-on authors will also want some time after a release candidate is released to update their add-ons, so a stable release will probably be at least 3-4 weeks after a release candidate is made available.

That said, I'm conscious that this editor work has been quite extensive, and I don't want to rush out a release if you're not ready. Do you anticipate needing to make further changes in the near future that will break add-ons targeting the code as it is now? Would you prefer to get the floating UI changes done before a release? Is there anything else you feel needs doing?

(Please don't feel pressured - my original estimate of Christmas for a release was way too optimistic, and I didn't even get the packaging changes finished until beta 3. It's also given Rumo some time to work through some v3 scheduling changes that were better made before it was labelled as stable, so the delay was for the best)

**Comment by hgiesel** [comment]
(this is resolved)
