### ISSUE TITLE
Can't add tag anymore

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#1697]
Running on 92bf23df995f99b7f52f8f9a33f0b73c49648962, add-ons disabled.
When I open the browser/add note, the button on the bottom left to add tags don't do anything. I don't even get an error message in the console

**Comment by hgiesel** [comment]
Duplicate of #1670

**Comment by Arthur-Milchior** [comment]
sorry. I did look for open bug but the title was not clear. i never used this shortcut.

**Comment by dae** [comment]
Thanks Arthur, I've added mentioned of the button to #1670
