### ISSUE TITLE
consider changes to 'forget'

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1700]
- Some users would like to reset the lapse count to delay leech flagging
- Some users aren't sure what 'Forget' will do

Associated thread:

https://forums.ankiweb.net/t/improving-forget/8644/7

**Comment by RumovZ** [comment]
I think there are two areas to consider:

1. Card data (i.e. reps and lapses; *not* forgetting interval and ease, as has been suggested on the forum, doesn't make much sense in my opinion.)
2. Revlog data

Should there be two separate options or one for both?
Regarding the revlog, I expect users don't want to see any entries when viewing a forgotten card's info, and the card shouldn't come up when searching for `introduced:x`, but they might still want the reps to be reflected in their stats. One option would be to replace the id in the revlog table with a dummy id.

**Comment by dae** [comment]
I was hoping for something more limited in scope for now :-) Anki treats the revlog as mostly immutable - once entries have been added for a card, they can't be removed except with a full sync, and I don't want to force a full sync on an action that some users may end up using on a daily basis, as that wastes network and disk resources. If we wanted to disassociate a card with its previous reviews without a full sync or DB schema changes, we'd need to change the card's id - basically deleting it and adding a new one in its place. And if the user had happened to modify the card on a different device more recently, they could end up bringing the old card back to life, causing two cards with the same ordinal to end up in the collection.

While I do think "I accidentally imported a shared deck from someone who included their learning history" is a legitimate problem that needs solving, I suspect we could come a long way towards solving that with a confirmation prompt when importing an .apkg that contains scheduling info. What I'm more focused on at the moment is:

- ensuring cards return to their original position when exporting with scheduling (shared deck export case)
- ensuring cards can return to their original position when manually forgot (cramming/wants to start again case)
- ensuring cards that have been forgotten won't trigger the leech threshold too easily, as they may have been completely rewritten (resetting lapses, or removing the acceleration after the first leech trigger)

If we're resetting lapses but leaving the revlog alone (well, actually, adding a new entry to make it clear the card has been rescheduled), then I guess a decent case could be made for resetting the reps count as well. The user would still be able to see the total reps in their review history, but the reps count, like lapses, would be a count since the card was reset. 

Does that sound reasonable?

**Comment by RumovZ** [comment]
Sounds reasonable. This is still meant to be optional, right? So there'd be a checkbox "Reset lapse and repetition counts".

**Comment by dae** [comment]
Sorry, that should have read “when exporting without scheduling”

And yep, if we have the option for original position, we might as well make
this optional too, as you mentioned earlier. Perhaps we could remember the
user’s choices like set due date does?

**Comment by RumovZ** [comment]
An alternative to disassociating revlog entries from a card would be filtering them out at fetch time, but that would require some indicator on the reset entry. It would presumably need to use a new ease number that corresponds to "manual reschedule with hard reset". Then when the revlog is requested, any entries after an entry with that ease number would get filtered out.

Just mentioning that in case the need arises in the future.

**Comment by dae** [comment]
This would be cheap and easy to do when showing the revlog screen, but I suspect handling it for search/the graphs would be a fair bit more complicated unfortunately.
