### ISSUE TITLE
F7 hotkey clash for 'Set text color' and 'Attach pictures/audio/video'

### ISSUE THREAD

**Issue by laggykiller** [ankitects/anki#1701]
When adding or browsing card, pressing F7 would trigger both 'Set text color' and 'Attach pictures/audio/video'. I am using version 2.1.50 (95dbf30f) on Windows.

![image](https://user-images.githubusercontent.com/61652821/156166121-8d8c37b6-c557-4984-bec9-b143aa5539f5.png)

**Comment by hgiesel** [comment]
I introduced this bug at some point, and then silently fixed it again. It's already fixed on the main branch.

**Comment by laggykiller** [comment]
Thank you! Confirmed that 'Attach pictures/audio/video' hotkey is changed to F3 in latest beta (2.1.50, 3564ece6). Closing.
