### ISSUE TITLE
Tag suggestions do not show up when adding a new card in fullscreen

### ISSUE THREAD

**Issue by computeristic** [ankitects/anki#1708]
When I am adding a new card and I start typing the first few letters of existing tags in the 'Tag' input bar, suggestions show up (then I can press 'Enter/Return' to autocomplete). However, when I make the window fullscreen, these suggestions do not show up anymore. This never hapenned before today but I did not change or update anything (anki or OS). I tried restarting anki and restarting my macbook. I also tried disabling all add-ons and then restarting anki. 

Anki: Version ⁨2.1.49 (dc80804a)⁩ Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
OS: macOS Catalina 10.15.7 (19H1715)

**Comment by dae** [comment]
Can you reproduce the issue with the latest beta?

**Comment by computeristic** [comment]
The issue is not reproducible in the latest beta, it works just fine. I'll be using the beta until the next update, thank you!

**Comment by dae** [comment]
Thanks for testing!

**Comment by computeristic** [comment]
@dae no problem! However, I noticed a change in behavior (which may be intentional). In 2.1.49, pressing enter/return after getting a tag suggestion autocompletes my partially entered tag. In the latest beta, I have to arrow up or mouse click the suggestion for autocomplete. This can be cumbersome when adding many cards and multiple tags, but I understand if it is intentional in order to prevent accidental autocompletions.

**Comment by hgiesel** [comment]
@computeristic
You can also use the Tab key to navigate through the items, so to select the first item, you can press Tab, and then Enter.

This was a deliberate change from the old behaviour, because under the old behaviour, there was no visual indication that the first item of the suggestions was "selected". However we're still opening to adjusting the behavior, and making it easier to use.

**Comment by computeristic** [comment]
@hgiesel ohh this is even better. I used to keep on typing until I eliminate all suggestions but the one I wanted. Navigating with Tab and Enter is better. Thank you for your work on the tag editor! I really appreciate FOSS developers and contributors.

**Comment by computeristic** [comment]
An issue that I stumbled upon while adding new cards in the latest **beta** is that I cannot access the tags via the Tab key (and I cannot Tab out of the tags either).
