### ISSUE TITLE
Decreasing and increasing number of card

### ISSUE THREAD

**Issue by andydeliot** [ankitects/anki#1718]
Hello ankitecters,
New card in the deck : 30
New card for today : 10
Decrease new card for today to -20
New card for today : 0
Increase new card for today to +15
New card for today : 5.
It seems the deck can have a negative number of new cards.
It's not very important, but It has an impact on me because I stupidly wrote -1000 and it's not possible to add +1000 because the number is limited to the number of new cards in the deck (here 30). So, I can't have any new card for today.

**Comment by dae** [comment]
The current development code has changed the behaviour of this screen, so it no long limits the numbers you can input. In the mean time, your limits should reset at the start of a new day.
