### ISSUE TITLE
Change note type is broken (and broke my collection in a way I don't understand yet)

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#1727]
Running on d100f7a2c8681b2d4dd1bf03797ef8fb3157358b

This is not a minimal bug report. I have no idea how to create a minimal report right now, when I tried, the bug did not occur. So I just give you the bug as I have it.

How to reproduce:
* Create a new collection 
* import [Emporte pièces.apkg.zip](https://github.com/ankitects/anki/files/8310622/Emporte.pieces.apkg.zip)
* Change note "emporte pièce" to "Basic (and reverse card)". Send fields "Definitions" to Front. Send Name to Back. Send cards "definitions" to "card 1" and "names-notations-denoted by" to "card 2". (Those are the two card type that actually have cards in this deck)

Expected result:
* Note "def, note" should remain as it is.

Actual result:
* Note "def, note" have cards that changes. "Definitions" become "Intuition" 

Note that if the same change is done on the "def, note" instead of the "emporte pièce", then the "def, note"'s card "names-notations-denoted by" become "assuming"

I've really no idea what's going on. And more importantly, if there is a way to reverse it, because it kind of broke my whole collection after more than four hours of review.
Usually, it would not be a big deal, because I always sync before doing important change, but I just discovered that sync do not create back-up anymore, meaning that I did important change without back-up. And since I don't even understand what occurred, I can't just write a script to reverse it myself.

Note that the change occurs even on notes that are not shown in the deck.

**Comment by dae** [comment]
Thanks for the repro Arthur, I've pushed a fix. Sorry about the lost work. :-( It would have resulted in all cards with a given ordinal from being changed to a different ordinal, so you may be able to recover by applying updating the current collection with the ordinals that were in the backup from 4 hours ago. You can see the SQL that was being executed by running your current checkout with TRACESQL=1

**Comment by Arthur-Milchior** [comment]
I assume TRACESQL is an environment variable. I may try eventually

Yep, I was already porting ord from 4 hours ago to current collection. Sadly, this is not even the first time it occurred to me, so I already had a script for that. (But last time, I broke the collection myself)

I know it can occur when running on main. Happy to be able to report bug. But I'll really need to find a way to make back-up that don't require to leave the profile, because that would considerably increase the cost

**Comment by dae** [comment]
We were already mostly there with our recent backup/exporting changes. Please give #1728 a go, you should find it performs reasonably well on your large collection.

**Comment by Arthur-Milchior** [comment]
Actually, I doubt it only changed the ord of existing card. I just discovered that 4156 were added between now and the last back-up previous to this change.
And I'm quite certain that I've not had time to create that many cards during the week-end.
Obviously, it may be a totally different bug, that occurred by coincidence. But I really have no clue what https://github.com/ankitects/anki/commit/e2eff7deaee5d7c380d0cb930186c62fa0309de5 does, and so I suspect it may be related as it would be a strange coincidence

What I really fail to understand is that I've got 8919 pair of cards that are duplicate of each other (same ord and same nid)
For 4927 such pairs, one of the card has queue = 0, so it may just be a card that was created during the bug, but for 3992 pair, none of the cards of the pair are new. And I don't yet know what's going on here

**Comment by Arthur-Milchior** [comment]
Never mind, I copied the ords from a wrong version of anki. I only have 9 duplicate cards now

**Comment by RumovZ** [comment]
https://github.com/ankitects/anki/commit/e2eff7deaee5d7c380d0cb930186c62fa0309de5 is really just about inserting some missing brackets in the SQL query. `SearchBuilder` is a tool to build many different Anki objects into an AST, which in turn can be written into a SQL statement.

I didn't work directly with this code, but introduced the bug when I added the SearchBuilder for some other PR. (The gotcha is that `.and_join()` does no implicit grouping/bracketing.)
Very sorry about that and I hope you could sort it out!
