### ISSUE TITLE
Audio cutting off early on Windows Desktop due to mpv, forking mpv while they solve this issue should fix it

### ISSUE THREAD

**Issue by Garethp** [ankitects/anki#1730]
Since Anki swapped over to mpv for Windows audio I've been having an issue with audio being cut off at the end of cards and decided to dig into it. As far as I can tell it's an issue with the audio draining for mpv not working correctly for the windows driver (and for other drivers but for this bug report I'm specifically talking about the windows driver). 

I've got an [issue logged against mpv](https://github.com/mpv-player/mpv/issues/9535) and I've got my own patchwork fix for this running locally. The patchwork solution is just to add a 150ms sleep [when the audio driver tried to shutdown](https://github.com/mpv-player/mpv/blob/master/audio/out/ao_wasapi.c#L229) and this lets windows properly play the audio before shutting the thread down. 

```c
        case WASAPI_THREAD_SHUTDOWN:
            Sleep(150);
            thread_reset(ao);
            goto exit_label;
```

The reason I'm not posting this in the forums is that I don't know how to compile mpv with all the dll's statically linked, so instead I wanted to know if you compiled mpv yourself or got it from someone else. If you compile it yourself, I can fork mpv at a specific version and you can compile from my forked repo to solve this problem while mpv works on it?

As far as I can see there have been numerous other people running into this issue posting on ankweb or reddit but because of how difficult this problem is to diagnose for someone else and how there's no clear workaround there doesn't appear to be much response to people asking for help, but I do think that this would be quite a wide-spread issue

**Comment by dae** [comment]
I'd prefer to avoid having to recompile mpv if at all possible. Did you try the various -ao options, and rule out third-party software such as Sonic Studio? https://forums.ankiweb.net/t/desktop-anki-2-1-35-no-audio-playback/3990

**Comment by Garethp** [comment]
I did try that, yes. This is roughly the steps I went through to try and pinpoint the issue as actually being with how mpv handles the audio driver

* I put logging in the `ao-wasapi` drivers to double check that it was making the correct calls
* Tested that just making the wasapi driver shut down 150ms slower fixes it, 
* I think I confirmed the root cause of it (MPV tells the thread with the wasapi driver to shutdown when it reaches the EOF of the sound file, but due to how wasapi works that shuts it down before all the audio is finished playing and therefore the audio gets cut off).
* Confirmed that documentation for the wasapi driver by Microsoft shows that you need to wait extra time for the audio to play before shutting down the thread, which MPV does not do
* Tested it against another mpv driver that should work similarly to see if it has the same issue (I tested playing the mp3 Japanese audio in mpv on Android and saw the exact same issue)

I'm fairly confident in saying that it's due to when mpv decides that the audio is "done" being out of sync with when the audio has finished playing in the wasapi drivers and ones that work similarly. You could wait for mpv to fix it properly if you really wanted, but I opened the ticket at the end of November and I don't think anyone who works in this area of mpv has had the time to look at it since. I've been working on the issue on and off since then to try and make it easier/quicker for them to fix it when they do get around to it, but I'm not sure when that'll be

**Comment by abdnh** [comment]
> The reason I'm not posting this in the forums is that I don't know how to compile mpv with all the dll's statically linked

You can [compile mpv on MSYS2](https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md#native-compilation-with-msys2). The resulting binary is dynamically linked, but you can probably test it with Anki by writing a simple add-on like [this one](https://ankiweb.net/shared/info/383102081), which I will just put its code here:

```python
from aqt import mw
from anki.utils import isWin
from aqt.sound import av_player, SoundOrVideoPlayer, SimpleProcessPlayer

class SimpleVLCPlayer(SimpleProcessPlayer, SoundOrVideoPlayer):
    default_rank = 3
    
    args = [
        'C:\\Program Files\\VideoLAN\\VLC\\vlc.exe',
        "-I dummy",
        "--dummy-quiet",
        "--play-and-exit",
        "--video-on-top",
        "--no-video-title-show",
        "--no-video-deco",
        "--video-x=5",
        "--video-y=5",
    ]

if isWin:
    vlc_media_player = SimpleVLCPlayer(mw.taskman)
    av_player.players.append(vlc_media_player)

```

**Comment by Garethp** [comment]
That's actually what I did, I compiled MYSYS2 with the change I mentioned in the main post and just pasted it into the Anki folder, replacing the distributed `mpv.exe` and it fixed the issue right away. As I said, the main I reason I didn't post it in the forums is that because it's dynamically it's not just a nice single `.exe` file that works as a drop-in replacement. There's all the dll files and libraries that come with it

**Comment by abdnh** [comment]
The Windows builds by shinchiro listed in [mpv's installation page](https://mpv.io/installation/) are statically linked (Try running `ldd mpv.exe`). You can see how they are built here: https://github.com/shinchiro/mpv-winbuild-cmake

**Comment by dae** [comment]
Looks like a pain to build on Windows :-(

@Garethp does https://ankiweb.net/shared/info/1586469444 help at all? 

One other thing that might be worth trying is modifying Anki to invoke mpv with two audio files instead of one, eg

mpv real_file.mp3 150ms_silence.mp3

Whether that helps or not will depend on how mpv handles the audio driver with multiple files. If such an approach worked, it would mean the delay could be adjusted on different devices, and we wouldn't need to try to rebuild mpv.

**Comment by dae** [comment]
Did you have any luck with the add-on or adding an extra audio file?

**Comment by Garethp** [comment]
Sorry for the delayed reply, I ended up busy when the notifications came in and forgot about them. Playing a silence mp3 after the real file does actually work to fix the audio, the plugin did not
