### ISSUE TITLE
Update demo/docs for editor changes

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1733]
Aside from making life easier for add-on authors, an updated demo will help us check the API is working as intended.

Related: https://forums.ankiweb.net/t/2-addons-conflicting-with-svelte-components-editortoolbar-toolbar-insertgroup/18019

**Comment by luc-languagetools** [comment]
many thanks for creating this, I'd love to test any changes, i'm happy to do some of the work if you set me in the right direction

**Comment by dae** [comment]
@luc-languagetools does rc2 resolve the duplicate group issue you were experiencing?

**Comment by luc-languagetools** [comment]
@dae no, I'm not able to get anki_new_format_pack working, so I don't know how to hook into the new editor API:
https://github.com/hgiesel/anki_new_format_pack/issues/8
let me know if more details are needed to reproduce. It could be the problem is with anki_new_format_pack.

**Comment by luc-languagetools** [comment]
If I could have my wish, I would love to see an example addon which creates a whole new component on the editor (not just adding a button like anki_new_format_pack), similarly to https://uploads-ssl.webflow.com/602f82f1abdf727c415dfca9/621f7b75edda7ddf95fa1705_2022-03-02_update_preview_audio.png
I'm happy to sponsor this development with money (please reach out languagetools@mailc.net), as I realize it may be quite specific to my addons.

**Comment by dae** [comment]
This should get you going with the add-on: https://github.com/hgiesel/anki_new_format_pack/pull/9

I'd recommend using its build system as a template for your build, since you need to exclude svelte & anki from bundling, and because your current bundle seems to be including import statements. The following change to your code may help, but I wasn't able to test them.

```
import * as NoteEditor from "anki/NoteEditor";

NoteEditor.lifecycle.onMount(({ toolbar }) => {
    toolbar.toolbar.append({component: LanguageTools, id: "languagetools"});
});
```

**Comment by luc-languagetools** [comment]
I can confirm your latest merge to anki_new_format_pack fixes those new toolbar buttons (like strikethrough) on 2.1.50 rc2, now let me try to update my addons.

**Comment by luc-languagetools** [comment]
I got everything working in HyperTTS now with 2.1.50 rc2 thanks to those updates. thanks a lot for updating the documentation as well, it wasn't clear at all to me that the anki/ dir is an git submodule.

**Comment by glutanimate** [comment]
Thanks for working on updating the docs!

@hgiesel @dae, is there any documentation / are there any examples regarding interfacing with the editor's fields? I'm trying to restore Image Occlusion's ability to hide its ID field (so as to prevent inadvertent changes to it). Managed to find a reasonable solution by hooking into `editor_did_load_note` via Python, but the timing is not ideal, causing the field to briefly flash before hiding.

However, attempting to access the `EditorFieldAPI.element` promise any earlier fails for me due to the property being undefined.

I.e., running this on `editor_did_load_note` to access a specific field element by its index works :

```javascript
require("anki/ui").loaded.then(() => {require("anki/NoteEditor").instances[0].fields[0].element.then((element) => {console.log(element)})});
```

but fails when injected either at the `editor_will_load_note` hook stage, or run even earlier via a local script injected via `webview_will_set_content`. Either of these stages seem to be too early.

Subscribing to `NoteEditor.lifecycle.onMount` also didn't help, and same story of course for getting the fields via their CSS selector at these stages.

Are there any other hooks/events/something similar that a caller can subscribe to in order to trigger as soon as all field components / elements are rendered to the DOM, but not yet shown (if there even is such a stage)?

Apologies in advance if I'm missing something obvious.

**Comment by hgiesel** [comment]
Yes, the issue with `NoteEditor.lifecycle.onMount` is that it's more about the visual component being initialized, and not about upstream logic like "notetype changed".

I don't think there's a better solution currently. The editor does not really know when the notetype changed.

I think once we use the Rust backend in the note editor, adding a hook here will be trivial: https://github.com/ankitects/anki/pull/1691/files#diff-f837972ae4746bfa1bb14c5e4b77fefa43d7f672709bc8744dc1061c13cca71eR72

**Comment by dae** [comment]
While making TS responsible for loading/saving field content in #1691 will make it somewhat easier to reason about things, this particular issue seems to be less about detecting a notetype change as it is about expecting the fields to be accessible after a call to setFields(), when they don't get populated until the next tick. The following seems to work (the change to `js` is just to demonstrate what an add-on might do in editor_will_load_note):

```
diff --git a/qt/aqt/editor.py b/qt/aqt/editor.py
index ad6094009..02688c99c 100644
--- a/qt/aqt/editor.py
+++ b/qt/aqt/editor.py
@@ -515,7 +515,7 @@ require("anki/ui").loaded.then(() => require("anki/NoteEditor").instances[0].too
         text_color = self.mw.pm.profile.get("lastTextColor", "#00f")
         highlight_color = self.mw.pm.profile.get("lastHighlightColor", "#00f")

-        js = "setFields({}); setDescriptions({}); setFonts({}); focusField({}); setNoteId({}); setColorButtons({}); setTags({}); ".format(
+        js = "setFields({}); setDescriptions({}); setFonts({}); focusField({}); setNoteId({}); setColorButtons({}); setTags({}); awaitFields().then(function() {{ require('anki/NoteEditor').instances[0].fields[0].element.then((element) => {{console.log(element)}}); }});".format(
             json.dumps(data),
             json.dumps(descriptions),
             json.dumps(self.fonts()),
diff --git a/ts/editor/NoteEditor.svelte b/ts/editor/NoteEditor.svelte
index 957b07616..0958d73e4 100644
--- a/ts/editor/NoteEditor.svelte
+++ b/ts/editor/NoteEditor.svelte
@@ -248,6 +248,7 @@ License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
             focusIfField,
             setNoteId,
             wrap,
+            awaitFields: tick,
             ...oldEditorAdapter,
         });
```

Perhaps in 2.1.51 we should be exposing this to enable such use cases? Preferably with a better name, and in a module rather than yet another global variable. Will need to look into whether we can expose a single shared tick function, or whether each component needs to export their own when required.

**Comment by hgiesel** [comment]
That's a good call.
We don't need to export `tick`, because it's not bound to the component (it's bound to the Svelte internals), so this also works:

```typescript
require(\"svelte/internal\").tick().then(() => {{ require('anki/NoteEditor').instances[0].fields[0].element.then((element) => {{ element.hidden = true; }}); }}); 
```

**Comment by dae** [comment]
Nice, that makes everyone's life a bit easier :-)

@glutanimate that approach should work for you without changes on our end, and as we need to expose that module anyway, it's likely not going to disappear soon.

**Comment by dae** [comment]
Further API tweaks/documentation are tracked in #1764 

There are also some notes about typechecking on https://github.com/hgiesel/anki_new_format_pack/pull/11

**Comment by andrewsanchez** [comment]
Just confirming this worked a charm. Thanks, @dae and @hgiesel!

```python
def hide_field_in_editor(js: str, note: Note, _: Editor) -> str:
    if "my field name" not in note:
        return js
    extra = (
        'require("svelte/internal").tick().then(() => '
        "{{ require('anki/NoteEditor').instances[0].fields[0].element.then((element) "
        "=> {{ element.hidden = true; }}); }});"
    )
    js += extra
    return js
```
