### ISSUE TITLE
Certain field content causes HTML editor to get stuck in infinite loop

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1740]
As reported on https://forums.ankiweb.net/t/anki-2-1-50-beta-6-9-stable-release/18181/62

Appears to have been introduced in 16e9e56ad8a52cf075b90f54e846c223736252cd

Adding a print statement to the top of removeProhibitedTags() shows that the HTML is oscillating between two states:

```
JS info /_anki/js/browser_editor.js:73476 html: n. <m. 1=""> jmd., der stiehlt bzw. gestohlen hat; einen ~ bestrafen, ertappen, fangen, festnehmen; haltet den ~! (Alarmruf, wenn man einen Dieb auf frischer Tat ertappt) [<ahd. diob,="" engl.="" thief,="" got.="" þiufs,="" þiubis;="" zu="" idg.="" *teup-="" sich="" niederkauern,="" hocken="" (um="" sich="" verbergen)]<="" body=""></ahd.></m.>
JS info /_anki/js/browser_editor.js:73476 html: n. <m. 1=""> jmd., der stiehlt bzw. gestohlen hat; einen ~ bestrafen, ertappen, fangen, festnehmen; haltet den ~! (Alarmruf, wenn man einen Dieb auf frischer Tat ertappt) [</m.>
```

**Comment by GPLv3-fan** [comment]
The issue appeared on card templates after using the "ssmtool":
https://github.com/FreeLanguageTools/ssmtool
Youtube video:  https://www.youtube.com/watch?v=y79_q08Zu8k

Card templates produced via "ssmtool" worked fine few weeks ago until now with 2.1.50 beta 9.

**Comment by GPLv3-fan** [comment]
Here is the Deck that caused the original issue, described by "Levitator" on Anki Forum:
https://my.opendesktop.org/s/MRCck5DEpdFXc3W

Open the browser and search the word "**Dieb**" on that deck.

**Comment by hgiesel** [comment]
> Does the HTML issue on Anki requires some action by the author of the sentence mining tool ?

The cause of this bug, that the inserted text contains `<` and `>` without escaping. If you take text from websites, you need to filter it appropriately, to make it valid HTML. That includes transforming `<` to `&lt;`.

I'm still looking into the exact origin of this bug.

**Comment by GPLv3-fan** [comment]
The code seems to work well now ! All the crashes disappeared. Thanks @hgiesel
