### ISSUE TITLE
not displaying anything in arco (arch based)

### ISSUE THREAD

**Issue by Apep-the-snek** [ankitects/anki#1741]
![image](https://user-images.githubusercontent.com/33030702/160243464-0a9e01b6-5016-4902-892b-3e98d0ca1249.png)
looks like this when i boot it up and it has no errors yet.
if i try study a deck i get nothing on screen, but i sometimes get a variation of this printed in the terminal: ```Qt warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3853, resource id: 10388149, major code: 40 (TranslateCoords), minor code: 0```, nothing crashes or freezes, and the window flashes white twice. occurs on a pretty fresh arco linux xfce system, i installed anki via this method with no errors: [https://docs.ankiweb.net/platform/linux/installing.html](https://docs.ankiweb.net/platform/linux/installing.html)

**Comment by Apep-the-snek** [comment]
workaround, run  ```anki --no-sandbox```, this will remove a popup at startup causing the issue, this is a temporary fix as this shouldn't be needed in the first place.

**Comment by dae** [comment]
It's documented on https://docs.ankiweb.net/platform/linux/blank-window.html
