### ISSUE TITLE
Document web exports

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1745]
https://github.com/ankitects/anki-addons should mention the API discussed on https://forums.ankiweb.net/t/error-loading-image-on-front-side-of-note-using-javascript/18610

**Comment by ShahRishi** [comment]
Hi, could I work on this issue?

**Comment by dae** [comment]
If you're able to work on this without requiring help, sure!

**Comment by doomdagadiggiedahdah** [comment]
Did you just want this in a README or located in one of the scripts?

**Comment by dae** [comment]
In https://addon-docs.ankiweb.net/, which is https://github.com/ankitects/anki-addons

**Comment by AryanilPanja** [comment]
@dae I would like to work on this issue but i am new to open-source so a little bit of guiding and assistance may help me a mile.
Thanks!

**Comment by dae** [comment]
The API is documented in the source code: https://forums.ankiweb.net/t/error-loading-image-on-front-side-of-note-using-javascript/18610/2?u=dae

It would be good to mention this in the the add-ons manual too. To do this, you'd have to make a change to the repo linked above, then submit a PR. I'm afraid if it's not clear how to do those things, this might not be the best issue to start with.

**Comment by ShahRishi** [comment]
Hi @dae I added the docs to a PR in this repo: https://github.com/ankitects/addon-docs. Thanks!

**Comment by brishtibheja** [comment]
Is this to be closed?

**Comment by dae** [comment]
Yep, thanks!
