### ISSUE TITLE
Large images load slowly on recent Qt versions

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1753]
https://bugreports.qt.io/browse/QTBUG-99130

6.2.4 looks to include a fix/improvement for this, but we can't update to it until https://github.com/ankitects/anki/issues/1751 gets fixed

**Comment by krishamafia** [comment]
yeah large images load very slowly in qt6 version .. moved back to 2.1.49 and i felt it is very smooth  after using 2.1.50 for couple of days.

**Comment by hgiesel** [comment]
You can use 2.1.50 with Qt5 as well, no need to go back to 2.1.49.

**Comment by dae** [comment]
Sort of - on Mac and Linux, the Qt 5 version is the same as .49, but on Windows we had to upgrade to Qt 5.15 for Python 3.9 support, and .15 unfortunately introduces the slowdowns.

**Comment by krishamafia** [comment]
2.50 qt5 not even opening on window 10

**Comment by dae** [comment]
Removing \program files\anki and then installing again may help. If it doesn't, please run anki-console and see what it says.
