### ISSUE TITLE
Inertial scrolling not working on Qt6 Mac build

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1770]
Qt 6.3 is due out in a few weeks; we should give it a try to see if it improves the situation at all.

https://forums.ankiweb.net/t/anki-2-1-50-beta-6-release-candidate/18181/84

**Comment by roxgib** [comment]
Inertial scrolling is working fine for me on RC2 and RC3 and when I build a wheel. I _am_ able to observe this issue when using `./run` however.

@hgiesel, have you experienced this with the released betas or [from a wheel](https://github.com/ankitects/anki/blob/main/docs/development.md), or is it just when running from source?  

I'm on MacOS 12.3 (ARM)

**Comment by dae** [comment]
If you're running from a venv you may be using a newer Qt version. The bazel/official builds are currently pinned to 6.2.2 due to #1751. Sounds like Qt may have fixed this in a subsequent point release.
