### ISSUE TITLE
Consider switching focus when enabling HTML editor

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1778]
https://forums.ankiweb.net/t/anki-2-1-50-beta-6-release-candidate/18181/124

@hgiesel WDYT? Would this be easy to do, and do you think it's a good idea?

**Comment by hgiesel** [comment]
Sounds like a good idea to me.

There's another issue related to this: If you have both visual + HTML editor open, and close the HTML editor while having focus in it (or vice versa with the visual editor), the entire editor field will be deselected.

It would make more sense to move the focus into another *editing input* (in this case the visual editor) of the *editor field*.

I remember trying to implement this when first writing the focus handling in the editor field, but encountered some issue. Let's see if it still exists.
