### ISSUE TITLE
`traceback.print_stack` throws an error on Windows

### ISSUE THREAD

**Issue by abdnh** [ankitects/anki#1786]
I've been investigating an error in AnkiConnect that turned out to be caused by the `traceback.print_stack` call in [requireReset()](https://github.com/ankitects/anki/blob/8100e81789ed633f862265a47ddbda8aacf3499a/qt/aqt/main.py#L779).

![image](https://user-images.githubusercontent.com/41397710/162557304-546ea98c-04af-4243-9002-81174634cf7d.png)

The error doesn't occur when running Anki from the console on Windows. The following minimal add-on triggers the error:
```python
import sys
import traceback

traceback.print_stack(file=sys.stdout)
```

Related issue in AnkiConnect's issue tracker: https://github.com/FooSoft/anki-connect/issues/308

**Comment by dae** [comment]
If you show repr(sys.stdout) in showInfo(), what does it say?

**Comment by dae** [comment]
To answer my own question, it appears to be None. That is unexpected; will investigate.

**Comment by dae** [comment]
Thanks for the report Abdo, please let me know if it's not fixed in the next build.
