### ISSUE TITLE
Note browser: sidebar links replace last search instead of being added to it

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#1788]
Reproduction:
* open the browser
* type a search FOO1
* type a second search FOO2
* click on a note type in the sidebar
* click on the search bar, 
* press the down key

Expected result:
* search is FOO2

Actual result:
* search is "FOO1"

The issue is that when you click on the left, it does not change the position in the list. So the selector behaves as if the content was "foo2". It can be seen because if you press the arrow on the right, you'll see that the top search content is still "FOO2".

For what it's worth, it's easier to add all search in the history, even if some are really simple and can be obtained by clicking again. But I understand it's not clear, since clicking on an element of the side bar is really easy

**Comment by dae** [comment]
@RumovZ any thoughts?

**Comment by RumovZ** [comment]
Good point about the selector index, which is an easy fix.
I also tend to agree about committing everything to history. The current distinction of programatic and manual searches is a bit unintuitive, and it's possible to construct complex searches via the sidebar now, that can't simply be reproduced with a single click. On the other hand, sidebar searches do have the potential to clutter the history, and make actually typed-in searches less accessible, and it's established behaviour. I'm undecided.

**Comment by dae** [comment]
Thanks for the quick fix :-) I'm not sure what the best course of action is for the other part either. Do you have any suggestions Arthur?

**Comment by glutanimate** [comment]
To maybe chime in quickly, I would personally prefer having sidebar searches not populate the search history. I completely see Rumo's point that users might want to go back to complex searches they've constructed, but I think that use case is comparatively rare to users just clicking onto a single tag or deck. I would argue that simple searches like that could crowd up the history quite quickly and make it less useful overall. I also think that it's more clear-cut for users to associate the search bar history with their own inputs than to make the jump to searches invoked via more distant UI elements.

Not to distract the discussion, but if I can make one somewhat related suggestion: I feel like the current UX for saving a search is fairly difficult to discover, hidden in the _Saved Searches_ context menu. 2.0 used to have a favorite icon next to the search bar, right? Is that something we could perhaps reintroduce? I think this could help with the "saving complex sidebar searches" use case, providing a more obvious and quick way for users to favorite meaningful searches.

**Comment by dae** [comment]
Thanks, you make some good points.

I'm not so sure about adding back that icon; a heart without a label is not necessarily self-explanatory, and every extra element on that page makes it a little more overwhelming for new users.

**Comment by Arthur-Milchior** [comment]
I can give you my opinion, and I will, but you know my collection is unusual.

I usually want to select a specific deck, then will spend quite some time working in this deck. Given the hundreds of deck, having the deck in the search history help, as finding it in the left bar may require quite some scroll. Same than having `cd anki/ankidroid` in my terminal, it's easy to type, but I still use history because it comes naturally under my hand.
Also, ctrl+f select the bar, and I've no such easy keyboard way to select a deck as far as I know.

Since duplicates are removed from history, I would not expect the history to be cluttered that much.

But in any case, I don't think I should be consulted as what would be best behavior when my use is so unusual and I can correct behavior I don't like with add-ons (and sometime do).

@glutanimate since I don't see you answering on discord, I'll try to use here to ping you. It would be good if you could look at the pings to you in moderation channel since you are still the only admin
