### ISSUE TITLE
"Sort by this field in the browser" request full sync and don't use it

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#1789]
Reproduction:
* open a collection with at least one note
* Sync (force if necessary)
* Open the "Fields" window of a note type with existing card
* Select a field which is not the sort field
* press "Sort by this field in the browser
* click save

Expect result:
* either just saving and changing the sort field
* or "sync" is red and require full sync

Actual result:
* A message warning there will be a full sync.
* when you accept, you can do partial sync

**Comment by dae** [comment]
Thanks Arthur!
