### ISSUE TITLE
There is no sound in the audio of version 2.150 (2.149 is normal). The system is MacOS 12.3.1. I hope to solve this bug

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [ankitects/anki#1790]
In the official version of 2.150, there is no sound whether the audio is made by plug-in or by myself. It is normal to downgrade back to 2.149
The system is Intel version, QT6 and Qt5 have tried

**Comment by shoudeyunkaijianyueming** [comment]
in_the_official_version_of_2_150_there_is_no_sound_whether_the_audio_is_made_by_plug_in_or_by_myself_it_is_normal_to_downgrade_back_to_2_149_the_system_is_intel_version_qt_6_and_qt_5_have_tried

**Comment by shoudeyunkaijianyueming** [comment]
I found the reason . So I disabled the plug-in advanced answer sounds.(it may have bug)

**Comment by dae** [comment]
Thanks for letting us know you found the problem.
