### ISSUE TITLE
Reduce font size of editor toolbar/field labels?

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1792]
https://forums.ankiweb.net/t/anki-2-1-50-inconvenient-interface-size/19024

**Comment by dae** [comment]
@hgiesel do you think we should adjust the field label size at all, or just call it 'done' since #1853 was merged in?

**Comment by dae** [comment]
@hgiesel ping

**Comment by hgiesel** [comment]
The value I changed did not affect the field labels, so they're still at the same size. I think we could hook the up to the `--base-font-size` var we also have floating around.

**Comment by dae** [comment]
With the following, the field name feels a bit tiny on Windows at non-2x. On a Linux machine it seems ok. On a Mac it feels a bit small as well. Maybe we only should be applying this on certain DPI configurations? I'm tempted to just call this complete for now, and wait until we see further feedback before moving further.

```diff
diff --git a/ts/editor/LabelName.svelte b/ts/editor/LabelName.svelte
index 527acdbda..20eb41f5c 100644
--- a/ts/editor/LabelName.svelte
+++ b/ts/editor/LabelName.svelte
@@ -10,5 +10,6 @@ License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
 <style lang="scss">
     .label-name {
         user-select: none;
+        font-size: var(--base-font-size);
     }
 </style>
```
![2022-06-20T12:35:26,510441453+10:00](https://user-images.githubusercontent.com/180542/174518590-e38e51f7-bdc7-4238-bb3d-1c6128c7b9c4.png)

**Comment by dae** [comment]
Let's call it complete
