### ISSUE TITLE
Pressing shift cancels pending bold status

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1795]
Appears to have been introduced in either 

52dc889e7fe35a950b8f3f94e9f5c2824830039a or 4117fbea6c9d0457fe24ae75d601eb99785d2a7a (the former fails to build).

https://forums.ankiweb.net/t/anki-2-1-51-release-candidate/18942/5

If this can be fixed easily/without risk of breaking other things, it would be nice to have for 2.1.51

**Comment by arensonzz** [comment]
I came here to open an issue about this weird behavior. Glad I first checked the existing issues!
