### ISSUE TITLE
selected text in card editor not copied into system clipboard on linux

### ISSUE THREAD

**Issue by karolszk** [ankitects/anki#1799]
Noticed in the latest 2.1.50 version of Anki. (qt6)
While I'm adding a new card: first write text and next select it, after this I've tried Ctrl-C or context menu action "Copy".
Text is copied in Anki itself because I can paste it into editor of the back card. But outside of Anki can't.
On previous version (2.1.49) this feature works perfectly.
Thank you.

**Comment by dae** [comment]
It works for me. Did you use the official binary package?

**Comment by dae** [comment]
At least one person on the forums seems to have resolved their problem by disabling add-ons.

**Comment by karolszk** [comment]
Hello @dae thank you for such quick answer. 

I am using the official binary package, I mean https://github.com/ankitects/anki/releases/download/2.1.50/anki-2.1.50-linux-qt6.tar.zst

About says:

Version ⁨2.1.50 (26d40c3a)⁩
Python 3.9.10 Qt 6.2.2 PyQt 6.2.2

on Debian bullseye, wayland and gnome. Additionally I don't have any add-ons installed.

**Comment by karolszk** [comment]
@dae I've done one more test. When I switched Gnome to X.org mode copy-paste works perfectly. When I switch back to my normal mode Wayland copy-paste doesn't work properly.
