### ISSUE TITLE
Align list items by default

### ISSUE THREAD

**Issue by kleinerpirat** [ankitects/anki#1801]
There have been multiple topics about this on the forum:
- https://forums.ankiweb.net/t/aligning-bulleted-lists/8366
- https://forums.ankiweb.net/t/formatting-bulleted-lists/8553
- https://forums.ankiweb.net/t/ordered-list-function/12039
- https://forums.ankiweb.net/t/bullets-and-number-list-on-ipad/6601

Since list insertion and editing is now officially implemented, I fear the rate of  such questions will increase.

![image](https://user-images.githubusercontent.com/62722460/163345135-1688cb60-91bd-4b52-851e-dcfafb11763f.png)

## Proposal
```
li {
    text-align: start;
}
```

**Comment by dae** [comment]
It seems sensible, though it may introduce problems in some (hopefully rare) cases like RTL text. WDYT @hgiesel @abdnh  @hikaru-y?

**Comment by abdnh** [comment]
`start` is meant to be directionality-aware, so I believe this won't cause any issues with RTL text.

Compare `left`:
![image](https://user-images.githubusercontent.com/41397710/163492996-7fdc2624-b2b4-4e26-9f80-7f6ddd64908a.png)

With `start` (with `dir=rtl`):
![image](https://user-images.githubusercontent.com/41397710/163493003-c17dbb8f-a9f8-44ba-97c4-257d312fdd28.png)

Current behavior with no explicit text-align:
![image](https://user-images.githubusercontent.com/41397710/163493081-c2861b42-9a11-4d6f-b150-3b44dfb20c45.png)

The relative order of the LTR and RTL parts of the text is the same in all cases, as text-align doesn't establish a new directionality context.

**Comment by dae** [comment]
Sounds promising :-) Want to prepare a PR @kleinerpirat? I'll wait another day from now to merge it in in case anyone has any objections.

**Comment by hikaru-y** [comment]
I think that would solve the weird spacing issue between markers and list items. However, when combined with Anki's built-in templates which have `.card{ text-align: center; }`, list blocks(`<ol>`, `<ul>`) will be placed on the left of the page (or right in the case of RTL), while text other than list items will be centered. Although definitely better than the current weird spacing between markers and items, some users may find it a bit odd, especially those with a wide-screen monitor.

**Comment by dae** [comment]
Any ideas on how we could do it better? Changing the default alignment to `start` for all text would 'fix' this, but I worry that the common case would then look worse, especially on a wide-screen monitor.

**Comment by hikaru-y** [comment]
As you can see from the links in @kleinerpirat's post, I assume that many users probably want a list element(`<ol>`/`<ul>`) as a whole to be centered horizontally, while its items(`<li>`) are left (or right in the case of RTL) aligned within the list element. I think that would look best on a wide-screen.

If we only had to consider built-in templates, such as `Basic`, `Cloze` or `Basic (and reversed card)`, we could accomplish what I described above by adding something like the following to `reviewer.scss`:

```scss
:not(li) {
    & > ul,
    & > ol {
        display: grid;
        justify-content: center;
        overflow-wrap: anywhere;
        word-break: break-word;
    }
}

li {
    text-align: start;
}
```

However, this would likely break templates where users have already  customized the styles for `<ol>`/`<ul>`. Unfortunately, I can't think of a way to accomplish the above without breaking all of the existing templates.

**Comment by kleinerpirat** [comment]
Thanks for chiming in @hikaru-y! I've also thought about this today and would have done it a bit differently:
```css
#qa > ul, #qa > ol {
  width: fit-content;
  margin: 0 auto;
  text-align: start;
}
```
I would prefer `:not(li) > ul` if our editor actually adhered to the [standard practice of nesting lists](https://stackoverflow.com/questions/5899337/proper-way-to-make-html-nested-list#:~:text=The%20proper%20way%20to%20make,in%20which%20it%20is%20nested.), but our indentation command appends new lists at the same level of the `li` it should actually be nested in:
```html
<ul>
   <li>Level 1</li>
   <ul>
      <li>Level 2</li>
      <ul>
         <li>Level 3</li>
      </ul>
   </ul>
</ul>
```
Would you mind explaining your reasoning for a `grid` display? I couldn't find a difference to my approach apart from a bit of extra margin on top.

---
@dae If we're going to change the default template stylesheets (or `reviewer.scss`), I'd like to kill two birds with one stone and tackle the issue of aligned text on wide screens too: https://forums.ankiweb.net/t/card-layout-center-block-of-left-aligned-text/5036.

Would it be sensible to use something like the Bootstrap [breakpoints](https://getbootstrap.com/docs/5.0/layout/breakpoints/) to set a max-width for `#qa`?

**Comment by hikaru-y** [comment]
@kleinerpirat Thanks for your comment!
> `#qa > ul, #qa > ol {`

Wouldn't this stop working just by enclosing a field in a `<div>` in the front/back template, like `<div>{{Front}}</div>`?

> Would you mind explaining your reasoning for a `grid` display?

`dispalay: grid;` is just one of many ways to center a list. As I mentioned in my previous comment, I don't think any method would completely prevent a template with customized ol/ul styles from breaking. However, of the several methods I have tried, I thought this one was the least likely to break user-customized templates.

> our indentation command appends new lists at the same level of the `li`

I did not know that. I couldn't figure out how to create a nested list with the editor button, so instead I took a sample from MDN and tested it with that. If there is a possibility that ol or ul could be a direct parent element, then the code in my previous comment needs to be modified as follows;
`:not(li)` -> `:not(li, ul, ol)`

**Comment by dae** [comment]
Breaking templates is a worry - we need to be quite conservative with any changes we make to reviewer.scss, or there's a risk a lot of people's existing cards will end up looking strange. The original proposal of just moving the text to the start doesn't seem *that* radical, though that may be a case of famous last words :-). Attempting to center the content but keep it left aligned feels like it has greater potential to breaking existing templates - would you agree?

In terms of introducing left-aligned-but-centered content in the future, ideally we will need to figure out an approach to implement that without breaking existing users. Some possible options:

- placing the new styling in the default notetype configuration. That will alter newly created notetypes, while leaving existing ones alone. Easy to implement, but it makes the styling section harder to comprehend for new users.
- adding a 'style version' attribute to notetypes, so that newly created notetypes have the new behaviour, but the extra styling is added by Anki instead of it being embedded on the template. We could potentially allow users to switch between the legacy and new styling behaviour. This might be the better approach, and allows us to make a bunch of other non-backwards-compatible changes at the same time. But since incremental changes will cause a lot of churn, if we go down this path, we are probably better spending some time brainstorming all the changes that we might want to make, then doing them all at once.
- something even more sophisticated, like allowing users to select a 'theme' for their notetype.

I guess the immediate question is: should we go ahead with @kleinerpirat's original solution, which is not ideal, but also hopefully not too risky, or would it be better to delay any fixes for now and plan a more comprehensive solution?

**Comment by kleinerpirat** [comment]
> extra styling is added by Anki instead of it being embedded on the template

Maybe we could go even further and move the default template CSS to an external stylesheet and leave the styles blank. One could argue prefilled styles are an easier entry point for customization, but there are other ways to facilitate it, like a cheatsheet tooltip for Anki's CSS selectors, where clicking a selector inserts a new rule.

Once we don't have to worry about confusing users with complex CSS, the door to themes and more sophisticated designs would be open.

> would it be better to delay any fixes for now and plan a more comprehensive solution?

I'd be fine with delaying changes until we have fully explored the possibilities and their pitfalls. Perhaps @hgiesel also has something in mind regarding user styles.

**Comment by hikaru-y** [comment]
@dae 
> Attempting to center the content but keep it left aligned feels like it has greater potential to breaking existing templates - would you agree?

Yes, I agree. So, I think we should go ahead with @kleinerpirat's original proposal for now, and in the future, we may try to find a comprehensive solution that includes [sharing assets across note types](https://github.com/ankitects/anki/issues/1120#issuecomment-866846629).

**Comment by dae** [comment]
@kleinerpirat I'm open to such things, but think we need to update the reviewer/previewer js code first, and get all the Anki clients using it, as it will make it a lot easier to roll out such changes if all clients are using the same implementation
