### ISSUE TITLE
Certain keyboard layouts cause Anki to crash on startup

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1814]
A fix is slated for Qt 6.2.5/6.4.0beta1; it doesn't look to have been merged into 6.3 yet.

https://bugreports.qt.io/browse/QTBUG-101201

**Comment by dae** [comment]
Coming in 6.3.1

**Comment by dae** [comment]
Please let me know if 2.1.54rc1 doesn't resolve the issue.

**Comment by chamili** [comment]
I had the same issue. I solved by uninstalling all extra keyboard layout of the system, maintaining only one. Then runing Anki and reinstalling my extra keyboard layout. Now Anki have no problem to start with my two keyboard layout installed.

**Comment by nicholascok** [comment]
I had this issue with us_qwerty-fr and fixed it as follows.
```
$ mv /usr/share/X11/xkb/symbols/us_qwerty-fr /usr/share/X11/xkb/symbols/us_qwerty_fr
$ setxkbmap us_qwerty_fr
```
After a bit of testing, it seems (at least for me) the issue is having a '-' in the filename.

**Comment by Horryportier** [comment]
@nicholascok I can confirm I've have tested it changing mine `real-prog-dvorak` to `real_prog_dvorak` and now i can lunch anki without an issue

**Comment by Kxeo** [comment]
Worked fine before, but I pressed Ctrl+Q when trying to press Ctrl+1, and now it's spitting out `xkbcommon: ERROR: [XKB-661] Couldn't process include statement for 'lv'`
Oops...

**Comment by somegenericdev** [comment]
For me uninstalling the Flatpak version and installing the native one was enough to fix the problem.

**Comment by thiswillbeyourgithub** [comment]
> I had this issue with us_qwerty-fr and fixed it as follows.
> 
> ```
> $ mv /usr/share/X11/xkb/symbols/us_qwerty-fr /usr/share/X11/xkb/symbols/us_qwerty_fr
> $ setxkbmap us_qwerty_fr
> ```
> 
> After a bit of testing, it seems (at least for me) the issue is having a '-' in the filename.

Thank you so much. I had the same issue with [us_qwerty-fr](https://github.com/qwerty-fr/qwerty-fr) and solved it thanks to you by doing the less invasive `sudo ln -s /usr/share/X11/xkb/symbols/us_qwerty-fr /usr/share/X11/xkb/symbols/us_qwerty_fr` followed by `setxkbmap us_qwerty_fr`

**Comment by daks** [comment]
Hi,
is there any fix to this problem?
I'm using "us-qwerty-fr" and the @thiswillbeyourgithub fix doesn't work for me (I can't load it with `setxkbmap us_qwerty_fr`).

Anki is the only app I know with this problem and switching layout before launching it and switching back right after is not practical.

I'm running Anki from flatpak (version 25.09.2) on i3 on Debian 13

**Comment by thiswillbeyourgithub** [comment]
Add details regarding "I can't load it"

**Comment by JurajMlich** [comment]
I started having a similar issue and opened a bug for it here https://github.com/ankitects/anki/issues/4427
