### ISSUE TITLE
provide a way to select tags in the tag editor

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1824]
https://forums.ankiweb.net/t/2-1-50-tts-bug-not-addressed-in-2-1-51/19307/7

**Comment by hgiesel** [comment]
Already possible - see https://forums.ankiweb.net/t/2-1-50-tts-bug-not-addressed-in-2-1-51/19307/10?u=hengiesel

**Comment by dae** [comment]
Sorry, I'd forgotten about that. Because it's a bit undiscoverable at the moment, it might be worth considering allowing cmd/ctrl+a when no text is typed in to do it in one step, but I'm happy to wait until more demand has presented itself if you're not convinced at the moment. :-)

**Comment by AnKingMed** [comment]
I was about to suggest the same thing because that's what I personally tried multiple times. I would definitely allow ctrl+a when no text is selected. I know of at least 6 people that asked me about this feature (all mentioning it as a reason not to upgrade yet) and I'm happy to have people comment here if necessary.  I think the current method is quite unintuitive and people won't naturally discover it

**Comment by dae** [comment]
From the thread above:

> Hi, when I do this it does work but when I paste into the add tag dialogue for another card it adds the multiple tags as one big tag without any spaces - should i raise a separate issue for this?

I can reproduce the issue here - pasting into the add tags dialog shows them separated by spaces, but it appears to be using newlines internally, which get stripped, leading to all tags merged into one. If changing the copying behaviour is impractical, we could adjust the add/remove tags dialogs to handle it.

**Comment by hgiesel** [comment]
> it might be worth considering allowing cmd/ctrl+a when no text is typed in to do it in one step

How would we detect that the tags are the supposed target in this situation? The focused element or `document.activeElement` would be somewhere outside of the tag area.

>  pasting into the add tags dialog shows them separated by spaces, but it appears to be using newlines internally

Yes, in the clipboard, they are separated by newlines.

**Comment by dae** [comment]
When the user's cursor is in the tags area, the active element is input.tag-input. Couldn't it capture the cmd/ctrl+a key, and if there is no text typed in, select all tags instead of selecting the currently-typed text?

**Comment by dae** [comment]
(by cursor I mean text input cursor - the blinking thing, not the mouse cursor)

**Comment by dae** [comment]
Caret might be a better word :-)
