### ISSUE TITLE
very slow tag autocomplete rendering in qt 5.14 (mac only)

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1825]
Appears to be a Chromium bug where a list of `<button>${suggestion}</button>` is extremely slow. Doesn't happen in 5.14 on Linux. Experimented with removing the default button styling, but it did not help. As a workaround for now, perhaps we're best off capping the max matches to about 10 when running on the older Chromium on Mac?

https://forums.ankiweb.net/t/2-1-50-tts-bug-not-addressed-in-2-1-51/19307/6

**Comment by AnKingMed** [comment]
I think capping to ~10 is a reasonable issue if that would solve the issue
