### ISSUE TITLE
image size constraint not applied until refocus when html tags are prepended

### ISSUE THREAD

**Issue by kleinerpirat** [ankitects/anki#1826]
https://forums.ankiweb.net/t/images-in-card-editor-odd-behavior/19486

The nth-child() CSS rule will not apply until the field is refocused:
https://github.com/ankitects/anki/blob/27f2e39ff91ae166d26807818fedad3cedf6e352/ts/editor/image-overlay/WithImageConstrained.svelte#L37-L52

I guess there are two ways to go about this:
1. use a more general way to constrain sizes (not on a per-image basis)
2. somehow force a state update when elements are inserted into `anki-editable`

**Comment by dae** [comment]
Perhaps related to #1804?

**Comment by hgiesel** [comment]
Yes, the image constraining needs a general overhaul, not just a bug fix.

**Comment by kleinerpirat** [comment]
Oh sorry for the duplicate, missed that thread. Closing in favor of #1804.
