### ISSUE TITLE
Custom study increase fail if you change the number of new card

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#1829]
Running on a3d9a25d18428b40fef6f00b33e4c769e1d71916

How to reproduce:
* open a deck
* open "custom study"
* "increase today's new card limit by ... cards" should be 0 
* Change the number to 2
* press ok
* open custom study
* press ok
* open custom study
* press ok
* open custom study
* Change the number to 3
* press ok

Expected:
* the number of new card to see should be increased by two, two, two and three.

Actual:
* The first time, the number is not increased. the second and third time it is increased by two, the fourth time it is not increased  

Anki was opened with no add-on.

**Comment by dae** [comment]
Thanks Arthur!
