### ISSUE TITLE
Anki crashing on start when multiple keyboard layouts set in DE

### ISSUE THREAD

**Issue by zaroth** [ankitects/anki#1839]
Arch Linux
Plasma 5.24.5
xorg-server 21.1.3
libxkbcommon 1.4.0
Source of Anki package: https://aur.archlinux.org/packages/anki-bin

When the keyboard layouts in KDE are set to this:

![image](https://user-images.githubusercontent.com/840021/167174809-fabebc7c-2969-4acd-b9a1-7487a6d46510.png)

Anki runs without problems. However, as soon as more than one keyboard layout is added:

![image](https://user-images.githubusercontent.com/840021/167176245-288dca3b-25e6-4a60-a57c-a42d5cac84dc.png)

Anki crashes on startup with the following error:
```
$ anki
Running with temporary Qt5 compatibility shims.
Run with DISABLE_QT5_COMPAT=1 to confirm compatibility with Qt6.
Preparing to run...
Qt info: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name Anki 
  *  browser-subprocess-path /usr/lib/qt6/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 
 
xkbcommon: ERROR: Couldn't process include statement for 'us(winkeys)'
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
[14076:14118:0506/183824.508854:FATAL:xkb_keyboard_layout_engine.cc(641)] Keymap file failed to load: us-winkeys
Trace/breakpoint trap (core dumped)
```

As far as I can tell, the anki-bin AUR package is using Qt6 - one of its dependencies is python-pyqt6. From the error it seems like it might be upstream (in xkb...?), however I haven't encountered problems in any other applications (yet?), just Anki - and I use keyboard layout switching all the time.

**Comment by zaroth** [comment]
Upon closer look, might be a duplicate of #1814.

**Comment by dae** [comment]
Yep
