### ISSUE TITLE
There is no CSS specifically for Linux desktop

### ISSUE THREAD

**Issue by mikunimaru** [ankitects/anki#1858]
Current CSS has the ability to specify CSS by platform, though.
However, the .linux class also applies to android in the current specification.
https://github.com/ankidroid/Anki-Android/issues/11272

Currently, the only available workaround is to use .linux to apply CSS to both android and Linux desktop, and then use .android to overwrite the original CSS to apply CSS only to Linux desktop.

On the android side, discussions are underway in the direction that it may be better to maintain .linux behavior to maintain backward compatibility.
So there is currently no CSS specifically for Linux desktop.

**Comment by mikunimaru** [comment]
@hgiesel 
Great description, actually works.
If this problem is to be solved by a change in the anki manual description, this description would be a good example.

**Comment by hgiesel** [comment]
Maybe `.linux:not(.mobile)` would be even clearer in its intent.

**Comment by mikunimaru** [comment]
I didn't explain it well enough, .android is a class that does not exist in the anki manual but is currently valid.

```CSS
/* The .linux class also affects Android, so if you specify only Linux desktops, exclude android. */
.linux:not(.android) {
```

How about this explanation?
(I am not good at writing in English, so I think some modification to the text is necessary.)

**Comment by dae** [comment]
Thank you both, I have updated the manual.
