### ISSUE TITLE
When importing from file, notes containing <anki-mathjax> do not render well on AnkiDroid

### ISSUE THREAD

**Issue by aviad21** [ankitects/anki#1869]
Anki version ⁨2.1.52 (ab1c2395)⁩
AnkiDroid version 2.15.6

When examining the HTML of the note using Anki's editor, there is no visible difference between a note created using the editor (**_Scenario-I_**, **_Scenario-II_** below) and a 'file import' note (**_Scenario-III_**).

However:
- When creating a note via Anki's editor - the mathjax appears appears well under AnkiDroid.
- When using 'file import' of the same note - the mathjax is not rendered under AnkiDroid.

To reproduce:

**_Scenario-I_** - Create note on Anki's editor:
1. Under 'Browse' select 'Add notes...'
2. Toggle HTML editor
3. Paste "\<anki-mathjax\>\frac{1}{3}\</anki-mathjax\>" under HTML section
4. Save note
5. Sync...
6. **AnkiDroid - OK**:
6.1. The HTML appears as "\\(frac{1}{3}\\)"
6.2. Renders well.

**_Scenario-II_** - Create note on Anki's editor:
1. Under 'Browse' select 'Add notes...'
2. Paste "\frac{2}{3}" under text editor
3. Mark and convert to Mathjax inline (Ctrl+M,M)
4. (note that the HTML correctly generated as "\<anki-mathjax\>\\frac{2}{3}\</anki-mathjax\>")
5. Save note
6. Sync...
8. **AnkiDroid - OK**:
7.1 The HTML appears as "\\(frac{2}{3}\\)"
7.2 Renders well

**_Scenario-III_** - 'Import file':
1. Create a file containing the note "\<anki-mathjax\>\\frac{3}{3}\</anki-mathjax\>"
2. Import the file, using 'Allow HTML in fields"
3. Sync...
4. **AnkiDroid - ERROR**:
4.1. The HTML appears as "\<anki-mathjax\>\frac{3}{3}\</anki-mathjax\>"  (i.e. not auto-converted as in previous scenarios)
4.2.  Does NOT render well.

**Comment by hgiesel** [comment]
The HTML tag `<anki-mathjax>` is entirely an editor phenomenon. If you want to write down the note fields in a file, you should use `\[ {your mathjax} \]` for block mathjax or `\( {your mathjax} \)` for inline Mathjax.

**Comment by aviad21** [comment]
Understood, thank you.
Is there a configurable way to omit the `<anki-mathjax>` tag, so that the HTML in the editor will show `\( {your mathjax} \)`?  (i.e. I use the editor to create/edit note fields, then copy resulted HTML to a spreadsheet...).

Otherwise, I now realize that I can export the notes to a .txt file, in which case the `<anki-mathjax>` is being excluded.

**Comment by hgiesel** [comment]
The HTML editor offers an interface for the user to easily edit the field content, it does not necessarily represent the exact HTML, that is put in the database.

> Otherwise, I now realize that I can export the notes to a .txt file, in which case the <anki-mathjax> is being excluded.

That is what you should do. Otherwise, we could maybe add a button to copy the _actual field content_ into the clipboard, which we could offer as a button on the toolbar.

**Comment by aviad21** [comment]
> we could maybe add a button to copy the actual field content into the clipboard...

That would be great!
Regardless, Anki is great! :)
Thank you.
