### ISSUE TITLE
anki add on problem? Please guide me through. How to fix it?

### ISSUE THREAD

**Issue by clifferchance** [ankitects/anki#1893]
Custom Shortcut Conflicts: 

reviewer set flag 4, reviewer set flag 5
share 'CTRL+5' as a shortcut

These shortcuts will not work.
Please change them in the config.json.

**Comment by abdnh** [comment]
Change the add-on's settings from *Tools > Add-ons*. Please post on the [forums](https://forums.ankiweb.net/). You're more likely to get help there.
