### ISSUE TITLE
Global switch for small/large images by default in the editor?

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1894]
https://forums.ankiweb.net/t/improving-image-resizing-in-editor/20200

I wonder if we could support a toggle that changed whether images without a data-shrink=true/false tag are shown as small or large? Eg true=small, false=large, missing=whatever the current global switch specifies. This would allow users to quickly switch between all-small and all-large, though if they manually adjusted an image to be different to the current default, it would "stick" and need manual adjustment from that point forward, which is potentially confusing. 

Other ideas welcome too :-)

**Comment by hgiesel** [comment]
Currently the toggle button switches between setting `data-editor-shrink="true"` and removing the flag altogether. Obviously for this feature, we'd have to toggle between `true` and `false`.

I still wonder if this should be a notetype-wide flag though. I could imagine that deck author A works with assumption "no flag means small size", and deck author B works with the assumption "no flag means big", and then user C wants to use decks from authors A and B.

**Comment by dae** [comment]
I think we need to answer two different but related questions here:

1) Should deck authors have control over the default sizing, or should that be left up to the user?
2) Should the option be global or per notetype?

If we focus on 2) to start:

The sample size on the following poll is small, but it seems to be overwhelmingly in favor of a global option: https://forums.ankiweb.net/t/default-image-size-in-2-1-53/20385/2

I do appreciate the argument that doing it per-notetype might be more flexible, and I think some users may prefer it that way. The downsides of doing it that way is that it's potentially confusing to users who expect the change to "stick" when switching between notes, and it's potentially more work for users who want to switch between "all big" or "all small" depending on what they're doing - they'd have to adjust the option multiple times as they move through their different notes.

Based on the above, global seems like it might be the better choice - what do you think?

If we then return to 1), if we were to add a global option, the deck author's preferences would cause trouble for the end user in our current implementation. There would be authors who used find&replace to force all images to be large or small, and we'd end up with confused users wondering why the global toggle wasn't doing anything. This is less of an issue with a per-notetype approach as the deck author could rely on the default, but the issue would still exist for any images that had been manually adjusted.

One way we could reduce the issues here is to strip out the editor-shrink property on export. That solves the deck sharing case at least, but still leaves the issue where any images that the user had manually expanded/shrunk would remain that way when the global toggle is changed.

If we do end up adding a global toggle, maybe it would be worth reconsidering our use of data- as well? Persisting expanded/contracted state was a choice we arrived at more for technical reasons rather than user demand, and the persisted state doesn't play well with a global toggle. I suspect the average user would like toggling to persist until they switch to a different note, but cares less about it persisting across sessions?

**Comment by dae** [comment]
The current behaviour seems to be inconveniencing a lot of users, so I think we should try address this in .55. Based on the results of the survey, I'd be tempted to strip out the field-embedded toggle, and just add a global toggle via an editor button, and see how feedback on it goes. If a demand for per-notetype functionality presents itself in the future, then we can revisit the issue - it would be fairly simple to have a (possibly hidden) setting that alters whether the toggle operates globally or for the notetype.

**Comment by hgiesel** [comment]
I think this could even be tackled by an add-on. We currently have a very flexible solution, an add-on could build on it. If we switch to an unflexible solution: add-ons won't be able to provide the flexible solution. That's why I'm against it.

Maybe I could write an add-on: "Shrink/expand images in deck/notetype/collection", which would basically run a regex on all notes of a deck/notetype/collection, and strips/adds the `data-` flag?

**Comment by dae** [comment]
While I agree with you on flexibility in principle, the reality is that if we're storing the expand/collapse state in the field, that's going to confuse people who attempt to use the global toggle. The majority of people seem to want a global toggle; I think we should meet the demand first, and then figure out how we can accommodate more niche cases, instead of the other way around. I also do not think field-embedded settings are a great way to expose this flexibility - it's wasteful to have to rewrite the notes just to change the state, especially in bulk.

**Comment by dae** [comment]
Can't we mostly solve this with global toggle + stripping of the field-embedded settings on save? Then we could add some escape hatch that add-ons could use to prevent the stripping for users who wanted the toggle to persist. There'd still be the issue of that leaking into shared decks though - maybe the stripping should be done at load time instead?

**Comment by hgiesel** [comment]
Currently, the visual editor will basically a do "pre-parsing" of the field content, to allow for some modifications before putting it into the contentEditable. Because of this pre-parsing, we can treat the string, we perform DOM operations on the string (we do that to sometimes remove a `<br>`).

We could also do this kind of "pre-parsing" before the note editor passes the field content to the editing inputs, so basically before the note editor is initialized. BUT, this will mean that the setting is also cleared when switching between rows in the browser or when an update is pushed from the CurrentEdit to the Browser. I can already feel people complaining because the image size is reset because of such scenarios...

**Comment by dae** [comment]
>  I can already feel people complaining because the image size is reset because of such scenarios...

I'm not sure how much of a problem it will be in practice - I don't recall seeing much in the way of feedback where users wanted to keep some images large and some small, and persisting the state reduces the usefulness of a global small/large toggle.
