### ISSUE TITLE
inline mathjax creates new line inside center envirnoment

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1900]
- center field
- type 'foo'
- cmd+m, m
- observe input has moved to new line, left centered

https://forums.ankiweb.net/t/2-bugs-strange-behaviors-when-combining-mathjax-inline-and-centered-text/20530

**Comment by hgiesel** [comment]
Seems to be a browser bug. You can also execute `setTimeout(() => document.execCommand('inserthtml', false, '<div class="test"></div>'), 2000)` from the inspector, and get the same result: The div being placed after the `<div style="text-align:center">...</div>`, instead of inside.

**Comment by dae** [comment]
Ok, so not our problem :-)
