### ISSUE TITLE
Minimalist design for editor / clear visual noise

### ISSUE THREAD

**Issue by kleinerpirat** [ankitects/anki#1911]
The current note editor has some visual noise  / clutter issues.

![image](https://user-images.githubusercontent.com/62722460/173558357-de3a791f-5e2f-43dc-bc71-389da041650a.png)

Sorted from most prominent to less dramatic, here are the areas I feel need work:
- [ ] dashed bottom border for `.label-container`
- [ ] editing button design
- [ ] grayish window background in light theme
- [ ] field borders
- [ ] border for StickyContainer
- [ ] thick outline on focus (3px)

---
#1881 changes the layout of the editor and introduces some new design questions.

At first, I thought it would be better if the new components looked like the current editing buttons. But actually, that button design is far from perfect. Maybe we're better off dropping it for something more minimal? What do you think about a look similar to TinyMCE's sample on their [landing page](https://www.tiny.cloud/)?

![image](https://user-images.githubusercontent.com/62722460/173552177-c49268e4-4662-43af-95f3-43a622408ba0.png)
(It also has a white window background, something we've discussed on the forum a while ago.)

Even though it wouldn't be as prominent as it is currently, one could still split button groups with vertical separators, like this:

![image](https://user-images.githubusercontent.com/62722460/173553598-f63a7619-1b8a-4594-a352-0595632d4113.png)

# Proposal
Here's a comparison from current state to my rework (perhaps better split into multiple PRs):

<img src="https://user-images.githubusercontent.com/62722460/173822401-ff1129e2-ccfa-4439-86a7-c8c56babdcb8.png" width="48%"> <img src="https://user-images.githubusercontent.com/62722460/173821010-d4471b12-4bdb-4317-86ae-3624fe58d46d.png" width="48%">

This is how I tackled each of the issues mentioned above:

| Issue                                       | Fix                                                                   |
|---------------------------------------------|-----------------------------------------------------------------------|
| dashed bottom border for `.label-container` | removed                                                               |
| editing button design                       | swap Bootstrap for custom borderless design, button groups separated with vertical lines |
| grayish window background in light theme  | changed to much lighter off-white (#f8f8f8)                                                      |
| field borders                               | lighter color (#d0d7de) + box-shadow                                       |
| border for StickyContainer       | swap for box-shadow                                                               |
| thick outline on focus                      | decreased width to 2px                                                |

---
Please let me know what you think of these suggestions. I'll happily provide PRs if you like these ideas.

**Comment by dae** [comment]
I think it looks good. The only suggestion I have is that perhaps a little more contrast between field label and field content areas might be nice. May be worth posting about this on the user forums first to get some more feedback?

**Comment by kvn1351** [comment]
Sorry for going slightly off topic but speaking of TinyMCE, why not implement that instead of a custom one? Patching the buggy behaviour and shortcomings of Document.execCommand() is quite the undertaking. And they've already done all of it. The license is LGPL so it shouldn't be an issue no?

**Comment by hgiesel** [comment]
@kvn1351 
It's sadly not as easy as you'd imagine.
First of all, TinyMCE has a lot of different assumptions. Anki implements something called a [multi-root editor](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/multi-root-editor.html): one toolbar, multiple fields.

Just to get that one simple thing to work in TinyMCE would require such a giant amount of hacking the editor, that it wouldn't be worth the effort, to end up with a product where we don't own / don't understand a good portion of the codebase.

**Comment by kleinerpirat** [comment]
Closed with #2002 and other PRs that are on the way.

**Comment by kvn1351** [comment]
> Anki implements something called a [multi-root editor](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/multi-root-editor.html): one toolbar, multiple fields.

I don't see why that would be an issue. First of all, my idea wasn't to use TinyMCE's Toolbar but rather just their improved execCommand and general handling/image overlays, etc.

So the editor would look just the same as now.

Also, please have a look at this:
https://www.tiny.cloud/docs/tinymce/6/multiple-editors/

So, delegating the various commands from the Anki toolbar to TinyMCE instances (as in the link above) should work perfectly well.

I'm just saying that it would be so much easier to go this route rather than trying to redo what they have achieved. Because that really does require a giant amount of hacking as you say. 

As for understanding the codebase. True, but that is often true within a project like Anki too.
Not to mention the quirks and bugs of Qt etc. Although perhaps things have changed since I stopped using it a couple of years ago.

My point is, that you might be right. But it might also simplify things considerably.

By the way, if you feel like talking more about this, I've opened this thread here:
https://forums.ankiweb.net/t/suggestion-how-to-improve-ankis-editor-by-a-lot-with-very-little-effort/22498

**Comment by woj-tek** [comment]
Hi,
sight comment: while I do like in general visual changes and improvements I wonder - why making light theme even lighter? IMHO previous gray was very nice and fit with the OS (macOS in my case). And while I like/prefer light theme nowadays (after a couple of years of being die-hard fan of dark themes), it seems that current versions is _brighter_ for some reason - especially note editor, but also main screen with decks list now in very-off-white background. Could it be toned down and pushed more into grays? :-)

**Comment by kleinerpirat** [comment]
We can definitely poll the community on that. I went for a very light off-white because it looks cleaner, especially in the previous 2.1.54 look. A big gray area looks uninviting to me.

However, with the new containers (e.g. around the deck overview, in deck options etc.), this might not be a big issue anymore, as we got some more variation now.

**Comment by woj-tek** [comment]
The border/container seems like a good idea (and looks quite great in dark mode). Maybe using previous gray and lighter gray in light mode would work?

Though, in my case it was more study/edit screens that seemed brighter. I think that especially on edit screen using darker gray was ok as there we already have white edit fields.

One other thing that's slightly off (main screen) is the highlight of selected and hover items - they use the same colour so in case of having one selected and putting mouse on item right below it looks a little bit off. Maybe using slightly different shade here would work better?

**Comment by woj-tek** [comment]
The new "minimalist" mode is great! Thank you :-)
