### ISSUE TITLE
I want to use Postgresql instead of Sqlite3 as backend db

### ISSUE THREAD

**Issue by Ranjith8796** [ankitects/anki#1926]
I am trying to change the rust backend DB SQLite to PostgreSQL. 
I found that cargo, bazel, etc, files need to be changed (by adding rust Postgres library)
can anyone tell me the steps that need to be followed, to change the backend DB?

**Comment by RumovZ** [comment]
You've opened two threads on the forum and got some valuable answers there. I think responding to the feedback over there will turn out to be more profitable to you than keeping opening topics.
