### ISSUE TITLE
Cannot run as standard user on macOS (description, diagnosis, and workaround)

### ISSUE THREAD

**Issue by algal** [ankitects/anki#1934]
## Problem: cannot run the app as a non-admin user on macOS

On my Mac (a MacBook Pro 15-inch, 2016, now running macOS 12.4), with the latest release build of Anki (Version ⁨2.1.54 (b6a7760c)⁩, Python 3.9.7 Qt 6.3.1 PyQt 6.3.1), it is only possible to run the Anki desktop app when I am logged in as an administrative user.

When I am logged in a non-admin user, the app's icon appears with a canceled circle overlay above it, placed there by macOS. When I try to run the app, I get a system dialog box saying this application is not supported for this version of macOS. When I click on the help button on the dialog box for more information, I get a macOS help window but without any content.

## At least one other report of this problem

I see another user also encountered this issue and reported it on the forums: https://forums.ankiweb.net/t/apple-silicon-2-1-53-qt6-only-opens-in-admin-account/20386. This user was reporting it for the Apple Silicon build, suggesting the problem is not unique to my machine or to one architecture.

I tried to reply there, to report my problem and my workaround, but the forum software will not send me the email needed to verify my email address, so I am unable to contribute there.

## Likely cause, and a workaround, for this problem.

I inspected the app bundle, found what seems to the the problem, and found a workaround.

All the files in the Anki.app bundle seem to be installed with file permissions such that the file owner is me (since I installed it),  the group is "admin," and only the owner and group have execution permissions. When I looked at other apps in my Applications/ folder, I found other apps installed with the "admin" group but they all had execution permissions for non-owner, non-group users (i.e., "other" users). Two examples of such apps are Wolfram Desktop and the Steam app.

Also, I found that the more modern applications seem to have the file group to "staff". These apps included Xcode, Visual Studio Code, and iTerm. I presume this is the preferred configuration. 

So I changed all files in the Anki.app bundle to use "staff" instead of "admin" as the user group, by executing the following command from the `/Applications` directory:

```
chgrp -R staff Anki.app/
```

After this, the app's icon no longer appeared with the canceled circle overlay, and I was able to run it from a non-admin user.

## Suggested bug fix

I suggest we could fix this problem by modifying the app's build script so that it sets the file permissions differently -- specifically, to set the group to "staff" instead of "admin".

**Comment by dae** [comment]
Thanks for the detailed report, I'll look into it.
