### ISSUE TITLE
col.models cache invalid after export

### ISSUE THREAD

**Issue by BlueGreenMagick** [ankitects/anki#1939]
# Steps to reproduce

1. Create a deck
2. Add a new note to the new deck with default Basic note type.
3. Export deck as .apkg file

=> In `mw.col.models._cache` "Basic" note type is renamed to "Basic-xxxxxx", but not renamed in db.

You can check this by running below code in debug console. The below two lines have different output because `mw.col.models.all()` uses cache, and `all_names()` doesn't.
```python
print([nt["name"] for nt in mw.col.models.all()])
print(mw.col.models.all_names())
```

It only seems to happen with the default Basic note type. 

This bug can be reproduced in 2.1.49, 2.1.50, and latest master.

**Comment by dae** [comment]
Presumably this does not happen when the new apkg code is enabled in the preferences? That will hopefully become the default in the next larger update, with the old exporting code being retired.

**Comment by BlueGreenMagick** [comment]
I didn't know about the new exporter! This bug isn't there if I use the new exporter.
