### ISSUE TITLE
tags area may need a maximum size or visibility toggle?

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1940]
https://forums.ankiweb.net/t/toggle-off-tags-in-viewer-anki-2-1-5/21044

**Comment by dae** [comment]
Would it be practical to lock it to one or two lines of height, except when it's focused? Or maybe the movement would be distracting.

**Comment by hgiesel** [comment]
Enlarging when focused would probably be similarly unpleasant as the enlarging toolbar was (is) in #1881.
We already hat the shortening of tag names (`...::leaf`) as one mechanism to shorten it.
We could probably (as an alternative), collapse all existing tags to one tag button, and have it displayed as `(name of newest tag) and 25 others...`.

So in the collapsed state, we'd have the tag icon + the `and xxx others...` button + the invisible TagInput, which can be focused via tab. Adding a new tag would update the `and others` button to show `(name of the new tag) and n+1 others...`. Clicking the `and others button` would transition to uncollapsed state.

In the uncollapsed state, we'd add a new "collapse" button to the right of the tag button, which is for transitioning to collapsed state.

What do you think?

**Comment by dae** [comment]
Yep, I had #1881 in mind when I made that comment :-) 

If you're suggesting that the collapsed/expanded state persists across notes (and perhaps even browser open/close), that would be a good way of avoiding distracting movement, as it would only happen when the user wanted it to.

Not as sure about summarizing though. How would the summary work in cases where the user only had a few tags, which were enough to fit inside a single line? Would they still be summarized, or would the user be able to see/edit them without having to expand? If the latter, how would we determine when to switch to a summary?

**Comment by firejake308** [comment]
As a user, I would expect the tags to be click-and-draggable, similar to how at present, you can currently drag the border between the "cards list" and the "fields editing area." If for any reason that would be difficult to implement, then Collapse/Expand would work just as well.

**Comment by dae** [comment]
At this point a simple approach might be better than none at all - perhaps we could simply have a toggle somewhere that locks the tag area to a maximum height, and otherwise renders things the same? If you agree, is this something you might be able to tackle in the next week @hgiesel?
