### ISSUE TITLE
Frozing field should be constant time

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#1945]
How to reproduce:
* tested on fe302a5d1b8ba2b8c398f22c28bdd67357c6f339 with no add-on
* take a collection, with a note type N with a lot of notes. In the example of my collection on www.milchior.fr/anki , take "Definition".
* open "add note"
* click on the button to freeze/unfreeze a field

Expected result:
* button change status immediately and allow to continue editing

Actual result:
* the action takes multiple seconds

Other test:

I tested on a clone of the Definition field, with 0 notes, and the change was instantaneous. So I'm convinced it's related to the number of notes and note the number of fields/card type. I suspect some sanity check iterates over each note, but in this case it's absolutely useless

**Comment by RumovZ** [comment]
It seems like it's the unconditional call to `generate_cards_for_notetype()`. Maybe the backend should check whether there've actually been template changes before calling that expensive routine.

**Comment by dae** [comment]
I think I introduced this in https://github.com/ankitects/anki/commit/5d835ae813dc01cd8101be9ae5062df9f87a2ab6. To avoid breaking that case again, I guess we'd need to compare the front templates with the ones on disk?
