### ISSUE TITLE
[Suggestion] Can we move the shared VS Code settings out of the project root?

### ISSUE THREAD

**Issue by glutanimate** [ankitects/anki#1981]
I think it's great that the project now ships with a series of handy presets for VS Code! However, since Code [doesn't support local workspace settings](https://github.com/microsoft/vscode/issues/40233), the fact that `.vscode` is part of version tracking does complicate things a bit in some scenarios. For instance, with my venv set-up, I have to add `"./qt"` to `python.analysis.extraPaths` in order to get suggestions from the local source tree rather than the venv-installed `aqt` build. But even more generally speaking, users might want to / need to use the workspace settings to set all kinds of project-specific settings that are particular to their preferences (ranging from custom themes to extension settings).

With that in mind, I would suggest the following change: Let's move `.vscode/settings.json` out of the project root and into a subfolder (e.g. `IDE`), adding the root-level `. vscode/settings.json` to `.gitignore`. Users who want to follow along with the shared workspace settings could then symlink `IDE/.vscode/settings.json` into the project root `.vscode` folder, while users who need to customize their workspace settings could simply copy the defaults over, and then adjust them as needed (and update them manually when upstream pushes changes).

If you think this is reasonable, I'd be happy to file a PR with the changes above and also update the [IDE docs](https://github.com/ankitects/anki/blob/main/docs/editing.md).

**Comment by hgiesel** [comment]
Another idea would be to rename the existing `.vscode` to `.vscode.dist`. That's what I've seen in other repos. If you want to use it, you can simple `cp -r` it to `.vscode`.

**Comment by dae** [comment]
It'll be a shame to lose the 'works out of the box' that we currently have, but if vscode provides no way to override the workspace customizations, I guess changing this will be for the best.
