### ISSUE TITLE
Adding optional reasons to reject in add_cards_will_add_note

### ISSUE THREAD

**Issue by sam1penny** [ankitects/anki#1983]
Currently, the `add_cards_will_add_note hook` does not have an option for add-ons to give a warning to a user. An example is an add-on to check if a note does not contain any tags before it is added. If so, then it should ask the user to confirm that they want to add a card without tags. (An example of this add-on using monkey patching is [here](https://www.reddit.com/r/Anki/comments/coc6wp/comment/ewi7m2m/?utm_source=share&utm_medium=web2x&context=3))

I can think of two possible ways to achieve this. The first option would be to add another hook, e,g add_cards_might_add_note. The second option would be to provide another argument to add_cards_will_add_note (a list of strings, initialised to be empty) and opening an askUser prompt for each string in the list. However this would break current add-ons that use the hook. 

Let me know which way is preferred and I'll open a PR :)

**Comment by dae** [comment]
This should already be possible - if a hook wants to confirm with the user, they can use askUser() inside the hook.

**Comment by sam1penny** [comment]
> This should already be possible - if a hook wants to confirm with the user, they can use askUser() inside the hook.

You can do it this way, but to return to the editor after opening an askUser() dialog an error dialog must be shown. So, for example, the the add-on asks the user 'Add cards without tags?'. If they select no, rather than returning straight to the editor they have to see (and close) another popup 'Error: Can't add cards without tags'.

**Comment by dae** [comment]
Good point. What if we used some sentinel value for problem - eg if problem was "ignore", then adding is aborted and no message is shown?

**Comment by sam1penny** [comment]
> 

I don't think that would be a good idea. Some add-ons I expect, at least [this](https://github.com/hgiesel/closet/blob/766b4233f641725ff018cba72aba1ed736451fd7/anki/src/addcards.py) add-on won't return their own problem if `problem` is not None, so we'd end up with the same compatibility issues. 

In general, it might cause confusion to add-on developers. On discovery that `problem` is not None, they would have to inspect it to see if it was an actual error (and should be returned immediately) or it was sent to "ignore" in which case they should still ask their prompt.

I think a hook, called just after `add_cards_will_add_note` would be most appropriate, despite being similar in function.

**Comment by dae** [comment]
You're right, I neglected to consider that case. Sounds like another hook is the best bet. :-)
