### ISSUE TITLE
Ensure text in editor wraps

### ISSUE THREAD

**Issue by dae** [ankitects/anki#1985]
Looks like we're not using break-word at the moment:

https://forums.ankiweb.net/t/report-bug-for-version-2-1-54/21674/3

**Comment by kleinerpirat** [comment]
Long words wrap fine on my end, both with the sample text from the forum post and with my own tests :thinking:

**Comment by dae** [comment]
It seems to only happen when the field is using `<pre>...</pre>`. Not sure how best to handle this - we could for breaking with !important, but whether that's a good idea or not, I don't know.
