### ISSUE TITLE
German ß not working on mac

### ISSUE THREAD

**Issue by zxl634** [ankitects/anki#1986]
Typing the German ß seems to invoke some other type of functionality, i.e. pasting the content of the clipboard (see example).

Machine information:
```
ProductName:	macOS
ProductVersion:	11.6.5
BuildVersion:	20G527
```

Anki:
```
Version ⁨2.1.54 (b6a7760c)⁩
Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
```

Typing ß seems to simply pase the contents of the clipboard, which in my case was the above information about Anki version.

https://user-images.githubusercontent.com/34809205/180658635-5443b0e5-fe04-4ac3-90ba-9e71a1cc2029.mov

**Comment by dae** [comment]
Can you reproduce it with all add-ons disabled?

**Comment by zxl634** [comment]
No, thanks! Will close issue here.

![image](https://user-images.githubusercontent.com/34809205/180726079-cf9ed33b-8dee-4d9e-9b95-3cd8dcd25d3d.png)

https://user-images.githubusercontent.com/34809205/180726282-e33eacaa-ea80-4b2e-83b2-0fce9f417123.mov
