### ISSUE TITLE
katex render error

### ISSUE THREAD

**Issue by chenboshuo** [ankitects/anki#1993]
the ketex said the support `\bm`
[doc](https://katex.org/docs/supported.html#:~:text=%5Cbm%7BAb0%7D-,Ab0,%5Cbm%7BAb0%7D,-%5Cmathbb%7BAB%7D),
and in their demo,it works
![image](https://user-images.githubusercontent.com/43953268/181879743-adc69a19-52c0-46f8-b78e-a4789d773f06.png)

but in anki,my code is

```html
<span class="tw-katex-display"><anki-mathjax block="true"> \mathcal{L}(\mathbf{\theta}) 
      \triangleq \frac{1}{N}
        \sum_{n=1}^N
          \ell(y_n , f(\mathbf{x}_n;\bm{\theta})) </anki-mathjax></span>
```
the render failed
![image](https://user-images.githubusercontent.com/43953268/181879689-d9e3d520-0ff7-468b-b04a-c2406334ab85.png)

**Comment by hgiesel** [comment]
We use MathJax 3, not Katex. [This issue](https://github.com/mathjax/MathJax/issues/1219#issuecomment-341059843) recommends to just use `\boldsymbol` instead.
