### ISSUE TITLE
Evaluate feasibility of using parts of TinyMCE

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2025]
When @hgiesel and I discussed this about 18 months ago, there were a few reasons TinyMCE was ruled out as an option:

- Its LGPL license would have made it difficult to share the editing code across all clients.
- Integrating it into Anki's editor, where each field has a different editor with a shared toolbar at the top, appeared to be difficult.
- When @david-allison tried it with AnkiDroid back in 2020, he [ran into issues](https://github.com/ankidroid/Anki-Android/pull/5975#issuecomment-671135463).

About 6 months ago, TinyMCE shifted to an MIT license, so that potentially unblocks the licensing issue. There is of course no guarantee that they will not switch to another license again at some point in the future, or shift one of the core plugins we come to depend on into their premium offering. But let's put those issues aside for now and focus on the remaining technical issues.

contentEditable is a mess, and implementing a solid editor is a huge amount of work. That makes TinyMCE appealing - it is battle-tested, and likely handles a number of DOM manipulations better than Anki's editor currently does, such as #2021. But we don't want the entire TinyMCE interface - ideally we just want the actual editing area, and a way to integrate it into Anki's existing UI/toolbar. 

Whether it's practical to do so, I do not know. We would need to do some testing/prototyping to see how feasible it is to use TinyMCE across multiple fields, linking it to our existing toolbar. It appears we can [suppress the standard pop-up toolbar](https://codepen.io/dae1/pen/RwMdaXX), though I do not know what is involved with integrating our own.

Then there'd be the question of if/how we could integrate various existing functionality, such as:

- The HTML editor. TinyMCE comes with one that is not really suitable for Anki, and is not available to us anyway - it's part of their "premium offering": https://www.tiny.cloud/blog/tinymce-free-wysiwyg-html-editor/#h_7570721309741658366220029
- The MathJax visual editor
- Copy/paste and drag&drop, including the filtering we apply.

It will likely be a fair amount of work to integrate, if it is even possible. The question comes down to whether the savings we'd gain from not having to deal with contentEditable issues (and getting things like better undo support for free) would be worth the effort.

Original suggestion by @kvn1351: https://github.com/ankitects/anki/issues/1911#issuecomment-1221503134

**Comment by kvn1351** [comment]
First of all, thanks for considering this :)

> This may also lead to a duplication of code for handling shortcuts, as TinyMCE handles them on its own, so it would have to be configured to match Anki's bindings (for overlapping shortcuts).

This seems to be trivial:
https://www.tiny.cloud/docs/api/tinymce/tinymce.shortcuts/

> About 6 months ago, TinyMCE shifted to an MIT license, so that potentially unblocks the licensing issue. There is of course no guarantee that they will not switch to another license again at some point in the future, or shift one of the core plugins we come to depend on into their premium offering.

This doesn't matter if my understanding of licensing is correct. All they can do is license new versions under a different license. They can supply the original version under a different license as well, but that does not invalidate the MIT license they granted to you already. At the very least not for that version of the code. Then you might say, well we'd be out of support. Yes, true, but so is Document.execCommand and others. I still think that it will be much more beneficial.

> Integrating it into Anki's editor, where each field has a different editor with a shared toolbar at the top, appeared to be difficult.

As I've stated in a previous comment, this shouldn't be an issue. First, it can be invoked on multiple fields like this: https://www.tiny.cloud/docs/tinymce/6/multiple-editors/
Second, we can keep Anki's toolbar intact and only call the right methods on the TinyMCE instance that currently has Focus. We'd be calling these re-implemented execCommands from here: https://www.tiny.cloud/docs/tinymce/6/editor-command-identifiers/#executable-commands

> Copy/paste and drag&drop, including the filtering we apply.

This is much better in the TinyMCE editor imo. So I'd just remove some buttons and change the CSS of their implementation.

> The MathJax visual editor

This might be problematic. It depends on how well one can manipulate the TinyMCE instance. I haven't tested it myself yet nor looked at much code.

> The HTML editor
Should be trivial. We can simply get the html and place it in the editHTML field and then apply it to the TinyIntance with `tinymce.activeEditor.execCommand('InsertHTML', false, 'My HTML content');` upon edits.

Also, for the record, my suggestion to do this wasn't a "Hey look what I found here. Implement this thanks". I first wanted to know what you thought about this idea in the first place and to hear from possible previous attempts as I now hear that you have made.
I'll try myself to get a WIP running. As you've said, it might be that I've grossly underestimated the potential amount of work and issues. If so, I'd be sorry to have wasted your time.

Once more, thanks a lot :)

**Comment by dae** [comment]
>> Copy/paste and drag&drop, including the filtering we apply.

> This is much better in the TinyMCE editor imo

I presume you're referring to https://www.tiny.cloud/docs/configure/content-filtering/#valid_elements? That looks fairly flexible, though we'd want to make sure we could continue to do things that we currently do like whitelist/blacklist certain attributes and styles depending on whether we're pasting from another field or some other source. Anki also intercepts pastes/drops, and when remote links to images are encountered, they get downloaded and the link rewritten - can that be done with TinyMCE?

> Also, for the record, my suggestion to do this wasn't a "Hey look what I found here. Implement this thanks". I first wanted to know what you thought about this idea in the first place and to hear from possible previous attempts as I now hear that you have made.
I'll try myself to get a WIP running

I'm open to the idea, but suspect a reasonable amount of work will be required to get it from the prototype stage to a suitable replacement. It would be good to know what's involved at least though.

FWIW, there's been an add-on that inserts TinyMCE into Anki since 2019, but it comes with a bunch of caveats: https://ankiweb.net/shared/info/805891399

**Comment by dae** [comment]
They've backflipped on the license: https://github.com/tinymce/tinymce/issues/9453

**Comment by krmanik** [comment]
The https://www.tiny.cloud/tinymce-alternatives/ website compares alternative and some of them are MIT License which may be used.
