### ISSUE TITLE
get error when play mp3 from web

### ISSUE THREAD

**Issue by oijqws** [ankitects/anki#2035]
Can't post on bbs 
JS warning /_anki/legacyPageData?id=2592358216608:0 A cookie associated with a cross-site resource at http://baidu.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by dae** [comment]
This is an issue with the site you're linking to, and Anki does not officially support remote audio.
