### ISSUE TITLE
Mathjax preview totally broke

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#2048]
Running in 8cf829d442f4e899dc95738aee168a707b1c2bb2 with no add-on

When I create a new mathjax element with ctrl-m m, I get
![2022-09-02-161147_956x1040_scrot](https://user-images.githubusercontent.com/357361/188167959-6f1fbbc6-8e3d-4a1c-940b-f29484b191d6.png)

The empty image is far far too big, and the text space is invisible.

Later, when I double click a mathjax expression to edit it, I don't see any cursor showing me I can edit. When I type, I realize that there is indeed a cursor in an editor. But the mathjax editor is inside the field editor, but hidden because it appears below the text, and the field editor is not increased.

(no screenshot because when I leave the note editor, or open the screenshot app, the mathjax editor lose focus and close itself)

**Comment by dae** [comment]
Closed via #2011

**Comment by Arthur-Milchior** [comment]
Thanks once again @hgiesel. Really really appreciate your work!
