### ISSUE TITLE
Inconsistent style when using dark mode on MacOS

### ISSUE THREAD

**Issue by roxgib** [ankitects/anki#2054]
Spot the differences:

Light Mode |  Dark Mode
:-------------------------:|:-------------------------:
![Light Mode](https://user-images.githubusercontent.com/33942237/189040301-5794b78c-92bb-40e6-8ddd-4e0219eb7de3.png) | ![Ugly Dark Mode](https://user-images.githubusercontent.com/33942237/189040292-530f596f-c509-4d32-bde1-40d20970cb65.png)

The wrong style is being applied during the switchover to dark mode somewhere. I'd suggest correcting it here:

https://github.com/ankitects/anki/blob/e2193950a9a048175b0a067e125ccc17ca8ea3b7/qt/aqt/theme.py#L259-L260

Replacing those lines with this...
```
app.setStyle(QStyleFactory.create("macos" if is_mac else "fusion"))  # type: ignore
```
...gives us...

Light Mode |  Dark Mode
:-------------------------:|:-------------------------:
![Light Mode](https://user-images.githubusercontent.com/33942237/189042004-a38ee460-c97e-4278-a545-a5e82633fe4f.png) | ![Pretty Dark Mode](https://user-images.githubusercontent.com/33942237/189042015-8ebf7e53-2651-433c-bb3d-ec2855006779.png)

...which is much nicer!

From reading https://github.com/ankitects/anki/commit/7dcbc7efec08ec2928523408dd9bc7bdaae03fd8 I gather that it was done this way because certain colours weren't correct? I haven't spotted any issues so far, but I haven't done a comprehensive search just yet. 

If the theme is being set elsewhere it might be better to remove that line, but otherwise would a PR making the above change be welcome?

**Comment by dae** [comment]
Thanks for the suggestion, I left some notes in the commit above.
