### ISSUE TITLE
Text color not preserved when pasting in dark mode

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2055]
Currently the foreground/background colors are explicitly excluded in styling.ts. I believe this was originally done to prevent unwanted white backgrounds when pasting from a typical webpage, but that no longer seems to happen, at least with Chrome. Will need to test on a few different browsers to make sure we don't introduce a regression.

https://forums.ankiweb.net/t/macos-pasting-in-dark-mode-is-stripped-of-colors/22818

**Comment by 7MinutesDead-Git** [comment]
I'd like to parrot I'm also experiencing this when attempting to copy/paste from webstorm, or likely any jetbrains IDE.

I was curious if there was a particular version of anki I could revert to for now as I'm not sure when this started.

**Comment by sachingooo** [comment]
This seems similar to #1078

**Comment by dae** [comment]
Thanks, it looks like this was a duplicate.
