### ISSUE TITLE
Change fill color of SVG used in Qt stylesheet

### ISSUE THREAD

**Issue by kleinerpirat** [ankitects/anki#2063]
In `qt/aqt/data/qt/icons/BUILD.bazel` you can make mdi icons available to Qt by simply appending their name.
For example, I used this method to set the triangle icons for table headers:

![image](https://user-images.githubusercontent.com/62722460/189532853-65f812ea-b39a-4289-8e4b-a186408bf36a.png)

https://github.com/ankitects/anki/blob/8f8f3bd465ed7e5c47108374106b8ec6ec2bd072/qt/aqt/data/qt/icons/BUILD.bazel#L37-L39
https://github.com/ankitects/anki/blob/8f8f3bd465ed7e5c47108374106b8ec6ec2bd072/qt/aqt/stylesheets.py#L254-L256

The icons show in black by default, but ideally it would have the default text color. After a lot of research I've concluded it isn't possible to set or invert an SVG's fill color in a Qt stylesheet.

I can think of two options:
- create two separate icons from Bazel, one for dark and one for light theme
- edit the svg fill color at runtime in `theme.py`
(preferred because it would allow theme-devs to use arbitrary colors)

Sadly, I don't know how to achieve either of the two.

**Comment by kvn1351** [comment]
Just use regular expressions to patch the SVG. Load it into a QString for example and render that string after patching.

**Comment by kleinerpirat** [comment]
> render that string after patching

Thanks, but this is not what I'm looking for. I want to define general styles so we don't need to set the icons on each widget individually. Qt stylesheets only accept SVG's via `url(path)`, so I'd need to directly edit and save the SVG in Qt's icon cache.

**Comment by kvn1351** [comment]
Perhaps you could store the SVGs as a font and go the route of https://github.com/spyder-ide/qtawesome.

This addon, https://github.com/ankipalace/Fastbar-with-nightmode-support, has dynamic icons that they simply invoke like this: 

```python
icon = qta.icon(icon_name, color="white" if night_mode_on or theme_manager.night_mode else "black")
```

According to QtAwesome's GitHub page you can load custom fonts:
> QtAwesome comes bundled with Font Awesome, Elusive Icons, Material Design Icons, Phosphor, Remix Icon and Microsoft's Codicons but it can also be used with other iconic fonts. The load_font function allows to load other fonts dynamically.

Or if you wanna integrate the coloring logic yourself, take a look [here](https://github.com/spyder-ide/qtawesome/blob/cfd5189178e2b79433364bbcd16ab4962515f5ac/qtawesome/iconic_font.py#L189). In particular `_paint_icon()`.

I hope this helps, perhaps this was still not what you intended :S 
If so, sorry for misunderstanding.

**Comment by kleinerpirat** [comment]
I'd like to execute this function on theme change:

```python
from aqt.utils import aqt_data_folder

icons =  os.path.join(aqt_data_folder(), "qt", "icons")

for filename in os.listdir(icons):
    if filename.endswith(".svg"):
        path = os.path.join(icons, filename)

        with open(path, "r") as file:
            data = file.read()

        data = re.sub(r"<svg", f'<svg fill="{self.var(colors.FG)}"', data, 1)
        data = re.sub(r"fill=\".+?\"", f'fill="{self.var(colors.FG)}"', data, 1)
        
        with open(path, "w") as file:
            file.write(data)
```
Console logs show this would work, but I don't have write permission from `theme.py` @dae.
