### ISSUE TITLE
Not possible to import CSV/TSV file on macOS with Russian localization

### ISSUE THREAD

**Issue by Kagami** [ankitects/anki#2075]
macOS 12.6
Anki 2.1.54

Preferences->Select Russian localization
File->Import->Not possible to import CSV files

### English (United States) (WORKS)
<img width="804" alt="Снимок экрана 2022-09-19 в 00 29 51" src="https://user-images.githubusercontent.com/533383/190928905-428c14a8-5f33-4e07-9948-af48bb7a91fe.png">

### Deutsch (WORKS)
<img width="805" alt="Снимок экрана 2022-09-19 в 00 30 44" src="https://user-images.githubusercontent.com/533383/190928903-a3f2811b-9f03-4c95-82e2-919fb3ca5108.png">

### Русский язык (DOESN'T WORK)
<img width="806" alt="Снимок экрана 2022-09-19 в 00 31 47" src="https://user-images.githubusercontent.com/533383/190928901-ea8dc744-227a-48b8-9a31-709672a60c8a.png">

Seems like related to the missing asterisk symbol.
Though those lines look the same (except the translation):
https://github.com/ankitects/anki-core-i18n/blob/c739cd0071cf4ab634e703bde06d282fadd99f2a/core/de/importing.ftl#L51
https://github.com/ankitects/anki-core-i18n/blob/c739cd0071cf4ab634e703bde06d282fadd99f2a/core/ru/importing.ftl#L54

**Comment by dae** [comment]
Thanks for the report; this has already been fixed in the development code.
