### ISSUE TITLE
MathJax in browser bugs when changing card

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#2086]
How to reproduce:
1. Open the browser
2. Select a card `C`
3. Select a field at position `i`
4. Open a mathjax window (new one or edit an existing one)
5. ctrl+n or click on a different card `C'` with at least `i` fields

Expected result:
Mathjax window get closed. New card get loaded

Actual result:
The new card gets loaded, except for its `i`th field that keeps the same value as the current i-th field of `C`. 

Good news is that when you close the mathjax window, the `i`th field of `C'` is actually loaded, and the new value is saved as the `ith` field of card `C`

**Comment by dae** [comment]
Fixed via https://github.com/ankitects/anki/commit/e14f87ba99a0bd81a45701dda0b05ae437fe2478
