### ISSUE TITLE
Card should disappear from the reviewer when it is deleted

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#2087]
How to reproduce:
* open the reviewer
* click b to open the browser
* delete the card
* close the browser

Expected result:
* the card should disappear, next card should appear

Actual result:
* the card remain. Reviewing, opening the browser again, or generally any action that should affect the card lead to an error message

**Comment by abdnh** [comment]
I vaguely remember hitting this issue a while ago, but I can no longer reproduce it now in the latest main.

**Comment by dae** [comment]
Should be fixed with the v3 scheduler

**Comment by dae** [comment]
Closing, as the issue should only be in the legacy codepath.
