### ISSUE TITLE
Field name appears in the middle of the field

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#2089]
This occur when there is many fields and so I need to scroll

![2022-09-25-200247_1235x1040_scrot](https://user-images.githubusercontent.com/357361/192158509-2177799e-1868-4800-8e62-7c5cf32976c3.png)

**Comment by dae** [comment]
Fix coming in #2070

**Comment by Arthur-Milchior** [comment]
Thanks :)
