### ISSUE TITLE
Command+Shift+C shortcut is broken after version 2.1.49 on MacOS

### ISSUE THREAD

**Issue by eschloff** [ankitects/anki#2090]
Shortcut for Cloze deletions (Command+Shift+C) when adding a new card is broken in version 2.1.50. I am using MacOS 11.6.5 and have tested this in versions 2.1.48 and 2.1.49 (both work), but then in 2.1.50-54 this shortcut only works about 15% of the time. Tricky to pinpoint because it's intermittent, sometimes works once or twice in a row but then doesn't work the next 10 times. I have verified that no other applications are open and that my global shortcuts do not contain this keyboard combination.

**Comment by hgiesel** [comment]
Are you sure you're actually using it while having a cloze notetype active? You can tell by the cloze buttons being present.

**Comment by eschloff** [comment]
Yes, very sure. I just retested to double check.
