### ISSUE TITLE
regression: duplicates are no longer red

### ISSUE THREAD

**Issue by balta2ar** [ankitects/anki#2098]
After a recent update:
```
[2022-09-27T06:31:38+0200] [ALPM] upgraded anki-git (r9620.3ec7e23d7-1 -> r9640.fe9b0aecf-1)
```
I noticed that duplicates are no longer highlighed with red:
![image](https://user-images.githubusercontent.com/340676/192950973-075cf405-e80d-4798-977c-46d508c0906e.png)
This header with "Show duplicates" used to be red in previous versions. I understand it could be a matter of personal preferences and tastes, but big read header was just sooo easier to notice, than a bleak "Show duplicates" label. I wonder if that could be reverted or configured. Thank you.

**Comment by kleinerpirat** [comment]
This is unintentional and was probably caused by a merge commit, in which the old variable name of the color was reintroduced:

https://github.com/ankitects/anki/blob/6944210fbe480a0448f7a6b8c501ec6584bf8de7/ts/editor/NoteEditor.svelte#L420
