### ISSUE TITLE
Switching input language crashes anki

### ISSUE THREAD

**Issue by rubisco57** [ankitects/anki#2105]
I am trying to switch anki's input language via hotkey using AutoHotkey. Unfortunately, the following script working on other applications crashes anki. 
`
^+l:: ;CTRL+SHIFT+L
	en := DllCall("LoadKeyboardLayout", "Str","00000409", "Int", 1)
	WinGet, windows, List
	Loop % windows {
	    SendMessage, 0x50, 0, %en%,, % "ahk_id " windows%A_Index%
	}
return
`
I suppose it is a bug, but would be happy to be proven wrong andappreciate any suggestions on how to determine and resolve this issue.

**Comment by dae** [comment]
Perhaps related to #1105

**Comment by rubisco57** [comment]
Thank you, @dae for your answer and your time. Indeed, the two issues are related. The suggested workaround, i.e. switching to Qt5 and changing the Video Driver to _ANGLE_ in Anki's preferences also worked for me.
