### ISSUE TITLE
Browser table styling issues

### ISSUE THREAD

**Issue by RumovZ** [ankitects/anki#2109]
I've investigated a bit regarding the [issues I found](https://forums.ankiweb.net/t/anki-2-1-55-beta/23470/30?u=rumo):

1. First fix is trivial: Give column labels some horizontal padding, so they remain separated from the borders if the column is very narrow.
2. In order to center the column labels, we could add negative padding to the right to compensate for the sort indicator. That looks fine for the non-sort columns, but will lead to the label and sort indicator of the sort column overlapping, if it is very narrow. There doesn't seem to be any way to style a column depending on whether it is sorted by, so I don't think this is solvable with stylesheets. Maybe we have to return to the old indicators?
3. The vertical header can easily be hidden. In fact, Anki is already explicitly disabling it on all platforms except Windows for some reason. However, then the left table border is missing (screenshot 1). As a hack, we could keep showing it, but use negative padding, so only the right border is visible (screenshot 2).
    ![grafik](https://user-images.githubusercontent.com/48286681/194408080-6b34e42d-8cc8-49ba-b87b-5d1a3a3d0430.png)
    ![grafik](https://user-images.githubusercontent.com/48286681/194408491-85db3525-b401-42d3-af66-8f8edd394c01.png)

WDYT, @kleinerpirat?

**Comment by kleinerpirat** [comment]
> we could add negative padding to the right to compensate for the sort indicator.

If there's a selector for the active header, I could also give the indicator a width of 0 by default.

> Maybe we have to return to the old indicators?

Changing a single property with stylesheets means we need to style everything. So that would mean going back to the previous look entirely.

> As a hack, we could keep showing it, but use negative padding, so only the right border is visible (screenshot 2).

That still leaves the header misaligned with the starting column, but maybe that's fixable. I've played around with this issue a lot, but somehow there's always one little part that's imperfect.

---
I'll be on a train ride tomorrow, so I can spend some time on this.

**Comment by RumovZ** [comment]
> If there's a selector for the active header, I could also give the indicator a width of 0 by default.

This leads to the text and arrow of  a narrow column superposing, if I remember correctly.

> Changing a single property with stylesheets means we need to style everything. So that would mean going back to the previous look entirely.

Oh, I didn't know that. I had assumed unstyled properties would just use the default. Is there a way to explicitly set the old indicator?

> That still leaves the header misaligned with the starting column

Yes, but only by 1px. 🙂

**Comment by kleinerpirat** [comment]
> Is there a way to explicitly set the old indicator?

Probably from the Python side, yes. As a web dev, styling widgets by subclassing them or modifying properties via scripts seems suboptimal, but there are [people who argue that this is the way to go for Qt.](https://www.kdab.com/say-no-to-qt-style-sheets/)

We can use our own mdi icons via stylesheets, if you'd like a differently looking arrow. I also managed to center the header text by giving the arrow a negative margin. Once I got the left border issue figured out, I'll push a PR.

**Comment by RumovZ** [comment]
I don't mind the look of the new sort indicators, on the contrary. This is just about the centering / overlapping issue. The old indicators were placed above the label, so they don't have this problem.

And yes, Qt's stylesheet support seems lacking, unfortunately. 

Curious to see, what you'll come up with!
