### ISSUE TITLE
Previously removed function minimizeHTML is needed by anki 1.x importer plugin

### ISSUE THREAD

**Issue by matthiashaack** [ankitects/anki#2111]
Installed 2.1.54 today and tried importing a deck in the old anki format http://www.tanos.co.uk/jlpt/jlpt1/vocab/n1-vocab-kanji-hiragana.anki then an error was shown: 

```
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-07 08:49:57

Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Roaming\Anki2\addons21\175027074\anki\importing\anki1.py", line 29, in run
    deck = u.upgrade()
  File "C:\Users\USERNAME\AppData\Roaming\Anki2\addons21\175027074\anki\upgrade.py", line 133, in upgrade
    self._upgradeSchema()
  File "C:\Users\USERNAME\AppData\Roaming\Anki2\addons21\175027074\anki\upgrade.py", line 200, in _upgradeSchema
    from anki.utils import minimizeHTML
ImportError: cannot import name 'minimizeHTML' from 'anki.utils' (unknown location)
```

### How to reproduce

Assumption: the importer plugin is not installed

1. Installed 2.1.54 today and tried importing a deck in the old anki format http://www.tanos.co.uk/jlpt/jlpt1/vocab/n1-vocab-kanji-hiragana.anki 
2. Popup opened telling to download a plugin 175027074
3. Install plugin and restart anki
4. Try to import the same deck again
5. Then the error popped up

### Investigation so far

Found out the function was removed in commit 0bb273a0ed90d7548052d5c9b10467ea577fc1e0 from Oct 1st 2021, before version 2.1.50 was created, (removed under assumption that no plugin used this). Up to version 2.1.49 it should still work (not tested). The plugin uses the minimizeHTML in file upgrade.py

### Workaround

Copy the missing function into the plugin code, then the import works as expected.

**Comment by matthiashaack** [comment]
FYI the owner of the plugin fixed this import issue today.

**Comment by dae** [comment]
Thanks @Arthur-Milchior
