### ISSUE TITLE
Can't (easily) change colors of old cards (PC)

### ISSUE THREAD

**Issue by Redysz** [ankitects/anki#2121]
Once some colors are used in a card, changing them later is difficult. It is not enough to select the word, but you have to select the word and the surrounding spaces/brackets, which color you do not necessarily want to change.
![Untitled](https://user-images.githubusercontent.com/25427869/194773807-7ca3dff3-f1c9-4fcf-9203-58d2af3ac15f.gif)

    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-10-09 19:14:54
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['BezAkcentow', 0, 'None', '']
    BetterSearch ['1052724801', 2022-01-25T23:25, 'None', '']
    The KING of Button Add-ons ['374005964', 2020-04-18T00:33, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1052724801 374005964
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by dae** [comment]
I can't seem to reproduce this. Please try the latest beta version, and post back if the issue persists for you.

**Comment by Redysz** [comment]
Hi @dae Thank you for your reply!

It persists on the latest beta as well. It's not easy to reproduce since it doesn't happen on all cards and the card had to be saved firstly and you need to try change a color after a while. Also the problem occurs only when you want to change the color near to punctuation without it or a space (just a word) and the color that is (and doesn't want to be changed) was set with space.

1. " some_text."  <--- color is set for " some_text" (with a space)
2. save it, restart anki. Probably update anki version meanwhile.
3. you want to change a color of the word "some_text" (without space) because it is default behavior of double click
4. now changing the color doesn't work (sadly: sometimes)

Video:

https://user-images.githubusercontent.com/25427869/205491925-ac8ebe63-664b-4a5d-8898-e0d0588f7709.mp4



What I discovered is: if I can't change a color in one card, the situation for that card won't change until I finally change the color  with surrounding space and/or punctuation. It means that the problem is in the card, not changing-color-feature (I guess). I have that card and because I didn't change the color I could "somehow" share this card with you if you tell me how.

**Comment by dae** [comment]
Would you be able to move one problem card to a separate deck, export it, and share it with me? Or provide the HTML of the field with the problem?

**Comment by Redysz** [comment]
Exported:
[Problematic Card Deck.zip](https://github.com/ankitects/anki/files/10149230/Problematic.Card.Deck.zip)


(no idea how to provide the HTML of the field)

**Comment by Redysz** [comment]
I've found even worse case, where I can't change the color of the word only (the word is in quotations, so to change color of the word I need to change color of quotation also). New card deck:
[Problematic Card Deck 2.zip](https://github.com/ankitects/anki/files/10149278/Problematic.Card.Deck.2.zip)

**Comment by dae** [comment]
Thanks, please let me know if the next beta fixes the issue for you.

**Comment by dae** [comment]
Yes, please wait for the next one.
