### ISSUE TITLE
Qt 6.4.0 update broke light theme on Manjaro Linux

### ISSUE THREAD

**Issue by kleinerpirat** [ankitects/anki#2124]
After 276c42e25057e6064c05ecc2556279aa7850f79e Anki defaults to night-mode colors ~~for widgets affected by stylesheets~~, resulting in illegible text and other atrocities:

![image](https://user-images.githubusercontent.com/62722460/194854090-1284b9ca-014f-4264-8b69-36b1900f3672.png)
(Screenshot from b4293573ddee1f9d4e9dd29200b3afe50b365efb)

Defining the faulty properties explicitly in the stylesheets should solve the issue. But I wonder why these defaults don't seem to work anymore:

https://github.com/ankitects/anki/blob/3d47c9547a1d18ca54d1858cff7712de8a3a67af/qt/aqt/theme.py#L276-L280

**Comment by kleinerpirat** [comment]
Actually, it isn't even related to stylesheets. The issue persists without them:

![image](https://user-images.githubusercontent.com/62722460/194856089-27bb4ad9-69de-4c67-9e4e-46f2a02bbb03.png)

**Comment by dae** [comment]
Light mode looks fine on my system - is your desktop environment set up to use a dark Qt theme?

**Comment by kleinerpirat** [comment]
Yes, if you mean that with "Follow System" it switches to dark mode. I'm busy tonight, but I'll investigate tomorrow.

**Comment by dae** [comment]
The light theme doesn't explicitly set the background IIRC, so that Anki matches the default background color on different platforms/themes. The downside is that it only works when the default background is light - if dark, you get illegible text.

**Comment by kleinerpirat** [comment]
Closed with #2137.
