### ISSUE TITLE
Strange potential bug in `DeckManager.deck_tree()`

### ISSUE THREAD

**Issue by langfield** [ankitects/anki#2153]
See the following MWE. Fails on `2.1.54` and `2.1.51`. Not sure if this is intended behavior, but IMO it does not adhere to the principle of least astonishment for devs using the API. Very strange that a deck available in `all_names_and_ids()` cannot be accessed from the deck tree. 

The 'bug' if it is indeed a bug, can be traced back to `fn hide_default_deck()` in `rslib/src/decks/tree.rs`. Obviously, `Collection.deck_tree()` in this file is meant to be used by the GUI, hence why the default is hidden. An alternative solution might be adding a field to your `DeckNode` type (no idea how this would be handled idiomatically, I'm not a Rust person) that indicates whether or not the deck should be hidden by the frontend.

I found this by fuzzing the Anki API with a `RuleBasedStateMachine` from the `hypothesis` library. See the original failure at the bottom.

```python
import tempfile
from pathlib import Path
from anki.collection import Collection


def main():
    """MWE."""
    # Initialize collection.
    tempd: Path = Path(tempfile.mkdtemp())
    col = Collection(tempd / "collection.anki2")

    # Default deck exists.
    dids = list(map(lambda d: d.id, col.decks.all_names_and_ids()))
    assert 1 in dids

    # Add a child deck.
    root: DeckTreeNode = col.decks.deck_tree()
    node = col.decks.find_deck_in_tree(root, 1)
    did = col.decks.id(f"{node.name}::A", create=True)
    col.save()

    # Default deck still exists.
    dids = list(map(lambda d: d.id, col.decks.all_names_and_ids()))
    assert 1 in dids

    # Add another deck.
    root: DeckTreeNode = col.decks.deck_tree()
    node = col.decks.find_deck_in_tree(root, did)
    did1 = col.decks.id(f"{node.name}::0", create=True)
    col.save()

    # Default deck still exists.
    dids = list(map(lambda d: d.id, col.decks.all_names_and_ids()))
    assert 1 in dids

    # Remove one of the new decks.
    col.decks.remove([did])
    col.save()

    # Default deck still exists.
    dids = list(map(lambda d: d.id, col.decks.all_names_and_ids()))
    assert 1 in dids

    # Try to grab default deck from deck tree.
    root: DeckTreeNode = col.decks.deck_tree()
    node = col.decks.find_deck_in_tree(root, 1)
    assert node is not None


if __name__ == "__main__":
    main()
```

```python
Traceback (most recent call last):
  File "/home/mal/empty.py", line 51, in <module>
    main()
  File "/home/mal/empty.py", line 47, in main
    assert node is not None
AssertionError
```

```python
============================================================ FAILURES ============================================================
___________________________________________________ TestAnkiCollection.runTest ___________________________________________________

self = <hypothesis.stateful.AnkiCollection.TestCase testMethod=runTest>

    def runTest(self):
>       run_state_machine_as_test(cls)

../../conda/envs/anki/lib/python3.9/site-packages/hypothesis/stateful.py:400:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../conda/envs/anki/lib/python3.9/site-packages/hypothesis/stateful.py:222: in run_state_machine_as_test
    run_state_machine(state_machine_factory)
../../conda/envs/anki/lib/python3.9/site-packages/hypothesis/stateful.py:107: in run_state_machine
    @given(st.data())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = AnkiCollection({}), data = data(...)

    @rule(data=st.data())
    def add_deck(self, data: st.DataObject) -> None:
        """Add a new deck by creating a child node."""
        dids = list(map(lambda d: d.id, self.col.decks.all_names_and_ids()))
        parent_did: int = data.draw(st.sampled_from(dids))
        root: DeckTreeNode = self.col.decks.deck_tree()
        children = map(lambda c: (c.deck_id, c.name), root.children)
        logger.debug(f"{root.deck_id = }, {root.name = }, {parent_did = }, {list(children) = }")
        node = self.col.decks.find_deck_in_tree(root, parent_did)
>       names: Set[str] = set(map(lambda c: c.name, node.children))
E       AttributeError: 'NoneType' object has no attribute 'children'
E       Falsifying example:
E       state = AnkiCollection()
E       Draw 1: 1
E       Draw 2: 'Ā'
E       state.add_deck(data=data(...))
E       Draw 3: 1651363201000
E       Draw 4: '0'
E       state.add_deck(data=data(...))
E       Draw 5: 1651363201000
E       state.remove_deck(data=data(...))
E       Draw 6: 1
E       state.add_deck(data=data(...))
E       state.teardown()

tests/test_sql.py:153: AttributeError
==================================================== short test summary info =====================================================
FAILED tests/test_sql.py::TestAnkiCollection::runTest - AttributeError: 'NoneType' object has no attribute 'children'
================================================== 1 failed, 3 passed in 26.73s ==================================================
```

**Comment by dae** [comment]
The hiding is deliberate; the default deck is a design wart that I'd like to remove in the future. I think the bug here is that the default deck is shown when selecting a deck in the add screen, which appears to be because the skip_empty_default argument is being ignored when include_filtered is false.

**Comment by langfield** [comment]
> The hiding is deliberate; the default deck is a design wart that I'd like to remove in the future. I think the bug here is that the default deck is shown when selecting a deck in the add screen, which appears to be because the skip_empty_default argument is being ignored when include_filtered is false.

Surely unexpected behavior in the `DeckManager` API is a bug in its own right, without invoking anything to do with the UI?

About the default deck: if it were removed, what would happen to new cards in a fresh collection? Doesn't this break backwards compatibility in all sorts of ways?

**Comment by dae** [comment]
I think "unexpected" is up for debate; others may be confused if the API returns different results to what is shown in the GUI. If you feel it needs a docstring to document the behaviour, I'd be happy to accept a PR.

Creating a deck on first load is not the problem, it's using a hard-coded id that is. I'll wager that there's not a lot of add-on code out there that directly references deck_id=1, but there are still references in the various Anki clients that will all need updating before a move becomes practical.

**Comment by langfield** [comment]
> I think "unexpected" is up for debate; others may be confused if the API returns different results to what is shown in the GUI. If you feel it needs a docstring to document the behaviour, I'd be happy to accept a PR.

You make an excellent point! 🥇 That's true!

I would be surprised if I was the only one who did this, even if it wasn't a good idea:
```python
# pylint: disable=too-many-lines, missing-function-docstring

reexec_if_needed()

DEFAULT_DID = 1

EMPTY = get_test_collection("empty")
```

For anyone finding this issue because they had the same problem, using `col.decks.children()` directly was sufficient for my use case.
