### ISSUE TITLE
HTML does not appear immediately in field

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#2179]
Running on dba4925aba6f3ecbb6980651a82e64b1ffe62eb7 without addon

How to reproduce:
* Open a note editor
* Ensure you have a field with some content
* click on <> above the field

Expected result:
* the html of the field content appears below

Actual result:
* the new text space is empty 
![2022-11-03-204249_688x91_scrot](https://user-images.githubusercontent.com/357361/199819512-2911d891-70c2-4441-9b2d-be1dd7d1d40b.png)

The content appear either when you edit the field or when you put the focus in the html version of the field.

Maybe related:
* Click on <>
* Click in the field
* use  tab

Expected result:
* focus is in the html part of the field

Actual result:
* focus seems to disappear. If you type, then the text appear. 

Finally, I'd like to note that the HTMl part of the field has "1" in a grey box on the left of the html field. And it took me a long time to understood that it's counting lines. I had to actually type a new line in the html field editor.
I suggest that, when there is a single line (which, I assume, will be most of the time), the 1 should not appear. It does not provide any relevant information and is mostly confusing to be honest.

I can split this in multiple issues if you prefer. Last one, I don't even know if it's actually an issue, so if I were not already testing code in this part of the app, I probably would have put it in the forum instead

**Comment by dae** [comment]
Thanks for these reports Arthur.

@kleinerpirat appears to have regressed in #2170

**Comment by dae** [comment]
Re the "1", I imagine it's impractical to show/hide line numbers depending on the number of lines, so we can either leave them as-is, or turn them off.

**Comment by Arthur-Milchior** [comment]
I'd be in favor of deleting it.
Two reasons.
First, when you write a field, the html is a single field. Even <br/> don't lead to newline. So, unless you decide to add explicitly new line (and I guess, in this case, indentation), you won't see new lines. And if you have code complex enough that you need to write the HTML manually, and that it's many line, I suspect it's worth using a separate editor and copy pasting, not to expect Anki note editor to be an IDE.

Also, intuitively, I expect line numbering is great if you want either to link or communicate to some specific line number in the code. This probably actually occurs sometime, given the number of user of anki. But I doubt it would be very useful unless both people are certain to share the same version of the note. That may actually be doable thanks to ankihub, or if they both just downloaded a shared deck, but I doubt this case is relevant.


By the way, my first guess about what 1 could mean was the level of tags in which my cursor is. After all, the button next to 1 allows to hide the content inside some tags

**Comment by dae** [comment]
I personally don't see the need for the line numbers either, but I did not originally add them. Do you have any objections to removing them @hgiesel?
