### ISSUE TITLE
Can we have a login profile in anki? 

### ISSUE THREAD

**Issue by AliakbarETH** [ankitects/anki#2194]
-   Have a question or feature suggestion?
-   Hi, I would like to suggest if we could add login/signup functionality so, we can access the anki in any device with current state saved     and concurrent all across the devices.
-   Problems building/running on your system?
-   Not 100% sure you've found a bug?

If so, please post on https://forums.ankiweb.net/ instead. This issue tracker is
intended primarily to track development tasks, and it is easier to provide support
over on the forums. Please make sure you read the following pages before
you post there:

-   https://faqs.ankiweb.net/when-problems-occur.html
-   https://faqs.ankiweb.net/getting-help.html

If you post questions, suggestions, or vague bug reports here, please do not be
offended if we close your ticket without replying. If in doubt, please post on
https://forums.ankiweb.net/ instead.

**Comment by abdnh** [comment]
https://docs.ankiweb.net/syncing.html
