### ISSUE TITLE
All fields reopen after adding a card

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#2200]
Running on dc4ac1da6630a90ebf506235eef1c2df0c1192fa

How to reproduce:
* open a "new note"
* close a field
* fill other field so that the note can be created
* click on "add" to add the note

Expected result:
* seing the window allowing to add a new card. Same fields open/closed

Actual result:
* all fields are now open

I'm quite certain it's a new behavior. I see the interest when you change note type. But, for use case such as mine, it makes it hard to use, because, depending on the deck, I'll have some fields I never use and opening them again makes hard to find the one I actually want to use

**Comment by dae** [comment]
This in on our radar; for now adjusting visibility in the fields dialog should make it permanent.
