### ISSUE TITLE
Imgur Returns 403

### ISSUE THREAD

**Issue by aus10code** [ankitects/anki#2234]
**Issue:**
When trying to link images from imgur in `<img src"">` tags it now throws a 403 error. It hasn't always done this. I have tried different user-agents with no success.

**Info:**
My current hypothesis is that imgur has issues with `127.0.0.1` requests which `_anki/js/reviewer.js` utilizes.

**Question:**
Is there a way to modify reviewer.js to utilize `localhost` instead of `127.0.0.1` as this has solved some other peoples issues on [stackoverflow](https://stackoverflow.com/questions/43895390/imgur-images-returning-403)

![image](https://user-images.githubusercontent.com/62197117/205479780-278892ff-792a-4b5d-899b-a200081022c4.png)
![image](https://user-images.githubusercontent.com/62197117/205479803-0a54ae06-5391-4bea-ba9a-70a284e5f87b.png)
![image](https://user-images.githubusercontent.com/62197117/205479807-4c4966ed-e0cb-491c-839f-637b5965c6f0.png)
![image](https://user-images.githubusercontent.com/62197117/205479820-168ff3e2-8829-4282-ab3e-c9bc1f1a63d8.png)

**Comment by dae** [comment]
Some machines lack a DNS entry for localhost, which 127.0.0.1 avoids. I'm afraid you'll need to fix this some other way - maybe the referrer suggestion in that thread.

**Comment by aus10code** [comment]
for anyone stumbling upon this issue in the future, I was able to solve it by putting
`<meta name="referrer" content="no-referrer">` above each `<img>` tag and `referrerpolicy="no-referrer"` inside of the `<img>` tag.

So each image looks like this
`<meta name="referrer" content="no-referrer">
<a href="https://i.imgur.com/9BREQpW.png"><img src="https://i.imgur.com/9BREQpW.png" referrerpolicy="no-referrer"></a>`

The meta tag alone _might_ (untested) fix it however the `referrerpolicy="no-referrer"` alone doesn't always solve the issue.
