### ISSUE TITLE
Esc can no longer be used to close dialogs after webview focused

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2238]
Ah, it's a bit more subtle than that, and reminds me why onEsc was originally introduced. Focus starts on the window, so pressing Esc immediately works. But if you click in the webview to focus something, then esc can no longer be used to close the dialog. It also affects the card info screen, graphs, and so on.

_Originally posted by @dae in https://github.com/ankitects/anki/issues/2237#issuecomment-1336921212_

**Comment by abdnh** [comment]
This appears to happen in webviews that don't include webview.ts.
