### ISSUE TITLE
Reviewing a single card in session decreases review cards due in session by more than 1

### ISSUE THREAD

**Issue by jtbeales** [ankitects/anki#2249]
Hi!

I'm running Anki Version ⁨2.1.54 (b6a7760c)⁩ on macOS 13.0.1 (22A400) on an M1 mac. I've run into an issue that I can't find documented elsewhere.

When I'm already in a review session (e.g., the screenshot below), reviewing a single card sometimes causes the number of review cards due (the green 38 in the example below) to drop by multiple cards (sometimes >10 cards). So I'll be studying cards, and marking most cards as "good" just moves the counter down by 1. However, occasionally, marking a card as "good" drops the counter by more than one card. 

I suspect that these cards might be getting buried, but per the documentation (https://faqs.ankiweb.net/the-2021-scheduler.html), I thought that the burying process happened after you launched a review session (i.e., the counts displayed at the beginning of the session already accounted for burying)? I'm running the v2 scheduler, I believe. However, I'm switching to v3 to see if this changes things.

Interestingly, the "Progress Bar original" add on is always aligned with the number of cards I'll _actually_ be required to review in a session. I.e., if the counter initially shows 40, but 10 cards will suddenly disappear from the counter, that add on would be showing my progress based on the 30 cards I would actually be required to review, not the 40 initially shown in the counter.

If this is a documented phenomenon, I apologize for not understanding that. It just seemed bizarre to me that the counter would drop by so many cards after a single card review when the notes in question only had 1-3 cards, not 10 (so burying more than 1-2 cards wouldn't make sense to me for these notes).

Thank you!

![image](https://user-images.githubusercontent.com/35981215/206534596-6fa80209-615a-4df8-a99f-6091ccb1dedb.png)

    

**Debugging Information**
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
    Platform: Mac 13.0.1
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-12-08 12:41:22
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Answer Confirmation for 21 ['1354051622', 2019-04-04T08:54, 'None', '']
    Button Colours Good Again ['2494384865', 2022-09-27T06:18, 'None', '']
    Copy notes ['1566928056', 2021-12-24T14:56, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2022-09-14T05:12, 'None', '']
    Image Occlusion Enhanced for Anki 21 ['1374772155', 2022-04-09T03:15, 'None', '']
    More Overview Stats 21 ['738807903', 2021-07-30T15:13, 'None', '']
    More Overview Stats ['2116130837', 2022-09-16T13:56, 'None', '']
    Progress Bar original ['1685464019', 2022-07-28T01:24, 'None', '']
    Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1354051622 1374772155 1566928056 1685464019 1771074083 2116130837 24411424 2494384865 738807903
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2022-09-26T20:28, 'None', '']
    Answer Shortcut Keys ['687138446', 2018-01-26T17:18, 'None', '']
    Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T11:06, 'None', '']
    Deadline2 ['723639202', 2021-05-02T00:45, 'None', mod]
    Extended Card Stats During Review ['1008566916', 2017-08-29T14:59, 'None', '']
    Frozen Fields ['516643804', 2020-02-29T23:12, 'None', '']
    Life Drain ['715575551', 2022-09-18T06:42, 'None', '']
    Multi-column note editor ['3491767031', 2021-11-02T11:18, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-03-23T13:32, 'None', '']
    Session Timer ['1287298831', 2020-06-30T12:35, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T05:11, 'None', '']
    Web Browser - Search terms Import texts and images automatically ['864545277', 2022-08-02T16:49, 'None', '']
    Zoom 21 ['1846592880', 2020-01-12T12:26, 'None', mod]
    load balancer ['1417170896', 2020-08-05T19:58, 'None', '']

**Comment by dae** [comment]
Please use the forums for such questions.
