### ISSUE TITLE
Mathjax editor closing via the enter key error

### ISSUE THREAD

**Issue by zhangpengfei133** [ankitects/anki#2258]
In the version  ⁨2.1.55 (f38c4e2f)⁩,When I close the Mathjax editor via enter key,the cursor go to heading of the line.
![20221209_204831 00_00_00-00_00_02 00_00_00-00_00_30](https://user-images.githubusercontent.com/44221035/206706446-1bf019d4-eaad-4353-86fa-df6daf425220.gif)

**Comment by dae** [comment]
Thanks for the report :-)
