### ISSUE TITLE
RTL problems on first run after a clean install

### ISSUE THREAD

**Issue by ROOMBON** [ankitects/anki#2269]
About that:
https://forums.ankiweb.net/t/anki-2-1-55-beta-7-rc1/25130/31

I marked with a red circle what needs to be reversed.

The deck browser:
![image](https://user-images.githubusercontent.com/76751053/207175105-b7d6ce5c-4238-42b4-b455-dad211cd164e.png)
Dialog box - OK - Cancel:
![image](https://user-images.githubusercontent.com/76751053/207175299-22c1740b-fdab-4d22-b94c-c6f8382dfde3.png)
In the browser, everything is reversed - the menu bar, the position of the sidebar, the alignment of the content in the sidebar to the right, and the direction in the menus.
![image](https://user-images.githubusercontent.com/76751053/207175691-38e43f56-93f6-4bf3-89da-250d7aae6b9d.png)
In the "Add" window - the position of the deck and card type buttons as well as the description should be on the right side of the button and not on the left.
![image](https://user-images.githubusercontent.com/76751053/207176022-fbb81fc4-b67a-42cc-a7a3-0807e8827779.png)
In the "Fields" window, everything is also reversed
![image](https://user-images.githubusercontent.com/76751053/207176204-c24702ac-acf0-42f0-9ddb-8f0acb2de803.png)
The gear menu in the Add window
![image](https://user-images.githubusercontent.com/76751053/207176411-26924d9a-6e86-4c3f-9a2f-250a393e9f4d.png)
A filtered deck window is also all upside down
![image](https://user-images.githubusercontent.com/76751053/207176641-2acf5d0a-bf39-4018-8ff4-bcd346477efc.png)
And on the review screen the buttons below are reversed - more and edit and the rating buttons. The bar above and the menus are also reversed as in the main screen.
![image](https://user-images.githubusercontent.com/76751053/207177302-8268c9c2-ce3c-4208-bea8-09bc4262baac.png)

**Comment by dae** [comment]
Thank you, please let me know if the next rc fails to fix the issues.
