### ISSUE TITLE
Text copied from QTextEdit/QPlainTextEdit contains PS characters instead of LF/CR

### ISSUE THREAD

**Issue by abdnh** [ankitects/anki#2275]
Text copied from QTextEdit/QPlainTextEdit widgets (e.g. in the card layouts, add-on config, deck description screens) contains Paragraph Separator characters instead of line feeds/carriage returns.

This can be reproduced in the 2.1.55 and the latest main. It's a Qt bug ([QTBUG-107004](https://bugreports.qt.io/browse/QTBUG-107004)). I'm just creating this issue to bring it to attention.

**Comment by dae** [comment]
Thanks for the heads up. If no serious issues are found before then, I'm hoping we'll be able to wait for the Qt 6.4.2 release, due out around mid Jan.
