### ISSUE TITLE
Regression with types in `aqt.gui_hooks`

### ISSUE THREAD

**Issue by PerchunPak** [ankitects/anki#2276]
After `anki 2.1.55` update, `mypy` raises new error
```
> mypy -c "import aqt; aqt.gui_hooks.card_will_show"                          
<string>:1: error: Module has no attribute "card_will_show"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
> mypy --implicit-reexport -c "import aqt; aqt.gui_hooks.card_will_show"
<string>:1: error: Module has no attribute "card_will_show"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

Possibly, it can be fixed with generating stubs for `aqt.gui_hooks`, as if I manually add `card_will_show = None` to the file, the problem resolves.

**Comment by dae** [comment]
If you follow the import style covered in the docs, it should work correctly.

```
from aqt import gui_hooks
gui_hooks.card_will_show
```

https://addon-docs.ankiweb.net/hooks-and-filters.html#new-style-hooks

**Comment by PerchunPak** [comment]
There is no difference for mypy. Please reopen it, as I have no button.
```
> mypy -c "from aqt import gui_hooks; gui_hooks.card_will_show"
<string>:1: error: Module has no attribute "card_will_show"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by dae** [comment]
You can resolve the problem for now by creating a py.typed file in the venv's _aqt folder, eg:

```
touch lib/python3.9/site-packages/_aqt/py.typed
```
