### ISSUE TITLE
Ninja not tracking changes in newly added files

### ISSUE THREAD

**Issue by kleinerpirat** [ankitects/anki#2277]
While working on a PR in `ts`, I found that Ninja skips building if my changes are isolated to newly added `.svelte` files.

## Reproduction steps

1. create a `Test.svelte` component, e.g. in `ts/congrats`
2. import and use `Test.svelte`, e.g. in `CongratsPage.svelte`
3. run Anki
4. make changes to `Test.svelte`

### Expected behavior
Ninja performs the necessary build steps on the next run so the changes are reflected in Anki.

### What actually happens
Ninja logs "no work to do" and starts Anki at step 3.

**Comment by dae** [comment]
For performance reasons, the build file is not regenerated on every run. You can force it to pick up new files by removing out/build.ninja

**Comment by kleinerpirat** [comment]
Thanks!
