### ISSUE TITLE
fcitx input broken on Linux?

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2278]
The extensions may need recompiling for the latest Qt; may make sense to wait for the 6.4.2 update.

https://forums.ankiweb.net/t/2-1-55-cant-type-japanese-text-after-update-fcitx-linux-issue/25488

**Comment by easyteacher** [comment]
libFcitx5Qt6DBusAddons.so.1 is linked to anki-2.1.55-linux-qt6ibFcitx5Qt6DBusAddons.so.1 which does not exist

**Comment by dae** [comment]
Thanks, that helped. Please let me know if the next build doesn't fix it for you.
