### ISSUE TITLE
Request: Allow user-defined separators on import dialog

### ISSUE THREAD

**Issue by draeklae** [ankitects/anki#2283]
In the new version of the import dialogue on the latest version (2.1.55), there is no possibility to set a custom separator. Only tab, pipe, and a few others are allowed. This was not the case in previous versions of Anki. Is there any particular good reason to forbid user-defined separators?

On another note, the file chooser dialogue displayed prior to the import dialogue also does not allow choosing files with arbitrary extensions. (It only allows files named *.csv, *.txt, *.xml, etc.) I suppose might make sense on, e.g., Windows, but there doesn't seem to be a good reason to impose this restriction on platforms such as Linux. (I usually don't add any extensions to my files, which makes this a bit of a nuisance.)

**Comment by dae** [comment]
Supporting custom separators adds complexity to the UI, and it's hard to justify when most users use the same common separator. What separator are you using, and is it coming from files you create yourself?

The extension requirement is so that Anki can identify what type of file is being imported. The previous approach lead to confusing errors when users tried to import unsupported file types, as Anki was trying to import them as a CSV.

@RumovZ heads up

**Comment by draeklae** [comment]
Yes, I'm using a custom separator because of files I create myself, but I can easily see having only the 6 separators offered (pipe, tab, semicolon, colon, comma, space) being a problem: Four of them are already useless if your cards contain formatted text (semicolon, colon, comma, space). Pipe might also come up in some texts, markdown, or LaTeX formulae. This leaves only tab, which is... well, not good because it is whitespace and hard to work with.

The old dialogue just let the user choose whatever they wanted. Maybe one can use a similar strategy to the csv import/export dialogue on LibreOffice? (Most common options are there, but you can also use a custom one if you want to.)

**Comment by RumovZ** [comment]
You can use any separator with any data. You only have to make sure to escape the separator if it appears in a row by wrapping the entry in quotes.
I can see how it is more convenient to be able to use a separator that doesn't appear in your data to begin with, but that's not trivial. Some characters have special meaning and the CSV library we're using only supports single bytes. So if you have been using a NBSP e.g., that wouldn't be possible anymore, anyway.
I would assume most users have their CSV files generated anyway and don't have to bother with separators at all.

**Comment by draeklae** [comment]
I would actually say that using generated CSV files are *more* of an issue in that case since then you have to trust that the program/library/whatever that you're using did get quotes and everything right. Anyway, it's the user's responsibility to provide Anki with a properly formatted CSV file and also tell it what the formatting is. If you just throw garbage at it, it's obvious that's going to end up getting jammed somewhere.

The custom separators were a feature in previous versions. I just can't follow the reasoning to suddenly cut back on a feature all of a sudden like this.

**Comment by RumovZ** [comment]
> I would actually say that using generated CSV files are more of an issue in that case since then you have to trust that the program/library/whatever that you're using did get quotes and everything right.

I trust my spreadsheet program to get this right like I trust my calculator to add two numbers correctly.

> Anyway, it's the user's responsibility to provide Anki with a properly formatted CSV file and also tell it what the formatting is.

But it is a program's responsibility to deal with invalid user input gracefully.

> I just can't follow the reasoning to suddenly cut back on a feature all of a sudden like this.

The importer has been completely rewritten in Rust. In the process, new features have been added and a few rarely used ones have been cut.
I'm sorry it's an inconvenience to you, but in fact, you're the first one to miss this feature.

**Comment by draeklae** [comment]
Well, here comes another plugin then I guess...

**Comment by dae** [comment]
I'm afraid it's not possible to make everyone happy all of the time, but I thank you for your feedback.

**Comment by xavier-taylor** [comment]
Respectfully adding my voice to this discussion - I was using "¦" as a separator because I could confidently remove it from any of the things I input into my custom made deck. For now I will just change it to pipe |, but I was surprised when I saw this feature gone today (I must have been using a slightly older anki till now).

**Comment by mod20388** [comment]
Indeed. In my case the simplest solution turned out to be csvkit (e.g., `csvformat -d'%' -D','` to convert from % to comma). The Anki importer somehow seems to never detect the correct separator, but that's just a minor nuisance I guess...
