### ISSUE TITLE
Separate Interval modifier for Decks / Subdecks

### ISSUE THREAD

**Issue by amalrajjs** [ankitects/anki#2292]
In the latest version there can't a separate interval modifier for separate decks and subdecks. Please bring back that feature.

**Comment by dae** [comment]
They can be customized per-deck with presets, as always. If you need help, please use the user forums.

**Comment by amalrajjs** [comment]
Do I need to create another Present for that? Now I can set separate New card / Review card for each Deck / Sub deck separately. Can you please include that feature to Interval modifier too?
