### ISSUE TITLE
anki doesn't support semi space

### ISSUE THREAD

**Issue by Ajax9039** [ankitects/anki#2293]
I'm using anki Version ⁨2.1.54 (b6a7760c) and it doesn't support semi space character (ZERO WIDTH NON-JOINER) with uni code U+200C it's an important part of my language ( persian ). is there a way to use it or can it be added in future ?

**Comment by dae** [comment]
Please describe the problem in more detail.

**Comment by Ajax9039** [comment]
it does support that character if you copy and paste it but I can't type it directly it's typed in Farsi keyboard by ctrl +shift +2 but it doesn't work in anki

**Comment by dae** [comment]
Does the issue exist in the latest Anki release, in both the Qt5 and Qt6 versions? What platform are you on?

**Comment by Ajax9039** [comment]
No, it didn't work in the last version but I've changed my keyboard to an older Persian standard where I need to type shift + space and it works fine.
