### ISSUE TITLE
Ok button in pop-up docs disappears on highlight

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2297]
https://forums.ankiweb.net/t/minor-issues-tag-layouts/25942/3

**Comment by winterhazel** [comment]
The cancel button (in the Add Preset pop-up, for instance) shares the same problem.

Before and after hovering:

![Screenshot_20230105_222004](https://user-images.githubusercontent.com/25729641/210911218-6162b8e8-b2b9-43a6-b23c-1ccdefaedeff.png)
![Screenshot_20230105_222017](https://user-images.githubusercontent.com/25729641/210911223-d2adc9a1-8da7-409c-b8d9-2b5ce2209441.png)

**Comment by dae** [comment]
@kleinerpirat do you know if this would be an easy fix for .56?

**Comment by kleinerpirat** [comment]
It's an interference by the bootstrap button styles. I think it's safe to move away from those, because they don't serve a major purpose in Anki anymore and can be easily replaced with our own styles.

**Comment by dae** [comment]
If it doesn't cause regressions, sounds good to me. It might be nice to keep the concept of a primary/default button though, which I don't think we have in our current custom styling.

**Comment by dae** [comment]
Would be great if you have a chance to look into this before 2.1.63, as it make Anki look a bit unpolished. :-)
