### ISSUE TITLE
Sporadic crashes when shutting down application

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2299]
Some users have reported that both the qt5 and qt6 versions can crashes on shutdown, eg https://forums.ankiweb.net/t/anki-quit-unexpectedly-error-macos-12-3-1-m1/25622. Presumably it's caused by non-deterministic garbage collection at shutdown destroying the Qt webengine objects in an order they don't expect. Explicitly deleting them first may help, but as I can't reproduce the errors on my machine, it's hard to test a fix. If any devs are experiencing this issue reliably, it would be great if they could dig into it.

**Comment by woj-tek** [comment]
I wasn't aware I have both Qt5 and Qt6 versions.

**Comment by dae** [comment]
I mean the problem exists in both the Qt5 and Qt6 versions of Anki - it's not specific to one of them.

**Comment by dae** [comment]
One user reports that sync on startup/shutdown was causing this.

**Comment by woj-tek** [comment]
I do have "sync on open/close" option enabled as well. Though, it only happens on shutdown and it seems sync finishes correctly.

**Comment by dae** [comment]
Is this still happening with the latest Anki?

**Comment by rouge8** [comment]
It hasn’t happened to me recently!

**Comment by dae** [comment]
Thanks, tentatively closing. Please post here if you're still seeing it.

**Comment by rodrigaj** [comment]
I'm seeing this consistenly upon shutdown. Manual sync is never a problem. When I reopen after the crash, and shutdown again, it never crashes. It never crashes on startup. 
I will try disabling automatic sync on close. 
Running MacOS Sonoma 14.1.2.
Anki Version ⁨2.1.63 (f356f177)⁩
Python 3.9.15 Qt 6.5.0 PyQt 6.5.0

**Comment by chrislongros** [comment]
The current version of Anki is 23.12.1, what about updating and checking if the problem persists ? :)

**Comment by rodrigaj** [comment]
Yes, thank you. I see that Anki version has changed format. I thought for a moment that I was 21 versions behind. LOL.
I installed 23.12.1, reset sync on close and will post back here if the crash on shutdown reoccurs.
