### ISSUE TITLE
Investigate switch to difflib

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2305]
1e0be26b7e11640c6381f7bdf2f686275a21ed08 migrated from the Python difflib to the dissimilar crate so we can use the code across all platforms, but it unfortunately does not seem to perform as well for some languages/inputs. There appears to be a Rust port of difflib available, so it might be worth looking into whether we can use that instead, if it gives better output.

https://crates.io/crates/difflib

https://forums.ankiweb.net/t/error-highlighting-after-typing-the-answer/25755/6

@RumovZ feel free to take this if it interests you

**Comment by dae** [comment]
We'll want to look into this as a matter of priority, as it appears that dissimilar will panic with certain non-Latin text input, eg

```
        let ctx = DiffContext::new("Сущность должна быть ответственна только за одно дело", "Single responsibility Сущность выполняет только одну задачу. Повод для изменения сущности только один.");
```

**Comment by RumovZ** [comment]
To be clear, that means the investigation part is over and we want to switch without question now?

**Comment by dae** [comment]
If the library isn’t suitable, there’s still the option of finding another
one, or trying to fix the panic in the one we currently use as a last resort

**Comment by dae** [comment]
Closed via #2322

**Comment by popyoung** [comment]
Still incorrect in 2.1.57

**Comment by dae** [comment]
Please create a new issue and describe the problems you're having/provide reproduction steps.

**Comment by dae** [comment]
Nevermind, I see you've posted in the forums. Please provide a card ID and the exact text you're entering, so I can try to reproduce the problem.

https://forums.ankiweb.net/t/bug-cloze-correction-doesnt-work-as-expected/26302/3
