### ISSUE TITLE
Nested clozes not supported in type answer

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2311]
reviewer.py is still using a simple regex approach. I imagine the easiest way to solve this for now will be to add a new helper method to card_rendering.proto that can be dropped in place of _contentForCloze() (after exposing it publicly via a method in collection.py)

https://forums.ankiweb.net/t/nested-cloze-feature-not-working-with-type-cloze-notetype/26180

@TRIAEIOU interested in tackling this?

**Comment by TRIAEIOU** [comment]
> @TRIAEIOU interested in tackling this?

I can have a look at it but have an upcoming exam so it may not be immediately. It should be noted I know nothing of proto and the RS ↔ PY integration so that would be a learning curve.

**Comment by dae** [comment]
Righto. If you or someone else starts working on this please post a reply; otherwise I'll pick this up when I have a chance.
