### ISSUE TITLE
Pending UI improvements

### ISSUE THREAD

**Issue by tatsumoto-ren** [ankitects/anki#2313]
Creating this issue to track some of the UI-related features people have been asking for. The discussions are scattered all over the forum, so I'm going to try to gather everything in one post so that we don't lose anything.

- [x] A "Minimal" theme in Preferences.
- [x] An option to apply your system theme (Plasma, GTK).
- [ ] An option to install custom styles.

## Minimal theme

Basically a switch that turns everything to how it was in 2.1.54. If the current theme can be described as *too flashy*, then the minimal one should be the opposite of that.

**A concept:**
![proposed](https://user-images.githubusercontent.com/69171671/211792048-33c68745-179f-4ad4-8cd7-156629208a60.png)

<details>

<summary>Some of the comments</summary>

![screenshot-2023-01-02-18-05-05](https://user-images.githubusercontent.com/69171671/210266086-83fd81b7-a1d5-4402-984b-2e2596557dd1.png)

![screenshot-2023-01-02-18-13-16](https://user-images.githubusercontent.com/69171671/210266640-4dca7dc5-eb16-4622-b0fd-d964e0058483.png)

![screenshot-2023-01-11-10-58-34](https://user-images.githubusercontent.com/69171671/211789577-cf0bf1d0-af4a-4c81-a5af-9688d11bbe76.png)

</details>

For Qt widgets this would mean not injecting too many CSS rules and letting them use *Fusion* as before. There could be some styles applied by default, but they shouldn't stand out.

**Examples:**

| Default | Minimal |
| --- | --- |
| ![screenshot-2023-01-11-11-26-58](https://user-images.githubusercontent.com/69171671/211795904-8d4004a5-971e-41d9-8bb2-b1978ec16c1e.png)  | ![screenshot-2023-01-11-11-31-42](https://user-images.githubusercontent.com/69171671/211795990-20b883f6-a6ef-44af-9553-33190384a1ae.png) |
| ![screenshot-2023-01-11-11-27-06](https://user-images.githubusercontent.com/69171671/211796086-a0983a23-a366-449d-b34c-f0672c62dc14.png) | ![screenshot-2023-01-11-11-31-48](https://user-images.githubusercontent.com/69171671/211796160-587d8804-c7f3-4a76-ae38-596e23c2c7c5.png) | 
| ![screenshot-2023-01-11-11-27-14](https://user-images.githubusercontent.com/69171671/211796282-cb6b1c5c-27da-4d12-8849-8fb4e715fee9.png) | ![screenshot-2023-01-11-11-32-45](https://user-images.githubusercontent.com/69171671/211796300-70276e52-34fa-4929-a61c-05c678bf9a32.png) |

## Apply system theme

We used to be able to have Anki conform to whatever system theme is installed, but the feature doesn't seem to work anymore. This could be another option in Preferences.

| Anki 2.1.55 | Adapta on 2.1.54| Arc on 2.1.54 |
|---|---|---|
|   ![screenshot-2023-01-02-00-55-24](https://user-images.githubusercontent.com/69171671/210188997-26c834c5-fa00-42a7-84c3-d3da26235b83.png)  |  ![screenshot-2023-01-02-00-44-34](https://user-images.githubusercontent.com/69171671/210188998-7dd19afb-9499-47fc-b385-7eaff7478281.png)   | ![screenshot-2023-01-02-01-07-47](https://user-images.githubusercontent.com/69171671/210189203-171bac4c-3e76-468c-b620-31456d59a629.png) |

## Custom styles

A hook that would allow add-on developers to populate the Preferences menu with their own options. Of course you can do it now but it requires more work. The hook would accept your custom CSS and add a new option automatically. This should make it easier to ship themes as addons and make them switchable/selectable. Think of themes in Firefox.

![proposed](https://user-images.githubusercontent.com/69171671/211805875-77248210-5d3d-4d69-a0ee-e19208472dc8.png)

----

If I forgot to mention something, below are some of the related threads.

* https://forums.ankiweb.net/t/2-1-55-gui-discussion/25848/
* https://forums.ankiweb.net/t/2-1-55-ui-breakage-due-to-force-applied-styles/25557
* https://github.com/ankitects/anki/pull/2287
* https://github.com/ankitects/anki/pull/2262

**Comment by tatsumoto-ren** [comment]
If all of this is too much work, I think that if only the first task is fulfilled, that's going to be enough for most people who commented on the forum.
Now, I can start working on it, however, I know very little about Anki's source code so I would appreciate if you tell me where to start.

**Comment by dae** [comment]
Looks like @kleinerpirat is on it: #2289

**Comment by kleinerpirat** [comment]
Thanks for pinging me @dae, I didn't notice this thread. It seems like we got similar ideas in mind.

**Comment by tatsumoto-ren** [comment]
@dae I have a great idea for a pull request that would rewrite the top toolbar (in the main window) in a superior way. There is a native class for making toolbars in PyQt, it's called `QToolBar`. You can read about it [here](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QToolBar.html) for example.
So I could make a custom class that inherits from `QToolBar` and replace the top toolbar with it. Of course, there should also be compatibility shims for add-ons. I think everybody agrees that embedding a webpage just to draw a few buttons is a crazy idea, it's too complicated and over-engineered compared to the native approach. 

There's an add-on that adds similar functionality to the Browser &mdash; [Fastbar](https://ankiweb.net/shared/info/46611790). You can look at [their github](https://github.com/AnKing-Memberships/Fastbar-with-nightmode-support/tree/master/src) to see how it's done.

**Comment by kleinerpirat** [comment]
It would be interesting to see how such a widget compares to the current toolbar and we'd probably be able to reach feature parity with the recently added auto-hide behaviour, but I'm not sure we should be spending too much time on new Qt widgets.

The latest toolbar changes were a hotfix (which admittedly I spent way too much time on), but I'm still convinced we should be working towards a unified main webview.

**Comment by tatsumoto-ren** [comment]
Hiding Qt widgets is easy. There's a built-in method for that. Creating animations is apparently tricky but most of the time they are not needed and unnecessarily rub your eye in the wrong way. 

I'm convinced we should be eliminating widgets based on AnkiWebView because such approach has proven to be error-prone. I expect that a unified main webview will cause even more breakage. Just today [I found another annoying visual glitch](https://forums.ankiweb.net/t/2-1-55-ui-breakage-due-to-force-applied-styles/25557/57?u=tatsumoto) with buttons on cards.

Not sure if there's an alternative approach. Maybe moving towards QML is an option. Or we could try isolating the Reviewer screen as much as possible to prevent any extra CSS from affecting cards.

**Comment by dae** [comment]
Yes, I am familiar with QToolbar - Anki used to use it a long time ago. I'm afraid I don't think buying further into Qt is the right path forward at the moment. The reviewer and editor are the two most important parts of Anki's UI, and I don't see them ever moving away from webviews, so we need a solid web renderer. Qt's Chromium port seems to have a lot of issues, and I suspect in the long run we may be better off moving away from Qt entirely.

> I think everybody agrees that embedding a webpage just to draw a few buttons is a crazy idea, it's too complicated and over-engineered compared to the native approach.

Are you being deliberately provocative, or do you just not realize how your comments come across? A charitable approach would be to assume there are reasons for the way things are currently done, and perhaps inquire if curious. When you come in, label what exists as "stupid", and make out that everything will be better if we just follow your "great idea", it is not pleasant. You have some valid points about certain things regressing in the last few updates (as will tend to happen when larger changes are made, and Matthias has been working hard on fixing the issues that have cropped up), but the tone you present the issues, as I pointed out previously on the forum, does not really encourage us to engage with you. Please try to be more considerate, or your comments risk getting ignored out of frustration.

**Comment by glutanimate** [comment]
(was typing this up as @dae replied – you beat me to the punch :) – so the Qt section is slightly repetitive, but still sharing to add the add-on perspective and touch on the spillover concerns)

I personally like Qt, but given that Anki has been moving towards more web-based components rather than fewer, I don't see this being a fruitful endeavor at this stage. A unified web view also means that add-on authors will be able to do more interesting things, e.g. add UI components that interact both with the toolbar and reviewer. Currently you need quite a bit of boilerplate code to mediate between the two, and add-on UI can't span between both views.

The issue with styles and logic spilling over between card content and Anki's UI is real, however, and is something we'll have to figure out how to tackle if we follow the unified web view path (e.g. iframe, shadow DOM, etc.). It will likely also be somewhat important from a security standpoint as we don't want to give code in card templates too much control over Anki. At the same time, whatever sandboxing we do should not prevent add-ons from having access to card content. So this will be an interesting problem to tackle, but not impossible.

**Comment by tatsumoto-ren** [comment]
> Qt's Chromium port seems to have a lot of issues, and I suspect in the long run we may be better off moving away from Qt entirely.

Okay. I think I understand your desire to remove Qt widgets. But if the end goal is to move away from Qt entirely then virtually all add-ons will be broken anyway right?

> Are you being deliberately provocative

No, the opposite actually. Before sending the post you're referring to, I redacted it to make it sound as soft as possible. I'm surprised that you criticize the tone of the writing though.

**Comment by dae** [comment]
I appreciate you making an effort. And yes, if one day we do eventually migrate away from Qt, add-ons that still use it will need to be updated.

**Comment by Aquafina-water-bottle** [comment]
@tatsumoto-ren I believe 2.1.57 solves the 2nd point:

> A new option in the preferences to switch between native styling and the Anki theme (on Mac/Linux).

Can you confirm/deny, and update the checklist if it works?

**Comment by tatsumoto-ren** [comment]
@Aquafina-water-bottle I think it works.
