### ISSUE TITLE
Change Rust import style?

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2320]
@RumovZ as the primary other contributor to the Rust parts, I wanted to get your input.

What would you think about changing the Rust import style to vertical with no nesting?
![2023-01-14T18:22:12,621974866+10:00](https://user-images.githubusercontent.com/180542/212463296-c8991b7a-76d3-4901-a7f7-4dc88a9f0646.png)

I find the former prettier, but find it to be cumbersome when actually working with the code - unused imports are harder to clean up (clippy can do that for us too, but can be slow for minor cleanups), and when refactoring code, it's difficult to find&replace the new module paths. Recently during large refactors I've ended up reformatting with the latter style, making the changes, and then reformatting back to the first style again after they're done.

The latter style is also less prone to merge conflicts, though to be fair, we don't get a lot of conflicting changes at the moment.

WDYT?

**Comment by RumovZ** [comment]
That's true. When I manually add an import in Python, I usually copy another line and adjust the last component(s). With nested imports that's not possible. Adding another import from a bottom-level module is usually simple enough, but it quickly gets cumbersome if you need to import from an intermediate namespace:
```rs
crate::top_mod::middle_mod::bottom_mod::{struct1, struct2};
# ↓
crate::top_mod::middle_mod::{bottom_mod::{struct1, struct2}, new_mod};
```
It's easy to misplace the curly braces if there is a lot of nesting.

So there's definitely an argument for flat imports here, but either would work for me.

**Comment by dae** [comment]
Thanks Rumo. I think I'll go ahead with this once I wrap up the branch I've been working on.
