### ISSUE TITLE
make use of 'ANKI_NOVERIFYSSL' in Rust-Code as well

### ISSUE THREAD

**Issue by mschwehl** [ankitects/anki#2324]
Hello Anki-Team

i set up an sync-server-rs in a k8s-environment using self-signed ssl certificates

using client 2.1.54 and the plugin 

"custom sync server redirector" - Working
"Enable HTTPS interception for foreign SSL certificate" - Not working

Workflow: Hit the sync-button
Message:  unsuccessful tunnel

After some research in the code (no rust / little pyton experience)
------------------------------------------------------------------------------------

there is the ```Client::builder()```
           
(https://github.com/ankitects/anki/blob/a7cb5e210e8733b97d1226cea3c9386593e6677a/rslib/src/sync/http_client.rs#L219)

and i think adding

``` danger_accept_invalid_certs(true) ```will help me like in the python-code

https://github.com/ankitects/anki/blob/b6a7760cb4041cfeb3a2aab757050a989f6a7493/pylib/anki/httpclient.py#L85

that seems not to be active

It would be great if you adapt the variable "ANKI_NOVERIFYSSL" in the rustcode as well

Greetings
Martin

**Comment by dae** [comment]
Disabling verification considerably decreases the benefits of HTTPS, so I'd prefer not to expose such a feature. The option you're referring to was added back when syncing went via Python, and the Python libraries weren't able to pick up extra trusted roots that are installed system-wide.

Better ways of solving this are to register your roots system wide, use LetsEncrypt to get proper certificates, or to use bare HTTP over some other form of encryption like a VPN.

**Comment by mschwehl** [comment]
Thank you very much for taking time looking in this issue

At my workplace we work with our own acme-server but one main issue is that  SSL certificates can be revoked at any time, so a client needs to be able to check a server to see what state they are in.

you cannot guarantee that in in a cooperate evironment where the infrastructure is not in your own hands, usually we add our pem-bundle to the applications (git / java-credstore) and so on 

In Rust, 

the doc states that you can add self-signed certificates using

```client.add_root_certificate(cert)```

I understand your conserns but it will be helpfull to

**Comment by dae** [comment]
You should already be able to point to a custom pem: https://github.com/rustls/rustls-native-certs
