### ISSUE TITLE
Anki crashes giving segmentation fault

### ISSUE THREAD

**Issue by z3n-k3rn3l** [ankitects/anki#2333]
I have run anki via terminal and by startmenu. In both case it's not starting up. Please find the below image which contain information while running anki from terminal..

Anki starting...
Initial setup...
Running with temporary Qt5 compatibility shims.
Run with DISABLE_QT5_COMPAT=1 to confirm compatibility with Qt6.
Preparing to run...
Qt warning: WebEngineContext used before QtWebEngineCore::initialize() or OpenGL context creation failed. 
Qt warning: QGLXContext: Failed to create dummy context 
Qt info: 

GL Type: disabled
Surface Type: OpenGL
Surface Profile: NoProfile
Surface Version: 2.0
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: no

Init Parameters:
  *  application-name Anki 
  *  browser-subprocess-path /usr/local/share/anki/lib/PyQt6/Qt6/libexec/QtWebEngineProcess 
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-gpu  
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl disabled 
 
addons21/1463041493/main.py:34:json is deprecated: please implement your own
addons21/1463041493/config.py:16:json is deprecated: please implement your own
Starting main loop...
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
Qt warning: QRhiGles2: Failed to create temporary context 
Qt warning: QRhiGles2: Failed to create context 
Qt warning: Failed to create QRhi for QBackingStoreRhiSupport 
Qt warning: QRhiGles2: Failed to create temporary context 
Qt warning: QRhiGles2: Failed to create context 
Qt warning: Failed to create QRhi for QBackingStoreRhiSupport 
Qt warning: QQuickWidget: Failed to get a QRhi from the top-level widget's window 
Qt warning: QQuickWidget::resizeEvent() no QRhi 
Qt warning: QRhiGles2: Failed to create temporary context 
Qt warning: QRhiGles2: Failed to create context 
Qt warning: Failed to create QRhi for QBackingStoreRhiSupport 
Qt warning: QQuickWidget: Failed to get a QRhi from the top-level widget's window 
Qt warning: QRhiGles2: Failed to create temporary context 
Qt warning: QRhiGles2: Failed to create context 
Qt warning: Failed to create QRhi for QBackingStoreRhiSupport 
Qt warning: QQuickWidget: Failed to get a QRhi from the top-level widget's window 
Qt warning: QQuickWidget::resizeEvent() no QRhi 
Qt warning: QRhiGles2: Failed to create temporary context 
Qt warning: QRhiGles2: Failed to create context 
Qt warning: Failed to create QRhi for QBackingStoreRhiSupport 
Qt warning: QQuickWidget: Failed to get a QRhi from the top-level widget's window 
Qt warning: QRhiGles2: Failed to create temporary context 
Qt warning: QRhiGles2: Failed to create context 
Qt warning: Failed to create QRhi for QBackingStoreRhiSupport 
Qt warning: QQuickWidget: Failed to get a QRhi from the top-level widget's window 
Qt warning: QQuickWidget::resizeEvent() no QRhi 
Qt warning: QRhiGles2: Failed to create temporary context 
Qt warning: QRhiGles2: Failed to create context 
Qt warning: Failed to create QRhi for QBackingStoreRhiSupport 
Qt warning: QQuickWidget: Failed to get a QRhi from the top-level widget's window 
conf key imgocc should be fetched with col.get_config(), and saved with col.set_config()
conf key imgocc should be fetched with col.get_config(), and saved with col.set_config()
conf key imgocc should be fetched with col.get_config(), and saved with col.set_config()
conf key syntax_highlighting_conf should be fetched with col.get_config(), and saved with col.set_config()
addons21/1463041493/config.py:61:setMod() is deprecated: no longer required
Qt warning: QRhiGles2: Failed to create temporary context 
Qt warning: QRhiGles2: Failed to create context 
Qt warning: Failed to create QRhi for QBackingStoreRhiSupport 
Qt warning: QQuickWidget: Failed to get a QRhi from the top-level widget's window 
Qt warning: QQuickWidget::resizeEvent() no QRhi 
Qt warning: QRhiGles2: Failed to create temporary context 
Qt warning: QRhiGles2: Failed to create context 
Qt warning: Failed to create QRhi for QBackingStoreRhiSupport 
Qt warning: QQuickWidget: Failed to get a QRhi from the top-level widget's window 
Qt warning: QQuickWidget::resizeEvent() no QRhi 
Qt warning: QRhiGles2: Failed to create temporary context 
Qt warning: QRhiGles2: Failed to create context 
Qt warning: Failed to create QRhi for QBackingStoreRhiSupport 
Qt warning: QQuickWidget: Failed to get a QRhi from the top-level widget's window 
Qt warning: QQuickWidget::resizeEvent() no QRhi 
[1]    79639 segmentation fault (core dumped)  anki

**Comment by dae** [comment]
Please follow the steps on https://faqs.ankiweb.net/when-problems-occur.html
