### ISSUE TITLE
Preference "When adding, default to current deck" has confusing (or maybe buggy) UX

### ISSUE THREAD

**Issue by 64kramsystem** [ankitects/anki#2341]
The preference "When adding, default to current deck" has a confusing (or maybe buggy) UX; the "current" deck is assumed to be always the one in the "Decks" tab of the main window, which is not always the case.

Specifically, when adding cards via "Browse" window, the intuitive definition of "current" deck is the one selected in the tree panel; instead, the one selected in the "Decks" tab is used, which is unintuitive and error-prone, especially because that window is in the background.

**Comment by dae** [comment]
The sidebar is merely a shortcut for entering search terms, and has no effect on what Anki considers to be the current deck. I don't think this should change, and it would make no sense when in multi-select mode where you can select multiple decks or no decks. I'd be happy to accept a PR that tweaks the documentation to make this clear though.
