### ISSUE TITLE
Anki Desktop GUI broken on Windows 10

### ISSUE THREAD

**Issue by alchemiker** [ankitects/anki#2342]
Problem: Main screen is a flickering mess of stripes.

Steps to reproduce:
1. Download Anki for Windows 10/11 (2.1.56 Qt6) from https://apps.ankiweb.net/
2. Run installer
3. Select German as language; confirm.
4. Open Anki by newly created icon on desktop.

The result can be seen here in the screenshot:

<img width="503" alt="Screenshot Anki" src="https://user-images.githubusercontent.com/63516327/213934428-98fdac46-4a00-43c8-aff8-83ca3263cd66.png">

The Card editor is also messed up:

<img width="562" alt="Screenshot Anki1" src="https://user-images.githubusercontent.com/63516327/213934607-64134704-90ea-46cc-8fe7-ad9c23d230de.png">

The menus and separate windows like the settings-window look fine:

<img width="500" alt="Screenshot Anki2" src="https://user-images.githubusercontent.com/63516327/213934636-5e2a1c63-1547-4330-bbb3-ddc4f72b0879.png">

Restarting the program or the PC didn't help. 

PC info:
Device: Lenovo ThinkPad X27 Signature Edition
Processor: Intel(R) Core(TM) i5-7300U CPU @ 2.60 GHz 2.71 GHh
Installed RAM: 8.00 GB
64-Bit
Windows 10 Pro

If you need further information or testing, let me know!

**Comment by dae** [comment]
Please use the user forums for reporting issues in the future. This one is likely fixed by changing your video driver: https://docs.ankiweb.net/platform/windows/display-issues.html

**Comment by alchemiker** [comment]
@dae thank you very much! The command from the documentation page you sent me fixed the issue, even though I had to restart three times 😂 I consider this issue thereby as closed and will close it now with this comment. If I might run into issues in the future, I will ask in the forum. Thanks for your patience!
