### ISSUE TITLE
Possible to set new/hard multipliers to NoneType in scheduler v2 deck options

### ISSUE THREAD

**Issue by calumapplepie** [ankitects/anki#2353]
See title.

Image shows the setting:

![Screenshot from 2023-01-27 17-38-40](https://user-images.githubusercontent.com/13556193/215142714-52048745-1197-4a5e-88e4-ff224ad6971a.png)

If I then hit "save", it will retain the nonexistent setting, and will cause Anki to throw an error when I am reviewing and select the appropriate review interval. (EG, if I nullify the Hard Interval, then when next I hit "hard" when reviewing, Anki prints a stacktrace and blames an addon).

I discovered this bug accidentally; I didn't go around setting things to null, and it was a headache to triage.  I couldn't work out how the typescript interfaces with the system, so I don't know where to add the error checking.  The relevant mis-set variable is (probably) $config.lapseMultiplier in ts/deck-options/AdvancedOptions.svelte

**Comment by calumapplepie** [comment]
Stack trace from unsetting hard:
`Error An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. When you've discovered the add-on that is causing the problem, please report the issue to the add-on author. Debug info: Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0 Platform: Linux-6.1.0-1-amd64-x86_64-with-glibc2.36 Flags: frz=True ao=True sv=2 Add-ons, last update check: 2023-01-27 16:20:16  Caught exception: Traceback (most recent call last):   File "aqt.webview", line 562, in handler   File "aqt.reviewer", line 655, in _onTypedAnswer   File "aqt.reviewer", line 414, in _showAnswer   File "aqt.reviewer", line 710, in _showEaseButtons   File "aqt.reviewer", line 797, in _answerButtons   File "aqt.reviewer", line 783, in but   File "aqt.reviewer", line 806, in _buttonTime   File "anki.scheduler.v2", line 1149, in nextIvlStr   File "anki.scheduler.v2", line 1044, in nextIvl   File "anki.scheduler.v2", line 916, in _nextRevIvl TypeError: '>' not supported between instances of 'NoneType' and 'int'`

**Comment by calumapplepie** [comment]
Annnnd from unsetting "New interval" (which btw could use renaming in the UI)
```Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
Platform: Linux-6.1.0-1-amd64-x86_64-with-glibc2.36
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-01-27 16:20:16

Caught exception:
Traceback (most recent call last):
  File "aqt.reviewer", line 498, in <lambda>
  File "aqt.reviewer", line 456, in _answerCard
  File "anki.scheduler.v2", line 458, in answerCard
  File "anki.scheduler.v2", line 487, in _answerCard
  File "anki.scheduler.v2", line 840, in _answerRevCard
  File "anki.scheduler.v2", line 857, in _rescheduleLapse
  File "anki.scheduler.v2", line 589, in _moveToFirstStep
  File "anki.scheduler.v2", line 582, in _updateRevIvlOnFail
  File "anki.scheduler.v2", line 870, in _lapseIvl
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

**Comment by dae** [comment]
Thanks for identifying the cause of these errors. I think the UI used to ensure values were valid, but this seems to have been lost as the code got refactored. I'll push a fix shortly.
