### ISSUE TITLE
Anki has a deck that shows that the learning times are inconsistent with the learning plan.(I need help urgently)

### ISSUE THREAD

**Issue by Benjamin-Watson0** [ankitects/anki#2365]
I'm not a developer. Because Anki forum closed my account (I don't know why), I have to speak here.
I don't know why the display on the desktop is wrong, and the display of the android is correct.
I tried to uninstall and install the old version, but it was not resolved.
Both "new card" and "due card" are wrong.
I encountered the same problem in the Ankidroid beta a few weeks ago.
https://github.com/ankidroid/Anki-Android/issues/13091
It is interesting that the anki desktop was displayed correctly last time. 
The correct display this time is ankidroid
![Screenshot_20230205_180112](https://user-images.githubusercontent.com/112467275/216812699-5c598303-51a9-4258-bc03-9591bad8dd53.jpg)
![image](https://user-images.githubusercontent.com/112467275/216812764-22da8eeb-0d76-43fc-ad0d-d419a41574e0.png)
![image](https://user-images.githubusercontent.com/112467275/216812767-4363ce46-ecb7-4c68-a3d9-c8b7ffb4a1c4.png)

**Comment by dae** [comment]
Not sure why your account would be closed. If you're using an alpha version, please see https://forums.ankiweb.net/t/syncing-issue-between-ankiweb-and-mac/26374/5. If you're using a stable AnkiDroid release, please ensure that 'legacy timezone handling', is disabled, and report the issue on AnkiDroid's github issues if problems persist.

**Comment by Benjamin-Watson0** [comment]
This time the error is on the anki desktop. There is no problem with the version of ankidroid I am using.

**Comment by Benjamin-Watson0** [comment]
Do I provide enough information? Please let me know if you need it.

**Comment by dae** [comment]
The desktop version is generally considered "canonical", so if you force a one-way sync to AnkiWeb from AnkiDroid and AnkiWeb counts differ from AnkiDroid, that implies the problem is AnkiDroid.

**Comment by Benjamin-Watson0** [comment]
Yes, the number displayed on ankiweb is the same as that on ankiweb. However, my deck learning plan is to learn 50 cards. I remember that I have learned about 10 cards, and the remaining number should be 40. I tested other decks, and they all behaved normally. Only this deck I can't explain. I look forward to your reply.

**Comment by Benjamin-Watson0** [comment]
The "new card" and "due card" cannot be changed with the learning plan, only the deck called "四级乱序词汇".

**Comment by Benjamin-Watson0** [comment]
Is there a problem with the deck itself?😢

**Comment by Benjamin-Watson0** [comment]
> 不知道为什么您的帐户会被关闭。如果您使用的是 alpha 版本，请参阅 https://forums.ankiweb.net/t/syncing-issue-between-ankiweb-and-mac/26374/5。如果您使用的是稳定的 AnkiDroid 版本，请确保禁用“旧时区处理”，如果问题仍然存在，请在 AnkiDroid 的 github 问题上报告问题。

The title is not detailed enough. 
There is only one  different from Android.

**Comment by dae** [comment]
Please follow the steps in https://faqs.ankiweb.net/when-problems-occur.html. If the issue still exists after that, can you provide your AnkiWeb email address (not password) so I can try to reproduce the problem?

**Comment by Benjamin-Watson0** [comment]
I have tried but failed,.
My ***@***.***

________________________________
发件人: Damien Elmes ***@***.***>
发送时间: 2023年2月6日 8:39
收件人: ankitects/anki ***@***.***>
抄送: Benjamin Watson ***@***.***>; Author ***@***.***>
主题: Re: [ankitects/anki] Anki has a deck that shows that the learning times are inconsistent with the learning plan.(I need help urgently) (Issue #2365)


Please follow the steps in https://faqs.ankiweb.net/when-problems-occur.html<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffaqs.ankiweb.net%2Fwhen-problems-occur.html&data=05%7C01%7C%7Ca3e5e174566d448af69c08db07daa9bd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638112407968150120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Z6UFyYpUt27zgDQFIKvKy5ZP17HRZoFutSRAbjhi2V0%3D&reserved=0>. If the issue still exists after that, can you provide your AnkiWeb email address (not password) so I can try to reproduce the problem?

―

**Comment by dae** [comment]
You can fix this by enabling the v3 scheduler, opening the deck options, and changing the settings back to "preset". After saving, you can switch back to v2 if you like.

**Comment by Benjamin-Watson0** [comment]
It seems that I can only change in V3 mode and cannot change in V2 mode.
Is there a problem with what I did?

https://user-images.githubusercontent.com/112467275/216865738-0eb3e908-6dae-4bc2-b7aa-2d81f4aa421f.mp4

**Comment by Benjamin-Watson0** [comment]
Whether the learning quantity can only be changed in V3 mode, if V2 mode is used to learn cards.

**Comment by dae** [comment]
The v2 scheduler only supports 'preset'. Due to a bug, Anki was using your v3 settings even when you switched back to v2. You can fix the problem for now by changing to v3, switching back to 'preset', and then changing back to v2.
