### ISSUE TITLE
Request: Initiate sync from the command line (without GUI)

### ISSUE THREAD

**Issue by doozan** [ankitects/anki#2369]
Since 2.1.57+ can run as a headless sync server, is there also a way to run it as a headless sync client to pull data from ankiweb or from a custom sync server?

**Comment by dobefore** [comment]
This may suits you.
> You can run the server without installing the GUI portion of Anki provided you have a copy of Python3.9+ installed.

https://docs.ankiweb.net/sync-server.html#without-gui-dependencies

**Comment by dae** [comment]
Such a feature is not currently available. Please use the forums when posting feature requests.
