### ISSUE TITLE
Literal links in ts are unchecked

### ISSUE THREAD

**Issue by RumovZ** [ankitects/anki#2380]
There is a test to check for broken URLs, but it can only cover members of the HelpPage enum. For that reason, the new literal links in the ts code should be replaced.
To efficiently fetch URLs from the backend en masse, as is required for the deck options screen, I guess we also need a new RPC that returns (a map of) all available pages from the backend?

**Comment by RumovZ** [comment]
A bit less so I imagine, but neither should be hard. There would be some drawbacks, though, the main one probably that we would only be able to detect full URLs. It wouldn't work if someone factored out the domain name from the literal links, e.g.

**Comment by dae** [comment]
Hmm. What about implementing a separate HelpPage enum in a .ts file instead? Seems easier to define them on the .ts end than try to pass them through from the backend.

**Comment by RumovZ** [comment]
You mean we set up a file like `ts/lib/help-pages.ts` and then add a Rust test that explicitly greps that file?

**Comment by dae** [comment]
Yep, WDYT?
