### ISSUE TITLE
Anki fails to launch when `SIGCHLD` is set to `SIG_IGN`

### ISSUE THREAD

**Issue by pedrominicz** [ankitects/anki#2396]
Anki fails to launch when `SIGCHLD` is set to `SIG_IGN`.
```text
t$ cat test.c
#include <signal.h>
#include <unistd.h>

int main() {
        signal(SIGCHLD, SIG_IGN);

        execlp("anki", "anki", (char*)NULL);

        return 1;
}
t$ gcc test.c
t$ ./a.out
Anki starting...
...
[...:FATAL:credentials.cc(306)] Check failed: . : No child processes (10)
Trace/breakpoint trap (core dumped)
```
When `SIGCHLD` is set to `SIG_IGN`, child processes don't become (live) zombies (see https://lkml.iu.edu/hypermail/linux/kernel/9606.2/0080.html), causing [this assertion](https://chromium.googlesource.com/chromium/src/sandbox/+/refs/heads/main/linux/services/credentials.cc#306) to fail.

I am reporting this here because, surprisingly, this issue doesn't happen with Chromium. If this is, in fact, an issue with Chromium, please help me escalate it upstream because I am unsure where I should report it to.

**Comment by dae** [comment]
I suggest you start by trying to reproduce the issue with a different Qt app that uses qtwebengine
