### ISSUE TITLE
Revisit independent review card burying

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2397]
There have been a number of users posting how they miss independent review card burying (eg https://forums.ankiweb.net/t/option-to-bury-sibling-review-cards-without-burying-sibling-new-cards-on-ankimobile/27495), so we may need to revisit the decision in https://github.com/ankitects/anki/issues/2352, and see if we can't find some way of supporting this use case without making things much more complicated.

**Comment by RumovZ** [comment]
All participants in the forum discussion say they would already be satisfied if review cards buried other review cards. This shouldn't be much more complicated then the old code and it's probably the only solution this could be said about.

**Comment by dae** [comment]
Sounds reasonable to me - if you wouldn't mind looking into that, it would be appreciated.
