### ISSUE TITLE
Anki keeps crashing on start

### ISSUE THREAD

**Issue by Gravity2106** [ankitects/anki#2399]
I am on Linux Mint 21.1 Cinnamon and using the last version of Anki (anki-2.1.60-linux-qt6) installed through sudo ./install.sh.
It keeps crashing on start, sometimes with a white screen. I have reinstalled it several times. It works just before select the language.

`Anki starting...
Initial setup...
Running with temporary Qt5 compatibility shims.
Run with DISABLE_QT5_COMPAT=1 to confirm compatibility with Qt6.
Preparing to run...
Qt info: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.3
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: no

Init Parameters:
  *  application-name Anki 
  *  browser-subprocess-path /usr/local/share/anki/lib/PyQt6/Qt6/libexec/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 
 
Starting main loop...
mpv not found, reverting to mplayer
`
![image](https://user-images.githubusercontent.com/45825337/221355402-44c81da6-7040-4c2f-b464-383ea36d1146.png)

Thank you

**Comment by dae** [comment]
Changing to the software driver may help. https://docs.ankiweb.net/platform/linux/display-issues.html
