### ISSUE TITLE
Intervals not updating.

### ISSUE THREAD

**Issue by topherbuckley** [ankitects/anki#2407]
Anki: 2.1.60
OS: Ubuntu 22.04 (though I noted the same behavior in recent Ankidroid)

# Issue Summary

It seems my intervals are not being updated. 

I noticed that I've been reviewing similar cards for a LONG time and thought something might be wrong, so I setup a single note deck called "test" with a simple front/back pattern and reviewed ahead while monitoring the ease and interval along with my answer and stated interval above the "Good" button. 

It seems my cards get stuck at the 1 day intervals. Trying to figure out why. Here at my deck options:

|New Cards||
|---|---|
|Learning steps|1m 10m|
|Graduating interval|1|
|Easy interval|4|
|||
|Lapses||
|Relearning steps|10m|
|Minimum interval|1|
|||
|Advanced||
|Maximum interval|36500|
|Starting ease|2.5|
|Easy bonus|1.3|
|Interval modifier|1|
|Hard interval|1.2|
|New interval|0|

Here are the card stats as I progress through reviews:

|Due|Ease|Interval|Answer|Next Stated Interval (above Good)|Note|
|---|---|---|---|---|---|
|New #1000890|(new)|(new)|Good|10m||
|2023-02-28|0.00%|(learning)|Good|1d|How can this be 1d already!? |
|2023-03-01|250.00%|1 day|Good|1d||
|2023-03-01|250.00%|1 day|Good|1d||
|2023-03-01|250.00%|1 day||||

Two things seem strange. 

1. Why would it jump from 10m to 1d interval so fast? (I would expect 250%*10m)
2. It gets stuck at an interval of 1 day over and over. Why? 

Any ideas? I'm using the V2 scheduler as I'm mainly using Anki on AnkiDroid, but it was easier to test this on the desktop version to monitor the ease and interval.

Happy to build it from source and have a look with gdb (does that work with Rust projects?), but I'm not familiar with the innards of this project so would appreciate if someone could tell me a good breakpoint for inspecting the interval update process that occurs after hitting an answer button.

**Comment by topherbuckley** [comment]
Looking into this more, I realized two things:

1. It appears [Reviewing Ahead](https://docs.ankiweb.net/filtered-decks.html#reviewing-ahead) obeys different scheduling, so my "test" deck was not a good way to test this. 
2. In the desktop app card browser, I realized there is useful info shown by right clicking on the card and clicking "info..." about the historical answers, ease, and status of the card. One snippet from one card is shown below:

|Date|Type|Rating|Interval|Ease|Time|
|---|---|---|---|---|---|
|2023-03-01 @ 18:43|Review|3|⁨3⁩ days|130.00%|⁨1⁩m|
|2023-02-26 @ 07:56|Review|3|⁨3⁩ days|130.00%|⁨10.56⁩s|
|2023-02-23 @ 10:47|Review|3|⁨3⁩ days|130.00%|⁨2.66⁩s|
|2023-02-20 @ 07:14|Review|3|⁨3⁩ days|130.00%|⁨6.18⁩s|
|2023-02-17 @ 20:03|Review|3|⁨3⁩ days|130.00%|⁨43.54⁩s|
|2023-02-14 @ 07:49|Review|3|⁨3⁩ days|130.00%|⁨8.3⁩s|
|2023-02-10 @ 07:35|Review|3|⁨4⁩ days|130.00%|⁨8.52⁩s|
|2023-02-05 @ 14:43|Review|3|⁨5⁩ days|130.00%|⁨5.11⁩s|
|2023-01-29 @ 09:24|Review|3|⁨7⁩ days|130.00%|⁨9.45⁩s|
|2023-01-24 @ 10:10|Review|3|⁨5⁩ days|130.00%|⁨48.73⁩s|
|2023-01-21 @ 08:58|Review|3|⁨3⁩ days|130.00%|⁨14.41⁩s|
|2023-01-19 @ 09:36|Review|3|⁨2⁩ days|130.00%|⁨4.91⁩s|
|2023-01-18 @ 09:26|Relearn|3|⁨1⁩ day|130.00%|⁨35.76⁩s|
|2023-01-17 @ 10:47|Relearn|3|⁨1⁩ day|130.00%|⁨30.51⁩s|
|2023-01-16 @ 13:22|Relearn|3|⁨6⁩ hours|130.00%|⁨2.49⁩s|
|2023-01-16 @ 11:34|Relearn|3|⁨1⁩ hour|130.00%|⁨2.49⁩s|
|2023-01-16 @ 10:22|Relearn|1|⁨10⁩ minutes|130.00%|⁨6.64⁩s|
|2023-01-16 @ 10:11|Review|1|⁨10⁩ minutes|130.00%|⁨10.84⁩s|
|2022-12-28 @ 04:19|Review|3|⁨20⁩ days|145.00%|⁨6.64⁩s|
|2022-12-14 @ 09:46|Review|3|⁨13⁩ days|145.00%|⁨5.11⁩s|
|2022-12-07 @ 18:32|Review|2|⁨7⁩ days|145.00%|⁨7.28⁩s|
|2022-11-28 @ 08:58|Review|3|⁨9⁩ days|160.00%|⁨7.58⁩s|
|2022-11-24 @ 11:35|Review|3|⁨4⁩ days|160.00%|⁨4.22⁩s|
|2022-11-22 @ 08:25|Relearn|3|⁨1⁩ day|160.00%|⁨4.8⁩s|

As you can see, from 2022-11-22 @ 08:25 up to 2023-01-29 @ 09:24 it appears normal with reseting on relearn as expected, and increasing intervals with "good" or "3 Rating". Then on 2023-02-05 @ 14:43 something weird happens. I answer Good/3 Rating, but the interval decreases from 7 days to 5 days. 

My guess so far is that sometime between 2023-01-29 @ 09:24 and 2023-02-05 @ 14:43 I changed the deck settings. More specifically, I think I increased the maximum intervals on the New Cards and Lapses. I can't recall exactly, but based on the history from "info..." I'd guess I had Relearning steps of 10m, 1h, 6h, 1d. Sometime between 2023-01-29 @ 09:24 and 2023-02-05 @ 14:43 I changed the Relearning steps to 10m 1h 6h 1d 2d 5d 10d 18d. Now what I think might be happening is that this 7 day interval at 2023-01-29 @ 09:24 is less than the maximum relearning step, or learning steps for new cards (identical intervals btw). Now I guess there is some logic within Anki that is bugging out at this. i.e. some unforeseen state is occurring and the logic responsible for updating the interval is spitting out nonsense. Why it settles from 7 days, 5 days, 4 days, then stays on 3 days is beyond me. I'd have to find this in the code to say more. Any help pointing me towards this interval update logic is appreciated!

Also just wanted to link to the [anki forum](https://forums.ankiweb.net/t/anki-scheduler-broken/27987/4) where I am also bringing up this issue.

**Comment by dae** [comment]
Let's continue this on your forum post; that's the best place to ask for help.

**Comment by topherbuckley** [comment]
It appears the proposed fix for this was provided [here](https://github.com/ankitects/anki/commit/4a053e5f883a0e05acf461beb4d3d8e3f535cd7b#) though I have left a comment in that commit as to why that doesn't seem like the best method for fixing this.
