### ISSUE TITLE
Where to store user background images?

### ISSUE THREAD

**Issue by kleinerpirat** [ankitects/anki#2424]
As you know, I'm currently working on a background setting for Anki Desktop. I got the mechanics down, but I'm not sure where to store background images.

The images need to be accessible to all webviews.

My WIP uses `collection.media`, but that was just so I could test the new feature easier. One advantage of the media folder is that it's synced, so other clients could also use the background. The disadvantage is the mass of unrelated images in the folder (although one could filter the file dialog to a certain prefix).

Would you prefer a separate folder in the profile directory?

**Comment by niuggg** [comment]
good
