### ISSUE TITLE
Update TypeScript Version

### ISSUE THREAD

**Issue by andrewpeters9** [ankitects/anki#2431]
**Why:**
* Current TS version used in Anki is approx. 2 years old
* Migrating from `4.4` → `4.9` would allow for stricter types, new functionality etc. and a generally more future-proof codebase

Happy to open up an MR for this myself if this is approved.

**Comment by dae** [comment]
Hi Andrew,

I think we're actually using 4.8.4 in the lock file, and it's just the package.json that is out of date. I tend to try to bunch dependency updates together, so I'd prefer to hold off on this until the next release is out the door (which is hopefully not far off). TS5.0 should be out at that point too. Will leave this open as a reminder.

**Comment by andrewpeters9** [comment]
Closing as resolved in latest updated.
