### ISSUE TITLE
Adding a Deck Selector to Statistics Page

### ISSUE THREAD

**Issue by yellowjello** [ankitects/anki#2434]
## Issue:
Right now, it is pretty awkward to switch the deck being used for the Statistics page.

From what I can tell, there are currently two ways to switch the deck, both of which are awkward:
1. Close the statistics page, click on the deck in the main screen, then open stats again.
2. Typing in the deck name as part of a search query. This is especially awkward if the deck name is very long.

## Proposed Solution:
We can add in a deck selector to the statistics page to make it quick and easy to switch decks.

To kickstart the discussion, I have made rough mock-ups for some UI layout options we can potentially chose.

### Option 1: Add new option in existing UI
<img width="800" alt="Screenshot 2023-03-10 at 5 28 39 PM" src="https://user-images.githubusercontent.com/5134058/224517724-5a78fbfc-5fc7-470b-bc17-3d35f5f33f97.png">

With this option, we show the deck selector when the "deck" option is selected and hide the search bar. The search bar comes back when the new "custom" option is selected.

### Option 2: Simplified UI
<img width="800" alt="Screenshot 2023-03-10 at 5 31 50 PM" src="https://user-images.githubusercontent.com/5134058/224517809-7c5959c4-3d43-4fb2-93ad-353d4e1d0644.png">

With this option, we just have the deck selector and the search bar. The deck selector will have a "Whole Collection" option for seeing stats and searching across all decks.

The search bar will be used to add additional filter options for the selected deck/collection.

**Comment by dae** [comment]
This screen needs to work on narrow screen phones as well, and the current deck/collection/search already take up the majority of the width, so if changing the layout, we'll need to try avoid making things wider. Your second screenshot looks nice, but unfortunately means switching between deck/collection is now two clicks instead of one. 

Another option would be to put the deck selector in the bottom with the Save PDF/Close buttons, where there is extra space.

**Comment by yellowjello** [comment]
> Your second screenshot looks nice, but unfortunately means switching between deck/collection is now two clicks instead of one.

Yeah that is a bit unfortunate and we should definitely look into ways to retain the 1-click access to the whole collection. But in the event that we can't find a way (without it being too awkward), how bad would the extra click be if it saves several clicks in the deck changing scenario?

> This screen needs to work on narrow screen phones as well

A thing we can potentially explore is having a flexible layout that can re-flow depending on the screen size, which is the approach taken by modern responsive webpages. Are we open to the possibility of having an extra row vertical space used when on mobile?

**Comment by giselaortt** [comment]
is anybody working on this issue ?
i plan trying if no one is.

**Comment by yellowjello** [comment]
> is anybody working on this issue ?
i plan trying if no one is.

I was thinking of chipping away at this issue in my spare time (1-2 hours/week), so it might end up taking a few weeks. I guess if you have the time, you can take this on instead of me.

> The way AnkiMobile does this is to make the deck name visible at the top of the window

I was thinking of putting the deck selector in the webview at first so that desktop and AnkiDroid would get it. But if AnkiMobile is doing something else, it would make sense to follow its approach and put the deck selector in the "wrapper" UI.

I guess I'll need to start an issue in AnkiDroid regarding this.

Question regarding implementation: does AnkiMobile implement deck selection by changing the current deck or does it do it by changing the search query (or something else)?

I've also did some quick prototyping with the deck selector in the bottom bar.

Here is the deck selector in the default centred layout:
<img width="699" alt="Screenshot 2023-03-25 at 1 42 37 AM" src="https://user-images.githubusercontent.com/5134058/227753869-90a0c34f-d9e7-4ef2-868b-f96df09418f3.png">

I thought it looked a bit weird, so I also tried a left and right aligned version, which I think works a bit better:
<img width="699" alt="Screenshot 2023-03-25 at 1 41 04 AM" src="https://user-images.githubusercontent.com/5134058/227753905-7bf2cffb-b2a3-469e-9f51-653172f6323a.png">

**Comment by dae** [comment]
The bottom layout looks better, but the button alignment is probably fixable too - have you wrapped the label and button on the left in a hbox? If so, adjusting the margins of the hbox may help.

AnkiMobile changes the current deck, then reloads the page, which ensures the current deck is shown even if the user was previously looking at the collection.
