### ISSUE TITLE
Linux: Default (fallback) input device not used; new stream always created

### ISSUE THREAD

**Issue by cammytown** [ankitects/anki#2438]
My microphone is very noisy, so I must use a noise suppression software/filter on it (i.e. NoiseTorch). This creates a new input in PulseAudio, which I then set as the default/fallback device.

![image](https://user-images.githubusercontent.com/735509/225104948-331aed24-3bde-42e1-bd13-694333064255.png)

However, Anki doesn't use it despite being set as the default device.

Additionally, if I then go into pavucontrol and edit the input device manually:

![image](https://user-images.githubusercontent.com/735509/225104069-571fdce5-3507-486a-a3a1-ebd11b0ccda4.png)

It does not hold, as it seems Anki creates a new audio stream with a different ID/name each time through QT, which pulse audio interprets as having separate config:

![image](https://user-images.githubusercontent.com/735509/225105309-2ea8946b-6b51-4215-845c-b261f4780795.png)
![image](https://user-images.githubusercontent.com/735509/225105350-746736ad-fb35-4f47-9f85-2e0a185be418.png)

(Note the string of numbers QtmPulseStream-84594-xxxxxxxxx)

Thus, I cannot change the audio device Anki uses through any means known to me or my internet search.

Cheers.

**Comment by PetrVladimirov** [comment]
Same here, I would love to have an option to use the default/fallback device instead.

**Comment by dae** [comment]
IIRC recording did not change on Anki's end since .54, so it's possible this is a change in Qt. Have you tried the Qt5 version?

**Comment by PetrVladimirov** [comment]
> IIRC recording did not change on Anki's end since .54, so it's possible this is a change in Qt. Have you tried the Qt5 version?

.54 works perfectly on Qt6 (tested on Debian 11 and Fedora 36). 

Here is a snippet from Anki (Debian 11) => About:
```
    Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1
    Platform: Linux
    Flags: frz=True ao=True sv=2

```

Thank you for your attention! Please let me know if you need any other info.

**Comment by dae** [comment]
What happens when you use 2.1.65-qt5?

**Comment by PetrVladimirov** [comment]
> What happens when you use 2.1.65-qt5?
    
```
    Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
    Platform: Linux-5.15.103-1 with-glibc2.31
    Flags: frz=True ao=True sv=2
```
    
![image](https://github.com/ankitects/anki/assets/35421649/df8295d1-b173-4110-925e-d3f7a0a85be4)

**Comment by PetrVladimirov** [comment]
> IIRC recording did not change on Anki's end since .54
I've noticed that the focus in .65 within IIRC recording window is on "cancel" and in .54 it is on "save" buttons respectively. So at least in this part someone might have changed something...

**Comment by dae** [comment]
What happens when you install the missing library mentioned in the error?

**Comment by PetrVladimirov** [comment]
> What happens when you install the missing library mentioned in the error?

Thanks, with `libpulse-mainloop-glib0` installed, voice recording works in .65 under Qt5 in Debian!

Any idea on what can be done to make it work under Qt6?

**Comment by dae** [comment]
'fraid not - it looks like Qt have changed the way they handle recording.

**Comment by PetrVladimirov** [comment]
> 'fraid not - it looks like Qt have changed the way they handle recording.

Can we somehow report it to a Qt bug tracker?

**Comment by dae** [comment]
You would need to reproduce the issue in one of the Qt sample apps to demonstrate the problem to them. That involves downloading Qt and building the relevant sample app, and is somewhat involved.

**Comment by dae** [comment]
If you wish to follow it up, please see https://github.com/ankitects/anki/issues/2652
