### ISSUE TITLE
"Hourly Breakdown" percentage axis is always 0-100%, even if maximum percentage is less

### ISSUE THREAD

**Issue by LukeLR** [ankitects/anki#2444]
In the "Hourly Breakdown" graph on the stats page, the percentage axis seems to be always scaled from 0-100%, even if the maximum par height is less than 100%. See the following example, where the maximum percentage is around 76%, but the axis on the right hand side of the graph shows it as 100%.

![image](https://user-images.githubusercontent.com/3177243/225586989-3dace60f-f378-42a8-8ea1-16fc24c985ea.png)

Possible solutions:

1. Adjust the upper limit of the percentage axis to the maximum percentage among the bars
2. Scale all bars down accordingly to a 100% maximum

Versions in use:
Anki Version ⁨2.1.60 (76d88073)⁩
Python 3.10.10 Qt 6.4.2 PyQt 6.4.2

**Comment by dae** [comment]
Please let me know your AnkiWeb ID privately (https://anki.tenderapp.com/dashboard/discussions) and the deck in question so I can use your collection to reproduce the issue.

**Comment by LukeLR** [comment]
This can be reproduced with a single card and a single review session. 
See the following backup of a profile containing just that minimal 
example attached.

**Comment by LukeLR** [comment]
This can be reproduced with a single card and a single review session. See the following backup of a profile containing just that minimal example attached.
[backup-2023-03-17-08.08.38.colpkg.zip](https://github.com/ankitects/anki/files/10998739/backup-2023-03-17-08.08.38.colpkg.zip)

**Comment by dae** [comment]
Thanks Luke, that's helpful.

**Comment by RumovZ** [comment]
Isn't this working as intended? The left y axis is for the bars (total number of reviews), the right one is for the

**Comment by RumovZ** [comment]
Isn't this working as intended? The left y axis is for the bar (total number of reviews), the right one for the line graph (percentage of correct answers).

**Comment by LukeLR** [comment]
You may be right. If it is really meant to be that way, then it's probably not a bug, just "misleading". One way or the other, it probably wouldn't hurt to not only scale the bars according to the absolute scale, but also to the relative scale, or maybe add a legend that mentions that the bars don't match the right axis.

**Comment by RumovZ** [comment]
> not only scale the bars according to the absolute scale, but also to the relative scale

There are two graphs in this chart. It's not possible to convey the same information in a single one. Am I misunderstanding what you're saying?

I think ideally the charts should speak for themselves without requiring a legend. Maybe one could style the y axes in such a way that it's more obvious which graph they belong to. E.g. the left one could have a blue tint, or it could be highlighted if a bar is hovered and the right one if the line graph is hovered.

**Comment by LukeLR** [comment]
What I mean is: a full bar always means 100%, so lower percentages all across the board actually lead to smaller bars. That way, it's conceivable on the first look how good your learning is across the day. And by scaling the absolute axis accordingly, you could still keep that absolute information in the same graph.

But of course, coloring the axes according to the meaning would also work, so one can understand first look that the bars don't match the percentages.

**Comment by dae** [comment]
> Isn't this working as intended?

Indeed - sorry, I'm surprised I missed that. :sweat:

**Comment by LukeLR** [comment]
But it's still misleading, isn't it? Seeing bars and a scale percentage that don't corespondent to each other?

**Comment by LukeLR** [comment]
I mean, that you missed it as well probably underlines that it's misleading somehow?

**Comment by dae** [comment]
The fact that I was sleepy and trying to get through issue triage as quickly as possible probably played a part. A lot of the Anki graphs have two y axes so they can convey more data at once. The hover tooltips are partly there so you can deduce what the bar and line are conveying. There is room for improvement, and Rumo's suggestion of coloring one of the axes to make things clearer sounds like it's worth considering.

**Comment by avighnac** [comment]
@lukawarren You’re right, it is a bit confusing and misleading.

**Comment by RumovZ** [comment]
I had a brief look and am not convinced many people would pick up on the colour coded labels, unless the CSS would be reworked more drastically.
Maybe adding something like 📈 and 📊 to the axes would be clearer?

**Comment by LukeLR** [comment]
I think, the main difference with this plot compared to the other ones is that the other plots either use only one axis, or both axes are absolute values just differently scaled, so it isn't possible that both axes apply to the bars. In this case, however, one axis is absolute and one relative values, therefore it would be meaningful if both applied to the bars.

I think any solution to make this clear would be fine. Personally, I'd prefer to scale the bars down so they match the relative scale, but if there are reasons against this, I think any other solution would do as well.

At least that's my opinion :)

**Comment by dae** [comment]
What do you think about adding those emoji to the tooltip instead of the graph, to keep the graph a bit cleaner?

**Comment by LukeLR** [comment]
Sounds like a good idea to me as well!

**Comment by RumovZ** [comment]
> I'd prefer to scale the bars down so they match the relative scale, 

This still doesn't make any sense to me. If I have a maximum of 1000 reviews at 8 o'clock with a success rate of 80%, sure I could scale the bars down so this particular one only has a height of 80% instead of 100%. Now for _this single bar_ both graphs coincide. But why should I waste any space to comply with this arbitrary constraint?
If anything, it could make the mistake of applying the right axis to the bar graph more likely.

> What do you think about adding those emoji to the tooltip instead of the graph, to keep the graph a bit cleaner?

👍

**Comment by LukeLR** [comment]
Not just the single bar, but all bars. The space wasted is minimal (probably all bars are scaled down by around 20%) but the graph will contain more information, as I won't only know how many (1000) reviews were successful, but also that I was able to review 80% of the cards correctly, which is the even more interesting figure in my eyes.

**Comment by RumovZ** [comment]
I'm totally lost. How can scaling down all bars by a constant amount increase the amount of conveyed information?

> also that I was able to review 80% of the cards correctly

That's what the line graph is showing, isn't it?

**Comment by RumovZ** [comment]
This only appears to work because you keep looking at a single data point. Say in your example you also have 8 out of 10 correct reviews at 5 o'clock. The corresponding bar could either be as high as the 8 o'clock bar to depict the correct percentage, or it could be 1/100 of its height to depict the total number of correct reviews. It cannot be both.
In other words, the data is 3-dimensional and it's mathematically impossible to illustrate it with a single 2-dimensional graph.

And by the way, the current bar graph shows the total number of reviews, not of successful reviews.

**Comment by LukeLR** [comment]
I think, any of the other solutions like adding emojis to the tooltip or coloring the axes would work as well. Maybe it's easier if we settle for any of these?
