### ISSUE TITLE
Anki can not save long-time cookie on Mac PC client 

### ISSUE THREAD

**Issue by i-cooltea** [ankitects/anki#2468]
I attempted to save my persistent data by using cookies and set the expiration time of the cookies to a few days, but when I restart my anki, the cookies will be deleted. This issue occurred on the Mac anki client, but was not found on the ankidroid.

This is my environmental information:
```
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-10.15.7-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-04-11 22:35:42
```

This is the code I used to set cookies
```
export interface CookieOptions {
  expires?: Date;
  path?: string;
  domain?: string;
  secure?: boolean;
  sameSite?: 'strict' | 'lax' | 'none';
}

const setCookie = function(name: string, value: string, options?: CookieOptions) {
  let cookieStr = `${encodeURIComponent(name)}=${encodeURIComponent(value)};`;

  if (options) {
    if (options.expires) {
      cookieStr += `expires=${options.expires.toUTCString()};`;
    }
    if (options.path) {
      cookieStr += `path=${options.path};`;
    }
    if (options.domain) {
      cookieStr += `domain=${options.domain};`;
    }
    if (options.secure) {
      cookieStr += `secure;`;
    }
    if (options.sameSite) {
      cookieStr += `sameSite=${options.sameSite};`;
    }
  }

  document.cookie = cookieStr;
};

const getCookie = function(name: string): string | null {
  const cookieArr = document.cookie.split('; ');
  for (let i = 0; i < cookieArr.length; i++) {
    const [cookieName, cookieValue] = cookieArr[i].split('=');
    if (decodeURIComponent(cookieName) === name) {
      return decodeURIComponent(cookieValue);
    }
  }
  return null;
};

const removeCookie = function(name: string) {
  setCookie(name, '', { expires: new Date(0) });
};

// @ts-ignore
export { setCookie, getCookie, removeCookie };

```

**Comment by i-cooltea** [comment]
I found that the port numbers of the addresses are different (one address accessed each time Anki starts), so the cookies are stored in different places. Is there any solution to this problem?

**Comment by i-cooltea** [comment]
Currently, every time the Anki client is restarted, the webview port number changes, resulting in inconsistent data locations stored and retrieved through localStorage. I am wondering if we should fix the webview port number in Anki for Mac, and for what purpose is this port number randomly generated? If the port number cannot be fixed, can Anki provide a persistence storage tool and retrieve data when restarting.
I would greatly appreciate it if you could give me a helping hand.

**Comment by dae** [comment]
The port is automatically assigned because a static one may be in use by another program. Cookies are not something Anki tries to support at the moment; I will move your original post to the Suggestions area of the forum to consider for some future release.

**Comment by i-cooltea** [comment]
Thank you for taking my opinion, 😊 
but I think it should not support cookies, 
but support data persistence (data will not disappear after software restart, 
and it is better to be a cross platform solution).

**Comment by connwork** [comment]
I was struggling with this issue for quite some time. I found that there was no way to save data set by js in the card template that would persist after closing and reopening anki. I made an addon to solve this that essentially exports selected localstorage values in an array to the media folder as a js file, which is then reimported and loaded back into localstorage after anki restart. You can see it here if you are interested: https://ankiweb.net/shared/info/92595818

**Comment by Vilhelm-Ian** [comment]
I require this feature for a note type I am creating. It would allow the user to save preferences.
