### ISSUE TITLE
Occlusions are misplaced at larger window sizes

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2492]
The attached demo.png contains two small squares. If I create occlusions over each of them, they display correctly at smaller window sizes, but as the window size grows, they start to become misaligned.

@krmanik heads up

<img width="621" alt="Screenshot 2023-05-10 at 1 00 00 pm" src="https://github.com/ankitects/anki/assets/180542/f22d17c0-b405-40dc-96fd-33d08fa61584">
<img width="2103" alt="Screenshot 2023-05-10 at 1 00 37 pm" src="https://github.com/ankitects/anki/assets/180542/1c6bed01-55ea-4b7b-862f-9480025a3be2">

![demo](https://github.com/ankitects/anki/assets/180542/ba824699-3d35-4c74-a19e-50c880c31373)

**Comment by krmanik** [comment]
I check the issues and fix it.

**Comment by krmanik** [comment]
I'm sorry, I didn't get time to implement, still busy.

Thanks

**Comment by dae** [comment]
No worries, I assumed as much - your studies take priority :-)
