### ISSUE TITLE
rslib: how can I update a note?

### ISSUE THREAD

**Issue by joelkoen** [ankitects/anki#2494]
Hi, I'm trying to update some notes with a Rust program I'm writing. I've got adding notes working, but I'm still pretty new to Rust and am a little confused why [this update_notes function](https://github.com/ankitects/anki/blob/802f10ea13f3e154772f5b75255c09f933f3f30a/rslib/src/notes/mod.rs#L354) isn't public. Is there a better way to update a note, or should there be a public function here?

**Comment by dae** [comment]
You're right, it should be public. Generally speaking, if you find a public method exposed in src/backend/* that isn't also a public Collection method, a PR to make it public would be welcome. In this case the cfg(test) tag will also need to be dropped.
