### ISSUE TITLE
Decks aren't displayed in the correct order when we combine alphabets and numbers

### ISSUE THREAD

**Issue by mostafasaleh1** [ankitects/anki#2504]
i'm using anki Version ⁨2.1.60 (76d88073)⁩, Python 3.9.15 Qt 6.4.2 PyQt 6.4.0. when i create decks showing as shown in the following photos, they don't get organised in the correct order. Especially with teen numbers always precede numbers single-digit numbers.

![image](https://github.com/ankitects/anki/assets/59813937/922124ad-9de7-4fb9-a1d7-9a16c54c936c)

![image](https://github.com/ankitects/anki/assets/59813937/3aa19589-99ad-4841-816a-5850c56d95aa)

**Comment by dae** [comment]
I've added a note about this on https://docs.ankiweb.net/getting-started.html#decks. If you have any further questions, please post them on the user forums.
