### ISSUE TITLE
While adding new cards, Anki keeps crashing, and reinstalling the latest version (anki-2.1.64-mac-intel- gt6) of Anki or restarting the computer does not help. No other program on my mac is affected. Of all my add-ons "Searching PDF Reading Note-Taking in Add Dialog" is producing a bug when enabled, while all other add-ons are disabled. The crash happens mostly, but not only, when the content on a field is deleted, while adding new cards...Kind regards Miles

### ISSUE THREAD

**Issue by Lugromiles** [ankitects/anki#2517]
- Have a question or feature suggestion?
- Problems building/running on your system?
- Not 100% sure you've found a bug?

If so, please post on https://forums.ankiweb.net/ instead. This issue tracker is
intended primarily to track development tasks, and it is easier to provide support
over on the forums. Please make sure you read the following pages before
you post there:

- https://faqs.ankiweb.net/when-problems-occur.html
- https://faqs.ankiweb.net/getting-help.html

If you post questions, suggestions, or vague bug reports here, please do not be
offended if we close your ticket without replying. If in doubt, please post on
https://forums.ankiweb.net/ instead.

**Comment by dae** [comment]
https://forums.ankiweb.net/t/desktop-mac-version-keeps-crashing-and-crashing/30553
