### ISSUE TITLE
Systemwide installations broken

### ISSUE THREAD

**Issue by MutonUfoAI** [ankitects/anki#2519]
Patch
[c49ea40ddf9440343edb684ae227708fe81c4f09](https://github.com/ankitects/anki/commit/c49ea40ddf9440343edb684ae227708fe81c4f09)
broke system wide installations
Please implement [MultiUser.nsh](http://nsis.sourceforge.net/Docs/MultiUser/Readme.html) to install this software for all users
thank you

**Comment by dae** [comment]
If you know of a way to support multi-user installs without showing an admin UAC pop-up when the user has selected to install for their local user, a clean PR would be welcome.

**Comment by dae** [comment]
Closing for now, but a PR would be welcome if someone figures it out.
