### ISSUE TITLE
<class 'TypeError'>: setValue(self, int): argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by Ametuer** [ankitects/anki#2534]
When trying to open preferences on Anki Linux Desktop: I got this error

Error 
An error occurred. Please use Tools > Check Database to see if that fixes the problem. 
If problems persist, please report the problem on our support site. Please copy and paste the information below into your report.
Anki 2.1.15 (442df9d6) Python 3.10.6 Qt 5.15.3 PyQt 5.15.6
Platform: Linux
Flags: frz=False ao=False sv=1

Caught exception:
  File "/usr/share/anki/aqt/main.py", line 882, in onPrefs
    aqt.dialogs.open("Preferences", self)
  File "/usr/share/anki/aqt/__init__.py", line 82, in open
    instance = creator(*args)
  File "/usr/share/anki/aqt/preferences.py", line 25, in __init__
    self.setupCollection()
  File "/usr/share/anki/aqt/preferences.py", line 80, in setupCollection
    f.lrnCutoff.setValue(qc['collapseTime']/60.0)
<class 'TypeError'>: setValue(self, int): argument 1 has unexpected type 'float'

Tools > Check Database did not fix the problem. Seems like a python bug

**Comment by dae** [comment]
Please see https://docs.ankiweb.net/platform/linux/distro-packages.html
