### ISSUE TITLE
Weekdays difficult to read in Chinese stats

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2535]
The 1/2/3 hanzi blend together. Reducing the font size for the labels for just that locale may help to make them a bit more legible.

You can test with './run -l zh_CN'

**Comment by chrissy0** [comment]
Could you clarify this? For me it looks like this:
<img width="309" alt="weekdays" src="https://github.com/ankitects/anki/assets/44864267/89eabbf3-b9df-4fdf-95f6-1568bb70b8ef">
I don't speak Chinese but from my limited knowledge of Chinese characters, 日 means "day" and should not be next to a row, but rather above the numbers. The lower characters represent 1-6, but 7 (七) is missing.

Is this an unrelated issue?

**Comment by dae** [comment]
The person who reported the issue to me said it was difficult to distinct Mon-Wed as separate characters, as all the horizontal lines blend together.

**Comment by git9527** [comment]
In Chinese, Mon (一), Tue (二), Wed(三) are all assembled by horizontal lines. If you look vertically, people might take Mon (一) and Tue (二) into a character with three lines, which will make confusing with Wed(三) . I think this is the original idea of the person who reported

**Comment by chrissy0** [comment]
Hey @git9527,

thanks for your input! My original confusion was the phrasing "blend together", which sounded like overlapping characters to me. Since this is not the case, I thought I was looking in the wrong place. Now it's clear though :)

**Comment by adeleke5140** [comment]
Hi, I've got frontend skill and would like to tackle this issue. is there a contributing guide I can checkout?

**Comment by adeleke5140** [comment]
@git9527 and @dae I would like to second @chrissy0 observation.

I know basic japanese and the first character 日 means day. The rest of the character go from 1 - 6 but there is an absence of 7 七(nana).

[source](https://jisho.org/word/%E6%97%A5)

**Comment by dae** [comment]
You're welcome to have a go. The language should be accessible via i18n/utils.ts:langs

**Comment by adeleke5140** [comment]
Thanks.

**Comment by mmjang** [comment]
As a native Chinese speaker, the readability is good enough for me. I tried set the font smaller, don't see any major improvements : /

<img width="441" alt="image" src="https://github.com/ankitects/anki/assets/5045203/cd6103a5-a720-4b7a-9120-1214c7eeb208">

**Comment by adeleke5140** [comment]
Glad to see this fixed. Tried to make the change but couldn't get the final part of the puzzle. 

Would keep looking to see if I can make other contributions.
