### ISSUE TITLE
Silent uninstall of Anki no longer possible on Windows

### ISSUE THREAD

**Issue by superusercode** [ankitects/anki#2541]
Documented in https://github.com/microsoft/winget-pkgs/issues/109046#issuecomment-1578281688 , using the nullsoft silent flags does not hide the anki uninstall prompt and prevents updating anki through winget.

> The installer itself requests for an uninstall once it detects a previous version in the system but the uninstall is not unattended/silent. Even if we include UpgradeBehavior: uninstallPrevious in the manifest, it does not resolve the issue. You can confirm this by using the --uninstall-previous experimental arg in the current preview version of WinGet, which has the same effect as UpgradeBehavior: uninstallPrevious in the manifest.
> Are there are any command line switches that can bypass the interactive prompts during the uninstall? If so we can add them in the manifest and make the uninstall silent. But even if that's resolved, it seems the uninstaller returns a success code even though the package isn't uninstalled completely that signals WinGet to proceed with the installation process. I believe the issue should be raised up to the publisher for a fix.
> ![image](https://github.com/ankitects/anki/assets/60588434/85f88550-470b-474d-b18c-f5bba13fa6b0)

**Comment by dae** [comment]
This only needs to happen once (we're migrating from system-wide install to single-user install), and the uninstaller program is from the old version, so it's not easy for us to retroactively update it.
