### ISSUE TITLE
Consider a way to propagate comments to our public API

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2548]
Re: https://github.com/ankitects/anki/commit/81ac5a91ad89a511eed35eb0607b7efe407e9e82

Currently there are multiple places where public methods can be documented: in the proto file's service definition, in the request/response messages, in the public rs method, in the Backend impl in Rust, in the collection.py public method which delegates to the backend, and in the Python backend impl. This somewhat discourages documentation, as there's a good chance our comments won't be seen by the people who need them.

The linked patch ensures the comments on the method definitions at least make it to the backend impls, and the request/response messages already had their documentation preserved. That leaves the public methods in collection.py and rslib.

To get the proto comments to our public methods, I can think of two approaches:

- Linking to them in the comments. Eg maybe_backup() in Rust could include as part of the docstring:

```
    /// See also [anki_proto::collection::collection_service::Service::create_backup]
```

If you hover over maybe_backup(), the doc shows a clickable link, and in IntelliJ, the link can be clicked to see the docs of the backend method. This doesn't seem to work for me though in VSCode.

An advantage of doing it this way is that we don't need to keep the comments in the different languages identical. The Rust methods may want to mention things that only apply in Rust for example.

The downside is it's a bit unwieldy, and it doesn't seem to be supported for Python - neither VSCode or IntelliJ appear to support links to functions.

- Another approach would be to have some script to automatically copy comments into our .rs/.py source code. We probably would need to delimit it eg ("from .proto:\n...\nend .proto:"), so that we can add other comments as well, without them being lost. 

We'd need to figure out how to deal with methods that don't have exactly matching names, eg create_backup -> maybe_backup. Maybe just rename for consistency?

Downsides would be the worked required to implement this, the slightly-increased repo size, and lost work if one accidentally edits the text inside the block instead of the proto.

@RumovZ and any other onlookers - do you have any thoughts?

**Comment by RumovZ** [comment]
Since there isn't really a 1-to-1 relationship between pub functions and RPCs, I wonder if it's possible or even desirable to try to automatically link one to the other?

Markup links in VSC work for me:

![grafik](https://github.com/ankitects/anki/assets/48286681/fe3aae62-c066-465b-9aa4-05880396eff2)

Of course, the Python LSP is quite lacking compared to Rust Analyzer. An alternative would be to use a documentation tool like Sphinx, which supports links in the generated HTML. However, since that still doesn't help with inline documentation, I'm not sure it would be worth it.

**Comment by dae** [comment]
I agree about Sphinx not seeming worth it, and you're right about there not being a 1:1 match - maybe I should give up on the copying idea and hope that linking improves in Python in the future. :-)
