### ISSUE TITLE
Update PyQt6-WebEngine

### ISSUE THREAD

**Issue by nihil-admirari** [ankitects/anki#2553]
Anki installed from pip comes with WebEngine based on Chrome 108. Provided binaries, however, come with Chrome 102.

I'm primary interested in `:has`, which is available since [Chrome 105](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility), but I guess a number of security issues was fixed as well.

**Comment by dae** [comment]
We use different Qt versions of different platforms, due to platform-specific bugs. An upgrade may come in the future if those bugs are resolved.

**Comment by nihil-admirari** [comment]
2.1.66 was released with Chromium 108.0.5359.220, which is the same Chromium one gets from pip. Apparently the issue is resolved.

**Comment by nihil-admirari** [comment]
WebEngine was updated to 6.6.0 (Chrome 112) bringing in a support for CSS nesting. Any chance of an update?

**Comment by dae** [comment]
Already done in 23.10.1rc.
