### ISSUE TITLE
Unable to save Fields dialog if all existing fields are deleted

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2556]
https://forums.ankiweb.net/t/bug-unrecoverable-state-when-modifying-card-type/31440

**Comment by dae** [comment]
> However I’m not sure what would be the desired solution.

Me either :-)

> A potential solution that I can think of is to throw an error when the user tries to delete the last remaining field which appears on the front of a card.

The updating of the template is deferred until saving time, so that would not be easy. Maybe update_templates_for_renamed_and_removed_fields() could check if the template has no field references after calling rename_and_remove_fields(), and add a reference to the first field if the template's currently empty? An added complication is that it would need to be a cloze reference for a cloze notetype.

**Comment by swektr** [comment]
Finally decided to give this issue a shot.  I wanted to get more familiar with Rust first but then I forgot about this issue.  Anyways I've made a draft pull request at #2663
