### ISSUE TITLE
Consider making reduce-motion and minimalist modes opt-in instead of opt-out

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2557]
Currently they apply unless manually excluded from HTML elements, and affect user's card templates as well as the UI. I think we may be better off changing them so that they only apply to select elements, as that's less surprising.

https://forums.ankiweb.net/t/box-shadow-issue/31475

**Comment by dae** [comment]
Related: https://forums.ankiweb.net/t/anki-pulsation-animation-stopped-working-on-mobile-devices-but-desktop-is-okay/31657

**Comment by tatsumoto-ren** [comment]
Apparently, the `body:not(.fancy) *` rule applies to cards too, and it breaks `box-shadow`s in people's templates and inside fields. 

<details>

![screenshot-2023-07-02-01-50-15](https://github.com/ankitects/anki/assets/69171671/d6c96ad3-1efe-44b4-aa05-f98e21a5e603)

</details>
