### ISSUE TITLE
Address accessibility warnings

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2564]
Currently we have some accessibility warnings disabled when running svelte-check, as Svelte upgrades introduced a bunch of them at once, and we couldn't tackle them at the time. They're disabled here:

https://github.com/ankitects/anki/blob/baa631c6efca6aeba8e0dc08056bbc43b1057d30/build/ninja_gen/src/node.rs#L228

If you remove one of those lines and run `./ninja check:svelte`, you can see where they occur (and they're also already shown in the editor). It would be nice if we could address these, even a few at a time.

**Comment by JayK1524** [comment]
I would like to work on this issue. Please guide me, how can I resolve this.

**Comment by dae** [comment]
If you Google one of the excluded error types, there are pages such as https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-noninteractive-tabindex.md that provide suggestions on how things might be addressed. I'm no accessibility expert, so it will likely be a learning experience for both of us. Please do some Googling, and if you think you've got an approach for how to address these, feel free to discuss before you start work on the change.

**Comment by derekdang** [comment]
I'm interested in working on this issue. I addressed the lint issues in ts/graphs/CardCounts.svelte to get an idea of what needs to be done. 

Added the tabIndex so the items that were clickable are now tabbable. The items that were clickable now open with Space/Enter.
I followed principles/guidelines found in 
https://www.w3.org/WAI/GL/wiki/Making_actions_keyboard_accessible_by_using_keyboard_event_handlers_with_WAI-ARIA_controls
https://usability.yale.edu/web-accessibility/articles/links
![accessibility demo](https://github.com/ankitects/anki/assets/21960193/a35a1fbd-8baa-4b30-822b-7a9c42fe2ff4)

https://gist.github.com/derekdang/dd231feb6ba558679bd80c642bc80bf8#file-cardcounts-svelte-L40-L53
https://gist.github.com/derekdang/dd231feb6ba558679bd80c642bc80bf8#file-cardcounts-svelte-L81-L84
The gist above highlights my changes.

**Comment by adeleke5140** [comment]
I have experience with fixing a11y errors. Can I get on this?

**Comment by dae** [comment]
Thank you both! Anyone's welcome to work on this, but please note down which things you're planning to fix, so people don't end up duplicating work. I'd also recommend starting small, so we can work through any potential design/style issues.

@derekdang I'm having trouble following that example - could you explain the logic behind calling addEventListener() in an on:keydown callback? Wouldn't it work just to do on:keydown={on_key_down}?

Some other thoughts:

- camelCase names are the norm in TypeScript
- to reduce the boilerplate of doing this in other places, it would be nice if the logic in on_key_down could be abstracted out into a separate function like `onEnterOrSpace()`, so we could do something like: `on:keydown={onEnterOrSpace(() => dispatch('search', { query: d.query })}`
- should we perhaps be using keyup instead?

Having said all that, perhaps an even better solution would be to switch to using `<button>` with these instead of links? Then I think we'd get the keyboard handling and tab index for free, and could just think about on:click. Presumably we could style the buttons to look like links, like how bootstrap does: https://getbootstrap.com/docs/4.0/components/buttons/?

**Comment by adeleke5140** [comment]
@dae Great suggestion. I would wait for @derekdang to tackle it first.

I agree with your last point that some of the `div` and `span` can be replaced with semantically appropriate element like `button` and `link`. With this, the element are keyboard accessible by default and can be accessed with the keyboard. It would also reduce our dependence on Aria-attribute.

**Comment by derekdang** [comment]
@dae 
I agree with the feedback regarding the eventListener. Some of this area is a little new to me so I had the eventListener wrap the onKeyDown in order to resolve an issue that I was seeing regarding `event` being deprecated (in https://developer.mozilla.org/en-US/docs/Web/API/Window/event) but I see that's not necessary.

Agreed with changing some of the elements to `button` or `link` where appropriate since it does handle `Space` and `Enter` for keyboard navigation.

I will defer to @adeleke5140 as Accessibility is also a new domain/area that I'm not all too familiar with.
I am okay divvying up the work with how you see fit @adeleke5140. 

I took the liberty of tackling some of the issues since it seemed like low-hanging fruit but I wasn't sure what was desired style-wise.
This PR addresses **a11y-no-noninteractive-element-interactions** https://github.com/ankitects/anki/pull/2578


**Original**
![image](https://github.com/ankitects/anki/assets/21960193/cdd8dbfd-b767-4e4e-a871-5cdb6e9dc24a)

**Changed to Button**
![image](https://github.com/ankitects/anki/assets/21960193/6319dfb8-367b-4414-8423-035aba57a64c)

**SettingTitle now tabbable**
![image](https://github.com/ankitects/anki/assets/21960193/05739489-73a5-4cbf-87c2-c7d06576c682)

**Comment by dae** [comment]
@derekdang Let's continue that discussion on https://github.com/ankitects/anki/pull/2578

@adeleke5140 

If you have any thoughts on that issue, please feel free to jump in.

> One ask I have is: how do I know which components apply to the anki UI?
e.g I wanted to fix a11y errors for the HandleBackground.svelte but found it hard to find what the component did and where.

A quick search through the source code seems to indicate it's used for the MathJax and Image overlays, that are shown when you click on either MathJax or an image in the editing screen.

> Sadly, I am used to console.log in order to debug. 

`./run` will allow you to surf to http://localhost:8080 in Chrome to debug webviews remotely. You can inspect/modify the HTML/CSS, and step through JS code if you insert a 'debugger;' statement in the code before using ./run.

**Comment by adeleke5140** [comment]
Thank you @dae.

I will see if there is anything useful I can contribute.
Your tips also clarifies where I was stuck.

Will push the first PR for

**Comment by derekdang** [comment]
New PR #2582  for a couple of other files. 

I looked into modifying `Badge` so that users could navigate to HelpModal without a mouse. Changing the span into a Button within `Badge` is a start but quite a few files use the Badge component. In some testing, some of that modification also introduces other UI/UX changes/bugs that may be unintended. It'd require more investigation and discussion IMO.

**Comment by dae** [comment]
Perhaps the best course of action might be to create a new component like ClickableBadge, and remove on:click from Badge? The only other usage of on:click is the revert button in the deck options screen, so we could switch that to ClickableBadge too. WDYT?

**Comment by adeleke5140** [comment]
Hi @derekdang, I saw that you started work on the Badge component. Are you done with your own tasks? Let me know which components you have fixed so that I can pick up the rest.

**Comment by adeleke5140** [comment]
@derekdang Alright, got it. Please I would appreciate if kept the list of what you have worked on updated so we don't both work on the same thing. Cheers.

**Comment by dae** [comment]
Looks like DuplicateLink may need some attention too: https://forums.ankiweb.net/t/keyboard-control/32986

**Comment by SteelColossus** [comment]
Hi there, I have taken a look at the issue mentioned with DuplicateLink, and have raised a new PR as https://github.com/ankitects/anki/pull/2646.

**Comment by adeleke5140** [comment]
@dae I apologize that I've been MIA for quite a while. Life just happened. 

Have all the issues relating to this been addressed? If not, I could still pick it up and work on them.

**Comment by dae** [comment]
Welcome back! It looks like we still have a few compiler warnings excluded in node.rs, so presumably there's still more work to do, which would be appreciated.

**Comment by adeleke5140** [comment]
Thanks for welcoming me back. I'm excited to jump back in.

**Comment by blikstiender** [comment]
Hello! Looking to start contributing to this excellent project! Came upon this issue, and I think the warning silencing code can be removed per 
```

**Comment by blikstiender** [comment]
Hello! Hoping to start contributing to this excellent project (used it to learn Hungarian to A2 level last year!) and came upon this issue. After a quick investigation I believe the warning suppression code can be removed. I made the following change: 
```diff
diff --git a/build/ninja_gen/src/node.rs b/build/ninja_gen/src/node.rs
index b87e105f0..f644ffdb0 100644
--- a/build/ninja_gen/src/node.rs
+++ b/build/ninja_gen/src/node.rs
@@ -226,18 +226,6 @@ impl BuildAction for SvelteCheck {
         build.add_inputs("tsconfig", &self.tsconfig);
         build.add_inputs("", &self.inputs);
         build.add_inputs("", inputs!["yarn.lock"]);
-        build.add_variable(
-            "compiler_warnings",
-            [
-                "a11y-click-events-have-key-events",
-                "a11y-no-noninteractive-tabindex",
-                "a11y-no-static-element-interactions",
-            ]
-            .iter()
-            .map(|warning| format!("{}$:ignore", warning))
-            .collect::<Vec<_>>()
-            .join(","),
-        );
         let hash = simple_hash(&self.tsconfig);
         build.add_output_stamp(format!("tests/svelte-check.{hash}"));
     }
```

and then ran: 
```bash
./ninja check:svelte
```

And received no warnings. Is this a correct indication that the accessibility issues have been addressed? If so would you like me to put together a PR for this?

**Comment by dae** [comment]
Unfortunately, the warnings have moved due to the change to sveltekit - they're now near the top of package.json. It would still be good to get rid of that code that's not being used, but we won't be able to close this ticket yet.
