### ISSUE TITLE
Align code blocks to the left by default

### ISSUE THREAD

**Issue by shunlog** [ankitects/anki#2573]
The [\<pre>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) HTML element represents preformatted text which is to be presented exactly as written in the HTML file. It is often used to represent multiple lines of code. For example:
```html
<pre>
def foo():
    print('bar')
</pre>
```

Currently, the `<pre>` element is centered by default, which results in unreadable code blocks ([HTML source for this card](https://pastebin.com/S0ThZyN4)):
![image](https://github.com/ankitects/anki/assets/48106195/e8f56878-1411-4660-9304-b71e27b352a6)

The expected behaviour is for code blocks to be left aligned:
![image](https://github.com/ankitects/anki/assets/48106195/9b963614-2984-4c78-8c7b-ef7c8438590b)

I believe this style covers everything:
```css
pre {
    text-align: left;
}
```
It only makes sense to align preformatted text to the left, so RTL text shouldn't be an issue.

List items have already been aligned in https://github.com/ankitects/anki/issues/1801. Now let's do the same for code blocks.

**Comment by dae** [comment]
It seems reasonable to do this if we also do it for lists, though I'm not sure `left` is necessarily fine in RTL - any thoughts @abdnh? Maybe it should be `start`?

**Comment by abdnh** [comment]
I agree, preformatted text can be RTL, even though this is not common. But since the majority of use cases for `<pre>` are for code (even in RTL templates), I'd say let's use left here.

**Comment by shunlog** [comment]
So it's settled then. I'll take this issue on me, looks easy enough.

**Comment by adeleke5140** [comment]
Majority of code is written in English and read from LTR, but for languages that uses the RTL system, would this also be ideal?

**Comment by adeleke5140** [comment]
@abdnh Alright, got it.
