### ISSUE TITLE
Synchronization changes the current card

### ISSUE THREAD

**Issue by Redysz** [ankitects/anki#2576]
Let's say I have 100 cards to repeat, I'm on the fiftieth, I've already read it (and listened to it - it has sound), but first I decide to press the "sync" button (I'm not sure if that's the correct name in English but this blue button for synchronization) - After I press it, the card changes, I have another card. This does not cause any error but only frustration because "sync" should sync, not change the current card and knock me out of rhythm.

```
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=False sv=2
Add-ons, last update check: 2023-07-12 15:25:58
    
```

**Comment by dae** [comment]
You may find it happens less frequently if you switch to the v3 scheduler, but it may still happen. Syncing may change which cards are currently available for studying, which is why the queues need to be recalculated.
