### ISSUE TITLE
error sending request for url (): error trying to connect: connection closed via error⁩

### ISSUE THREAD

**Issue by xyzmst** [ankitects/anki#2584]
<img width="295" alt="image" src="https://github.com/ankitects/anki/assets/5778792/0c48b6fc-a129-4aa4-9df0-89675b3e2bc3">

Suddenly encountered this error, tried uninstalling and reinstalling, creating a new account but it still doesn't work. I also tried other versions and got the same result.

anki-2.1.65-mac-apple-qt6.dmg
<img width="279" alt="image" src="https://github.com/ankitects/anki/assets/5778792/e2d2d17c-1d59-4f95-af25-bf5bc2ac6c6b">

**Comment by xyzmst** [comment]
It should be a server issue, and now it's working again.

**Comment by xyzmst** [comment]
This error has reappeared, indicating that the issue is likely with the desktop application, as the iOS client did not report any errors.

**Comment by dae** [comment]
The desktop and iOS client use the same syncing code, so if one is failing and the other working, that implies an issue with your computer, such as firewall/VPN/proxy setup, or different network setup on the two devices.

**Comment by xyzmst** [comment]
Thanks, I think I know where the issue is.
