### ISSUE TITLE
Schedule of the integration of Qt 6.5.2 release

### ISSUE THREAD

**Issue by homunet** [ankitects/anki#2589]
Hello, developers.
I'm M1 Mac user. As many reported in the Issues board, I am facing problems that halt Anki abruptly.
So I downgraded Anki to 2.1.61 which is the version before the update to QT 6.5. It has reduced the occurrence of malfunctions.
The latest update of Qt reported many improvements including the fix to exceptions causing freeze or hangs.
https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.5.2/release-note.md
Is there any schedule for an upgrade of Qt integrated into Anki Desktop?

**Comment by dae** [comment]
Please be patient - PyQt 6.5.2 only came out yesterday. The next beta build of Anki should include it, and will hopefully be ready in a week or so.

**Comment by homunet** [comment]
HI dae
Thank you for responding.
I am relieved hearing that the upgrade is included in the roadmap.
We all respect the hardwork of developers. We can wait until the change.
