### ISSUE TITLE
Respect Sort Order in Filtered Deck

### ISSUE THREAD

**Issue by khesed** [ankitects/anki#2607]
Filtered decks' `selected by` field does not respect `deck-config-sort-order-card-template`-like sort orders. I'd like to add a checkbox which manually respects creating the filtered deck to sort New cards by card type.

Would making a modification near the following five locations be sufficient? Can you foresee any problems which might arise?

* Adding a boolean member to `FilteredSearchTerm`: https://github.com/ankitects/anki/blob/main/rslib/src/decks/schema11.rs#L345C6-L345C6
* Adding a checkbox to the UI: https://github.com/ankitects/anki/blob/main/qt/aqt/forms/filtered_deck.ui#L201-L210 & https://github.com/ankitects/anki/blob/main/qt/aqt/forms/filtered_deck.ui#L335
* Text: https://github.com/ankitects/anki/blob/main/ftl/core/decks.ftl#L28
* Checking if the new boolean member of `FilteredSearchTerm` is enabled. If so, sort New cards by card type: https://github.com/ankitects/anki/blob/main/rslib/src/storage/card/filtered.rs#L30

For actually implementing the sorting, I could not find how sorting by card type is done normally in queue building except https://github.com/ankitects/anki/blob/main/rslib/src/scheduler/queue/builder/sorting.rs#L18-L30

I'm unfamiliar with the card database architecture to construct a query which has a case that is specific to the new cards found, and since the above queue-building doesn't appear to be done in SQL, there's no reference query I can use. Could you help me find the architecture?

**Comment by dae** [comment]
I'd prefer not to change this part of the code at the moment, but I can offer a potential workaround: if you create a filtered deck and then nest it inside a normal deck, clicking on the normal deck should show the filtered deck's cards in the order defined by that normal deck.
