### ISSUE TITLE
Golang client 

### ISSUE THREAD

**Issue by gedw99** [ankitects/anki#2613]
- Have a question or feature suggestion?

feature
- Problems building/running on your system?

yrs I want to use a ku for golang apps.

- Not 100% sure you've found a bug?

No bug but it would be good to generate off the protobufs a golang client

**Comment by gedw99** [comment]
https://github.com/gioui

example

https://github.com/g45t345rt/g45w#demo

**Comment by dae** [comment]
Sorry, I have neither the time nor the interest in working with golang. Please use the forums for any future suggestions you may have.
