### ISSUE TITLE
Undoing IO image change causes mask deletion and makes note permanently uneditable

### ISSUE THREAD

**Issue by glutanimate** [ankitects/anki#2620]
**Steps to reproduce**

1. While reviewing or browsing through IO notes, draw up the mask editor
2. Change the image using the image replacement button
3. Click on the undo button

**Expected behavior**

Image switches back to the previously selected image.

**Actual behavior**

- Image does not change
- All masks disappear
- Any new masks drawn do not get saved to the note upon closing the editor
- Any further edits to the note are impossible, even after restarting Anki

Tested against main with https://github.com/ankitects/anki/commit/70506aeb99d4afbe73321feaf75a2fabaa011d55 reverted.

----

**Screencasts**

Note losing occlusions on undoing (cf. field contents before and after as shown in debug console):

https://github.com/ankitects/anki/assets/5459332/2afe178b-efe1-45f9-969e-59e5533b0a05

Note remains uneditable, even after restarting Anki:

https://github.com/ankitects/anki/assets/5459332/0dbaa0b7-81ac-4fe2-b04c-713fc8d301e6

----

**Thoughts**

- Users undoing an image change could be a fairly common scenario, e.g. if they noticed that they picked the wrong image – which can happen easily if the file picker doesn't draw thumbs.
- With that in mind, and given that users could essentially lose a note and all of the cards & scheduling data associated with it, I would see this as fairly severe and something we should fix before shipping IO (or at least before shipping the _Change image_ button)

**Comment by dae** [comment]
How common/useful is it to be able to change an image when there are already occlusions made? Would an easy/lazy fix for this be to just disable the button for existing notes?

**Comment by glutanimate** [comment]
I think the main use cases for me in the past have been tweaking the original image to some degree, e.g. fixing a mistake or adding an annotation. Compared to editing the masks, it definitely has a significantly smaller utility and I wouldn't be surprised if most IOE users have never used it. So if fixing the undo behavior is not trivial, disabling it when editing seems reasonable for now.

I wouldn't kill the feature permanently, however, as I do think it's an essential aspect to IO notes being fully editable and thus consistent with other Anki notes (ideally we shouldn't have any user inputs that are a one-way street).

**Comment by dae** [comment]
Thanks for the detailed reply Hikaru, I am inclined to agree. For the rare occasions when users might want to do this, maybe we could just provide a "reveal in file manager" option in the future that opens to the file in the media folder, and they can save over the old copy if they want. That wouldn't even need to be specific to I/O cards.
