### ISSUE TITLE
Consider exposing gfx driver options in the GUI for Qt6

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2625]
With Qt5, if the user selects a graphics driver that doesn't work on their system, we're able to detect it in msgHandler() and automatically select a different driver, so the user is not stuck being unable to open Anki. This no longer worked in Qt6, so the option was removed from the GUI, as we don't want users to make an easy change in the GUI and then be locked out.

A number of GUI versions have elapsed since then, and it may be time to check that this is still the case. For example, if vulkan is selected and fails on your systems as in https://forums.ankiweb.net/t/2-1-66-card-not-revealing/33603/5, does Qt let us know in the message handler?

If not, we should at least document the options described in that thread, as currently we only cover software/no software in the manual.

Some extra background: as of Qt 6.5.1, Qt switched from using OpenGL by default, to using DirectX11. I don't believe dx11 was an option when we originally switched to Qt6 - or if it was, I wasn't aware of it.

@RumovZ @abdnh if either of you wouldn't mind checking this when you have a chance, that'd be appreciated.

**Comment by abdnh** [comment]
All of `d3d11`, `opengl`, `vulkan`, and `gles2` seems to work for me: Anki is launching and the reported issue doesn't occur after some brief testing. Here are the info shown with `QSG_INFO=1`:

```
Qt debug: FLIP_* swapchain supported = true, ALLOW_TEARING supported = true
Qt debug: Default swap effect: FLIP_DISCARD
Qt debug: Adapter 0: 'Intel(R) UHD Graphics' (vendor 0x8086 device 0x9B41 flags 0x0)
Qt debug:   using this adapter
Qt debug: Adapter 1: 'Microsoft Basic Render Driver' (vendor 0x1414 device 0x8C flags 0x2)
Qt debug: rhi texture atlas dimensions: 512x512
Qt debug: rhi texture atlas dimensions: 512x512
Qt debug: rhi texture atlas dimensions: 512x512
```

If I set a backend not supported on Windows like `metal` I get the following errors:
```
Qt warning: Failed to create QRhi for QBackingStoreRhiSupport 
Qt warning: QQuickWidget: Failed to get a QRhi from the top-level widget's window
Qt warning: QQuickWidget::resizeEvent() no QRhi
```

Looks like the first message was added in Qt 6.4.0: https://github.com/qt/qtbase/blob/8db5896bbe9b7285abed2db681e80fd9110e2ba8/src/gui/painting/qbackingstorerhisupport.cpp#L131

Maybe we can rely on that?

@cjdduarte did you perhaps get the same error with `QSG_RHI_BACKEND=vulkan`?

**Comment by cjdduarte** [comment]
> vulkan
@abdnh ,  When I use Vulkan, this is how the main window of Anki appears to me

![image](https://github.com/ankitects/anki/assets/42243532/2f07949f-8b9d-4a8d-94ba-c9ea41510f3b)

Initial setup...
Running with temporary Qt5 compatibility shims.
Run with DISABLE_QT5_COMPAT=1 to confirm compatibility with Qt6.
Preparing to run...
1021636467 inserted a new menu.
anki_fen_vis: executing from ANKI gui
anki_fen_vis: config {'coordinates': False, 'size': 320, 'square_light': '#EDD4AE', 'square_dark': '#AB7E5B'}
Starting main loop...
deckDueTree() is deprecated; use decks.deck_tree() for a tree without counts, or sched.deck_due_tree()
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
Qt debug: Initializing QRhi Vulkan backend 0x1bfd848c220 with flags 0
Qt debug: Enabled instance extensions:
Qt debug:   VK_KHR_get_physical_device_properties2
Qt debug:   VK_KHR_surface
Qt debug:   VK_KHR_portability_enumeration
Qt debug:   VK_EXT_debug_utils
Qt debug:   VK_KHR_win32_surface
Qt debug: Physical device 0: 'AMD Radeon(TM) Graphics' 2.0.270 (api 1.3.250 vendor 0x1002 device 0x1638 type 1)
Qt debug:     using this physical device
Qt debug: queue family 0: flags=0xf count=1
Qt debug: queue family 1: flags=0xe count=2
Qt debug: queue family 2: flags=0xc count=1
Qt debug: 149 device extensions available
Qt debug: Enabling device extensions:
Qt debug:   VK_KHR_swapchain
Qt debug:   VK_EXT_vertex_attribute_divisor
Qt debug: Using queue family index 0 and queue index 0
Qt debug: rhi texture atlas dimensions: 512x512
Qt debug: rhi texture atlas dimensions: 512x512
Qt debug: rhi texture atlas dimensions: 512x512
Qt debug: Creating new swapchain of 3 buffers, size 2560x1009, presentation mode 2
deckDueTree() is deprecated; use decks.deck_tree() for a tree without counts, or sched.deck_due_tree()

**Comment by dae** [comment]
@abdnh thanks for that. To confirm, those messages could be checked by the message handler?

@cjdduarte that doesn't look too bad in this case, since you presumably can still open the preferences screen. What's bad is when Anki crashes on startup, as then users struggle to recover from the change.

**Comment by dae** [comment]
Sounds promising! If you'd like to explore this further / look into restoring GUI control over the graphics driver for Qt6, that would be appreciated.
