### ISSUE TITLE
Something (probably Svelte 4 upgrade) has broken exported components

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2629]
https://forums.ankiweb.net/t/anki-2-1-66-beta/32463/27

Perhaps caused by 'svelte/internal' no longer being publicly exported in Svelte 4. We'll need to investigate whether the current approach is even feasible anymore. Even if we're able to fix this, I think we're going to need a less fragile approach moving forward.

**Comment by dae** [comment]
Let's focus on a short term fix for now. I think this broke when svelte/internal was changed to svelte in export-runtime.ts. We should start by updating the example add-on to svelte4, and switching it to the new import location to see if that fixes things.

**Comment by abdnh** [comment]
This seems to work as a short term solution:
```diff
diff --git a/ts/sveltelib/export-runtime.ts b/ts/sveltelib/export-runtime.ts
index 0744db3d9..5f9de74b3 100644
--- a/ts/sveltelib/export-runtime.ts
+++ b/ts/sveltelib/export-runtime.ts
@@ -7,7 +7,15 @@

 import { registerPackageRaw } from "@tslib/runtime-require";
 import * as svelteRuntime from "svelte";
+// eslint-disable-next-line @typescript-eslint/ban-ts-comment
+// @ts-ignore
+import * as svelteInternal from "svelte/internal";
+// eslint-disable-next-line @typescript-eslint/ban-ts-comment
+// @ts-ignore
+import * as svelteDiscloseVersion from "svelte/internal/disclose-version";
 import * as svelteStore from "svelte/store";

 registerPackageRaw("svelte", svelteRuntime);
 registerPackageRaw("svelte/store", svelteStore);
+registerPackageRaw("svelte/internal", svelteInternal);
+registerPackageRaw("svelte/internal/disclose-version", svelteDiscloseVersion);
```

I tested the example add-on with this patch and Svelte 4.

**Comment by dae** [comment]
@abdnh thanks!

@luc-languagetools after updating your add-on to Svelte 4, can you confirm running from the latest Anki HEAD fixes your problem?

**Comment by dae** [comment]
Assuming this is fixed until we hear otherwise.

**Comment by luc-languagetools** [comment]
I actually took this opportunity to move away from svelte components. I can iterate on new features faster if it's python only, because of regression testing (pyqt-test + unit tests). I'll probably get back into svelte at some point later for some other features, but will probably be for standalone components (similar to what Anki does with Rust + Svelte).

Before the editor moved to typescript + svelte, I had some pretty fancy per-field integration in Language Tools and I had to undo all that when the editor was updated. I'm all in favor of trying new stuff, but I have to keep things stable for long-term users of AwesomeTTS / HyperTTS / Language Tools so i'm a little bit cautious.

**Comment by dae** [comment]
Fair enough.

**Comment by luc-languagetools** [comment]
@dae here's how I replaced editor components: https://languagetools.anki.study/updates#2023-10-18 
with 3 buttons, the functionality is pretty much identical, and more automated.

**Comment by kvn1351** [comment]
> @abdnh thanks!
> 
> @luc-languagetools after updating your add-on to Svelte 4, can you confirm running from the latest Anki HEAD fixes your problem?

@dae I can confirm that my Svelte addon works great on 23.10.1! :)

In general, I think that this version was a big win. Thanks a lot.

**Comment by kvn1351** [comment]
Since Svelte 5 my addons are broken one more. It was indeed a bad choice to develop in svelte I suppose.
