### ISSUE TITLE
Potential improvements to the Image Occlusion UX

### ISSUE THREAD

**Issue by kleinerpirat** [ankitects/anki#2631]
I just tried the current IO implementation and really like that it now operates in the same window. I didn't have the time to thoroughly test the feature, but at a first glance, I got some suggestions.

## 1. IO Button should always show
Users who know Aristotelis' Image Occlusion add-on are used to having a separate notetype for the feature, but I don't think checking for a separate notetype is the first thing a new user would think of. I would look for a button in the toolbar. Currently the IO button only appears when you select the right notetype, so you need to know there's a special notetype somewhere in the potentially long list of third party notetypes a user might have downloaded.

## 2. Provide a way to paste an image from the clipboard
As far as I can see, there's only a "Select image" button, which opens a file explorer window. If there is a way to get a clipboard image into the editor, I apologize but suggest making it more discoverable.

### Current behavior
Currently the button serves as a toggle between two views (again something old-school IO users are used to): one for image editing and one for the fields. I don't think splitting the IO editor into two views is necessary and can be confusing. The Editor fields disappear, but the toolbar for editing field content still shows, so users might think there's something wrong.

The image editor could simply be its own field, with the rest (Header, Back Extra, Comment) below. It would also make scrolling through IO content in the browser easier.

### Suggested behavior
The button could be used as a shortcut to switch to the IO notetype and paste the image from the clipboard if there is one. When the IO notetype is selected, it simply acts as a toggle for the IO editor. (i.e. masks). To make this intuitive, the button would change its appearance depending on the notetype.

Cheers!

---
*Been off for a while, sorry for leaving you hanging like that. Hope you're all doing well!*

**Comment by dae** [comment]
Welcome back!

> 1. IO Button should always show

The reasons why it doesn't:

- it's consistent with the cloze behavior, where the cloze button is only visible on cloze notetypes
- it's not clear what it should do if the user clicks on it when a non-i/o notetype is selected, and they have more than one i/o notetype

> 2. Provide a way to paste an image from the clipboard

Agreed this would be nice.

> I don't think splitting the IO editor into two views is necessary and can be confusing

Previous discussion: https://github.com/ankitects/anki/pull/2485#issuecomment-1608420798

**Comment by dae** [comment]
I've split 2 off into a new ticket.
