### ISSUE TITLE
Provide a way to reload WebEngine

### ISSUE THREAD

**Issue by nihil-admirari** [ankitects/anki#2635]
Some JavaScript stuff (modules, custom elements) is preserved across cards and is never reloaded from disk.

For modules, there was a [workaround](https://github.com/nihil-admirari/modern-cloze-overlapper/tree/master#reloading-_cloze-overlappermjs): reload a module with a dummy query parameter (e.g. `?dev=1`).

[`Custom elements`](https://github.com/nihil-admirari/modern-cloze-overlapper/blob/master/_cloze-overlapper.mjs#L219), however, can be neither redefined nor removed; restarting Anki is the only way out.

Is there a way to do an F5 on Qt WebEngine? Anki Debug Console command would suffice.

**Comment by dae** [comment]
Going back to the deck list doesn't help?

**Comment by nihil-admirari** [comment]
It does, thanks.

**Comment by nihil-admirari** [comment]
Sorry, actually it doesn't. The first time I tried to go back to the deck list it appeared to be working, so I closed the issue. But since then I was unable to reproduce it. Tried closing all Browse, Preview, Manage Note Types etc. windows or opening and closing them again, but: reload doesn't happen.

**Comment by dae** [comment]
When moving to the deck list and back to the reviewer, Anki loads a new HTML page, which I'd expect to clear out any custom elements from that webview. Closing other windows will not help if your goal is to refresh the review screen, as they use different webviews.

**Comment by nihil-admirari** [comment]
Ok, it resets custom elements (which is why I've said that the method helps, since I didn't get an element already defined error). It does make previous workaround `?dev=1` viable again.

But it doesn't reload the module. Is it possible to reload modules without playing with query parameters or closing Anki?

**Comment by dae** [comment]
Not sure - maybe something in the chrome developer tools might help.

**Comment by nihil-admirari** [comment]
I do have Inspector addon installed, but I haven't found anything in developer tools that could force a module reload.

**Comment by nihil-admirari** [comment]
Found a way: during preview in DevTools on the Network tab, check “Disable cache”, and press Ctrl + Shift + R. It empties the card's page completely, but after navigating to the next/previous card and back the module is reloaded.
