### ISSUE TITLE
Add text tool to image occlusion?

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2651]
https://forums.ankiweb.net/t/feature-request-editing-in-image-occlusion/34052

http://fabricjs.com/fabric-intro-part-2#text

**Comment by krmanik** [comment]
I will implement this, the text feature already implemented in other PR, I will take from that create PR here.

**Comment by abdnh** [comment]
@krmanik I've been actually working on this in the last two days and will send a draft PR soon. Would be happy to hear your thoughts on it!

**Comment by krmanik** [comment]
@abdnh 
Go for it, because I have not started yet. I will give my feedback on your PR later.
