### ISSUE TITLE
New cards suddenly are mixed

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#2662]
I had the same issue at the same time on anki and ankidroid. Running on 5004cd332bf1514e57f5c48bcbe43cd86f982a7a on anki and recent HEAD on ankidroid.

I used to have all review cards first, then new cards. Being thousands of cards late, seeing new cards is not really an option right now. I got a message in anki telling me I need to update to V3 scheduler. I accepted. But I don't see anything in https://faqs.ankiweb.net/the-2021-scheduler.html that state that there is a change in order between new and review cards. So I don't know whether it's the actual cause of my issue.

**Comment by dae** [comment]
In v3 the setting is in the deck preset instead of the preferences, so you'll need to customize it again.

**Comment by Arthur-Milchior** [comment]
May I suggest, during update, for each deck options that does not have an explicit preference already, to copy the value from preferences, maybe?

**Comment by dae** [comment]
The problem is we can't know if the value has been set by the user already, so if we did this, it would mean the user's chosen value gets reset if they switched to v2 and then back to v3.
