### ISSUE TITLE
Allow creating an image occlusion from the clipboard

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2664]
Previously mentioned on #2631

**Comment by abdnh** [comment]
Instead of adding a "Select image from clipboard" button, what about making the existing button ask the user whether they want to use the image in the clipboard if any is detected?

**Comment by dae** [comment]
Hmm. I would think it might be a bit simpler to have two different buttons - that way the user doesn't need to deal with a pop-up when an image happens to be on the clipboard but they want to select an image, and when they want to use the clipboard, they don't need a separate confirmation step. WDYT?

**Comment by abdnh** [comment]
I think I agree. The two-button approach is also probably better for discoverability.
