### ISSUE TITLE
Add an option to stop the card timer when answer revealed

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2665]
This would only affect the on-screen display - we still need the full time with question+answer when recording entries in the review log.

https://forums.ankiweb.net/t/stop-timer-after-showing-answer/29937

**Comment by BEST8OY** [comment]
Just one question
Will it be possible for someone to create an addon to convert that stopped on-screen timer into tag for current answering card?

**Comment by abdnh** [comment]
> Will it be possible for someone to create an addon to convert stopped on-screen timer into tag for current answering card?

You mean tagging the card with the time? I guess that's possible by reading `Reviewer.card.timer_started` after `Reviewer._showEaseButtons()` is called.

**Comment by dae** [comment]
If you need help creating such an add-on, @abdnh offers such services: https://www.fiverr.com/abd_nh

**Comment by hnvy** [comment]
> they will try to study cards that took more time to answer more effectively in the future.

I'm curious, what subject would this be useful for? I have never thought of time to be used as a metric to assess the effecetiveness of recall (one-word vs. ten-word answer).

Feel free to contact me on Ankiweb Forums: https://forums.ankiweb.net/u/hnvy/summary if you'd like to discuss this idea further! I'm interested in hearing more :)



HR

**Comment by abdnh** [comment]
> I'm curious, what subject would this be useful for? Language? Maybe maths? I have never thought of time to be used as a metric to assess the effecetiveness of recall (one-word vs. ten-word answer).

It might be useful for people practicing conversation, for example.
