### ISSUE TITLE
Cmd+, preferences shortcut conflicts with bullet list shortcut

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2672]
https://forums.ankiweb.net/t/shortcut-for-bullets-in-the-edit-window-opens-preferences-instead/34522

One way we could solve this is to turn the edit window into a main window like add/browse, so it gets its own menu without preferences listed there.

**Comment by Lexa013** [comment]
Hello, i am experiencing the same issue when adding new cards. Is there any way to solve it ?

**Comment by Danika-Dakika** [comment]
Duplicate post in the Forums: https://forums.ankiweb.net/t/cmd-coma-on-mac-opens-the-preferences-menu-instead-of-a-creating-bullet-list/56816
