### ISSUE TITLE
Loop Error when "Compute optimal retention" on Anki 23.10 Beta1

### ISSUE THREAD

**Issue by filipenanclarez** [ankitects/anki#2677]
OS: Windows 10
Anki version: 23.01+1

![image](https://github.com/ankitects/anki/assets/27212546/6e1c0e3d-e531-4adc-8dbe-3801e371abaf)

I can't find error.log to send

@L-M-Sherlock this happening when i try to "Compute optimal retention"

Here my collection to help reproduce

[backup-2023-09-24-14.23.24.colpkg.zip](https://github.com/ankitects/anki/files/12709234/backup-2023-09-24-14.23.24.colpkg.zip)

**Comment by dae** [comment]
I can't seem to reproduce this - clicking Compute after importing that backup works for me. What is shown in the console? https://addon-docs.ankiweb.net/console-output.html

**Comment by filipenanclarez** [comment]
> I can't seem to reproduce this - clicking Compute after importing that backup works for me. What is shown in the console? https://addon-docs.ankiweb.net/console-output.html

You change the params like image?

**Comment by dae** [comment]
Could you copy + paste them here please?

**Comment by filipenanclarez** [comment]
> Could you copy + paste them here please?

```
0.4539, 2.4708, 4.4940, 10.1726, 4.6113, 1.0770, 0.7907, 0.0065, 1.8461, 0.1000, 1.2860, 2.1311, 0.0960, 0.2613, 1.3191, 0.2322, 2.7905
```

But the main change is "Days to simulate" to 36500

**Comment by dae** [comment]
I don't get an error, but it is of course very slow. @L-M-Sherlock what do you suggest we limit that value to?

**Comment by filipenanclarez** [comment]
> I don't get an error, but it is of course very slow. @L-M-Sherlock what do you suggest we limit that value to?

I try again, and get the error again ... 

My steps:

1 - Open Anki
2 - Select HSK3.0 deck options
3 - Enable FSRS
4 - Run "Compute optimal retention"
5 - Change "Days to simulate" to 36500
6 - Click "Compute"
7 - Wait for the end, and then, error comes.

Please see the video above with log windows open:


https://github.com/ankitects/anki/assets/27212546/2b5fc16c-1541-4a0b-9627-bd19bf3e8d74

**Comment by L-M-Sherlock** [comment]
36500 is too long for simulation. I recommend limiting it under 5000.

**Comment by L-M-Sherlock** [comment]
It's really too slow, and I can't cancel it.

**Comment by dae** [comment]
Now capped to 10 years.
