### ISSUE TITLE
You can still review on sched v2, no add-on needed

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#2678]
Running on c2b1ab5eb06935e93aea6af09a224a99f4b971f0 

How to reproduce:
Let's take a deck D with many cards to review.
* On ankidroid, open deck D, review one card, sync
* on computer, open deck D, click on sync,

Expected behavior:
* I should be asked to update to sched V3 before being able to review

Actual result:
* I can review as usual. Only once I quit the deck and try to open another one I can't review anymore and is asked to update

Relatedly: I'd appreciate an option to tell "always update on v3 after a sync", given that until AnkiDroid is updated, this will need to be accepted very often

**Comment by dae** [comment]
Sorry Arthur, I'm not following you. The v2 code has been stripped out, so if reviewing works, it means you're using v3. There is no need to toggle v2/v3 in AnkiDroid - if you're using the new backend you can use v3 already, and if you're using the old backend AnkiDroid will use v2 even if you have v3 enabled.

**Comment by Arthur-Milchior** [comment]
I fear my title is poorly phrased. I would have hoped the description would be of more help.

The problem is that, I can, in this order:
* sync
* review
* be requested to upgrade to v3.

I do not know exactly what the "upgrade" button does. If it does not do anything to the card itself, then the behavior is acceptable. If there is actually changes to the card values during the upgrade, then it means that I just had the V3 algorithm applied to a card with V2 parameters.

In any case, I believe that, from a user point of view, if we actually should request them to upgrade, it should be impossible to review before the upgrade is done. Otherwise, it seems strange to request the upgrade before opening the reviewer.
Right now, if your collection use V2, it's only impossible to open the reviewer, but if the reviewer is already open, it's possible to review. This does not seem to be a consistent user experience.

Another simple solution would be that, at the end of the synchronization, if the collection uses V2, to close the reviewer.

**Comment by dae** [comment]
https://faqs.ankiweb.net/the-2021-scheduler.html#compatibility

All upgrading does is set a flag in the config so that v3-capable clients will use v3 instead of v2. v3-incapable clients will continue to use v2.

I can't seem to reproduce this issue. Were you testing with latest HEAD? If I change back to v2 on another client and sync, then try to continue studying, it gives me an error that the v1 scheduler is no longer supported. (it should say v1/v2).

**Comment by Arthur-Milchior** [comment]
I edited my original report to add the version I was testing with. Not current HEAD probably, given I've not closed in a few days. 
I've just done `git pull; ./run` and can't reproduce anymore, with or without add-ons, it works as expected, so great.
sorry for the noise.
