### ISSUE TITLE
Float left/right buttons are reversed

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2713]
https://forums.ankiweb.net/t/note-field-editor-image-float-buttons-wrong-way-round/35515

**Comment by geldbogen** [comment]
see my pull-request for this:
[https://github.com/ankitects/anki/pull/2719](url)

:)

**Comment by dae** [comment]
So, this issue turned out to be more complicated than originally expected. The icons are fine, so reversing their names is probably not the best approach here. What's happening is that $direction is undefined, and we're comparing it against 'ltr', so that fails and we end up with right-to-left instead, where the icons are reversed. This is probably happening because direction is a context variable and only accessible within a field, and the image overlay is not nested inside individual fields - it's a shared component defined inside <Fields> instead.

Maybe we could solve this by removing all the ltr/rtl logic? I'm not sure we even need it, as users can click on left or right depending on which side they want, and we're using left/right, not start/end.
