### ISSUE TITLE
Docker for anki sync

### ISSUE THREAD

**Issue by sbhal** [ankitects/anki#2715]
Can we have official docker image to run sync server?

**Comment by dae** [comment]
Feature requests belong on the forums. This is not something I'm likely to add in the near future, but it should be fairly simple to build yourself.

**Comment by LuckyTurtleDev** [comment]
First version of docker prototype. 
This version is currently limited to x86. Since many user probably would like to use Raspberry Pi to host an armv7 and armv8 version should also be a good idea.

```dockerfile
FROM rust AS builder
SHELL ["/bin/bash", "-uo", "pipefail", "-c"]

ENV TARGET x86_64-unknown-linux-musl
RUN rustup target add "$TARGET"

RUN apt-get -y update && apt-get -y install protobuf-compiler musl musl-dev musl-tools
ENV PROTOC=/usr/bin/protoc
RUN cargo install --locked --target "$TARGET" --git https://github.com/ankitects/anki.git --tag 23.10 anki-sync-server
RUN ldd /usr/local/cargo/bin/anki-sync-server


FROM scratch
ENV SYNC_BASE=/data
COPY --from=builder --chmod=0755 /usr/local/cargo/bin/anki-sync-server /
CMD ["./anki-sync-server"]
```

**Comment by JiangLongLiu** [comment]
> First version of docker prototype. This version is currently limited to x86. Since many user probably would like to use Raspberry Pi to host an armv7 and armv8 version should also be a good idea.
> 
> ```dockerfile
> FROM rust AS builder
> SHELL ["/bin/bash", "-uo", "pipefail", "-c"]
> 
> ENV TARGET x86_64-unknown-linux-musl
> RUN rustup target add "$TARGET"
> 
> RUN apt-get -y update && apt-get -y install protobuf-compiler musl musl-dev musl-tools
> ENV PROTOC=/usr/bin/protoc
> RUN cargo install --locked --target "$TARGET" --git https://github.com/ankitects/anki.git --tag 23.10 anki-sync-server
> RUN ldd /usr/local/cargo/bin/anki-sync-server
> 
> 
> FROM scratch
> ENV SYNC_BASE=/data
> COPY --from=builder --chmod=0755 /usr/local/cargo/bin/anki-sync-server /
> CMD ["./anki-sync-server"]
> ```

When I used this dockerfile to build, the following error occurred. I don’t know the reason. Can you please tell me the cause of the error?

```
Step 10/15 : RUN cargo install --locked --target "$TARGET" --git https://github.com/ankitects/anki.git --tag ${version} anki-sync-server
 ---> Running in 7e0b9aaa711f
    Updating git repository `https://github.com/ankitects/anki.git`
    Updating git submodule `https://github.com/ankitects/anki-core-i18n.git`
    Updating git submodule `https://github.com/ankitects/anki-desktop-ftl.git`
    Updating git submodule `https://github.com/ankitects/PyOxidizer.git`
error: could not find `anki-sync-server` in https://github.com/ankitects/anki.git?tag=23.10 with version `*`
The command '/bin/bash -uo pipefail -c cargo install --locked --target "$TARGET" --git https://github.com/ankitects/anki.git --tag ${version} anki-sync-server' returned a non-zero code: 101

```


![image](https://github.com/ankitects/anki/assets/7019907/70a05a21-a573-4884-92d1-a142e14e913a)

**Comment by JiangLongLiu** [comment]
> @JiangLongLiu Any reason you're trying to build yourself? You can use the already published and working image linked in [#2715 (comment)](https://github.com/ankitects/anki/issues/2715#issuecomment-1869765943)
> 
> https://github.com/LuckyTurtleDev/docker-images/pkgs/container/anki

Thank you very much for your help, the image has been downloaded.

Due to network issues in my area, I cannot download the image directly from ghcr.io. So I took a zigzag approach
1. Download the image through the proxy website
`docker pull ghcr.dockerproxy.com/luckyturtledev/anki:23.12.1`
2. Rename the downloaded image
`docker tag ghcr.dockerproxy.com/luckyturtledev/anki:23.12.1 ghcr.io/luckyturtledev/anki:23.12.1
`
3. Delete the image downloaded through the proxy
`docker tag ghcr.dockerproxy.com/luckyturtledev/anki:23.12.1 ghcr.io/luckyturtledev/anki:23.12.1
`

**How should I build a docker container through docker-compose?** Is there any corresponding blog article that I can refer to?

**Comment by LuckyTurtleDev** [comment]
> How should I build a docker container through docker-compose? Is there any corresponding blog article that I can refer to?

You remove `image: SOMEIMAGE` and add instead `build: .` or `build: SOMEPATH` .

**Comment by LuckyTurtleDev** [comment]
> When I used this dockerfile to build, the following error occurred.

I have rebuild the image, but can not reproduce your error.

Is their any reason, why you build an outdated version from anki?

**Comment by LuckyTurtleDev** [comment]
Keep in mint the Dockerfile might change in future, the **current version of Dockerfile and a rebuild image is available at**: https://github.com/LuckyTurtleDev/docker-images/tree/main/dockerfiles/anki.

**Comment by JiangLongLiu** [comment]
非常感谢您

**Comment by JiangLongLiu** [comment]
> Keep in mint the Dockerfile might change in future.
> 
> The **current version of Dockerfile, prebuild image and doc is available at**: https://github.com/LuckyTurtleDev/docker-images/tree/main/dockerfiles/anki.

thank you very much !

**Comment by JiangLongLiu** [comment]
> > When I used this dockerfile to build, the following error occurred.
> 
> I have rebuild the image, but can not reproduce your error.
> 
> Is their any reason, why you build an outdated version from anki?

Because I specified the version number to build
