### ISSUE TITLE
Show profile name when deleting profiles

### ISSUE THREAD

**Issue by soliviantar** [ankitects/anki#2717]
From: https://forums.ankiweb.net/t/show-profile-name-when-deleting-profiles/35483

When a user goes to File > Switch profile… they can delete a profile, but the pop-up window only says:

`All cards, notes, and media for this profile will be deleted. Are you sure?`

and it might be blocking the profile selection that will be deleted (see attached image, the profile that will be deleted is not shown anywhere). To prevent mistakes, I think it would be useful to change the message to:

`All cards, notes, and media for the profile [NAME OF PROFILE] will be deleted. Are you sure?`

![delete profiles](https://github.com/ankitects/anki/assets/25809253/e1494d1d-82ae-4187-9e06-8b77d3147602)

**Comment by adeleke5140** [comment]
This looks quite fun to tackle, @dae would it be possible to add the hacktoberfest label to i?

**Comment by chandraiyengar** [comment]
Hey, this is my first issue so i might have missed some things. I've made that PR^, let me know if there's anything to change/add

**Comment by dae** [comment]
Closed by #2722
