### ISSUE TITLE
"Preview" window size gets reset every time (starting from 2.1.66)

### ISSUE THREAD

**Issue by CrAZONE0** [ankitects/anki#2724]
Starting from Anki 2.1.66 every time you open the "Preview" window the size will get reset. Addons have nothing to do with the issue. Happens on the latest beta as well (23.10beta4)

Platform: Windows 11

**Comment by dae** [comment]
Original report: https://forums.ankiweb.net/t/anki-doesnt-remember-the-window-size-of-preview/35565

@abdnh can you reproduce this on Windows?
