### ISSUE TITLE
Overlaying one shape over another causes both to be shifted to the canvas origin

### ISSUE THREAD

**Issue by glutanimate** [ankitects/anki#2725]
Split off from https://github.com/ankitects/anki/pull/2705#issuecomment-1752147723:

> - Drawing a mask over a text label will oftentimes cause both to be shifted to the canvas origin:
> 
>      https://github.com/ankitects/anki/assets/5459332/fd7cf97a-396c-4b9e-b29a-8bbd2e5952b1
> 
>      Generated field content (note the negative coords):
>      
>      ```
>      {{c0::image-occlusion:text:left=-0.0948:top=-0.0641:fill=rgb(0,0,0):oi=1:text=Test:scale=1.}}
>      {{c2::image-occlusion:rect:left=-0.2298:top=-0.1435:oi=1:width=.4576:height=.2848}}
>      ```

In practice users will likely most often run into this when adding text, but this seems to affect all shapes and could e.g. also be triggered by two closely adjacent shapes overlaying each other slightly (and inadvertently).

**Comment by dae** [comment]
@abdnh interested in looking into this?

**Comment by hikaru-y** [comment]
I actually already started working on this a few hours before your comment and found the cause and a fix, so I just sent a PR.
