### ISSUE TITLE
23.10beta5: ModuleNotFoundError

### ISSUE THREAD

**Issue by Erik262** [ankitects/anki#2731]
After downloading and starting the latest beta version (23.10beta5) on macOS 14.0, the application (anki-23.10-mac-intel-qt6.dmg) launches but there is no response. An error message appears when running via Terminal:

`╭─[Mac-Pro] as erik in ~                                                                                       07:38:22
╰─-▶ /Applications/Anki.app/Contents/MacOS/anki ; exit;
Anki starting...
Initial setup...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "aqt", line 40, in <module>
  File "anki.lang", line 12, in <module>
  File "anki._backend", line 14, in <module>
  File "anki.backend_pb2", line 5, in <module>
ModuleNotFoundError: No module named 'google.protobuf'

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]`

**Comment by MrBananaPants** [comment]
Same here. Anki won't start in Beta 5 (macOS 14.1 Beta 3, Qt6)

**Comment by Drayan** [comment]
Same. Anki beta 5 won't start. MacBook Pro m1, MacOS 14.0 (Anki-23.10-mac-apple-qt6.dmg)
