### ISSUE TITLE
Don't block collection tasks when syncing media

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2736]
@abdnh I just noticed https://community.ankihub.net/t/a-progress-dialog-is-shown-for-background-operations-such-as-media-syncing-in-anki-23-10-beta/8314 - the change in behavior was not intentional. We can probably resolve this by using without_collection in start_monitoring(), and then use self.mw.backend instead of self.mw.col.

**Comment by abdnh** [comment]
My post was about AnkiHub's media syncing rather than AnkiWeb's, but the same issue applies here.
