### ISSUE TITLE
CSS-only changes in Anki are not recognized for synchronization

### ISSUE THREAD

**Issue by MtDeity** [ankitects/anki#2743]
I've encountered an issue where changes made exclusively to the CSS in the Anki PC version are not being recognized for synchronization. This leads to discrepancies in the appearance of my cards between Anki on my PC and AnkiDroid after syncing.

To replicate the problem:

1. Modify the CSS of a card template in the Anki PC version.
2. Attempt to synchronize the changes.
3. The changes to the CSS are not recognized or included in the synchronization.

This poses challenges, especially when relying on specific stylings for card appearance across devices. A workaround like modifying other parts of the template to trigger a change detection can be cumbersome.

I believe that any change, including those limited to CSS, should be recognized and synchronized appropriately. I hope this issue can be addressed to enhance the user experience across platforms.

Thank you for your time and consideration.

**Comment by dae** [comment]
This is likely an AnkiDroid issue, so does not belong here. It's also likely to be fixed when 2.17 comes out, due to architectural changes.
