### ISSUE TITLE
Grouped shapes lose their grouped status upon editing

### ISSUE THREAD

**Issue by glutanimate** [ankitects/anki#2759]
When editing a note with grouped shapes, the shapes seem to lose their grouping in the masks editor. Performing changes that prompt the note to be saved causes all groups to be dissolved.

**Steps to reproduce**:

1. Create an IO note with grouped shapes
2. Edit the note while e.g. moving one shape slightly
3. Close the editor

**Expected results**

- Shapes continue to be grouped during editing
- Shapes continue to be grouped after editing

**Actual results**

- Shapes are not grouped during editing
- Shapes are not grouped after editing

https://github.com/ankitects/anki/assets/5459332/effe9663-2ef7-486d-a5a2-3ce2488882a1

**Comment by dae** [comment]
@abdnh this appears to have regressed in #2705. We'll need to fix this before a stable release, as simply viewing a note with a group causes the editor to rewrite it, changing the cloze numbers.

**Comment by abdnh** [comment]
Will look into it today.
