### ISSUE TITLE
Shape selection seems to stick to newly created shapes, sometimes producing artifacts

### ISSUE THREAD

**Issue by glutanimate** [ankitects/anki#2769]
https://forums.ankiweb.net/t/anki-23-10-release-candidate/35967/40

Can partially reproduce this here. It seems like the selection / resize controls currently stick to newly drawn shapes. Have not been able to reproduce the [Windows-solitaire-like](https://i.kym-cdn.com/entries/icons/original/000/030/063/solitaire.jpg) artifacting yet.

Steps to reproduce the selection issue:

1. Draw a shape
2. Draw a second shape
3. Select the first shape

**Expected result**: First shape is selected

**Actual result**: First shape is momentarily selected before selection jumps back to second shape

**Comment by dae** [comment]
@hikaru-y unfortunately this seems to have regressed in #2760
