### ISSUE TITLE
Provide shortcut keys in I/O editor

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2770]
Also, allow to delete occlusion blocks (what do you call the yellow rectangles that hides what is being tested?) by tapping the `Delete` button in the keyboard would be nice

_Originally posted by @BrayanDSO in https://github.com/ankitects/anki/issues/2768#issuecomment-1774163617_

**Comment by BrayanDSO** [comment]
A nice shortcut would be to capture a image bitmap or image file pasted by pressing `Ctrl+V`

**Comment by BEST8OY** [comment]
I would like to see some of these too if possible.
Ctrl+Z for undo
holding Alt and clicking on a box to delete that box.
Holding Ctrl and clicking to select multiple box because the select tool is not really flexible if you have a lot of boxes in an image

**Comment by dae** [comment]
You can already select by shift+clicking. I think the delete key is going to be more obvious to users than using alt.

**Comment by BrayanDSO** [comment]
Also, allow to move IO masks with the keyboard arrow keys

**Comment by dae** [comment]
Some suggested shortcuts: https://forums.ankiweb.net/t/image-occlusion-enhanced-keybinds-image-occlusion/36610

**Comment by BEST8OY** [comment]
> You can already select by shift+clicking. I think the delete key is going to be more obvious to users than using alt.

@dae 
In Windows holding Shift sometime produce a notice in windows which says you've pressed Shift key more than 5 times and it's really annoying in long run.
Please evaluate the possibility of switching to Ctrl+Clicking for selecting

**Comment by dae** [comment]
Solved with #2809
