### ISSUE TITLE
Rapid title bar flickering in main menu, browsing and editing menus

### ISSUE THREAD

**Issue by FarmYard-Gaming** [ankitects/anki#2771]
Rapid flickering occurs when at the main menu, editing a card or being in the Browse tab. My title bar is blue on Windows 11 when the app is selected, and anything from typing to moving the mouse causes flickers anywhere from double the original length to all the way down the screen. The refresh upon pressing the Sync button does this too. It's distracting for a start but it also completely kills productivity and I genuinely worry about the possibility of it triggering an epileptic reaction.
I should add, I've turned off the coloured title bar in the Windows 11 Personalisation settings - instead of being blue, it's just a black flicker, so it's not that.
Neither OBS nor the Windows Game Bar picks it up, so I have to record this externally for you to see what I'm on about. It was actually more severe here than it usually is: https://youtu.be/QNG_DLkfJ_U
(The video won't fit in GitHub's 10MB limit, so a link will have to do)

**Comment by dae** [comment]
I can't reproduce this on a W11 machine here, so I presume it's related to your video card, video drivers, or some utility you have running on your machine. If none of the video drivers listed in the preferences screen of the 23.10 release candidate help, the next step would be to try and reproduce it outside Anki, and report it to the Qt people if you can. 23.10 is using Qt 6.5.3.
https://github.com/ankitects/anki/issues/2652

**Comment by dae** [comment]
The 23.10.1 release uses Qt 6.6. Did that make any difference?
