### ISSUE TITLE
Numbers don't match in Stats and Browser search

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#2783]
Stats shows 87 cards with difficulty between 0.95 and 1 while Browser search shows 2225 cards.

<img width="527" alt="image" src="https://github.com/ankitects/anki/assets/92206575/4a3c9504-9a21-42e4-a216-f39f228d9f8b">
<img width="380" alt="image" src="https://github.com/ankitects/anki/assets/92206575/16d12b19-2820-4475-a523-7401ff86e779">

Stats shows 5395 cards with difficulty between 0.45 and 0.5 while Browser search shows 24 cards.
<img width="531" alt="image" src="https://github.com/ankitects/anki/assets/92206575/9ebfb085-1ecb-4e7a-bf3c-31b7b84708ad">
<img width="430" alt="image" src="https://github.com/ankitects/anki/assets/92206575/22b30868-21fc-4cd2-b6d6-5f6d269dbda3">

<hr>

Similar issue exists with Stability.
<img width="287" alt="image" src="https://github.com/ankitects/anki/assets/92206575/d7bceca9-9450-44a6-bb8c-c2f0d1698a00"><img width="331" alt="image" src="https://github.com/ankitects/anki/assets/92206575/0e62eebc-4f65-4afe-aea7-c0752dbcba8e">

<img width="315" alt="image" src="https://github.com/ankitects/anki/assets/92206575/8d950efc-ea55-4d8d-b7ba-a51785af22a8"><img width="338" alt="image" src="https://github.com/ankitects/anki/assets/92206575/960b8eb5-ab73-42d8-a14d-786a0071de5b">

But, this issue doesn't exist for the subsequent ranges.
<img width="296" alt="image" src="https://github.com/ankitects/anki/assets/92206575/83ee6f3b-d75f-4120-9149-12dce5b4319b"><img width="346" alt="image" src="https://github.com/ankitects/anki/assets/92206575/ccd2751d-469c-499a-8b3a-833ff71107ad">

### Debug Info
Anki Version: 23.10rc2

**Comment by user1823** [comment]
I have not tested it yet, but there was no fix for the stability issue mentioned above.

Also, I found out later that the intervals graph has the same issue as the stability graph.

**Comment by user1823** [comment]
I have tested this in rc3.

The issues in the difficulty graph have been solved. Thanks!

But the issues in the stability and intervals graphs have not been solved. One thing I noticed was that the issue can't be reproduced when the suspended cards are excluded by adding `-is:suspended` to the query at the top of the Stats screen.

**Comment by dae** [comment]
I can't seem to reproduce this on a collection here. Are you able to share a small apkg that demonstrates the issue when imported into a new collection?

**Comment by user1823** [comment]
I have found out the differences. 

## Stability Graph

The difference is because of learning cards (both intraday and interday). The learning cards are included in the Browser search but not the Stats.

The following search query returns cards that are exactly equal in number to the discrepancy in the values in Stats and Search.

```
deck:current prop:s>0.5 prop:s<100.5 is:learn -is:review
```

One example of such cards is the following.
<img width="495" alt="image" src="https://github.com/ankitects/anki/assets/92206575/45376895-5abd-47c4-a54f-e113083fba71">

Not directly related to this issue, but I think that cards with stabilities between 0 and 0.5 should also be included in the first bar of the graph.

## Intervals Graph

The difference is because of abnormal cards (from a pre-made deck) that are "new" but still have an interval. I can't be sure whether these cards had these intervals when they were imported into my collection or they got them afterwards by some error.

These cards are included in the Browser search but not the Stats. The following search query returns cards that are exactly equal in number to the discrepancy in the values in Stats and Search.

```
deck:current prop:ivl>=1 prop:ivl<=10 is:new
```

One example of such cards is the following.
<img width="495" alt="image" src="https://github.com/ankitects/anki/assets/92206575/436fac11-be1b-4762-8998-0008c0adac49">

**Comment by dae** [comment]
I've added support for 0 day stability. I can't reproduce the issue with learning cards though.
![2023-11-05T13:25:50,093400665+10:00](https://github.com/ankitects/anki/assets/180542/cef50699-806f-45d2-8992-c31f126fa9ac)

Regarding the bad data with intervals, I think it's better to fix the data than Anki have to deal with all the ways add-ons and manual editing can break our assumptions.

**Comment by user1823** [comment]
> I've added support for 0 day stability.

Thanks. However, I think that it doesn't make sense to include negative stability in the Search (as seen in the screenshot of Browser shared by you)

> I can't reproduce the issue with learning cards though.

Then, I will share an apkg when I am at my Desktop.

> Regarding the bad data with intervals, I think it's better to fix the data

I also think the same way. But, what is the best way to do it?

**Comment by dae** [comment]
In the debug console, `mw.col.db.execute("update cards set ivl=0 where queue=0")`, then force a one-way sync to AnkiWeb if you use it.

**Comment by user1823** [comment]
Here is an apkg that reproduces the issue in a new profile: [Default.zip](https://github.com/ankitects/anki/files/13258700/Default.zip) (Replace .zip by .apkg in filename)

Here are my FSRS weights in case you need them:
1.1820, 1.8221, 14.4503, 64.9697, 5.0312, 1.5229, 1.7660, 0.0001, 1.8037, 0.1033, 1.1253, 1.8543, 0.1669, 0.6046, 0.0133, 0.0016, 6.3586

**Comment by dae** [comment]
I imported that into a fresh profile with FSRS enabled, and clicked on each of the4 stability graph bars, but the browser results matched each time. Maybe the start-from-0 change affected things? Please let me know if the issue continues in the next rc.

**Comment by user1823** [comment]
> clicked on each of the 4 stability graph bars

In my Anki, no bars were shown in the stability graph.

> Maybe the start-from-0 change affected things? Please let me know if the issue continues in the next rc.

May be possible. I will check in the next rc.

**Comment by user1823** [comment]
> I can't reproduce the issue with learning cards though.

You solved this issue in https://github.com/ankitects/anki/commit/fb05e430c0539895f509edca43db662908fed411 very explicitly. Looks like you forgot that you just solved it. 😅
<img width="679" alt="image" src="https://github.com/ankitects/anki/assets/92206575/c2a8128f-abd8-4b78-b036-0b5ef5cd36d0">

**Comment by dae** [comment]
Indeed 😅
