### ISSUE TITLE
Problem in RTL texts show

### ISSUE THREAD

**Issue by RZHSSNZDH** [ankitects/anki#2786]
Anki has problem in showing texts with mix of RTL and LTR parts. It shows them correct in card editing page, but not in card reviewing page (main page of card).
For example this is card's editing page and the order of words is correct:
![image](https://github.com/ankitects/anki/assets/69734726/e36b5ce8-f750-445d-9271-32cb3c3e79bd)
But in card's main view page it changes and is not correct anymore:
![image](https://github.com/ankitects/anki/assets/69734726/9be89169-27d3-46b6-bc36-97eec45db527)

**Comment by dae** [comment]
Please see https://docs.ankiweb.net/templates/fields.html#right-to-left-text, and please use the forums if you have further questions.
