### ISSUE TITLE
Display issue with HTML Editor

### ISSUE THREAD

**Issue by hnvy** [ankitects/anki#2789]
Hello,

As shown in the GIF below, part of the HTML editor becomes missing whenever you toggle "Use HTML editor by default" _and_ "Collapse by default".

```
Version ⁨23.10 (7428ecad)⁩
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
```

![sdk](https://github.com/ankitects/anki/assets/84394475/6abf389e-0e6b-4784-a4f2-32c07f25d93b)

Harvey

**Comment by NameLessGO** [comment]
Can confirm in 2.1.66 Qt 6 M1
