### ISSUE TITLE
Image occlusion editor does not render SVGs

### ISSUE THREAD

**Issue by ghost** [ankitects/anki#2800]
- **anki version:** anki-23.10-mac-apple-qt6.dmg
- this is for anki's new image occlusion note type, not the image occlusion add-on

# reproduce
1. click add new note
2. select "Image Occlusion" note type
3. click "Select Image"
4. select a `.svg` image
5. image frame is presented in the image occlusion editor, but the image itself is not

# additional details
- png images render fine
- the image doesn't render in the edit window of search/browse either
- the image does render in preview or when learning/reviewing the note
- bug remains after disabling all add-ons

**Comment by dae** [comment]
Fixed in #2809
