### ISSUE TITLE
Change Note Type page keyboard control of selecting new note type is broken

### ISSUE THREAD

**Issue by grepgrok** [ankitects/anki#2802]
On the Change Note Type page, you can tab to focus on the selector for the new note type, enter to open the options, and enter to select a new card, but note type options pane doesn't close after that and there seems to be no way to get it to close with keyboard controls alone.

This is problematic for accessibility.

**Comment by grepgrok** [comment]
I'll try to take care of this, I just wanted to make a note of it just in case.

**Comment by Say-Hi-To-Me** [comment]
I am sorry for bothering you. But can you increase FSRS's "Desired retention" from 0.97 up to 0.99 included? (idk how hard it is but it seems as replacing 7 with 9). #2803(https://github.com/ankitects/anki/issues/2803).

**Comment by dae** [comment]
Please don't post on unrelated issues.
