### ISSUE TITLE
(FSRS) Replace the word "weights" with "parameters"

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#2807]
>> This isn’t terribly important, but I think using the word “parameters” rather than “weights” is better
> 
> I think you’re right, but the next update will not have much time to bake, which will not give translators much time. Please note this on GitHub so it doesn’t get forgotten about, and we can change it when there’ll be a few weeks between changing and a stable release.

https://forums.ankiweb.net/t/anki-23-10-release-candidate/35967/130

**Comment by dae** [comment]
I've changed my mind on this one - I think we can update the English wording without breaking the existing translations. Translators won't be notified, but they can update their translations in the future if they feel it suitable to do so.
