### ISSUE TITLE
Consider providing a way to have parent decks impose a limit on reviews

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2818]
Not sure what the best course of action is here - changing the current behavior will bring back the old problems for everyone, and is potentially disruptive. We could perhaps add another preset option that controls whether the clicked-on deck takes limits from the root or from itself. It's been a while since I looked into the counts traversal code, so we'll need to look into how simple or complicated it would be to add this in. @RumovZ any thoughts?

**Comment by tomkahn** [comment]
Thank you for your openness to this and other issues, Damien.

I had originally thought that another option in the deck settings would be most fitting as this is also where people set their review limits which are affected by this setting, but a global option in Settings > Revision might also be an option? If so, a hint in the deck options that mentions this might be helpful. I'd be fine with either.

**Comment by RumovZ** [comment]
I can't really tell, either, without investigating further, but I could look into it.
However, regarding the [use case last mentioned on the forum](https://forums.ankiweb.net/t/a-common-problem-for-law-and-med-students-with-the-v3-scheduler-per-branch-counting-of-new-cards-reviews-affecting-deck-limits/36866), I had a different idea: There could be a global counter similar to the timebox limit. So you set it to 100, and every 100 reviews it would tell you to take a break. Would that be sufficient for other use cases, too?

**Comment by dae** [comment]
On the one hand, doing this as a timebox has some appeal, as it avoids having to try and weave this into the existing deck list / reviewing code, and avoids an extra option users have to think about. On the other hand, it means the tracking gets pushed from the backend into the frontend (timeboxing is handled at the Qt layer), which means all the different clients have to re-implement the logic. Even if we shifted the tracking code to the backend, the frontend would still need extra logic to handle the case where the timer has elapsed and present a dialog. For this reason, I think I'd lean towards a deck option instead, if it is not going to make things much more complicated - WDYT? If you concur and this interests you, if you wouldn't mind looking into this further to see how feasible it will be, that would be appreciated.

**Comment by RumovZ** [comment]
Sure, will do.
