### ISSUE TITLE
Show deck name during study

### ISSUE THREAD

**Issue by nobe4** [ankitects/anki#2844]
Hi 👋 

Neither the Web or Desktop app show the current deck the card is pulled from:

This is generally fine but can lead to confusion when some deck share information.

For instance:

![Image](https://github.com/ankitects/anki/assets/2452791/98a9c767-ca76-46f4-a559-0e993ff549dd)

This view could match:
- [ASL Alphabet](https://ankiweb.net/shared/info/654252746)
- [NATO phonetic alphabet](https://ankiweb.net/shared/info/766972333)
- and others

A possible improvement would be to add a line showing the name of the deck. E.g.:

![Image](https://github.com/ankitects/anki/assets/2452791/d24aa452-8792-475e-a1df-feb7918fe402)

Would that be an worthy addition?

**Comment by dae** [comment]
Please use the forums for feature requests. This is already possible - see the special fields section of the manual.
