### ISSUE TITLE
transforms to groups of objects are not persisted

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2876]
- When items are made into a group, and the group resized, the changes are not persisted
- When 2+ items are selected but not made into a group, resizing the selection results in glitchy behavior

https://forums.ankiweb.net/t/cannot-change-image-occlusion-mask-dimensions/38078

**Comment by dae** [comment]
@abdnh interested in looking into this?

**Comment by abdnh** [comment]
Will have a look
