### ISSUE TITLE
Deck options screen can be slow to appear

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2877]
Especially when screen is wide enough for two columns. Appears to be due to our use of [column-count: 2](https://github.com/ankitects/anki/pull/1260), and each extra option we add seems to make it a bit slower. Might be worth thinking about a switch to css grid? Having options flow from left to right instead of top to bottom first is not ideal, but neither is the slowdown.

There's also a noticable slowdown when toggling FSRS on/off when two columns are shown.

@hikaru-y @abdnh @kleinerpirat any thoughts?

**Comment by tatsumoto-ren** [comment]
Even with one column the window going to take time to appear, since it's not using a native toolkit.
