### ISSUE TITLE
Anki 23.12beta2 qt6 MacOS app crash

### ISSUE THREAD

**Issue by hoonlight** [ankitects/anki#2880]
Hi,

I'm having an issue with intermittent crashes when launching apps on my M1 pro macbook. 
This happens after installing 23.12beta2-qt6. I am using macOS sonoma 14.2 public beta.

The logs are shown below.
[log.txt](https://github.com/ankitects/anki/files/13623072/log.txt)

**Comment by hoonlight** [comment]
I even rolled back ANKI to the previous stable version, but I still have the app crashing issue.

**Comment by dae** [comment]
Have you tried all the steps on https://docs.ankiweb.net/troubleshooting.html?

**Comment by hoonlight** [comment]
> Have you tried all the steps on https://docs.ankiweb.net/troubleshooting.html?

I installed 23.12beta3 and followed that process, and everything seems to be fixed. Thanks.

**Comment by hoonlight** [comment]
This issue has come up again. However, it seems to have been resolved after installing 23.12.beta2 qt6.

**Comment by dae** [comment]
'reset window sizes' in the preferences screen may help in the future.
