### ISSUE TITLE
Anki blocks on startup when no Internet connection is available

### ISSUE THREAD

**Issue by sommerluk** [ankitects/anki#2881]
# Title

Anki blocks on startup when no Internet connection is available

# Steps to reproduce

1. Make sure you have an AnkiWeb account
2. Make sure you have configured Anki Desktop to use this account
3. Make sure you have enabled automatic sync: Tools->Preferences->Syncing->Automatically sync on profile open/close
4. Close Anki Desktop
5. Make sure you have no Internet connection (disable Wifi/LAN…)
6. Open Anki Desktop
7. Anki Desktop shows an error message “Please check your Internet connection”  ![neuer screenshot](https://github.com/ankitects/anki/assets/6830724/239968d3-f3fe-433a-ba1c-57e27912a92d)

# Actual behavior

- Anki Desktop does not react neither to clicks on the “OK” button nor to the return key on the keyboard.
- It seems not possible to start Anki Desktop without Internet connection.
- The only way to close Anki seems to be to kill it.

# Expected behaviour

- Anki Desktop reacts to clicks on the “OK” button and to the return key on the keyboard. It then starts up without having synchronized.

# Additional information

- It seems like both, the progress window and the error message window have focus. At least that’s what the window’s colored borders suggest.
- This bug does _not_ occur on synchronization while _closing_ Anki Desktop. So if you start up Anki _with_ an Internet connection, then disable the Internet connection, then close Anki, you get an error message that actually reacts on mouse clicks and key strokes as expected.

# Anki version information

Version ⁨23.10.1 (fac9e0ee)⁩
Python 3.9.15 Qt 6.6.0 PyQt 6.6.0

(Has been installed via Flathub.)

# Environment version information
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-89-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700HQ CPU @ 2.80GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630

**Comment by dae** [comment]
I've pushed some fixes. When 23.12beta3 comes out, please let me know if you can still reproduce the problem.

**Comment by sommerluk** [comment]
This issue still persists in the 23.12.1.

It seems the window containing the progress bar is modal to the window with the “OK” button, which prevents the user to actually push the “OK” button.

**Comment by dae** [comment]
I can't seem to reproduce this - I don't get a 'checking...' popup, whether the network is inaccessible or down (instant failure / delayed failure). Do you have any add-ons installed? Can you reproduce it using the official Anki bundles on our website?

**Comment by sommerluk** [comment]
Thanks for your patience.

It seems the offending add-on is https://ankiweb.net/shared/info/369581638 (Spell Checker). The error only occurs if _both_ this add-on is installed _and_ Anki is configured to sync automatically on startup.

There is in existing bug report https://github.com/ValentinSchmitz/spell-checker/issues/8 for the add-on, but it has not been addressed since.
