### ISSUE TITLE
Import suggest two fields when one exist

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#2882]
Import the file [anki.csv](https://github.com/ankitects/anki/files/13624216/anki.csv)

Select "comma" separator. Keep HTML not allowed.

The table show there is a single field. still, field mapping did not update and show two example of fields, separated by the space, as it was first offered.
![2023-12-09-143154_1330x1081_scrot](https://github.com/ankitects/anki/assets/357361/e7243063-1106-4041-a622-0eed15295ff6)

It should offer a single field.

**Comment by dae** [comment]
@RumovZ heads up
