### ISSUE TITLE
Field mapping's preview try to display html

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#2883]
Try to import a CSV file with some HTML content. For example my first line is `<img src="major_C______increasing_Dflat__decreasing.svg"/>,`.
Unselect "allow HTML in fields"

As you can see, the field mapping show a broken image instead of showing some HTML code
![2023-12-09-143435_1323x1146_scrot](https://github.com/ankitects/anki/assets/357361/44451936-1223-4788-bf34-c403304f3c59)

**Comment by dae** [comment]
@kleinerpirat this appears to have regressed in #2227, as our Select component is using `@html`. Do you recall what prompted the change? Can you think of any Select usages where we actually need to support HTML?
