### ISSUE TITLE
Card info should perhaps update instead of toggle?

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2892]
https://forums.ankiweb.net/t/have-to-select-info-twice-when-the-card-info-window-is-already-open-first-time-just-closes-the-window/38396

**Comment by akashreddy03** [comment]
The card info updates automatically whenever the selected row changes in the browse window and there is no need to right-click and select info again. I guess we can either do nothing when the dialog is already open or just leave it as it is and let it toggle (i.e close the window)

**Comment by dae** [comment]
Yep, good point. But perhaps we should 'bring to top' instead of toggling, like when the user presses 'a' when the add screen is behind the main window? Given that we're automatically updating already though, this doesn't seem super urgent.
