### ISSUE TITLE
"Type error, failed to fetch"

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankitects/anki#2895]
I just go this error message. "Type error, failed to fetch"

I was done with a deck and left anki opened during hours. But not over the hour of new day.
This is not a big deal, but quite strange, and would be better without it.

![2023-12-17-160532_834x1406_scrot](https://github.com/ankitects/anki/assets/357361/3cf2721b-905e-4157-9104-2b042eeff9d0)

I can't really try to reproduce without add-ons, given it may take hours, but  my add-ons probably not caused it. I have 
![2023-12-17-161534_409x137_scrot](https://github.com/ankitects/anki/assets/357361/fb89140d-6930-419b-87d4-8975370596c6)

**Comment by CodingVampyre** [comment]
I appear to have the same issue, and for me, **no add-ons** are active. The error appears ever few hours and do not seem to have an effect on my actual usage. I still can go through my cards as usual. 

Using 
- MacOS 14.1.2 and 
- Anki Version ⁨23.12.1 (1a1d4d54)⁩ Python 3.9.15 Qt 6.5.3 PyQt 6.5.3

**Comment by abdnh** [comment]
I hit this yesterday after my device went to sleep for hours while the congrats screen is active. The congrats screen refreshes every minute, and I suspect the error is coming from there.

**Comment by boxed** [comment]
I get this several times a day with 23.12.1. I leave Anki open on the "congratulations" page too. 

I would think this issue should be reopened.

**Comment by boxed** [comment]
Upgraded. Got the error. So not fixed unfortunately.

**Comment by dae** [comment]
What type of computer is it, and what are you doing around the time the errors occur?

**Comment by boxed** [comment]
MacOS Sonoma 14.4.1, I've just left anki open at the "congratulations" screen.

**Comment by dae** [comment]
And to double-check, you confirmed in the about screen that you're running 24.04?

Do you see exactly the same as the screenshot Arthur posted above when it happens?

**Comment by boxed** [comment]
![Screenshot 2024-04-10 at 10 12 46](https://github.com/ankitects/anki/assets/332428/7d037e74-4c80-4f81-b08b-b67b9fae91f5)
![Screenshot 2024-04-10 at 10 12 57](https://github.com/ankitects/anki/assets/332428/9d2471e1-b7dc-474b-bc02-aab09fd4504f)

**Comment by dae** [comment]
Thank you, I've reopened the issue. We're masking the error in the 1 minute refresh, so I guess this is happening when we reload the page every 10 minutes. Not sure why the network would fail in such circumstances however, if your machine is not going to sleep or waking up around the time the error pops up.

**Comment by adamschmalhofer** [comment]
Also hit by this. Running the flatpak with
Version ⁨24.04.1 (ccd9ca1a)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1

**Comment by Arthur-Milchior** [comment]
> What type of computer is it, and what are you doing around the time the errors occur?

Ubuntu.
And when the error occurs, I have left anki open, doing a lot of things without touching anki.

I can't state whether it still occurs. I'm so late in my reviews that I have not reach this screen in quite some time

**Comment by adamschmalhofer** [comment]
I think it has now been a while since I've been hit by this. Now on Version ⁨24.06.2 (33a92379)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1

**Comment by dae** [comment]
Is there anyone using 24.06.2+ that is still seeing this error?

**Comment by dae** [comment]
Please let us know if you are.

**Comment by adaschma** [comment]
After months of this problem being gone, it is now reappearing

Version ⁨24.11 (87ccd24e)⁩
Python 3.11.9 Qt 6.7.2 PyQt 6.7.1

on Flatfak/Linux.

**Comment by jedgett** [comment]
This was fixed for me in 24.06-ish but it's back now in ⁨24.11 on MacOS 15.2. Same as before it pops up while Anki is running in the background sitting on the Congratulations screen.

**Comment by abdnh** [comment]
#3594 comes to mind here, but the error is masked as @dae [said here](https://github.com/ankitects/anki/issues/2895#issuecomment-2046926263)...
