### ISSUE TITLE
Merging cloze notetypes can break them

### ISSUE THREAD

**Issue by RumovZ** [ankitects/anki#2904]
Regarding the report of basiskarten in https://forums.ankiweb.net/t/anki-23-12-beta/37771/121, my working hypothesis is that the user changed the notetype of previously imported notes and that's why the various different notetypes got merged. If they didn't, it would indicate a bug. basiskarten is investigating this.

Definitely an issue is the merging of cloze notetypes. I hadn't considered those at all in the initial implementation. I suggest the following solution:
1. For cloze notetypes, fields are merged as usual, but templates are not, because the (first) template of each notetype is assumed to be identical, regardless of id.
2. If an attempt is made to merge a cloze with a regular notetype, the import aborts with an error. I don't see any way to merge in a somewhat reasonable fashion in this case.

Considering this issue has the potential to break notetypes, do you want to include the fix in 23.12? I would then try to submit it in the next couple of days.

**Comment by dae** [comment]
I'm torn - it's an important issue when it does happen, but I'd like to get 23.12 out, and I don't want you to feel pressure to get this fixed if you have more important commitments like family over this holiday period. So, whenever you don't have anything better to do would be fine :-) 23.12.1 can always be released soon after if necessary.

**Comment by RumovZ** [comment]
Thanks for your consideration. I guess I'll have the time, but it's hard to predict.
On this note, happy holidays! 🎄

**Comment by dae** [comment]
Thanks Rumo, hope you have a good one :-)
