### ISSUE TITLE
Documentation for Console Output for Mac is wrong: https://addon-docs.ankiweb.net/console-output.html

### ISSUE THREAD

**Issue by TommasoBendinelli** [ankitects/anki#2905]
Hi there,

The documentation https://addon-docs.ankiweb.net/console-output.html for Mac user is wrong:

This is how it is.
**macOS**
Open Terminal.app, then enter the following text and hit enter:
/Applications/Anki.app/Contents/MacOS/anki

This is how it should be
**macOS**
Open Terminal.app, then enter the following text and hit enter:
/Applications/Anki.app/Contents/MacOS/AnkiMac

**Comment by dae** [comment]
The documentation is correct for recent Anki releases.
