### ISSUE TITLE
Avoid animating hover changes in webviews

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2908]
Currently we animate hover transitions in the default interface, and these animations perform quite poorly on some video drivers. This makes the interface feel laggy/clunky, and is a bad out-of-box experience. Compare the standard hover:

https://github.com/ankitects/anki/assets/180542/7839197c-8ab3-482a-bb75-9952de7e47ee

With the hover performance in minimalist mode:

https://github.com/ankitects/anki/assets/180542/9ae67bf4-d253-4739-bc38-0391a3869710

We should remove the animation, but keep the color change. 

f10a29a93dc2dc66cabc91bec58d489204f53841 is semi-related, though in that case I removed the hover change altogether, instead of just removing the animation (the transition directive in the css)

**Comment by jcznk** [comment]
Another thing that might be worth considering is disabling/removing  `backdrop-filter: blur(var(--blur));` from the following code. As far as I understand, it is only useful when the user sets a custom background image, which is currently only possible using an add-on. Also, it seems to be responsible for the 'flickery' behavior of the Deck Browser experienced by some users (https://forums.ankiweb.net/t/anki-main-screen-get-really-flickery/37044, https://forums.ankiweb.net/t/flickering-bug-at-home-screen/29441, https://forums.ankiweb.net/t/flashing-when-scrolling-in-newest-release-of-anki/31160). At least, disabling that line seems to fix the issue on my computer.

From: http://127.0.0.1:62938/_anki/css/deckbrowser.css

```diff
.fancy table {
    border: 1px solid var(--border-subtle);
    border-radius: var(--border-radius-medium);
    box-shadow: 0px 2px 1px -1px rgba(20,20,20,.12), 0px 1px 1px 0px rgba(20,20,20,.06), 0px 1px 3px 0px rgba(20,20,20,.04);
    transition: box-shadow var(--transition) ease-in-out;
    background: var(--canvas-glass);
- backdrop-filter: blur(var(--blur));
}
```

**Comment by dae** [comment]
@kleinerpirat any thoughts?
