### ISSUE TITLE
Shortcuts are conflicting with text input in image occlusion on mobile

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2915]
We're already testing for `!$textEditingState` which works in the desktop editor, but we perhaps need to be adjusting that state as the user navigates between the two tabs on mobile. Original report:

https://forums.ankiweb.net/t/bugs-report-image-occlusion-problems/38868

@abdnh if you're not busy with holidays/family, would you mind looking into this when you have a chance? It should be a pretty easy fix, and you can test the mobile client's page via http://localhost:40000/_anki/pages/image-occlusion.html#test-/home/dae/foo.jpg, replacing the path at the end with a valid path.

**Comment by abdnh** [comment]
I guess this can be closed.

**Comment by dae** [comment]
Thanks Abdo!
