### ISSUE TITLE
Incorrect stability of card with incomplete revlog

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#2921]
In Anki 23.12.1 (as well as 23.10.1), the cards with incomplete revlog have incorrect stability.

For example, the following card has a stability of 2.13 months but I expected it to be 9.44 months (for SM2 retention = 0.92).

<img width="533" alt="image" src="https://github.com/ankitects/anki/assets/92206575/465e9630-d3a8-4d2b-b10f-cc93b995cc07">

The card is attached for easy reproduction: [Bug.apkg.zip](https://github.com/ankitects/anki/files/13800708/Bug.apkg.zip) (rename the file to remove .zip at end)

The stability is not corrected if I change the weights in Deck Options and click "Save" to recalculate memory states. However, if I review the card on AnkiDroid and then reschedule it using helper add-on's auto-reschedule after sync function, the stability gets corrected.

Example of such card:
<img width="560" alt="image" src="https://github.com/ankitects/anki/assets/92206575/c7d42e8f-b5aa-4add-b27b-07ef15653240">

**Comment by dae** [comment]
The review log is only used when the are 2+ usable entries. For 0 or 1 entries, stability is inferred from the card state.

**Comment by user1823** [comment]
> For 0 or 1 entries, stability is inferred from the card state.

This can cause issues in the 1 entry case. If the SM2 retention and desired retention are not the same, the stability will change each time the memory states are recalculated.

So, I think that the revlog should be used even in the 1 entry case.

**Comment by dae** [comment]
I don't disagree, but it's not a trivial change, as set_memory_state() expects to only receive an existing memory state if there are 2+ entries, as the later entries are applied to the initial learning state.

**Comment by user1823** [comment]
> but it's not a trivial change

I understand. But, a solution must be found. I am sure that I am not the only person affected by this issue.

**Comment by user1823** [comment]
Fixed in https://github.com/ankitects/anki/pull/3639
