### ISSUE TITLE
Anki-web migration to Next.js with Shadcn/UI

### ISSUE THREAD

**Issue by filipedev6** [ankitects/anki#2934]
- **Have a question or feature suggestion?** Migration of the main site built in Jquery to Next.js using Shadcn/UI.

Main documentation of Next.js - [Next.js](https://nextjs.org)
Main documentation of Shadcn/UI - [Shadcn/UI](https://ui.shadcn.com)

I have a great desire to participate in the development of this new feature for the growth of anki and recognition of the platform, a page built with the main technologies, currently has a chance of greater growth.

**I will bring updates on this issue soon**

**Comment by dae** [comment]
Thank you for the offer, but I'm afraid I'm not interested in changing AnkiWeb's architecture at this time.
