### ISSUE TITLE
Incorrect anki card being displayed

### ISSUE THREAD

**Issue by jasonaher** [ankitects/anki#2946]
I've been having an issue where the wrong card is being displayed. The bug displays itself in many ways. One iteration is where the front side of the card is some card already studied that day, but the back side is the correct card. Sometimes, only the back side is incorrect, and rarely both sides are actually incorrect, and I can tell because well it's always of a card I completed that day and the time interval suggestions are not changing as the real card would after whichever choice would be made. Giving the card an input and then undoing it will usually display the correct card, but not always, and it's getting really annoying because it will happen a lot. Restarting the app doesn't really seem to have an effect on the appearance of the bug. Restarting my computer has had little to no effect. I am on the latest version, and going to tools to check database has also had no effect. I am currently on the latest version 23.12.1 and on windows.

**Comment by abdnh** [comment]
Try switching the video driver from the preferences.
