### ISSUE TITLE
Display bug related to the string "fl"

### ISSUE THREAD

**Issue by lijunkang12** [ankitects/anki#2968]
Hi, I have encountered one peculiar bug in the editor of cards. If I type "fl" or "fi" in a field (not the HTML one), then insert a line change between "f" and "l" or "i", then the HTML editor correctly display ```f<br>l```, but the field actually shows
```
fl
l
```
If I add a letter after the first line, then the phantom "l" goes away.

Here is my debug info:

Anki 23.12.1 (1a1d4d54)  
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.3-arm64-arm-64bit

**Comment by dae** [comment]
I can't reproduce this. Does the issue exist without add-ons? Is your keyboard set to English input?

**Comment by lijunkang12** [comment]
Thank you for your reply. I do not use any add-ons, and my keyboard is indeed set to English input.

Maybe I have not been more precise in my description. To reproduce this bug on my computer: I open the window to add new card (titled "Add"), enter the following in the editor field (not the HTML one, the other one; I don't what its name is): the string "fl", move the cursor to between "f" and "l", then hit the return key on my keyboard.

The font for my note is Helvetica Neue, but I suspect that is not the culprit; the issue persists if after changing the font to Times.

**Comment by dae** [comment]
It doesn't seem to happen for me:

https://github.com/ankitects/anki/assets/180542/24f230e4-d7fc-4a10-b05a-3b2dc04f8ca0

**Comment by lijunkang12** [comment]
I went back to test some popular fonts and discovered that this bug only happens to certain fonts (Helvetica, Helvetica Neue, Times, Futura), but not to the others (e.g. the default font Arial, Times New Roman, Georgia, Monaco, etc).

**Comment by dae** [comment]
Thanks, I can reproduce it with Helvetica. Let's see if the next Qt6 update (~hopefully 2 weeks) helps.

**Comment by dae** [comment]
Next Qt release still isn't out.

**Comment by lijunkang12** [comment]
It's okay; this is only a minor bug. I am already grateful that you spent time on diagnosing the problem. Please take your time!

**Comment by lijunkang12** [comment]
This problem no longer persists in 24.04beta1. Thank you!

By the way, do you have a (or an estimation of) release date for the stable version?

**Comment by dae** [comment]
Hopefully within a few weeks.
