### ISSUE TITLE
Theme → Follow System should not require a restart (Fedora/GNOME)

### ISSUE THREAD

**Issue by Igetin** [ankitects/anki#2970]
# Description

When using the "Follow System" option for the "Theme" setting of Anki, the system theme changes are only reflected after the application is restarted. On my system, I have configured the dark mode preference to change according to the time of day, and pretty much all of my applications change their appearance automatically when the system preference changes. Anki does not. It should be possible for Anki as well, since Telegram, which also uses Qt, reacts to the system theme change immediately.

# Steps to reproduce

1. Go to _Tools_ → _Preferences_ → _Appearance_; select the _Follow System_ option for _Theme_
2. Switch the system dark mode preference
3. Anki does not react to the preference changing

# Video demonstration

https://github.com/ankitects/anki/assets/14016863/a5b0be80-eaf4-4210-bb0b-32232399eb47

# Anki version

Anki 23.12.1 (Qt 6)

# System details

- Operating system: Fedora 38
- Desktop environment:  GNOME 44.7
- Windowing system: X.Org server 1.20.14

**Comment by dae** [comment]
On Linux the theme is only checked every 5 minutes, as it can cause log spam on some distros.
