### ISSUE TITLE
Assigned memory state after 'set due date'+optimize incorrect

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2998]
If the user uses an interval like '0!' to set a card's due date, then optimizes the deck to assign new memory state, the card will receive the wrong stability.

Reported on https://forums.ankiweb.net/t/old-reviews-before-forget-used-in-fsrs-optimisation/40819/17?u=dae

**Comment by abdnh** [comment]
Is this still valid after https://github.com/ankitects/anki/pull/3002#issuecomment-1937464827?

**Comment by dae** [comment]
I think so, yes. Pick a card with a long interval, use 'set due date' to give it '0!', and then make a minor change to the FSRS weights and save. The card has an interval of 1 day but a stability of the interval before 'set due date'.

**Comment by L-M-Sherlock** [comment]
> The card has an interval of 1 day but a stability of the interval before 'set due date'.

Is it expected? The `set due date` shouldn't change the stability.

**Comment by L-M-Sherlock** [comment]
My test result after 2b890b0eee7a9fb40a137ec2ce7aacd9044d0258

<img width="800" alt="image" src="https://github.com/ankitects/anki/assets/32575846/157c6ef8-9840-4016-9913-122529be7fae">

<img width="800" alt="image" src="https://github.com/ankitects/anki/assets/32575846/117f7830-de54-44fa-8131-9400d9d1f64e">

**Comment by user1823** [comment]
> Using a separate revlog entry to distinguish them is an option in the future

If this is planned, I think that doing this as early as possible would lead to the maximum benefit (by preventing the accumulation of "ambiguous" revlog entries in users' collections).

Anyway, creating a separate revlog entry should not be a difficult task apart from deciding how exactly to distinguish them.

**Comment by L-M-Sherlock** [comment]
Maybe we can integrate the feature `Grade Now` of this add-on: https://ankiweb.net/shared/info/1021636467

**Comment by user1823** [comment]
> Maybe we can integrate the feature Grade Now of this add-on

Yes. But, I think there is a more pressing need to use separate revlog entries for "Set Due Date" and "Reschedule cards on change".

**Comment by abdnh** [comment]
I guess this can be closed after #3508
