### ISSUE TITLE
Revlogs before Forget used for optimization if not followed by Learn

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3001]
https://forums.ankiweb.net/t/old-reviews-before-forget-used-in-fsrs-optimisation/40819/17

Solution:

Search for Forget entries (manual entry & factor = 0) and filter out the entries up to the Forget entry.

This filter needs to be inserted before the code that decides whether to use normal formula or memory_state_from_sm2 to initialise the memory states.

**Comment by user1823** [comment]
> If Forget is the last entry, the card will be new, and memory state is not assigned to new cards.

Yes, but the revlogs of those cards are being used for optimization, which is not appropriate.

Also, if the card is introduced using Set Due Date after being Forgot, the old revlogs would continue to influence the memory states (unless the above-mentioned patch is applied).

**Comment by L-M-Sherlock** [comment]
> Search for Forget entries (manual entry & factor = 0) and filter out the entries up to the Forget entry.

I have a simple solution. Just insert a code to check whether the last entry of revlog is generated by `Forget`.

https://github.com/ankitects/anki/blob/3110e2d23543d663323924ab5360992a36879c92/rslib/src/scheduler/fsrs/weights.rs#L181-L188

**Comment by user1823** [comment]
> Just insert a code to check whether the last entry of revlog is generated by Forget.

It won't work if the revlog is like follows:
> ... R R F S R R

Here,
- F = Forget
- S = Set Due Date
- R = Review

**Comment by L-M-Sherlock** [comment]
I get it. An improved version is check whether we have found the last learning entry when the current entry is generated by Forget.

**Comment by user1823** [comment]
What if there is no learn entry (because the user has a habit of introducing new cards by Set Due Date)?

I think that the solution proposed by me is simple enough and covers all the cases.

**Comment by L-M-Sherlock** [comment]
I need to read the source code to find out an appropriate place to add the new card filter.

**Comment by user1823** [comment]
It looks like the code needs some more comments to make it easier to understand.

By the way, I recommend you to hold off working on this issue until https://github.com/ankitects/anki/pull/2922 is merged to avoid conflicts.

**Comment by L-M-Sherlock** [comment]
I find that the simplest method is to add `-is:new` to the default query.
