### ISSUE TITLE
Inconsistency between previewer and reviewer

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3004]
For a custom card template, the ```<hr>``` between the Question and the Answer is not appearing in the reviewer though it appears in the previewer. I understand that Anki can't support every possible customization of the templates. But since the preview is correct, the reviewer is also expected to display the card correctly.

Reviewer:
<img width="498" alt="image" src="https://github.com/ankitects/anki/assets/92206575/6a2662e2-65ec-41d5-aa4e-95d3f88573a6">

Previewer:
<img width="483" alt="image" src="https://github.com/ankitects/anki/assets/92206575/5009ee2e-400c-4ff0-87f8-7996c1db8135">

Card: [bug.apkg.zip](https://github.com/ankitects/anki/files/14229293/bug.apkg.zip) (rename to remove .zip at the end)

Edit:
The issue is about the use of quotes in the id attribute (i.e., `<hr id=answer>` vs `<hr id="answer">`)

For a basic card, the horizontal line displays whether the quotes are used or not. But for some reason, for this card template, it is not being displayed in the reviewer when quotes are not used.

To avoid confusion, it is probably better to make things consistent.

**Comment by user1823** [comment]
I have tried to simplify the template as much as I could while still reproducing the issue. Here is the simplified template:

Front:
```html
<div id='front'>{{Front}}</div>
<div id='type'>{{type:Back}}</div>
```

Back:
```html
<div id='front'>{{Front}}</div>
<hr id=answer>
<div id='back'>{{Back}}</div>
```

There is nothing special in the styling section.

**Comment by dae** [comment]
Probably related to the hack in https://github.com/ankitects/anki/blob/f4a8f7d9c7bc21f6f519758b8f208117a914b7ff/qt/aqt/reviewer.py#L721
