### ISSUE TITLE
Previous/Next bug in Docs

### ISSUE THREAD

**Issue by NameLessGO** [ankitects/anki#3005]
Problem:
When using Left/Right arrows in [Anki Manual](https://docs.ankiweb.net/), the doc can't separate between `2.1 Windows` and `2.1.1. Install & Upgrade` which causes `next` to loop the platform page, this problem affects [Mac](https://docs.ankiweb.net/platform/mac/installing.html) and [Linux](https://docs.ankiweb.net/platform/linux/installing.html) subpages

<img width="185" alt="image" src="https://github.com/ankitects/anki/assets/66227691/4438063c-3d59-4bfd-9c45-7ef83d6dea46">

What should be like:
<img width="136" alt="image" src="https://github.com/ankitects/anki/assets/66227691/8562c2a0-0e75-46fb-9704-060a2ad586b9">

Repo: https://github.com/ankitects/anki-manual

Mdbook previous/next function
https://rust-lang.github.io/mdBook/format/theme/index-hbs.html?highlight=next#2-previous--next

**Comment by dae** [comment]
I don't think index.hbs is relevant here. It's an issue with how the pages are listed in _SUMMARY.md, and if we change it, it will mean we'll need to write separate subcategory pages.

**Comment by thewilliamdrew** [comment]
I just added separate subcategory pages. Also updated links to problem pages (linking to the `.md` file instead of the live URL)

**Comment by dae** [comment]
I think this issue is on @abdnh's todo list.

**Comment by thewilliamdrew** [comment]
Oh I'm sorry! I didn't see that anywhere. 

I just noticed that the "bug" was probably because in `SUMMARIES.md`, the subpage and sub-subpage for platforms were pointing to the same `.md` file.
