### ISSUE TITLE
Fuzz doesn’t work with short maximum interval

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3015]
> I find that the maximum interval is applied after fuzz_bounds. So if the original interval is longer than maximum interval, the fuzz intervals will be longer than maximum interval, too. The current implementation will clamp the fuzz lntervals with maximum interval, so they will be equal to maximum interval. Should we apply maximum interval to the original interval before fuzz?
> 

Originally reported on https://forums.ankiweb.net/t/fuzz-doesnt-work-with-short-maximum-interval/41274

**Comment by L-M-Sherlock** [comment]
I think it's not a FSRS-specific issue.

**Comment by dae** [comment]
🤦 I'm too used to associating your reports with FSRS stuff :-)
