### ISSUE TITLE
show preset in card info

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3020]
> could we add a feature request for displaying preset in card information, seems like a good enhancement

Originally reported on https://forums.ankiweb.net/t/issues-with-anking/41344/8

**Comment by jcznk** [comment]
Another thing that could be useful to display on the card info screen is the original deck a card belongs to, when the card is being reviewed in a filtered deck. Currently, the only ways to check the original deck are to either 1. add {{Deck}} to the template, or 2. load the card in the Browser and check the Deck column.

For example, something like: 'Deck: Filtered Deck (Original Deck)', like in the Deck column of the Browser.

**Comment by dae** [comment]
Sounds good.
