### ISSUE TITLE
Some siblings are not buried during review

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3026]
When the new card in the following sample deck is reviewed, the sibling is not buried.

Deck: [Bug.zip](https://github.com/ankitects/anki/files/14393391/Bug.zip) (Rename to replace .zip by .apkg)

This bug is reproduced on both Desktop and AnkiDroid.

**Comment by dae** [comment]
Anki fetches cards cards in learning/review/new order, and can only bury siblings that come later in that order. Since new comes last, the review card doesn't get buried. Ideally it would not have this limitation, but there were technical reasons why it's implemented this way.

**Comment by user1823** [comment]
If the review card was due today, is it possible that Anki would have shown me the new card first?
- If so, then there is a problem that must be solved even if it requires a workaround.
- If not, then we can close this issue.

**Comment by dae** [comment]
Review cards are gathered earlier, so they will always be shown in preference to new siblings if burying of both is enabled.
