### ISSUE TITLE
Ligatures misunderstood by text comparator

### ISSUE THREAD

**Issue by nkalivoda** [ankitects/anki#3033]
[Ligature Problem.apkg.zip](https://github.com/ankitects/anki/files/14397407/Ligature.Problem.apkg.zip)

If a typed answer containing an incorrect ligature is submitted, the text comparator only sees the correct part of the ligature and ignores the incorrect part, highlighting the incorrect answer in green. This has been observed with incorrect "fi" being matched as green with back "f", but presumably occurs with other ligatures as well.

To see an example, import the attached deck, which contains one card with the front:

> The back of this card is "f". Type "fi" to see that the "i" is highlighted in green even though it is an error.

and back:

> f

Follow the instructions on the card, and you will see the problem.

Danika_Dakika on the forum has already found a solution. One just needs to add the following to the card styling (under .card):

>  font-variant-ligatures: no-common-ligatures;

However, it would probably good if the problem didn't arise in the first place.

**Comment by Danika-Dakika** [comment]
Forum thread for reference: [Error in text comparison highlighting (type: card)](https://forums.ankiweb.net/t/error-in-text-comparison-highlighting-type-card/40643?u=danika_dakika)

**Comment by Danika-Dakika** [comment]
I think it definitely would. This outlines [the categories](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures#values) pretty well.

**Comment by dae** [comment]
So to clarify what's required here, presumable we'd want to set `font-variant-ligatures: none` on `code#typeans` (.card may cause unwanted side-effects)?

**Comment by Danika-Dakika** [comment]
I think so. This won't ever be a problem in type-answer with the default monospaced font because it doesn't have ligatures. So since `code#typeans` is the only way to change the font to one that _does_ use ligatures, preventing ligatures there should do it.
