### ISSUE TITLE
"Creating backup" message interrupts typing

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3039]
While typing in the fields for creating a new note, I am often interrupted by the "Creating backup" popup, which takes me to the deck screen.

The following forum thread mentions a similar problem which was said to be already fixed: https://forums.ankiweb.net/t/creating-backup-popup/36590

Anki version: 23.12.1

**Comment by dae** [comment]
Did you test without add-ons?

**Comment by dae** [comment]
I can't tell you which to try disabling, as I don't know what they do in the background. To reproduce the issue, you could try setting your backup frequency to 1 minute (but it will only be checked every 5 minutes).

**Comment by user1823** [comment]
I have not seen the issue since the last time I posted. It might be because:
- the issue was in one of the add-ons that I disabled; or
- the issue was in Anki but fixed in 24.04 beta (I upgraded to the beta the same day it was released).

Anyway, since you don't have to do anything to fix it, I am closing this issue. Sorry for the trouble.

**Comment by dae** [comment]
No problem; glad to hear it's resolved.
