### ISSUE TITLE
Remind the user to optimize FSRS parameters occasionally

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3042]
> what about adding a pop-up window that regularly (say, once per month or once per three months) reminds the user to re-optimize parameters? I remember you mentioned that it was planned.

We could record timing.days_elapsed into the collection config each time all deck configs are optimized at once, then check if more than 30 days has elapsed since it was last recorded. 

Presenting the information to the user, the simplest option would be to shown a warning in the deck options screen if more than 30 days has elapsed. This requires no changes to the frontend on any of the clients, and avoids a few issues with a pop-up that I'll cover below. The downside is that users may forget to optimize if they never open their deck options.

The alternative is to present some sort of pop-up outside of the deck options screen. That will require new logic in each of the clients, and we need to be careful about timing:

- A modal pop-up can conflict with other pop-ups such as the syncing window, new version notice, etc.
- If the dialog gives the user the option to 'optimize now', the timing relative to a sync matters. After the initial sync on startup is best, as that way we won't clobber incoming settings from other clients.
- Checking on startup wouldn't help users who leave Anki running for weeks. If we also checked on a timer, collection config could get lost if the user has pending changes that haven't been synced.

Personally I like the deck config approach as it's simpler, but some users may not consider that sufficient. Thoughts?

Originally reported on https://forums.ankiweb.net/t/anki-24-04-beta/41792/5

**Comment by L-M-Sherlock** [comment]
I'm afraid that it would annoy or confuse users.

**Comment by dae** [comment]
As the former requires less work and would present less issues, I think it may make sense to start with that: it's an improvement over what we currently have, and if it proves insufficient, we can always switch to the latter in the future.

**Comment by abdnh** [comment]
Should this be closed after e9d3b46d4781ef2e07ad9af13105876efce0a069?

**Comment by dae** [comment]
Yep - thanks!
