### ISSUE TITLE
Support cards/day limit in FSRS optimizer

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3046]
https://github.com/open-spaced-repetition/fsrs-rs/pull/141

We need to expose learn_limit and review_limit in the GUI, and make it a union with the daily cost setting: https://github.com/open-spaced-repetition/fsrs-rs/pull/141#issuecomment-1867285828

**Comment by dae** [comment]
@abdnh another one for you if you're interested

**Comment by abdnh** [comment]
I got confused by "optimizer" in the title. I assume the issue is about the frontend part of #3075. In addition to exposing the simulation inputs in the GUI, we need to graph the results (probably in a popup window).

**Comment by dae** [comment]
I'll need to defer to @L-M-Sherlock on this, as the simulator has been changed a few times. When writing this ticket, I was under the impression we'd just need to expose those two values, but I'm not sure how they fit in now / how things will change if we add a built-in graphing simulator in the future.

**Comment by L-M-Sherlock** [comment]
These two values should be exposed in the built-in simulator in the future.

**Comment by dae** [comment]
So, to confirm, you're saying there's nothing we should do for now?

**Comment by L-M-Sherlock** [comment]
Yeah. The current finding optimal retention feature doesn't require it.

**Comment by L-M-Sherlock** [comment]
This issue could be closed.
