### ISSUE TITLE
Show deck name in deletion pop-up

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3047]
>  Currently, once you delete a deck, a little message pops up for a second that says “n cards deleted.” It would be nice if it said, “n cards in deck Deck Name deleted” 

Originally reported on https://forums.ankiweb.net/t/bring-back-warning-before-deck-deletion/41810/2

**Comment by anton69420** [comment]
Can i do this?

**Comment by dae** [comment]
Sure. Please create a new string in the .ftl, instead of changing the current one. Suggested wording:

"<count> cards deleted from <deck name>".

**Comment by escribapetrus** [comment]
I don´t know if the guy's tackling this, but I have the change in a local branch here.
I tried pushing the PR, but got "permission denied". Did I do something wrong? New to OS here.

**Comment by anton69420** [comment]
Well i was working on it but i didn't get very far. Curious how you did it.

**Comment by dae** [comment]
Please make sure you fork the repo and push your changes to your fork - it won't work if you try to push them to this repo directly.

**Comment by escribapetrus** [comment]
Will do. I created a [PR](https://github.com/ankitects/anki/pull/3057), but it's giving me some problems with this ftl/core-repo submodule that are making me cry tears of blood.

I'll copy the code into another branch and try again.
