### ISSUE TITLE
Some minor regressions with IO pan/zoom after #3052

### ISSUE THREAD

**Issue by glutanimate** [ankitects/anki#3068]
@krmanik thanks a bunch first of all for your work on #3052! The touch ergonomics of the new pan and zoom implementation seem really nice and like a major improvement over what we had before. Same with the image quality on zoom – great job!

I didn't have time to follow development as closely over the last 3-4 weeks, but finally found some time today to play around with the RC, and I think I stumbled on some minor regressions in IO's pan & zoom support on desktop:

### Scrolling no longer seems to work

I've only tested this on Linux so far, but I no longer seem to be able to pan a zoomed-in image by using my mouse wheel. Similarly, scrollbars no longer seem to appear:

https://github.com/ankitects/anki/assets/5459332/f01f9175-eec9-4e41-90c7-889fd4109cf9

### Issues with window resizing and image recentering

For the most part the editor seems to respond smoothly to window size changes with the image's size and position being adjusted accordingly. However, it seems like this currently does not work correctly sometimes, causing the image to be off-center and also remain so when using the recenter / restore zoom button:

https://github.com/ankitects/anki/assets/5459332/fcb13ab8-28bd-433f-b521-edd171286c71

### Issue with zoom/pan state persisting

I have not been able to nail this down yet and find a reproducible series of steps, but it looks like under some circumstances, the editor will remain stuck in zoom/pan mode, even though a mask tool is selected:

https://github.com/ankitects/anki/assets/5459332/8b7934f3-f20d-4a23-b7f5-90c4e9de62e3

----

Also more of a suggestion, rather than a regression, but: I would personally prefer if we removed the red border surrounding the image (if this isn't just a temporary change to debug the layout). It sticks out fairly starkly compared to Anki's design language and I don't think the border needs to be as prominent. Is there any particular reason you went with a red border @krmanik?

**Comment by krmanik** [comment]
> Scrolling no longer seems to work

The panning with mouse wheel is not supported, it also be implemented like currently CTRL+Mouse wheel help in zoom, so ALT+Mouse wheel help in panning, it can be done.

> Issues with window resizing and image recentering

I will implement fix for it.

> Issue with zoom/pan state persisting

This is fixed in the PR

**Comment by krmanik** [comment]
@glutanimate 
I push the fix about almost issues in the PR #3066, please try again and let me know.

**Comment by dae** [comment]
@glutanimate could you confirm what's left to do for this issue?

**Comment by glutanimate** [comment]
From my testing everything seems to be resolved. Thanks again @krmanik!
