### ISSUE TITLE
Shift revlog count from progress to return value

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3070]
Sorry for barging in, but I suggest adding the review count to the "Evaluate" window.
![image](https://github.com/ankitects/anki/assets/83031600/15e1a89d-bbf6-4c33-8e87-5909ce10b24b)

_Originally posted by @Expertium in https://github.com/ankitects/anki/issues/3051#issuecomment-1987231996_

**Comment by Expertium** [comment]
I'll elaborate a little more: the number of reviews is displayed when optimization/evaluation is running. However, when this number is small, optimization/evaluation will finish so fast that the user won't even see it.

**Comment by dae** [comment]
We can do this, but it will mean the count is only shown when the operation completes.

**Comment by Expertium** [comment]
Why not both?

**Comment by dae** [comment]
Because it's redundant, and requires extra code.
