### ISSUE TITLE
Clarify what "optimal retention" means

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3074]
> It's not obvious at all what "optimal" means, so I think there should be a short sentence saying something like "This value of retention minimizes the amount of studying per day" or something along those lines.

_Originally posted by @Expertium in https://github.com/ankitects/anki/issues/3065#issuecomment-1994803366_

**Comment by Expertium** [comment]
This is more tricky than I thought. In Anki 24.04 workload/knowledge will be minimized (see this article: https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Optimal-Retention), and it's very hard to explain what that is in just one sentence.

**Comment by Expertium** [comment]
Maybe something like "This value of retention will allow you to remember the most information in the least amount of time", but that sounds confusing.

**Comment by user1823** [comment]
> it's very hard to explain what that is in just one sentence.

It doesn't need to be a single sentence, unless you are planning to add it in the Deck Options page itself rather than the help modal. If that's what you are thinking, I want to tell you that it is not a good idea to add descriptions of the features in the Deck Options page. Just think how cluttered the page would become if every setting had its description there.

For sure, I am in favor of adding the description. But I want it to be added to the help modal rather than just below the setting.

**Comment by Expertium** [comment]
> It doesn't need to be a single sentence, unless you are planning to add it in the Deck Options page itself rather than the help modal.

I meant something like this:
![image](https://github.com/ankitects/anki/assets/83031600/357d2250-bfbf-47b2-a5df-af58440d4faf)

**Comment by user1823** [comment]
I guess that dae would have to make the final decision. But, in case that you didn't understand what I meant by help modal, here is the screenshot that probably explains it better.

<img width="960" alt="image" src="https://github.com/ankitects/anki/assets/92206575/2b27b183-9979-4d67-a83b-fbf70a5af13c">

I think that we should add the description in this modal.

Also, after #3065, the "if it significantly differs from 0.9, it's a sign that ...." part is not valid because the user is not entering a value of time per day.

Somewhat unrelated, this help modal can't be opened by clicking "Compute optimal retention" because clicking it just toggles the HTML `<details>` tag that contains this section. So, another intuitive option to open the modal should be considered.

**Comment by Expertium** [comment]
I'm afraid that few users actually read these.

**Comment by dae** [comment]
The forum's a better place if you want to solicit non-developer feedback.

**Comment by brishtibheja** [comment]
This "compute optimal retention" thing have actually confused me. Isn't 0.9 an arbitrary number and why does having a number close to 0.9 is important? Should I maybe start a thread in the forum?

**Comment by Expertium** [comment]
The new implementation only requires you to enter the number of days to simulate.
As for what it does, it tries to find the best ratio of how much time you spend on your cards vs how much you remember.

**Comment by brishtibheja** [comment]
I was having a discussion on this last year and optimal retention came up. I initially thought it might mean the retention rate for which you can learn the highest amount of cards. Would that be correct?

> The new implementation only requires you to enter the number of days to simulate.

This would be great!

**Comment by user1823** [comment]
I recommend continuing the discussion on Anki Forums.

**Comment by Expertium** [comment]
> I was having a discussion on this last year and optimal retention came up. I initially thought it might mean the retention rate for which you can learn the highest amount of cards. Would that be correct?

It was changed. I recommend reading this: https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Optimal-Retention

**Comment by brishtibheja** [comment]
okay so now this is basically the ratio of workload/knowledge. This sounds great actually. For my purposes it will ensure I am getting highest return for the time I spent in Anki. The rest I can spend reading my books.

**Comment by user1823** [comment]
Completed in https://github.com/ankitects/anki/commit/6e1ae5231b8945b758695e0588aa2fe91ce7f1bf
