### ISSUE TITLE
Related cards are shown together with Random sort order

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3090]
I am having the issue described in https://forums.ankiweb.net/t/bug-the-random-option-in-the-review-sort-order-setting-is-not-truly-random/29199/5. In short, related cards are being shown consecutively even though I have set the Review Sort Order to Random. This issue is reproduced on both Anki and AnkiDroid.

As you advised in the above forum thread, I sorted cards by the Due column in the Browser. I found that the first card seen in the reviewer is not at the top or the bottom of the sorted list. So, I think that there is a bug.

Example Deck: [sort order bug.zip](https://github.com/ankitects/anki/files/14734383/sort.order.bug.zip) (change extension to .apkg)

When clicking the deck to study, the first card that comes up is "5". However, it is neither at the top nor at the bottom of the sorted list.

<img width="359" alt="image" src="https://github.com/ankitects/anki/assets/92206575/22a89fdc-f900-4f08-8582-dc333f16a2d9">

I also tested using "Deck, then due date" as the Review Sort Order. The same behavior was noticed in that case too.

**Comment by user1823** [comment]
I tried four review sort orders (`Random`, `Deck, then due date`, `Due date, then deck`, `Due date, then random`). With each one of them, I got the cards in the same order (5 → 12 → 6  → 8).

**Comment by dae** [comment]
All sorting options will randomize identical values (eg when sorting by due date, 3 cards due on the same day will be randomized). The random order depends on when the card was last modified, so it is consistent.

**Comment by user1823** [comment]
> All sorting options will randomize identical values

Ok, that explains why the order is the same with all of the above Sort Orders. But, the cards are not shown in the due order as seen in the Browser. Is that normal? I am asking this because your comment in the above forum thread suggests otherwise.

> The random order depends on when the card was last modified

This seems to be responsible for showing related cards consecutively.

If two cards were last modified on the same day and are both due today, they are likely to have the same interval too. So, it means that they have at least 3 things in common:
- last modified date
- due date
- interval.

So, it is likely that they would be related to each other. I suggest changing the method used to randomize the order.

**Comment by dae** [comment]
The random component is not shown in the browser.

Both the card id and modification time are factored in, so two cards modified at the same time will only appear together by random chance.

**Comment by user1823** [comment]
> Both the card id and modification time are factored in

But, related cards are likely to be created together, due to which they are likely to have similar cids. 

I am not sure exactly how the randomness can be increased. But, with the current implementation, I frequently see related cards one after the other.

**Comment by dae** [comment]
Cards are not sorted by card id. The id and mtime is fed into a hash function, and we sort on the hash. So cards are no more likely to appear together as apart.

The code is in Rust and used by AnkiDroid as well.

**Comment by user1823** [comment]
If you are confident that the sorting is random, my conclusions might be a result of the confirmation bias.

Nonetheless, can you point me to 
- the code that randomizes the order of reviews cards; and
- the code that chooses which new cards to insert at a given point in the queue?

Once I am convinced that no improvements are required/possible, I will close this issue.

**Comment by dae** [comment]
`impl fmt::Display for ReviewOrderSubclause {`

The new card sorting is below that.

**Comment by user1823** [comment]
Based on the documentation in https://docs.aws.amazon.com/redshift/latest/dg/r_FNV_HASH.html, it seems that `mod` is used as the seed of the hash algorithm. 
https://github.com/ankitects/anki/blob/e911b4b69ae433818510da098d0ac2661e88664f/rslib/src/storage/card/mod.rs#L724

The page also says:
> To compute the hash of a table with multiple columns, you can compute the FNV hash of the first column and pass it as a seed to the hash of the second column.

I don't think Anki is doing this. It seems that Anki is directly using `mod` as the seed.

I know that outputs of LLMs shouldn't be trusted blindly. But here is what Windows Copilot says in this regard:

> Using `id` as the input and `mod` as the seed could indeed give you a good dispersion, especially if the `mod` values are varied and distributed over a large range. This is because different seeds will produce different hash values, even for the same input.
> 
> However, using the hash of `mod` as the seed could potentially give you even better dispersion. This is because the hash function will further mix up the bits of `mod`, leading to a wider range of possible seed values. This could result in a more uniform distribution of hash values, which is generally desirable in hashing.

As I mentioned in one of my previous comments, `mod` for related cards is likely to be similar. So, I think that it would be better to use the hash of `mod` as the seed, not `mod` itself.

Sorry for bothering you if Anki indeed uses the hash of `mod` as the seed.

**Comment by dae** [comment]
fnvhash is defined in sqlite.rs. It hashes all of its arguments, and doesn't take a seed.

**Comment by user1823** [comment]
I am closing this issue because I couldn't find anything that required change.
