### ISSUE TITLE
The update interval of timer display

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3096]
> Sometimes I use the timer (deck option - timer - show answer timer) to monitor how much time I spend in answering a card. However, from time to time I feel that the timer is not very consistent, i.e. it may display different numbers for the same amount of time spent. This is especially obvious when enabling auto advance and “stop timer on answer”: e.g. if I set the “time to reveal answer” as 3.4 seconds, when the answer is revealed the timer may stop at either 00:03 or 00:04.

Originally reported on https://forums.ankiweb.net/t/the-update-interval-of-timer-display/42849

Two issues by the looks of it:

- in reviewer-bottom we use a 1 second timer that's not aligned to when a card is presented
- the start time is rounded to integer seconds in reviewer.py:780

We don't want to increase the update frequency too much, as it will waste CPU cycles, but maybe 0.5 or 0.3 would be enough?

**Comment by AntoineQ1** [comment]
Hello !
I'd love to contribute to Anki ; could I suggest the necessary code changes in a PR ?
Sincerely,

**Comment by dae** [comment]
Yes, a PR would be welcome - thank you for the offer.
