### ISSUE TITLE
“1 hours today”

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3102]
> I’ve noticed that if you study for exactly one hour, you’re told “Studied n cards in 1 hours today (_m_s/card).”
> This is an incredibly minor point, but ideally it would say “1 hour” instead of “1 hours” (but be plural again for “1.1 hours”, “1.2 hours”, etc.).

Originally reported on https://forums.ankiweb.net/t/1-hours-today/42956

It's caused by non-integer numbers that are rounded to an integer in format_number_values(), eg 1.0005 becomes 1.00 which ends up being to 1. I'm not sure we can easily fix this, as I think the plural choice is happening in fluent's code, not ours. Converting the fluent numbers to integers if they round to an integer might work?

**Comment by hnvy** [comment]
Hi!

I realise this is a very minor issue, would it not be possible to display all of the numbers in decimal format (including 1, 2, 3, etc.)?

Numbers expressed in the decimal format use the noun's plural form.

Showing "1.0" will not only guarantee unity between the first hour and the remainder, but it will also address the plural problem that is mentioned above.

So:
- 1 -> 1.0
- 2 -> 2.0
- 3 -> 3.0
- ...

I guess it would be a lot easier to code than the alternative?

I hope that makes sense.



Harvey R.
