### ISSUE TITLE
"Select All" does not work properly in image occlusion in 24.04

### ISSUE THREAD

**Issue by kcrimson1** [ankitects/anki#3107]
使用 全选+组合 功能, 制作卡片之后, 我发现没有任何遮挡在上面, 只显示图像。
我发誓我没有修改任何有关图片遮挡模板, 所以这应该是版本更新带来的错误。能尽快修复吗, 我很喜欢这个新功能。

**Comment by dae** [comment]
@krmanik this appears to have regressed in #3052 - the select all feature doesn't seem to be working correctly anymore. If the shapes are manually selected, they can be grouped.

**Comment by krmanik** [comment]
I have tested it and created similar issues here, https://forums.ankiweb.net/t/it-seems-that-the-group-cloze-is-not-working-as-expected-in-io
the issues seem to be on touch based device. I am implementing fix for it now.

**Comment by krmanik** [comment]
I am not able to understand that it is working properly in add mode, but it is causing issue in edit mode.

**Comment by dae** [comment]
I reproduced the issue the OP mentioned by testing on a Mac - haven't tried on iOS. It's broken in add mode too. Create two rectangles, click on 'select all', then 'group', then 'add'. The card doesn't show any rectangles when it's reviewed.

**Comment by krmanik** [comment]
The select all needs to skip bounding box selection, then it will work.

**Comment by dae** [comment]
Associated PR: https://github.com/ankitects/anki/pull/3109

**Comment by abdnh** [comment]
Can be closed.
