### ISSUE TITLE
Missing install steps

### ISSUE THREAD

**Issue by JulienPalard** [ankitects/anki#3110]
Followed the instructions from https://betas.ankiweb.net/ on Debian Trixie and I missed two packages:

I had to:

    apt install python3-pyqt6.qtquick python3-pyqt6.qtwebengine

in order to have anki work.

It had installed aqt/anki 23.12.1.

Looks like after adding the two missing dependencies it works.

As a side note I used `pipx` instead of manually creating a venv, maybe the doc could be upgrade to look like:

    $ sudo apt install python3-pyqt5.{qtwebengine,qtmultimedia} python3-pyqt6.{qtquick,qtwebengine} pipx
    $ pipx install --system-site-packages aqt
    $ ~/.local/bin/anki

it's two lines shorter, and pipx is recommended by Debian:

```
mobian@mobian:~$ cat /usr/lib/python3.12/EXTERNALLY-MANAGED
[externally-managed]
Error=To install Python packages system-wide, try apt install
 python3-xyz, where xyz is the package you are trying to
 install.

 If you wish to install a non-Debian-packaged Python package,
 create a virtual environment using python3 -m venv path/to/venv.
 Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
 sure you have python3-full installed.

 If you wish to install a non-Debian packaged Python application,
 it may be easiest to use pipx install xyz, which will manage a
 virtual environment for you. Make sure you have pipx installed.

 See /usr/share/doc/python3.12/README.venv for more information.
```

**Comment by dae** [comment]
pipx is an extra dependency - I'd prefer to keep them to a minimum.

Are you sure qtquick was required, and not pulled in by the installation of qtwebengine? The latter is already mentioned in the docs.

**Comment by dae** [comment]
Thank you, I have updated the docs to add the qtquick dependency.
