### ISSUE TITLE
Linux aarch64 build

### ISSUE THREAD

**Issue by senekor** [ankitects/anki#3111]
Hello. I have an M1 Macbook Air running Asahi Linux. I wanted to use anki on it, but apparantly there are no Linux aarch64 builds. I'm a developer so I could probably(?) build it myself, but I thought it's worth checking in with the devs first.

Are there no Linux aarch64 builds because there is no demand? Or is there some technical reason (i.e. some dependency not working on ARM)? Are the devs open to provide first party builds, or is it recommended to build myself? Would you like development help with providing the ARM builds? (I have experience with Rust.)

**Comment by dae** [comment]
Please see the notes in docs/linux.md. Until (Py)Qt start providing Qt wheels, users will need to rely on their distro's Qt instead.

**Comment by Knirps1** [comment]
Is this the reason why there is no more python wheel for linux aarch64 on PyPI?

**Comment by dae** [comment]
Nope, that was just oversight. I've uploaded it now.

**Comment by joshua-stone** [comment]
@dae It appears that PyQt6 has uploaded aarch64 wheels very recently:

https://pypi.org/project/PyQt6/6.7.1/#files

Is there anything else that Anki would depend on for aarch64 support?
