### ISSUE TITLE
[bug]cards mixed up. back didn't match front. or the front isn't the correct one.

### ISSUE THREAD

**Issue by stevenyuan49** [ankitects/anki#3117]
during the learning in PC, it quite often have this sutiation.
the back answer didn't match the front. 
or when start the learning next card, the front card keep the same with previous card , didn't change.
this situation seems to begin from the anki 23 version. and still the same in 24, not fixed.

**Comment by dae** [comment]
Please see https://docs.ankiweb.net/troubleshooting.html, particularly the video driver.

**Comment by stevenyuan49** [comment]
thanks a lot.
