### ISSUE TITLE
Future Due stats Issue`

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3125]
> Hi! I am on anki 24.04 and my future due with backlogs looks like this. This problem occurs only when my filtered decks have cards that are in intraday learning
> if I empty the decks the future due and backlogs shows up correctly
> image877×648 27.5 KB
> I know that this was an unsolved problem in the previous version but the logs say that it has been solved so just letting y’all know that it is still persisting
> PS nothing shows up in the browser when i click on those super overdue cards

Originally reported on https://forums.ankiweb.net/t/future-due-stats-issue/43314

Previous patch that tried to fix this: b248911b0f477173594a60d672b23439943cf5a9

**Comment by abdnh** [comment]
@dae are you able to reproduce this? I had no luck so far.

**Comment by dae** [comment]
The original reporter doesn't currently appear to have the issue with their collection, so let's tentatively close this and see if we get a new report.
