### ISSUE TITLE
err 500 "invalid number" on deck import, improve error message, worked on previous versions and with "legacy import"

### ISSUE THREAD

**Issue by kralo** [ankitects/anki#3139]
```
Anki 24.04 (429bc9e1)  
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.8.0-22-generic-x86_64-with-glibc2.39
```
running `ANKIDEV=1 TRACESQL=1 LOGTERM=1 ./anki` and then importing [this public deck](https://github.com/kralo/elwis-anki-parser/releases/download/v2.0.1/sbf-see-2023.apkg) leads to the following "error 500".

```
ql: SELECT id,   name,   mtime_secs,   usn,   common,   kind FROM decks WHERE id IN (SELECT DISTINCT did FROM cards WHERE id IN (SELECT cid FROM search_cids))
sql: SELECT id,   name,   mtime_secs,   usn,   config FROM notetypes WHERE id IN (SELECT DISTINCT mid FROM notes WHERE id IN (SELECT nid FROM search_nids))
sql: SELECT ord,   name,   config FROM fields WHERE ntid = 1431526661260 ORDER BY ord
sql: SELECT ord,   name,   mtime_secs,   usn,   config FROM templates WHERE ntid = 1431526661260 ORDER BY ord
sql: SELECT val FROM config WHERE KEY = 'nextPos'
sql: drop table if exists search_cids
sql: drop table if exists search_nids
sql: rollback
Traceback (most recent call last):
  File "aqt.mediasrv", line 629, in wrapped
  File "aqt.mediasrv", line 515, in import_anki_package
  File "aqt.mediasrv", line 497, in import_request
  File "aqt.mediasrv", line 610, in <lambda>
  File "anki._backend_generated", line 1865, in import_anki_package_raw
  File "anki._backend", line 173, in _run_command
anki.errors.InvalidInput: Eine Nummer war ungültig oder außerhalb des zulässigen Zahlenbereichs.
```

It however works, when I check settings->"Use legacy import/export".

a) Could you improve the error message to specify which card, or setting caused this error or even what the input was?

b) this deck u**sed to import fine.** Just now verified it 
  imports without errors in anki `2.0.52 Qt 4.8.1 PyQt 4.9.1`
  **import without errors** in `Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1`

 fails in `Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0`
 fails with error 500 "invalid number" in `Anki 2.1.60 (76d88073) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0`
 fails with error 500 "invalid number" in `anki-2.1.66-linux-qt6`

I suspect d482e90c6be7785478a8b5e8c788b8c1a02c6c00 to be the culprit to break the import.

[original user report](https://github.com/kralo/elwis-anki-parser/issues/3)

**Comment by RumovZ** [comment]
The issue is with the included media. Anki expects the media filenames to be named 0, 1, 2, ..., but they look like 0013feb72f0d3324714 instead.
It would be nice if the import continued to work with the new importer. But since this seems to be a very specific issue caused by the way a third-party tool is creating apkgs, it's probably not worth the effort to support this in Anki. Or what do you think, @dae?

`InvalidInput` indicates an unexpected error, so usually little effort has been put into providing more context.

**Comment by dae** [comment]
I agree - the third-party exporter did something different to Anki, and I don't think we should complicate our code to support their broken implementation that just happened to work by chance in the past.
