### ISSUE TITLE
Cards being repeated in filtered deck after pressing end

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3140]
- Create some new cards, fail them into the learn queue
- Create a filtered deck with rescheduling off, and answer easy. Observe they are not removed from the deck.

Originally reported on https://forums.ankiweb.net/t/cards-being-repeated-in-filtered-deck-after-pressing-end/43511

**Comment by dae** [comment]
@abdnh another one for you if you're interested

**Comment by 01Axel01** [comment]
Don't mind my question, how to solve this problem?
I am planning to do 20 filtered deck

**Comment by dae** [comment]
Please wait for the next Anki update.
