### ISSUE TITLE
Add maximize buttons to Note Types editor

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3151]
> Some things do not fit, so the window needs to be resized, but there is no maximize button. Examples of what does not fit:
> Tools  → Manage Note Types:
> horizontally and vertically
> Fields
> vertically
> Options
> the default texts fit

Originally reported on https://forums.ankiweb.net/t/add-maximize-buttons-to-note-types-editor/43803

**Comment by balavinaithirthan** [comment]
What are the files that are related to this issue?

**Comment by dae** [comment]
models.py and models.ui

**Comment by cdonat2** [comment]
@dae is this issue still relevant? If so, i could try to take a look if thats ok.

**Comment by dae** [comment]
It's still open, but I won't be able to guide you through it I'm afraid.

**Comment by cdonat2** [comment]
Thanks for letting me know. If there is any other issue that has a higher
priority I would be happy to contribute. In any case I will check out this
issue in detail as well.

Is there by any chance a person to contact that could recommend an issue as
a starting point for contributing?

**Comment by dae** [comment]
If you have questions, you're welcome to ask on forums.ankiweb.net, and someone may be able to answer you.

**Comment by cdonat2** [comment]
Thanks will do.

**Comment by ChazWinterYT** [comment]
Close this issue if it has been addressed, please.
