### ISSUE TITLE
Insufficient padding in import page

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3156]
As visible in the screenshot below, there isn't enough padding, especially on the left side.

![image](https://github.com/ankitects/anki/assets/92206575/337a9dec-cc15-477a-b346-7866069b9209)

Anki version 24.04.2 (a1fa865b)⁩

**Comment by EugeneTarasenko** [comment]
There is an issue with the button paddings too.
![Screenshot 2024-04-22 at 02 57 29](https://github.com/ankitects/anki/assets/87163666/a86af33c-252c-4c63-899c-ed7bd25800db)
