### ISSUE TITLE
Noticeable delay after pressing space in editor field

### ISSUE THREAD

**Issue by sarsamurmu** [ankitects/anki#3157]
Whenever I press space there is a delay before a response occurs. I've tried disabling all my add-ons, but this problem remains.
This is what I've found using the inspector
![image](https://github.com/ankitects/anki/assets/44255990/ea41aa6e-ab29-4fe5-aafd-85f2e1488cb4)
The code that is causing the problem
![image](https://github.com/ankitects/anki/assets/44255990/27b634b8-ce44-48d7-9719-7cc9462d7d71)
Looks like the more `mousemove` occurs, the more listeners get added to the document. When I keep adding multiple cards, these buggy listeners also add up, and the delay becomes more than 2 seconds and the editor becomes unusable

I've tried finding the code but this code is probably not part of Anki codebase, or fabric.js codebase. Maybe some other dependency is causing this?

You can test this by moving around your mouse in editor while pressing space. After some time you would notice the lagging in the editor.

**Comment by abdnh** [comment]
Fixed in this PR: https://github.com/ankitects/anki/pull/3150

**Comment by sarsamurmu** [comment]
Awesome
