### ISSUE TITLE
Background Images are eliminated by using the option Check Media

### ISSUE THREAD

**Issue by Jupy-languages** [ankitects/anki#3169]
So, I have my cards personalized with background images, for example:

(This code is located in the Styling section of the card)
.card {
 font-family: arial;
 text-align: center;
 background-color: white;
 **background-image: url("Russian_Background.jpg");**
 background-size: cover;
}

For this to work, the image is saved in the media folder of Anki. 
The issue is that if you use the option Check Media, appart from deleting the media that you actually are not using, it will also delete these background images that ARE being used.

**Comment by RumovZ** [comment]
This is explained in the manual: https://docs.ankiweb.net/media.html#checking-media
