### ISSUE TITLE
Support for python scripting while app is open

### ISSUE THREAD

**Issue by bjb568** [ankitects/anki#3179]
I'm trying to write a python script that reads data from my anki2 file. For example:

```py
from anki.storage import Collection
print(len(Collection("some_path/collection.anki2").find_cards("is:due")))
```

This works when the Anki app is closed, but when it's open I get this error: anki.errors.DBError: Anki already open, or media currently syncing.

It seems like the Anki app holds an exclusive lock on the database while it's running. It would be nice if reading from the database worked while the app is open.

**Comment by RumovZ** [comment]
Please use the forum for feature requests
