### ISSUE TITLE
Bug: UI interactable before it's updated (Anki Desktop 24.04.1 Windows 11)

### ISSUE THREAD

**Issue by jakkarn** [ankitects/anki#3185]
I just downloaded the latest version from the Anki website 24.04.1 and run it on a new laptop with decent performance. I started practicing the following deck: 

Taiwan TOCFL 2023 wordlist with audio (Traditional)
https://ankiweb.net/shared/info/956460973

Sometimes the UI didn't update fully when showing the next card. It happened twice on the *ni = you* card such that the image wasn't updated and it instead showed the previous image for *wo = I/me* and it led to me pressing the show answer and then both the image and the description changed from the *wo* card to the *ni* card.

A similar thing happened for another card (can't remember which). The picture was correct, but the answering-UI wasn't updated so it stuck on the "again", "easy", "good", "hard" buttons for almost 1 min and then it updated to the correct "show answer" UI.

I don't know what causes it, but I think the user shouldn't be able to interact until the whole next card is loaded and shown. Hiding the prompt in the meanwhile would be good.

keywords: delay; performance; lag; update; UI; practice;

**Comment by RumovZ** [comment]
Please follow the steps from [troubleshooting](https://docs.ankiweb.net/troubleshooting.html), especially changing the video driver.

**Comment by jakkarn** [comment]
Thanks for the response!

I just changed the video driver to OpenGL from directX and see if it happens more times. It doesn't happen all the time, so even if it seems to solve the problem, I need maybe a week to confirm that it really does not happen. 

Although, even if it is a problem with the video driver, can't the code be modified to prevent this from happening in the first place? My guess is that there is some async QT operation that you can wait for.

I can confirm that restarting Anki also temporarily solves the problem, but I don't notice the problem until I press "show answer" and it doesn't match the other side (which depends on me having learnt that card) so it's not a great experience.

**Comment by RumovZ** [comment]
I don't know, but as this issue is even mentioned in the manual, I assume that it would have already been fixed in Anki's code if that were possible.
Please post on the forums if you have further questions.
