### ISSUE TITLE
Nested clozes cause exponentially growing html

### ISSUE THREAD

**Issue by naipofo** [ankitects/anki#3189]
Nested clozes generate some weird html, cause they render the inner cloze and then escape it to put in the data-cloze attribute. This results in weird html in attribute:
```html
<span class="cloze" data-cloze="<span class=&quot;cloze&quot; data-cloze=&quot;&quot; data-ordinal=&quot;1&quot;>[...]</span>" data-ordinal="1">[...]</span>
```
and that html contains nested html escapes that grow exponentially. This huge html chunk slowes down `extract_av_tags` to a crawl and crashes anki.

This starts to cause crashes with ~11 nested clozes. Some shared decks on ankiweb have those and a user might make them by mistake, so there should be some kind of safeguard.

Originally reported on https://forums.ankiweb.net/t/memory-leak-when-search-specific-kanji-japanese-hieroglyph/44394/2

**Comment by dae** [comment]
Thanks for digging into this! It sounds like we may need to both limit the levels of nesting, and also place bounds on extract_av_tags if possible.

**Comment by Danika-Dakika** [comment]
@abdnh @dae Was #3264 intended to break existing clozes? This is [causing some trouble for users](https://forums.ankiweb.net/t/nested-clozes-doesnt-work-for-more-than-3-nests/52661?u=danika_dakika).

**Comment by abdnh** [comment]
Yes, the change affects existing clozes.

**Comment by aiaiads** [comment]
This really has causes some problems for me. 3 nests limit is too low

**Comment by aiaiads** [comment]
I can't believe you changed this feature so simply without any big discussion. I use anki mostly with the fill in the blanks template, so I have a lot of cards that are affected.
