### ISSUE TITLE
Intervals don't update after changing Desired Retention

### ISSUE THREAD

**Issue by brishtibheja** [ankitects/anki#3234]
My `desired retention` was previously set at 77 percent which I then update to 90 percent. I don't use `reschedule cards at change`. Now the intervals shown on top of `hard`, `good` and `easy` buttons should change. Note that I'm speaking of the intervals that each grade will assign to the cards and not the already assigned intervals. They are shown to you by default in the review screen.

Here's where I think the anomaly lies — the same intervals shown for one of my relearning cards doesn't change at all. The said card has gone through the default steps `1m 10m` and `FSRS` determines now what happens at the last step. It feels as if the change in desired retention isn't being taken into account.

*( originally reported here in FSRS's repo: https://github.com/open-spaced-repetition/fsrs4anki/issues/657 )*

___

**Addendum:**

The deck for ease of reproducibility —

[漢字 Writing__Level 10-4__4. Level 6-20240617133543.zip](https://github.com/user-attachments/files/15871976/Writing__Level.10-4__4.Level.6-20240617133543.zip)

(rename `.zip` —> `.apkg`)

cid:`1564439362436`

**Comment by dae** [comment]
Thank you for the report!
