### ISSUE TITLE
[24.06.2] Image Occlusion regression (flickering)

### ISSUE THREAD

**Issue by jcznk** [ankitects/anki#3239]
Version ⁨24.06.2 (33a92379)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Windows 10, no add-ons.

Also reproducible on 24.06.1. Does not occur on 24.06 rc2.

Each time the Front and/or Back side of an IO card is loaded, the image flickers. The following gifs are recorded on fresh installs of Anki, using the default IO note type. The same problem arises when using any custom note type containing the "anki.imageOcclusion.setup()" script.

On 24.06rc2 (no flickering)
![On 24 06rc2](https://github.com/ankitects/anki/assets/60730312/6e7820c3-0c47-4107-9af7-33d9418bdd2c)

On 24.06.2 (flickering when loading the Front and or Back side of a card)
![On 24 06 2](https://github.com/ankitects/anki/assets/60730312/01eef286-a2b7-4b82-909d-2400d74cbd78)

**Comment by dae** [comment]
@jcznk thanks!

@abdnh regressed in 548066f92cc23ee944a61269c1d2a52bc206e491. Maybe we can make the setupI18n call to immediately before we use the translation, so the reviewer no longer needs to load the .ftl files in the common case?
