### ISSUE TITLE
The “reuse internal” clipboard feature cannot handle primary selections

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3249]
> This is a bug report.
> Steps to reproduce:
> 
> Run Anki-24.04.1 on X11 Linux.
> Copy text A from a field using Ctrl+C to put that text into the clipboard buffer.
> Select some other text B to put that text into the primary selection.
> Middle-click with the mouse to paste the primary selection.
> Text A from the clipboard buffer is actually pasted instead of text B from the primary selection.

Originally reported on https://forums.ankiweb.net/t/the-reuse-internal-clipboard-feature-cannot-handle-primary-selections/46115

**Comment by tholin** [comment]
I think this issue should be reopened since the patch merged to fix the issue was reverted in f3b0afcc624c6fb2ff259cf34e819cc2c651da67. I don't have the permission to reopen issues myself.
