### ISSUE TITLE
Rename “Change Deck” to "Select Deck"

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3266]
Currently, the undo action for moving a card to a different deck, and selecting a different deck, use the same "Change Deck" string. To better distinguish between the two, we could add a new string for Op::SetCurrentDeck, such as "Select Deck" instead.

Originally reported on https://forums.ankiweb.net/t/rename-change-deck-to-move-cards/46286/4

**Comment by escribapetrus** [comment]
I'll try to take care of this.

**Comment by vectflow** [comment]
This seems like a very easy fix if it's just the English that needs to be changed. I don't speak any other languages — what are the expectations here? I can easily open a PR for this with just the English change.

**Comment by dae** [comment]
It requires a little knowledge about our translation system: https://translating.ankiweb.net/anki/developers.html
