### ISSUE TITLE
Toggling image occlusion masks makes added text vanish

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3268]
> With Anki version 24.06.2 an image occlusion card that has had text added to it using the editor as documented here hides the text when toggling the image occlusion masks using the button after revealing the answer.
> Steps to reproduce:
> 
> add an image occlusion note and add text using the built-in editor
> add an occlusion shape to generate cards
> review the card, show answer and click ‘Toggle Masks’
> 
> Result: the occlusion masks get removed AND the text vanishes
> Expected result: only the occlusion masks get removed, the text remains
> Please let me know if you need further information.

Originally reported on https://forums.ankiweb.net/t/possible-bug-toggling-image-occlusion-masks-makes-added-text-vanish/46531

**Comment by escribapetrus** [comment]
I'll try to take care of this.
