### ISSUE TITLE
Good interval of relearning card sometimes increases after pressing Again

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3270]
After https://github.com/ankitects/anki/pull/3236, the interval of a relearning card is recalculated when it leaves the relearning stage. The fuzz applied depends upon the value of `reps`, which in turn depends on the number of times the card was rated `Again` or `Hard` during the relearning phase.

Let me use an example to explain the problem better.

- For testing purpose, I pressed `Again` on a review card with an 11 month interval.
- When the card was shown again (as a relearning card), the `Good` interval was shown as 1.1 month.
- I pressed `Again` again and then the `Good` interval became 1.2 month. This increase in interval on pressing `Again` is not expected.
- I pressed `Again` again and then the `Good` interval became 1 month.
- I pressed `Again` again and then the `Good` interval became 1.3 month. 

Because the value of `reps` is increasing continuously, the fuzz is changing, leading to unexpected results.

@L-M-Sherlock, please have a look. I know that this issue will be solved in FSRS v5 but we need a stopgap measure till then.

One idea is that we should store the value of reps in a new variable when the card enters the relearning stage and use this variable to calculate fuzz instead of using the actual value of reps.

Theoretically, the same problem can occur with learning cards too. But that requires w[0] to be sufficiently large, which makes it rare.

**Comment by L-M-Sherlock** [comment]
FSRS-5 is coming soon.

https://github.com/ankitects/anki/pull/3298
