### ISSUE TITLE
[Bug/Suggestion] In card browser, keyboard shortcuts for Toggle Mask Editor and Change Note Type are identical

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3276]
> Problem
> In the Card Browser, the Toggle Mask Editor and Change Note Type keyboard shortcuts are identical/duplicated: Ctrl + Shift + M. When I input that shortcut, the Change Note Type Window comes up. The only way to select Toggle Mask Editor is manually clicking with the mouse.

Originally reported on https://forums.ankiweb.net/t/bug-suggestion-in-card-browser-keyboard-shortcuts-for-toggle-mask-editor-and-change-note-type-are-identical/46658/3

**Comment by dae** [comment]
Previous PR: https://github.com/ankitects/anki/pull/3136

**Comment by escribapetrus** [comment]
I'll take a look.
