### ISSUE TITLE
I need developers to put anki on my website

### ISSUE THREAD

**Issue by ChristianMarques** [ankitects/anki#3289]
From what I read, it is allowed to put the anki system on my website because it is open source.
I want to see if it is viable.
Qualified and interested anki project participants, please contact me on: christian.mcjm@gmail.com.

**Comment by dae** [comment]
You would need to find & pay a qualified person to do the work, and would need to honor the terms of the open source license agreement, including sharing any changes you make.

**Comment by ChristianMarques** [comment]
Yes, I want to pay a person or people to develop it and I also want to honor the terms of the open source license. I'm going on an English exchange this semester, I've been studying programming, web design... I want to create a pattern, a workflow and study to optimize results. I have been trying to build a good network of contacts so that we can grow together.
If you have contact information for programmers that you can recommend, I would be grateful.
Sorry for any errors in writing, my English is still very basic, the translator helps a lot while I learn.
thanks

**Comment by ChristianMarques** [comment]
@dae  What is your area of ​​expertise, what is your experience, can you give me your contact email, telegram, whatzap?
