### ISSUE TITLE
I have found a bug, I suppose.

### ISSUE THREAD

**Issue by Say-Hi-To-Me** [ankitects/anki#3300]
1) I installed Windows 10 and downloaded latest Anki version and I encounter a problem with importing TSV filed into an Anki deck.
Problem was what I was not able to import TSV files and probably other files too to Anki.

2) I find out what that error is gone when instead of latest Anki version like 24.06.3 and few recent one I installed Version ⁨24.04.1 (ccd9ca1a)⁩.

3) In latest versions error was written on the white screen with such text “500: Failed to read ‘C:/Users/0/Downloads/’: Access is denied. (os error 5)”.

4) Before finding out solution I have tried debugging instructions from Anki manual and it didnt worked. 
Than I created a support ticket on Anki forum.
Ticket https://forums.ankiweb.net/t/debugging-permission-problems/46920/4 

5) Now my problem is solved by using older version of Anki but I think it's imported for reporting this bug because Anki is my №1 is the most valuable piece of app/services which I use.

I am sorry for my grammar mistakes I am working daily on improving my English language skills. :)

**Comment by dae** [comment]
Please see my reply on your forum thread.
