### ISSUE TITLE
WIndows on ARM support

### ISSUE THREAD

**Issue by nekoteai** [ankitects/anki#3309]
- Have a question or feature suggestion?
- **Feature Request**
- Problems building/running on your system?
Heavy memory and cpu load on ARM Windows because of emulated X64 execution.IT may be resolve by running an ARM execution

It seems that msvc and rust toolchain supported windows on arm well now.So will arm build possible?
[https://rust-lang.github.io/rustup/installation/windows.html](https://rust-lang.github.io/rustup/installation/windows.html)

**Comment by dae** [comment]
Please use the forum for future feature requests. Re Windows ARM, we won't be able to support it until all our dependencies do.

**Comment by nekoteai** [comment]
As I made some investigation on this topic,so I'll provide some information here
- A working Python ARM64 3.9.x canbe found on nupkg 
https://www.nuget.org/packages/pythonarm64/3.9.10
- [Qt 6.8.0 ](https://download.qt.io/online/qtsdkrepository/windows_arm64/desktop/qt6_680/qt6_680/)have officially supported WOA
- but Qt Webengine have error building on native WOA,may need cross compile,or wrong compiler
- PyQt6 support build Windows on ARM wheels on newer version of pyqt_builder.
#https://github.com/Python-PyQt/PyQt-builder/issues/14
- mpv and Lame have 3rd ARM build on github too
the main barrier of building the woa execution might be anki's building system which hardcoded dependency.It need update,i'll try if I can provide a pr

**Comment by dae** [comment]
#3081 will also be a problem

**Comment by evonnedms** [comment]
Hi team 👋

Just following up on the earlier discussion around native support for Anki on Windows ARM64 devices.

We understand there are some blockers—particularly around Qt WebEngine and build system dependencies—and we appreciate the transparency you've shared so far. As part of Microsoft’s FastTrack App Assure program, we’re actively working with developers to help accelerate compatibility with Windows on ARM.

If there’s any way we can assist—whether through technical guidance, testing resources, or coordination with upstream maintainers—we’d be happy to collaborate.

Let us know if you'd be open to continuing the conversation or if there's a preferred channel for deeper technical engagement.

Thanks again for all the great work you do with Anki!

— Evonne
Fasttrack App Assure Manager, Microsoft

**Comment by dae** [comment]
@evonnedms we appear blocked by upstream issues; I have documented them on https://github.com/ankitects/anki/issues/4079
