### ISSUE TITLE
Move 'ignore reviews before' to advanced

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3319]
The number of people who will want to use 'Ignore reviews before' will certainly decrease from that. More reason not to have it in FSRS category. But we will want to still document that (in the tutorial and in the Anki Manual).

@dae Can you move this feature to Advanced?

_Originally posted by @brishtibheja in https://github.com/ankitects/anki/issues/3314#issuecomment-2249301436_

**Comment by Expertium** [comment]
And rename it to "Ignore cards reviewed before", please.

**Comment by dae** [comment]
(renaming already done)
