### ISSUE TITLE
Improve UX: Blank Input for New Deck Names

### ISSUE THREAD

**Issue by devingdaniels** [ankitects/anki#3332]
This issue arose when I was helping a user get started with the app. They were confused about why they could create a new deck and press OK, but nothing appeared to happen. When creating a new deck via the Create Deck button, the form input field is auto populated with the name of the deck currently in focus or the last one clicked on by the user. Since there cannot be two decks with the same name, it seems there could be an improvement here:

Suggestion: The new deck form input should not be populated with the current or previously clicked deck title; it should be blank. If the user types a name that matches an existing deck name, there should be an indication that duplicates are not allowed. They can then either change the name and press OK or press Cancel. 

Version info:
Anki 23.12.1 (1a1d4d54)  
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.5-arm64-arm-64bit

**Comment by dae** [comment]
Please use the forum for future requests/suggestions. In this case, we need to balance what's more obvious to new users, with what is most convenient - by filling in the current deck name, users can easily edit it without having to type it from scratch. This is useful when e.g. creating "lesson 2" from "lesson 1", and when adding subdecks to existing decks.
