### ISSUE TITLE
Toggling list items currently loses editor focus when empty item

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3338]
> The Ctrl+, and Ctrl+. operation to toggle unordered/ordered list items will allow more text to be typed after the list if the caret is on a list item with text, but if it is on an empty list item, the editor loses the ability to be typed in until it is clicked again, while still retaining the blue outline.

Originally reported on https://forums.ankiweb.net/t/toggling-list-items-currently-loses-editor-focus-when-empty-item/47685

**Comment by lukesbart** [comment]
I am currently working on this issue. I found where this call happens and am trying to figure out why the element loses focus.
