### ISSUE TITLE
.DS_Store file shown as an unused media file

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3341]
> recently on my iMac when I use the Tools command “check media” the .DS_Store file is shown as an unused file. If I delete it, it is regenerated by MacOS. In my opinion it should not be shown. Is it shown intentionally or is this a bug?

We should perhaps exclude it from the check, like we already do in `files_in_trash()`.

Curiously, when I went to reproduce this, I could not get the `.DS_Store` file to be generated on my machine.

Originally reported on https://forums.ankiweb.net/t/ds-store-file-shown-as-an-unused-media-file/47751

**Comment by L-M-Sherlock** [comment]
Here are my steps to generate the `.DS_Store` file:
1. Open `collection.media` directory
2. Switch to icon view 
3. Move a file to a new position
4. Check Media in Anki
