### ISSUE TITLE
Unused functions in ts/lib/tslib/dom.ts incorrectly use HTMLParamElement

### ISSUE THREAD

**Issue by rlanday** [ankitects/anki#3343]
In ts/lib/tslib/dom.ts:

https://github.com/ankitects/anki/blob/bab83ffce02129426028e25a848d98ad1f1f5626/ts/lib/tslib/dom.ts#L145-L148

These two functions contain an obvious mistake: `HTMLParamElement` should be `HTMLParagraphElement`. These functions are only used by the two exported functions below:

https://github.com/ankitects/anki/blob/bab83ffce02129426028e25a848d98ad1f1f5626/ts/lib/tslib/dom.ts#L151-L152
which do not seem to be used anywhere, so these functions can likely be removed.

**Comment by DillBal** [comment]
Made a PR for this issue
[Pull Request](https://github.com/ankitects/anki/pull/3345)
