### ISSUE TITLE
Possible to show “last” subdeck name in Browser?

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3348]
> Hi! I have lots of decks and subdecks. So when I go to browse my cards, I have to widen the “Deck” column quite a lot to find out which “last”/“final” subdeck each card belongs to.
> Is it possible to only see this “final”/“last” in the Browser? In other words, I would like a separate column in the Browser mode that shows the “final”/“last” subdeck of each card/note.

We probably can approximate it with Qt.ElideLeft.

Originally reported on https://forums.ankiweb.net/t/possible-to-show-last-subdeck-name-in-browser/47905

**Comment by dae** [comment]
Actually, a bit more complicated than first thought. Presumably we'll need to set this in paint(), but we'll need to know whether the cell is a deck or not. Any preferences on how we approach this, @RumovZ?

**Comment by brishtibheja** [comment]
Is this going to be a seperate column or the same column. I would prefer later.

**Comment by RumovZ** [comment]
I have no preference at the moment. But I can imagine that there would quickly be someone to complain that they can't see the topmost deck's name. Maybe ElideMiddle would be able to cover more use cases?

**Comment by dae** [comment]
I'd much prefer to avoid an extra option, and middle does sound like the best way to do that.
