### ISSUE TITLE
heads up: anki 24.06.3 does not build with rust 1.80

### ISSUE THREAD

**Issue by martinetd** [ankitects/anki#3350]
rust 1.80 breaks everything that uses `time` before 0.3.35, see https://github.com/rust-lang/rust/issues/127343 (or the nixpkgs tracking issue, https://github.com/NixOS/nixpkgs/issues/332957 ) for details.

For anki, time was already updated in dca962c81ecc8ba98e81d06c169bffae0c77794d so there is nothing to do, but that isn't included in any release so distros packaging anki from sources that already want to update their rust won't be able to build it.
I've worked around the issue by updating just `time` here for nixpkgs: https://github.com/NixOS/nixpkgs/pull/333602

In my opinion this doesn't warrant rushing a new release, this is just to track that there's potentially some fallback for other maintainers.
I'll close this immediately.

**Comment by onyasumi** [comment]
Stuff like this will (and has) flown under the radar of many packagers, including arch. In the future, there really should be a release (even if its a minor one) that at least builds with the latest rust.
