### ISSUE TITLE
Create a new revlog entry for "Reschedule cards on change"

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3357]
Currently, the revlog entry for "Reschedule cards on change" is the same as that for "Set Due Date". This is the cause of several issues, including
- https://github.com/ankitects/anki/issues/2998
- https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/442
- https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/434

There must be other issues too that I am not remembering.

The solution is to use a separate revlog entry to distinguish "Reschedule cards on change" and "Set Due Date".

The first step is to decide the column in the revlog table whose value can be changed while minimizing add-on breakage (they may be making assumptions about the possible values).
Possible options: `type`, `ease`, `factor`

IMO, `type` is the only column where a change would appear to be "logically" correct. However, I am not sure if using `type = 5` for "Reschedule cards on change" would lead to significant add-on breakage.

**Comment by brishtibheja** [comment]
I assume it has to be an +ve integer number?

**Comment by dae** [comment]
Type=5 is the most logical. I'm not too concerned about add-ons as we've added '4' in the past too, but it will require going through the Anki codebase to make sure we handle that case in all the graphs/stats.

**Comment by brishtibheja** [comment]
I assume the search `prop:resched` will still work for us users? That's sometimes useful.

**Comment by user1823** [comment]
I hope that 24.10 would have a new revlog entry for "Reschedule cards on change". The faster we fix this issue, the lesser would be the number of ambiguous revlogs in users' collections.
