### ISSUE TITLE
Align the answer buttons in the reviewer

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3359]
Simplest solution for now: have translators pick words for the left and right buttons that are roughly equal in length, like we deliberately did for the English buttons. We might want to add a comment to the two strings to let translators know of this, and possibly split them into separate strings if they're being used in other locations as well.

> The “Show Answer” and “Easy”, “Good”, “Hard”, and “Again” buttons are all misaligned with the centre. This is especially obvious with centre-aligned card templates.

Originally reported on https://forums.ankiweb.net/t/align-the-answer-buttons-in-the-reviewer/48079/

**Comment by akashreddy03** [comment]
Woudn't fixing the width of left and right buttons solve this issue?
