### ISSUE TITLE
Image occlusion masks don't stay in the same place

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3370]
> Default IO, I don’t use any add-ons.
> I’ve been with this problem since the Anki’s June update, my image occlusion masks keep moving as I review them At the start, all works normal, but, after 1 or 2 weeks, it’s all dislocated.  It happens gets worst everytime I study/answer the IO notes.
> I’ve asked in Anki’s Discord and Sorata had said that it’s a bug and Expertium have said that he have the same problem too.
> 

Originally reported on https://forums.ankiweb.net/t/bug-report-masks-in-io-moves-by-itself-ankis-24-06-2-update/48263

**Comment by dae** [comment]
@krmanik a heads up in case you're interested in working on this

**Comment by krmanik** [comment]
Hey dae, Due to limited time I have, I request other contributors to please take this issue, I am happy to assist if help needed.

**Comment by sheikheddy** [comment]
I think we can close this now?
