### ISSUE TITLE
please remove this restriction "serialized custom data must be under 100 bytes"

### ISSUE THREAD

**Issue by djidos** [ankitects/anki#3388]
I am writing a custom scheduling to use on anki
some custom data is very long

e.g., 
customData.easy.a = x...x
when the "x...x" is long enough, the restriction will start to work

please remove this restriction "serialized custom data must be under 100 bytes", since this restriction does not make much sense
thanks a lot

**Comment by dae** [comment]
https://forums.ankiweb.net/t/please-remove-this-restriction-serialized-custom-data-must-be-under-100-bytes/48781
