### ISSUE TITLE
Paste from Clipboard bug

### ISSUE THREAD

**Issue by chrislongros** [ankitects/anki#3438]
I can not paste clipboard contents into a new flashcard. The bug is not limited to image pasting but also text insertion etc. The only way to paste right now is using Ctrl + Shift + X 

Version ⁨24.06.3 (a437003d)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1

Operating System: Arch Linux 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.2
Kernel Version: 6.11.0-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 7950X3D 16-Core Processor
Memory: 30.5 GiB of RAM
Graphics Processor: AMD Radeon RX 550 / 550 Series
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B650 GAMING X AX V2

**Comment by dae** [comment]
Are you using the middle mouse button to paste? Could it be related to #3249?

**Comment by chrislongros** [comment]
> Are you using the middle mouse button to paste? Could it be related to #3249?

I use Ctrl+V

**Comment by chrislongros** [comment]
Solved with https://github.com/ankitects/anki/commit/f3b0afcc624c6fb2ff259cf34e819cc2c651da67
