### ISSUE TITLE
[Bug] Reschedule doesn’t work on cards in filtered deck

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3439]
> If I use Reschedule cards on change, while some cards are in a filtered deck, rescheduling doesn’t happen for cards in the filtered deck.

Originally reported on https://forums.ankiweb.net/t/bug-reschedule-doesnt-work-on-cards-in-fiktered-deck/49896

**Comment by dae** [comment]
update_memory_state() is already attempting to write to original_due if non-zero, so hopefully it's just the selection criteria that needs to change

**Comment by L-M-Sherlock** [comment]
```
DeckIdsWithoutChildren(s) => format!("did:{}", s),
```

It doesn't include the cards in filtered decks.
