### ISSUE TITLE
Multiple SIGSEGV in _rsbridge.so using v24.06.3 (gdb bt full included)

### ISSUE THREAD

**Issue by GithubAnon0000** [ankitects/anki#3444]
# Description
Anki crashes immediately after opening it. Running in the terminal with gdb shows a SIGSEGV in the https connector (see bt1 file). This behavior does not happen all the time. Most of the time it won't crash after running anki.

It happens even if all extensions are turned off.

Sync is turned off. According to my app firewall (opensnitch) the only connection anki opens is to 127.0.0.1:44559 via tcp from process `/usr/local/share/anki/lib/PyQt5/Qt5/libexec/QtWebEngineProcess` and cmdline
```
/usr/local/share/anki/lib/PyQt5/Qt5/libexec/QtWebEngineProcess --type=utility --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FontSrcLocalMatching,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --lang=de --service-sandbox-type=network --no-sandbox --use-gl=desktop --application-name=Anki --webengine-schemes=qrc:sLV --shared-files
```

I can open anki when I hold shift upon opening it. A message then appears telling me that extensions had been turned off and sync had been skipped.

There is another SIGSEGV when opening anki while holding the shift key, then clicking on tools > check database OR clicking on the collection > export (see bt2 file). This never happened before either.

I removed all Anki and Anki2 files from ~/.local/share/ – same result.

# OS Version
Debian 11 (bullseye, oldstable), X11, Gnome 3.38.5.

# Anki Version
Anki 24.06.3 (d678e393)  
Python 3.9.18 Qt 5.15.2 PyQt 5.15.5
Platform: Linux-6.1.0-0.deb11.17-amd64-x86_64-with-glibc2.31

# `gdb bt full` files

[gdb_bt.zip](https://github.com/user-attachments/files/17157971/gdb_bt.zip)
_sha512sum:_
```
e6c850b28f2bc7d294a0db3d53719c4287f779a297ed685351b9c844944dc406e5c64004705e541d99529f14371d86950fa118a1ace10e4c77bf026718c12b3a  gdb_bt.zip
```

**Comment by dae** [comment]
Maybe memory corruption? If you figure out repro steps, please feel free to reopen.

**Comment by dae** [comment]
Possibly cosmic ray, cached libraries in memory, etc.
