### ISSUE TITLE
Discrepancy between add-on and native True Retention

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3453]
@L-M-Sherlock

The native true retention is counting less failures than the add-on.

Native True Retention:
<img width="523" src="https://github.com/user-attachments/assets/a5ef6a88-e1cb-40b0-aefd-01545258c77f">

Add-on True Retention:
<img width="523" src="https://github.com/user-attachments/assets/d184955f-44ff-414a-bca2-34259eda2067">

Deck: [Deck.zip](https://github.com/user-attachments/files/17175446/04-24.zip) (Rename to .apkg)

**Comment by L-M-Sherlock** [comment]
I cannot reproduce the discrepancy with the deck:

<img width="512" alt="image" src="https://github.com/user-attachments/assets/854efbaa-ba55-4c44-adc9-e707c550e33b">

<img width="512" alt="image" src="https://github.com/user-attachments/assets/02fa882d-2ad4-4d95-9437-86c485cbc13f">

**Comment by L-M-Sherlock** [comment]
Could you send me the collection file? I guess some revlogs are lost when you export the deck.

**Comment by user1823** [comment]
Here is the collection file;
[collection-2024-09-29@12-42-05.colpkg.zip](https://github.com/user-attachments/files/17178339/collection-2024-09-29%4012-42-05.colpkg.zip) (Rename to remove .zip)

**Comment by L-M-Sherlock** [comment]
Thanks, I reproduce this discrepancy:

<img width="833" alt="image" src="https://github.com/user-attachments/assets/b00f5fcd-6861-4384-adca-4af27c282018">

<img width="833" alt="image" src="https://github.com/user-attachments/assets/bc9cd8ca-0ddc-43c1-90a0-2f3b45c0c8c0">

It looks like the native True Retention count more revlogs than the add-on. I will check it soon.

**Comment by L-M-Sherlock** [comment]
I figure it out. The helper add-on filters out the reviews of deleted cards. I will add them back.

**Comment by user1823** [comment]
> It looks like the native True Retention count more revlogs than the add-on. 
> I figure it out. The helper add-on filters out the reviews of deleted cards.

This is because you are loading the "Collection" stats in the new Stats page. IMO, this is not really a bug. The add-on is only loading the "Deck" stats while Anki can load both "Deck" and "Collection" stats.

However, there is still a discrepancy when you load the "Deck" stats in the new Stats page.

<img width="523" src="https://github.com/user-attachments/assets/a5ef6a88-e1cb-40b0-aefd-01545258c77f">
<img width="523" src="https://github.com/user-attachments/assets/d184955f-44ff-414a-bca2-34259eda2067">

Here, the native true retention is counting less failures than the add-on.

**Comment by L-M-Sherlock** [comment]
> Here, the native true retention is counting less failures than the add-on.

I find that I forget to filter out manual reviews and filtered reviews. Now they are consistent:

<img width="833" alt="image" src="https://github.com/user-attachments/assets/df6dca6e-a3f5-494d-9d0a-75f9a4068269">

<img width="833" alt="image" src="https://github.com/user-attachments/assets/b149fd67-cea4-48fd-9df6-135f691723c7">

**Comment by user1823** [comment]
> I find that I forget to filter out manual reviews and filtered reviews. 

In the add-on or in native true retention?

**Comment by L-M-Sherlock** [comment]
In the add-on. I'm fixing it.
