### ISSUE TITLE
Properly convert FSRS 4.5 parameters into FSRS 5 parameters

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3463]
@L-M-Sherlock @Expertium

The initial difficulties (D0) calculated using default FSRS 4.5 parameters with the formulas of FSRS 4.5 and FSRS 5 are quite different.

This implies that if the user doesn't re-optimize their parameters after updating to 24.10+, the scheduling is very likely to be worse than with FSRS 4.5. Obviously, we don't want the Anki update to make the scheduling worse.

Ideally, the user should re-optimize their parameters after updating to 24.10+. But, we can't assume that all users will do that. So, to reduce the damage, we should try to find out how to properly convert FSRS 4.5 parameters into FSRS 5 parameters (apart from just adding two zeroes).

Specifically, we want to find out how to convert w4, w5 and w7.

**Comment by Expertium** [comment]
w7 is the same as before, though the exact numerical values isn't guaranteed to be the same, of course.
As for w4 and w5, I'm not sure. I made this to help you (and anyone else reading this) to visualize initial D: https://www.desmos.com/calculator/vhuux5h5qa

**Comment by user1823** [comment]
Thanks for the link. It was indeed helpful.

I propose the following:

Let the values of w4 and w5 in the FSRS 4.5 parameters be $a$ and $b$ respectively.

Then, we should perform the following calculations:

$$ c = a + 2b $$

$$ d = \frac{\ln\left(3b+1\right)}{3} $$

And these values should be used as the converted values of w4 and w5 in FSRS 5.

In the graph below, 
- the black line represents the initial D calculated using the FSRS 4.5 formula and the default FSRS 4.5 parameters
- the purple curve represents the initial D calculated using the FSRS 5 formula and the default FSRS 4.5 parameters
- the blue curve represents the initial D calculated using the FSRS 5 formula and the converted FSRS 4.5 parameters

![image](https://github.com/user-attachments/assets/cc02fece-4373-4eff-9c0d-0a2e4cd1d765)

**Comment by Expertium** [comment]
@L-M-Sherlock unless this is terribly impractical for some reason, use user1823's formulas (`c` and `d`) to internally convert w4 and w5 in ANki 24.10 beta (without notifying the user).

**Comment by L-M-Sherlock** [comment]
The converting is executed in FSRS-rs. Please open an issue there to remind me.
