### ISSUE TITLE
New option to enable FSRS short-term scheduler

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3497]
https://forums.ankiweb.net/t/fsrs-5-1d-scheduling-and-learning-steps/50242/54

The FSRS short-term scheduler is very unlikely to schedule an interval less than 4 hours. If one has to clear all their (re)learning steps to enable the short-term scheduler, it is unlikely to be useful because the Again interval would be too long.

So, for the users who want to try the FSRS short-term scheduler, we have to find a solution that allows them to define their own steps and let FSRS determine if they need more same-day reviews or not.

As suggested in the Forums post, I think that a good solution would be to allow an interested user to enable the short-term scheduler through the debug console.

Or as suggested by Expertium, we can make a simple command that the user can enter into the custom scheduling field.

@L-M-Sherlock

**Comment by Expertium** [comment]
> enable the short-term scheduler through the debug console.

That would reduce the number of users who use FSRS's short-term scheduling to approximately 0

**Comment by user1823** [comment]
The debug console method was intended to be an additional way to enable it. I am not suggesting the removal of the existing method (leaving the steps blank).

But, your suggestion of adding an option in the custom scheduling seems to be a better alternative.

**Comment by DerIshmaelite** [comment]
> But, your suggestion of adding an option in the custom scheduling seems to be a better alternative.

But I think this only applies to single presets. There is no way to apply to the entire collection through the custom scheduling. There should be a way as well to apply to the entire collection.

**Comment by mlidbom** [comment]
Yes please. I'm running this way now and it's great. Please let me keep it.

**Comment by DerIshmaelite** [comment]
I share this sentiment as well. I have found it phenomenal and it has already helped save me a lot of headaches.
