### ISSUE TITLE
Editor width is changing as tag completions shown

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3514]
Reported on https://forums.ankiweb.net/t/anki-24-10-beta/49989/251

**Comment by dae** [comment]
@hikaru-y do you remember which of the listed fixes on e79060487bf09eccb5d5e1282e0d9bff7aa3a223 required the removal of portalTarget? When I put it back, it seems to resolve the changing width. In the absence of a better fix, I'm wondering which is the lesser of two evils.

**Comment by dae** [comment]
This is an annoying bug which I'd prefer fixed before release, but I don't think anyone at the moment has an idea of how it might be fixed, so it's going to have to wait unfortunately. Any JS/CSS gurus want to swoop in and save us? :-)

**Comment by abdnh** [comment]
I was planning to take a look, but yeah, editor code is complicated 😓

**Comment by dae** [comment]
If you wanted to look into it and you happen to figure it out before the release, I'd be happy to build another rc. :-) But if there's no clear solution by release time, it probably doesn't make sense to hold the release up for it.
