### ISSUE TITLE
Discrepancy between add-on and native "Estimated total knowledge"

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3517]
@L-M-Sherlock

The native Estimated total knowledge is higher than the add-on.

Native Estimated total knowledge: 5,865 cards / 4,726 notes

Add-on Estimated total knowledge: 5839 cards / 4707 notes

Deck: [Deck.zip](https://github.com/user-attachments/files/17175446/04-24.zip) (Rename to .apkg)

(After importing the deck, enable FSRS with the default parameters. I don't know why the FSRS settings are not exported with the deck.)

**Comment by L-M-Sherlock** [comment]
It's expected because the add-on doesn't includes suspended cards.

**Comment by user1823** [comment]
Why does the addon exclude the suspended cards and the native version include them?

By the way, the inconsistency persists even after I add `-is:suspended` in the new Stats screen.

After adding `-is:suspended`, I get: 5,861 cards / 4,727 notes

What's even more interesting is that the number of notes **increases** on adding `-is:suspended`.

**Comment by L-M-Sherlock** [comment]
> Why does the addon exclude the suspended cards and the native version include them?

Because the stats are calculated separately in the native version. In the add-on, "Estimated total knowledge" and "Daily load" are calculated in the same time.

**Comment by Expertium** [comment]
@dae I've mentioned this before. Ideally, the add-on stats and the native stats should be the same, to avoid confusion. Excluding suspende cards is very reasonable and frankly, I'm not sure why Anki doesn't do it

**Comment by L-M-Sherlock** [comment]
> By the way, the inconsistency persists even after I add `-is:suspended` in the new Stats screen.

The native version only excludes new cards:

https://github.com/ankitects/anki/blob/23b7d63659d8230019be898db977c41b1e20ceaf/rslib/src/stats/graphs/retrievability.rs#L25-L44

> What's even more interesting is that the number of notes **increases** on adding `-is:suspended`.

Because the number of siblings decreases in this case... I will try to solve it.

**Comment by L-M-Sherlock** [comment]
> Excluding suspended cards is very reasonable and frankly, I'm not sure why Anki doesn't do it

Should we exclude suspended cards when plotting the retrievability distribution as well?

**Comment by L-M-Sherlock** [comment]
OK. If a card of a given note is suspended, should we consider it in calculating the estimated total knowledge by note?

For example, the note X has card A, card B and card C. $R_A = 0.9$, $R_B = 0.8$, $R_C = 0.7$. The estimated total knowledge by note is (0.9 + 0.8 + 0.7) / 3 = 0.8. What if the user suspends card C?

**Comment by user1823** [comment]
Well, that is a difficult question.

But, IMO, because the card C is suspended, we can assume that the user is not learning that part of the note. So, the knowledge of the note is (0.9 + 0.8) / 2 = 0.85

I think that the current beta also does this, which would explain why the knowledge by notes increases on excluding suspended cards.

But, as I mentioned above, there is a discrepancy in knowledge by cards too, which can't be explained by this.

**Comment by L-M-Sherlock** [comment]
I guess it's caused by this function:

https://github.com/ankitects/anki/blob/23b7d63659d8230019be898db977c41b1e20ceaf/rslib/src/browser_table.rs#L127-L139

As the comment says, it's not accurate in some cases.

**Comment by Expertium** [comment]
> But, IMO, because the card C is suspended, we can assume that the user is not learning that part of the note. So, the knowledge of the note is (0.9 + 0.8) / 2 = 0.85

I agree.

**Comment by filipenanclarez** [comment]
> OK. If a card of a given note is suspended, should we consider it in calculating the estimated total knowledge by note?
> 
> For example, the note X has card A, card B and card C. R A = 0.9 , R B = 0.8 , R C = 0.7 . The estimated total knowledge by note is (0.9 + 0.8 + 0.7) / 3 = 0.8. What if the user suspends card C?
> 
> @filipenanclarez, your feedback is wanted.

For me, the suspended card have a problem, or this card is already memorized. So, i think this card need to be excluded from the math. In this example, we divided by 2 besides 3. Only active cards counts to my knowledge stats (in my opinion).

**Comment by L-M-Sherlock** [comment]
The weird card:

<img width="1108" alt="image" src="https://github.com/user-attachments/assets/03739476-7da0-4bf2-9bfd-2d24e40cfec4">

<img width="1406" alt="image" src="https://github.com/user-attachments/assets/bf945925-c52a-4788-95f3-37b3b35e5d9c">

**Comment by user1823** [comment]
> The weird card:

I don't know how this card got that due date. Maybe due to a bug in a past version of the Helper add-on?

But, correcting the due date date with the Helper add-on doesn't solve the issue.

**Comment by L-M-Sherlock** [comment]
> But, correcting the due date date with the Helper add-on doesn't solve the issue.

Did you reschedule all cards and excluded suspended cards?

**Comment by user1823** [comment]
> Did you reschedule all cards

Rescheduling all cards did the trick. But, why do I need to reschedule them? Saving the deck options page (after enabling FSRS) should already assign the correct memory states to the cards, right?

**Comment by L-M-Sherlock** [comment]
> should already assign the correct memory states to the cards, right?

But some cards' due is incorrect in your deck. `reschedule all cards` could fix it.

**Comment by user1823** [comment]
Ok. So, it's using due - ivl to calculate the last review date and then using this last review date to calculate retrievability. Right?

Can it see the last review date directly from the revlog just like the card info page?

**Comment by L-M-Sherlock** [comment]
> Can it read the last review date directly from the revlog just like the card info page?

It's slow if we do it in thousands of cards.
