### ISSUE TITLE
Burying still affects daily load

### ISSUE THREAD

**Issue by user1823** [ankitects/anki#3529]
@L-M-Sherlock

After https://github.com/ankitects/anki/pull/3516, I expected that burying cards will have no effect on the daily load.

However, even in 24.10 rc 1, burying cards increases the daily load.

Slightly unrelated, but there seems to a difference in rounding of the value between the add-on and native stats. After unburying all cards, Anki showed a daily load of 161 reviews/ day while the add-on showed a daily load of 162 reviews/day.
(With siblings of today's reviews buried, Anki showed a daily load of 166 reviews/ day.)

**Comment by L-M-Sherlock** [comment]
> However, even in 24.10 rc 1, burying cards increases the daily load.

I cannot reproduce it:

Before burying any card:

<img width="872" alt="image" src="https://github.com/user-attachments/assets/2a2d4377-709d-4e65-91f3-61a65b1452e4">

Then bury some cards:

<img width="765" alt="image" src="https://github.com/user-attachments/assets/880ba010-7acd-4c72-ae31-273e8000c994">

I still get the same figure:

<img width="872" alt="image" src="https://github.com/user-attachments/assets/39f30e03-e078-4407-87a8-b37aed140843">

**Comment by user1823** [comment]
Try burying all cards to see if it makes any difference. If you still can't reproduce, I will share a deck for reproduction.

**Comment by L-M-Sherlock** [comment]
Weird... OK, I reproduce this bug successfully. Will dive into the code.

<img width="835" alt="image" src="https://github.com/user-attachments/assets/6a34a22a-bac1-47ba-8348-0ddf96066e25">

**Comment by L-M-Sherlock** [comment]
I figure it out. Burying a new card sets its queue to buried. And the buried card is counted in daily load.
