### ISSUE TITLE
Improve feedback of resetting parameters [deck options]

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3531]
> https://www.reddit.com/r/Anki/comments/1g9qh7f/resetting_fsrs_parameters_to_default_not_working/ 2
> This user says that it looks like resetting parameters is stuck in an endless loop (it’s not).
> Some time ago someone on Discord also thought that resetting parameters is forever stuck (I can’t find screenshots, unfortunately).
> It seems that the feedback could be improved.
> Maybe just make it so that the circle-arrow symbol needs to be clicked only once, and there is no pop-up that requires a second click?

Originally reported on https://forums.ankiweb.net/t/improve-feedback-of-resetting-parameters-deck-options/51036/9

Removing the confirmation step is the easiest on our end. I'm not sure it's needed - in the rare cases where a user misclicks, they can either avoid saving, or save and then undo if they want to check what the old value was. But a normal pop-up dialog with `confirm()` would be ok too.

**Comment by Expertium** [comment]
Here are a few options:
1) Remove the confirmation entirely
2) Make it a more prominent pop-up, like the "Discard changes" one
3) Keep the current implementation, but don't make the arrow animated, just make it static
