### ISSUE TITLE
Display some kind of completion message when CMRR is done

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3532]
> When the Minimum recommended retention computation ends, the “Iteration: 6…” should be replaced with something more “definitive”, to make it clearer that it ended. Perhaps “Iterations: 6.”?

Originally reported on https://forums.ankiweb.net/t/display-some-kind-of-completion-message-when-cmrr-is-done/51081/3

My vote would be to just hide the progress text once the operation completes.

**Comment by Expertium** [comment]
I think "Converged in x iterations" gives a feeling of "completeness" if that makes sense, but I'm ok with not displaying any text.

**Comment by dae** [comment]
I think "converged" and even "iterations" is going to be tough for a lot of Anki users. Let's either show nothing, or keep it simple. It doesn't necessarily need to be shown in the progress area - a tooltip/temporary pop-up could work too.
