### ISSUE TITLE
Easy Days shouldn't allow the user to set all days to "Reduced or "Minimum"

### ISSUE THREAD

**Issue by Expertium** [ankitects/anki#3545]
https://forums.ankiweb.net/t/anki-24-10-release-candidate/51191/29?u=expertium
![image](https://github.com/user-attachments/assets/40549dd0-826a-4353-ac08-abc0e08606db)
Users shouldn’t be allowed to set all days to “Reduced” or “Minimum”. It achieves nothing (no reduction) and makes the user misguidedly think that he can just reduce the number of reviews with no downsides.

This was a problem in the FSRS Helper add-on too, LMSherlock fixed it: https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/485/commits/9f5cada5f10d4b7229a471dde51cd482a0b71085
I asked him to fix it in the native implementation too, but he said he's not familiar enough with Anki frontend to do it. So hopefully someone else will after reading this issue.

**Comment by Gardengul** [comment]
The current implementation is convenient if the user needs to switch one day to normal mode from time to time.

**Comment by Expertium** [comment]
The problem is that setting all days to Normal is the same as setting all days to Reduced, which is the same as setting all days to Minimum. Each day will have (roughly) the same number of due cards. But users don't know it, and we should make sure that they don't do something that will make them confused and will cause them to complain.
I advise you (or anyone else reading this) to implement the same fix that LMSherlock implemented in the commit I mentioned.

**Comment by Gardengul** [comment]
It is enough to indicate this in the hint. When it appears.

**Comment by Expertium** [comment]
People don't read hints.
One way to solve this would be to act an interactive bar chart (below the table with radio buttons) that shows the relative load on each day, so that the user can see how the load will differ when he changes settings. But I doubt anyone would be interested in coding that.

**Comment by CloseChoice** [comment]
what exactly are the combinations that shouldn't be allowed here? All to "Reduced" or all to "Minimum" or also a mixture between the two without a "normal" day?

**Comment by brishtibheja** [comment]
Do we also disable radio buttons for the last remaining day or we just show a pop-up?

**Comment by Expertium** [comment]
Just show a pop-up

**Comment by brishtibheja** [comment]
Most users will not be able to tell why the pop-up is significant/important unless you explain it to them. They still might end up believing Easy days will remove reviews from every single day.

**Comment by Expertium** [comment]
Hm. I guess let's show a pop-up and revert the last change to radio buttons that caused it.
Example:
![image](https://github.com/user-attachments/assets/cd9ba0e7-b2f0-4044-b48c-00d806bd9f2a)

**Comment by dae** [comment]
Just to clarify one point: I think we should do this with a yellow inlay warning, not a "pop-up" dialog box, since blocking the user from saving would be inconsistent with how we handle other non-sensical input like steps longer than graduating interval.

**Comment by brishtibheja** [comment]
If someone sets all days to "Reduced" or "Minimum" maybe we can also skip the calculation for easy days and just make the code behave like it's "Normal" for all days. Or that's unnecessary?

**Comment by Expertium** [comment]
In those cases it will behave like it's Normal anyway

**Comment by brishtibheja** [comment]
I was asking if it would require less computation to do it this way?

**Comment by Expertium** [comment]
Not really
