### ISSUE TITLE
Disallow setting all days to easy

### ISSUE THREAD

**Issue by dae** [ankitects/anki#3551]
Originally reported on https://forums.ankiweb.net/t/anki-24-10-release-candidate/51191/29

**Comment by dae** [comment]
Maybe a warning in the UI when no days are set to normal? How do we succinctly express it? "You can't make every day easy."?

**Comment by Gardengul** [comment]
https://github.com/ankitects/anki/issues/3545
The same thing.

**Comment by Expertium** [comment]
Yeah, I already made an issue.
Anyway, I was thinking of a pop-up that says "At least one day has to be set to Normal".

**Comment by dae** [comment]
Sorry, I'd forgotten about that. Closing in favour of your previous report. I also prefer your suggested wording.
