### ISSUE TITLE
No link to source code for anki and aqt python packages on PyPI

### ISSUE THREAD

**Issue by joshdavham** [ankitects/anki#3597]
Currently, the project description sections for the [anki](https://pypi.org/project/anki/) and [aqt](https://pypi.org/project/aqt/) python packages on PyPI are pretty bare and there's no link to any repo containing the source code.

![anki_pypi](https://github.com/user-attachments/assets/0808e7a3-171b-4fb8-854b-1cc121ebbe6f)

To be completely honest, even after doing a bit of digging, I'm still not even completely sure where to find the source code!

I think that adding a simple link to the the repos with the source code (or the specific directory where it's found) for these two packages could be of great help to python developers who are hoping to get into developing anki addons.

Let me know what you think 👍

**Comment by dae** [comment]
docs/development.md
