### ISSUE TITLE
Avoid exec_() in studydeck.py

### ISSUE THREAD

**Issue by dae** [ankitects/anki#987]
https://forums.ankiweb.net/t/intermittent-hanging-on-add-screen-when-attempting-to-change-note-type/6003 reports that the screen is hanging, and I think there's a decent chance it's caused by the call to self.exec_(), which has been the source of crashes in the past. Taking a different approach by calling .setWindowModality() to make the window modal, and removing the .exec_() line may fix the issue. But as all users of StudyDeck currently expect .name to be set by the time the constructor finishes, the code will need to be refactored to accept a callback that is called once the dialog is closed.

**Comment by charltonaustin** [comment]
Hi @dae  and team. Is anyone working on this? I was going to take a look. I'd like to get more involved in the project and though this might be a good place to start. Please let me know if there is somewhere else I should be looking.

**Comment by charltonaustin** [comment]
It looks likes the window has been set to modal already here, `qt/aqt/studydeck.py:83`, and that the success call back is run in onAddDeck here, `qt/aqt/studydeck.py:179`. Is that correct? Should this be closed?

**Comment by dae** [comment]
The .exec() call is still there - it was renamed from .exec_() since this issue was originally posted. This might not be the best ticket to get started with I'm afraid - all existing callers will need to be updated to handle a callback, and it will likely break some add-ons that rely on the current behaviour, so it's something we probably won't want to merge in immediately.

**Comment by charltonaustin** [comment]
Sounds good. Do you have a suggest for a ticket that would be better suited to start with?

**Comment by dae** [comment]
Nothing springs immediately to mind I'm afraid, but if you follow along on the forums, I imagine something will come up.

**Comment by roxgib** [comment]
The use of exec in QDialogs and QMenus is causing issues with an [add-on I'm developing](https://github.com/roxgib/anki-contanki), so I've tried to develop a fix. If it's accepted I'll implement it for other QDialogs and QMenus.
