### ISSUE TITLE
Trialing issue tracker on main repo

### ISSUE THREAD

**Issue by dae** [ankitects/anki#988]
The separate [help-wanted](https://github.com/ankitects/help-wanted) has been running fine for months, so perhaps it's time to try enabling issues on this repo, as it will make it easier for developers to coordinate. I'm hoping the comments in the issue template will limit the number of support requests we get here. 🤞

**Comment by dae** [comment]
Tweaking the issue template and having a link to the forums seems to have improved things somewhat, and having issues open here is convenient, so I think they're here to stay now.

**Comment by arathunku** [comment]
Hey, @dae. It looks like the best way to reach you is via GitHub issues, but I didn't want to spam you with another one with a simple question - what's the best way to do 1 time donation to Anki development? Have you considered enabling GitHub Sponsors for the project? 

Long time Anki user,
Cheers :) 

Also props for using Rust!!! Excited to see another project using it ;)

**Comment by dae** [comment]
I'm afraid I can't accept donations, but that's kind of you to offer. You can still help out by buying AnkiMobile for yourself or a free, or just telling your friends about Anki.

**Comment by arathunku** [comment]
That's a shame! Hopefully one day. :) I've been using Anki for over 10 years and wanted to pay back in some way. I'll continue spreading the word, best SRS software! Cheers
